### ISSUE TITLE
Login Form accepts empty userid 

### ISSUE THREAD

**Issue by m-prabhu** [appirio-tech/connect-app#1013]
### Expected behavior
When user id is empty, login form should check for its availability and request the user to provide it

### Actual behavior
Login Form accepts the empty user id and don't inform the user about it. It does authentication check and report as 'password is incorrect'

### Steps to reproduce the problem
- goto https://connect.topcoder-dev.com
- click login
- leave the user field as 'empty', provide 'some password' and click sign in
- There is no validation for 'user id' availability. You will receive 'Password incorrect' message

### Screenshot/screencast
![selection_048](https://user-images.githubusercontent.com/30400318/28541215-d2522824-70d5-11e7-81b2-7f459c2f6e2f.png)
![selection_050](https://user-images.githubusercontent.com/30400318/28541224-d8b65640-70d5-11e7-8060-0e94705b50c5.png)

--

#### Environment
- OS: Windows 7 32 bit
- Browser (w/version): Firefox 54, Chrome 59
- User role (client, copilot or manager): Not Applicable
- Account used: Not Applicable

**Comment by fnisen** [comment]
Guys, please follow the behavior here: https://accounts.topcoder.com/member. 

1. The Log in button should not activate if at least one field is empty
2. Both parts of the form should not be cleared when a validation error is returned, so that the user can easily fix their mistake (if they've made a one character typo, for example). (I saw an example of the password form being cleared).
3. The validation should not be "sticky"; it should go away once the user starts typing, so that they're not confused about why they're seeing the error.

**Comment by chq-matteo** [comment]
@fnisen we have an error for inactive users who have to contact support. Should that be non sticky too?

**Comment by chq-matteo** [comment]
@fnisen actually here https://accounts.topcoder.com/member validation is sticky

**Comment by chq-matteo** [comment]
So point 3 maybe is out of scope for this issue

**Comment by fnisen** [comment]
@chq-matteo fair enough. Let's count #3 as out of scope and just fix #1 and #2. 
@gondzo please chime in whether you want further fixes now or to handle this later.

**Comment by gondzo** [comment]
@fnisen login button is disabled if either of the fields is empty

**Comment by fnisen** [comment]
Thanks @gondzo; it's working well.
