### ISSUE TITLE
Project spec information is not saved when changing project types

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#1037]
Start here: http://connect.topcoder-dev.com/new-project/ while logged out
Select any project and fill out "Project Name" and "Ref code"; change project type by clicking the button in top right and selecting a new project type. 

Current behavior: all previously entered info is wiped out.  
Desired behavior: any common info to the two projects, such as "Name," "Notes," etc. should be carried over from one project to another.

**Comment by vikasrohit** [comment]
@fnisen we have every field in project spec template so whenever user changes the project type, it swaps the template and should empty every thing. However, if field names are same across two templates, browser may retain the old values. I have noticed one [issue](https://github.com/appirio-tech/connect-app/issues/993) which in facts reports otherwise of this issue.

**Comment by fnisen** [comment]
Regarding that issue, it seems like if the info has been stored in local storage, it will stay there. But, if it's not already in local storage, when you switch project types, it won't be put there. 

What's the logic for when we do or don't save to local storage?

**Comment by vikasrohit** [comment]
We save to local storage when user leaves (refreshes the page, closes the tab or clicks on Continue button) the project details form. We remove it from local storage only after successful call to project creation api (for logged out user it happens after success reg/login and for logged in user we immediately call project creation api). We move to project details page only after clearing the local storage.

**Comment by fnisen** [comment]
@vikasrohit don't think we ever resolved this issue. I tested just now. If I come to create a new project (without having anything previously saved in local storage) and change types, my info is being wiped. Can you please fix this?

**Comment by vikasrohit** [comment]
Okay, I have to compare every field of project templates for copying old values to new project type. Still, I will check if there is any quick and easy solution for this.

**Comment by vikasrohit** [comment]
While working for #1102, found that it can be fixed as well. 😬 
Changes are in dev. Please let me know if any further changes required for the same.

**Comment by fnisen** [comment]
@vikasrohit it's working, but why not copy other fields as well, such as Goals and Users, if they overlap?

**Comment by vikasrohit** [comment]
For copying other fields, I have to make sure that field exists in both templates. Its possible, let me try today and if it does not work or create any issue, we can handle it later as enhancement to currently implemented one.

**Comment by vikasrohit** [comment]
Done. Copied goal and users fields as well. I am validating that if these fields exists in the template of the updated project/product type. I have put this validation to ensure that we don't get spurious fields when we have a template which does not have these fields.

**Comment by fnisen** [comment]
@vikasrohit copying is working. I'm seeing two issues though:
- I now get the browser warning about unsaved changes when I want to change project type; we don't need this if the form is not being erased (e.g., user can still click back and see what they've entered)
- Notes section is not being copied

**Comment by vikasrohit** [comment]
1. They are still loosing the changes @fnisen. what about the fields that are not common? e.g. Number of screens in AVD product.
2. Notes is not copied yet. I can add that to the list.

**Comment by fnisen** [comment]
1. Fair point. It feels like we get the user into an error state, even though this is the expected experience. Seems like we need an app message, not a browser warning. Let me talk to Vic about this one
2. Thanks, please add

**Comment by vikasrohit** [comment]
Done. Changes are in dev.

**Comment by vic-topcoder** [comment]
On competitors when you change project type you lose all data but project name (Crew). I still think we should have a 100% compatible (required) information when creating project, and secondary (context-specific). When we move towards a unified project structure these wouldn't have to change at all. For the time being persisting name and description would suffice. We should have description for chat bot and testing.

**Comment by fnisen** [comment]
@vikasrohit the information copying is working well. Can you please turn off the unsaved information warnings though? I get one when I first click "Change project type" and then again when I click on a different project type from the project menu. Discussed this UX with Vic.

**Comment by vikasrohit** [comment]
@fnisen I tried today to get rid of that unsaved content warning, however, it seems bit tricky here because actually there is a content that has changed when user has entered the information for the first time. One solution is to not make project state dirty in such cases, but we don't know if user is going to click on 'Change project type' next. So, we have to make project state dirty whenever user is editing any field of the project. Now the other solution is to check which fields are exactly changed and if no other field is altered other than the ones which we retain during type change, don't show the warning. Now again to do that I have to do field by field comparison and personally I feel that it may introduce more edge cases. If we can not afford having the alert for the first time user enter the information, I will do that.
On the side note, we are any way saving user's project in local storage, why we need to show the unsaved content warning anyway?

**Comment by fnisen** [comment]
@vikasrohit--I agree with your last point. I don't think we need the unsaved content warning b/c the content is indeed being saved. We may technically lose some elements that are not universal (such as device type), but I don't think a user would have expectations that they would be saved. I think we can get rid of the warnings for both the case of changing project type and closing the browser tab. If you agree, please go ahead and make those changes.

**Comment by vikasrohit** [comment]
Yep, Agree. We need to set right expectations of our connect managers, if they have seen the unsaved content warning in past for any project.

**Comment by vikasrohit** [comment]
Done. Changes should be in dev by EOD.

**Comment by fnisen** [comment]
Working well--thank you.
