### ISSUE TITLE
If user enter the same email address as the update email; page navigation issue happens

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#1061]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL https://connect.topcoder-dev.com

- Click 'Login' > Register for Free

- Fill all the required data and click Confirm

- Once the PIN is requested click 'Edit'

- Enter the same email address (dil88888@qa.team)

- Click 'Update email and send a new PIN'

- Observe it goes to security PIN page and redirects to update email page and display the error message

Actual Result(s)
-----------------------------------------------------------------
- If user enter the same email address as the update email; page redirects to the verify page and come again to the update email page to display the error message ("Email is already in use, please use different email address")

Expected Result(s)
-----------------------------------------------------------------
- Page must remain in the same page and display the error message ("Email is already in use, please use different email address")

URL where the Bug Appears
-----------------------------------------------------------------
https://accounts.topcoder-dev.com/connect/pin-verification

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![36](https://user-images.githubusercontent.com/4592712/28624891-3a257a42-7238-11e7-80f9-dafaf1e5a15b.jpg)

https://www.screencast.com/t/9t44WQDHBr

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 Pro (64bit) 
- **Browser:** Google Chrome 59.0.3071.115 (Official Build) (64-bit) / IE11
- **User role (client, copilot or manager):** not logged in
- **Account used:** NA

**Comment by fnisen** [comment]
Validation has been wired to be sticky, which is incorrect. Go here: https://accounts.topcoder-dev.com/connect/registration, try an existing email address (e.g., filipp@appirio.com), and then start to erase it, one character at a time. Do you see how it throws a validation error, but then quickly goes away? That's the kind of UX we need.

**Comment by vikasrohit** [comment]
@fnisen @gondzo @chq-matteo Actually it was kind of intentional to make the email field non editable while we are checking and updating email address so that user do not update the email in the text box or click on the update button again, in between.
I am not sure what would be the ideal behaviour here. If we want to keep the form as is while doing the actual update, we should show loading icon on top of the form and disable the update button while updating.

For the sticky behaviour of errors, the errors from server are mostly sticky because no validation event is fired when user is updating the field after a server side error. All front end validation would be non sticky. However, we can make the server errors non sticky as well.

**Comment by chq-matteo** [comment]
@vikasrohit I've found a solution for the email input, but the password one requires a non trivial amount of work

**Comment by fnisen** [comment]
@vikasrohit @chq-matteo looks like Vikas is already addressing the issue here https://github.com/appirio-tech/connect-app/issues/1091. I've commented there about a possible approach.
