### ISSUE TITLE
[$100] Pin screens

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#1073]
This is a placeholder issue for a bug bash to track related issues.

Fixing all of the following bugs is in scope
- [x] #1040
- [x] #1060
- [x] #1061

**Comment by gondzo** [comment]
@andela-onnenanya any progress ?

**Comment by andela-onnenanya** [comment]
@gondzo Having hard time with npm install. The package installations throw errors `npm ERR! tar.unpack unzip error` and `npm ERR! tar.unpack untar error`. Have tried clearing cache but no luck.

**Comment by gondzo** [comment]
I don't have that issue, it's probably something with your environment. check https://docs.npmjs.com/getting-started/fixing-npm-permissions

If you can't fix your install issues in the next few hours, just add open for pickup label to this issue (so someone else can pick it up). After you fix your environment you can pick up another task. Thanks!

**Comment by andela-onnenanya** [comment]
Ok, I will open it for pick. Thank you.

**Comment by chq-matteo** [comment]
Issue #1040 is wrong *there are* validation checks (topcoder api) for the email.
`dil2@qa` is valid because it is not syntactically wrong as email (`qa` could be a top level domain)

Synctactically incorrect email
![2017-07-30](https://user-images.githubusercontent.com/6654800/28753599-11b30ea6-7537-11e7-8dce-ab1ea71081d6.png)

Syntactically correct email
![2017-07-30 2](https://user-images.githubusercontent.com/6654800/28753603-22adfd92-7537-11e7-83e3-d5ed51fdb954.png)

**Comment by gondzo** [comment]
see #950 for related email validation discussion. Lets use the same validation in the pin screens

**Comment by chq-matteo** [comment]
this is also on branch [feature/copy-change-pin-verification](https://github.com/appirio-tech/accounts-app/tree/feature/copy-change-pin-verification) since on branch dev there is no script or view for pin-verification
