### ISSUE TITLE
Design new loading/busy state

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#1094]
Following up on this comment: https://github.com/appirio-tech/connect-app/issues/977#issuecomment-319765362

**Comment by vikasrohit** [comment]
@fnisen @vic-topcoder 

> Ideally we should provide a "loading/busy" state for the field that is being processed at the time. A global spinner does not make sense. I'd rather see it removed entirely. While loading the field should change state to indicate the process. We can design a quick "loading/busy" state with @sirakovaDimitrina, but I'll keep this as P2 and do it after release. For the time being - let's hide the spinner (it is not the same one we use inside Connect anyway).

I guess, we are never showing loading icon for a change in a particular field. We show loading icon whenever, user is hitting the submit button of the form or if we are doing some processing on the page load and don't want users to perform any action in between. So, I think having a global spinner does make sense here.
Yes, the spinner right now is different because they are separate app. We can use the same image for loading in accounts app as well. We have to copy the existing loader component with new image in accounts app so that we don't disturb the member side pages.
