### ISSUE TITLE
"Create a new project" action should consider the product from the URL

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1104]
### Expected behavior
It should directly load the project details page for the specified product in URL.

### Actual behavior
It loads Product selection screen instead.

### Steps to reproduce the problem
- Open http://connect.topcoder-dev.com/new-project/wireframes.
- Enter few details e.g. name, ref code. Filling one should be enough.
- Now refresh the page.
- Click on "Create a new project" project button when asked for handling incomplete project
- Notice the page where it leads the user to

### Screenshot/screencast
<img width="1280" alt="screen shot 2017-08-09 at 4 12 24 pm" src="https://user-images.githubusercontent.com/2417632/29117911-9fa5b4aa-7d1d-11e7-9958-81f2edd8ded9.png">

--

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): N/A
- Account used: N/A

**Comment by vikasrohit** [comment]
@fnisen should we load the wireframes details page or update the URL instead to not have 'wireframes'?

**Comment by fnisen** [comment]
@vikasrohit in this scenario, if they have the URL as http://connect.topcoder-dev.com/new-project/wireframes and they reload, I think we have to take them back to that page, not to the "You started a project with us recently" page. I think we just reload that page with their existing info, in case they reload accidentally, so nothing is lost. 

This issue is related to what we were discussing here: https://github.com/appirio-tech/connect-app/issues/1035. I think changing the URL to mirror what is happening in the app would make the experience clearer for the user.

**Comment by vikasrohit** [comment]
@fnisen I guess we can not differentiate between user explicitly(or accidentally) reloading the page and reopening the tab/browser with this URL. So, IMO, I am afraid if we can avoid the "You started a project with us recently" page in such cases. If we do, it would not be loaded even when user is coming back to new project (may be by clicking the same marketing deep link after closing the tab/browser) later on.

Yes, it is related to #1035. I found this issue when working on #1035. 😬

**Comment by fnisen** [comment]
@vikasrohit sorry, I'm a little confused here. How do you want to proceed with this one?

**Comment by vikasrohit** [comment]
@vic-topcoder I think two tier menus, is good opportunity to handle this issue. I am thinking if we should directly show the project details form when user is coming back to the new project flow for the same project category and product i.e. if user has accessed /new-project/visual_design/wireframes previously and closed the tab and opens the same marketing link  (/new-project/visual_design/wireframes) or refreshed the page somehow, we should take user to the project details form. However, if user clicks some different marketing link e.g. /new-project/visual_design/visual_design_concepts, we should show the incomplete project confirmation to user.

**Comment by vic-topcoder** [comment]
@vikasrohit let's not introduce the category as a part of the URL, this will create confusion in the future as categories can change, and projects in them also. It is much easier if the url is always following the `<url>new-project/{project_short_name}`

**Comment by vikasrohit** [comment]
@vic-topcoder Okay. Then we won't be able to track people who are leaving the project flow on project category selection screen.

**Comment by vic-topcoder** [comment]
As per our last conversation: product categories can have their unique URL to allow tracking. `~/new-project/{project-category}` and we'll keep all product URLs as `~/new-project/{project_short_name}`. This allows each page to have a URL and fluidity in moving products between categories, which would preserve the URL for deep links (we share with external services and pages).

**Comment by vikasrohit** [comment]
It should be up there in dev.

**Comment by mtwomey** [comment]
Awesome, thanks, @vikasrohit. Victor confirms this is as desired in dev. Kindly deploy to prod.

**Comment by vikasrohit** [comment]
@mtwomey Okay. These changes would go to production only after full changes for two tier menu are tested in dev.

**Comment by vic-topcoder** [comment]
@vikasrohit what's the latest status of this one?

**Comment by vikasrohit** [comment]
@vic-topcoder I have already pointed to the actual issue reported in this issue. Here it is again, https://github.com/appirio-tech/connect-app/issues/1104#issuecomment-329694958

In simple words, please try creating a project using link http//connect.topcoder-dev.com/new-project/wireframes, just enter the name of the project, refresh the page or reopen the link, now you would see the incomplete project confirmation wizard step. Is it desired behaviour? IMO, we should directly take user to the project details page in this case as user has opened the same link again. However, if user has clicked or opened a different project type link e.g. http://connect.topcoder-dev.com/new-project/frontend_dev, we should show the incomplete project step.

**Comment by vic-topcoder** [comment]
Yes, if the user opens the same link/reloads the page, we should skip the "incomplete project" page and just reload the last state of the same page. If the user loads another deep link before submitting the page, we should show the incomplete project screen. In that case clicking on the "create a new project" should redirect to the correct form from the last deep link instead of the project main screen.

Example:
User is working on https://connect.topcoder-dev.com/new-project/frontend-development, doesn't submit the project, somebody sends then a new link to open, and they click on https://connect.topcoder-dev.com/new-project/incomplete

We display the incomplete screen, and the user wants to create a project from the new link. They click on the "Create a new project" button. The wizard should respect the target page through the deep link and load the corresponding form (chatbot) instead of the main project menu.

**Comment by vikasrohit** [comment]
Should be fixed and change in dev env.

**Comment by vikasrohit** [comment]
Verified on production. Seems to work fine for me.
