### ISSUE TITLE
Add IBM chatbot as a project type

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#1106]
Can you please add "IBM chatbot" as a project, but make it accessible only as a deep link for now (/ibmchatbot), rather than adding it to the project catalog.

Here is the spec: https://docs.google.com/a/appirio.com/document/d/1Qp-vljS7vvt3jldsj_4ZVyYZP6NGBp1s5TFinB1zCSg/edit?usp=sharing. 

Please put in dev and we'll iterate from there with the chatbot team (Patrick, Clinton, Mess, etc.). Thank you.

**Comment by vikasrohit** [comment]
@fnisen I don't think we have ability to create dynamic and linked questions right now. By dynamic/linked I mean that selecting some value in one question show/hides another. Can we convert such questions to simple required textbox field? That way we can have it compulsory to answer and if they have some values for selecting a particular value in first question, they answer it in it. e.g. instead of asking `Do you have existing agent scripts?` and than showing textbox when user selects `Yes`, can't we ask `Please copy paste your existing agent scripts, if available, enter N/A if not.` or something similar.

**Comment by vikasrohit** [comment]
Deployed changes with non finished changes. As I described, it needs fix for the dynamic questions.  Right now I have shown only yes/no options for them.

**Comment by fnisen** [comment]
@vikasrohit I've changed the questions to not be dynamic, as you said: https://docs.google.com/a/appirio.com/document/d/1Qp-vljS7vvt3jldsj_4ZVyYZP6NGBp1s5TFinB1zCSg/edit?usp=sharing, along with some copy updates. 

Also, please remove the chatbot project from the project creation menu. We don't have a contract signed with IBM right now, and I don't want it to accidentally become public if we deploy to prod (that's why I only wanted the deep link to start).

**Comment by vikasrohit** [comment]
Done copy changes as well as hidden the Chatbot option from the `Select you project type` page.

**Comment by mtwomey** [comment]
@vikasrohit I'm closing, kindly advise (or reopen) if you want it open.
