### ISSUE TITLE
Spec form fields are not expandable plus styling issue

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#1107]
As a Manager, if I go to view a project of which I'm not a member, I cannot expand the spec form fields. For example, below, I can't grab the corner of the Description field and drag it down. 

It is also an incorrect grey color, which Didi has fixed here: https://github.com/appirio-tech/tc-ui/commit/1e4dcb6e9e04896da15d40a690871bc0e761adb5. Can you please deploy that?

<img width="1280" alt="screen shot 2017-08-09 at 5 34 00 pm" src="https://user-images.githubusercontent.com/12552247/29144994-185d9042-7d29-11e7-885a-b78c4dff0706.png">

**Comment by vikasrohit** [comment]
@fnisen I am able to expand the textarea even if it is disabled. Is it specific to any particular browser or OS?

**Comment by fnisen** [comment]
@vikasrohit are you trying it on a project of which you aren't a member? It works if you're part of the project and on some sections, such as Notes, but not otherwise. I'm on Mac OS 10.12/Chrome 59.

**Comment by fnisen** [comment]
Also, can you please deploy Didi's style change, as mentioned above?

**Comment by vikasrohit** [comment]
Yes, I tried on a project where I am not member. I am mostly certain about that because it was showing that dark grey background.

**Comment by vikasrohit** [comment]
I have asked Didi about those changes. It seems to me like we need more modification for disabled text boxes.
However, in any case it should be visible as soon as we deploy build for connect. So, it should be there right away as well.

**Comment by fnisen** [comment]
OK, waiting for Matt to fix the Manager permissions issue before I can test.

**Comment by vikasrohit** [comment]
@fnisen I am actually confused because the original screenshot shows that fields are indeed expandable. And Didi's changes in fact disabling the expandability of disabled text areas. Further, though, we may not be rendering text boxes (HTML input[type=text])we need to apply the same changes to text boxes as well, I think right they are only being applied to text areas (HTML textarea).

**Comment by fnisen** [comment]
@vikasrohit the text boxes do show that they're expendable (with the corner indicator), but they don't work when you actually try to expand. I don't know why Didi would have changed them to not be expandable. You can chat with her on Slack if she's online later or feel free to fix things directly, if you know what to do. 

In the end, we need two things: text boxes that are readable and expandable. : )

**Comment by vikasrohit** [comment]
@fnisen I have tried to make disabled textboxes readable with personal likes. Please let me know if we still want to tweak it. For resizable thing, I can resize the textboxes on both Safari and Chrome after removing the Didi's changes. Please see https://screencast.com/t/roCgczujV

**Comment by vikasrohit** [comment]
@fnisen Did you get chance to look into it?

**Comment by fnisen** [comment]
@vikasrohit I checked with Vic and the grey is not quite correct, but it's good enough for now. I think Didi might check in with you, but in case she doesn't, I'm comfortable pushing this out as it is and updating later.

**Comment by vikasrohit** [comment]
Okay. I think there was some confusion for the requirements here. Didi's changes removed background color completely from disabled text boxes which made them more difficult to identify and expand. Therefore, I added a lighter gray background to the disabled boxes. @sirakovaDimitrina  @vic-topcoder Please feel free to make changes as required.

**Comment by vic-topcoder** [comment]
I'm thinking through this and the obvious solution is to use the enabled form styles on the specification as it is really important to be able to read through the page easily. The only change we should do is to remove the "save changes" button at the bottom if you are a manager that can't edit the spec, instead of disabling the field and visually turning it dark gray. The goal of the page in terms of UX is to let everybody quickly READ through the form, not to prevent people form editing the form.

I think Didi did create disabled styles that match the normal text fields with content (white background, gray border) and empty fields (grayish fill and gray border) - it should be visually the same. It is all about reading through that information. Disabled should only lock the fields and don't let you change them, not prevent you from reading it. Right now the reading experience is visually broken with the dark gray elements.

The general rule of thumb is - if something is not allowed on a page, remove it (this is in regards with the "save changes" buttons).

**Comment by fnisen** [comment]
@vikasrohit ☝️

**Comment by vikasrohit** [comment]
I think Didi has already implemented the changes, I can't see any grey background there.

**Comment by fnisen** [comment]
Looks like it--thanks for checking.
