### ISSUE TITLE
Chatbot: spec page not showing validation errors

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#1131]
### Steps to reproduce the problem
- Create a chatbot project while logged out
- When prompted, log in
- Got to spec and delete information from text sections (e.g., Description or other questions); notice that validation is triggered, but no error message is shown
- Other project types don't trigger validations like this. Did you mean to add something new for the Chatbot project? 
- Related issue: https://github.com/appirio-tech/connect-app/issues/1133

![screen shot 2017-08-21 at 11 16 16 am](https://user-images.githubusercontent.com/12552247/29532691-2330c62c-8663-11e7-94a1-3e7584432a9e.png)

![screen shot 2017-08-21 at 11 16 27 am](https://user-images.githubusercontent.com/12552247/29532700-28d603e4-8663-11e7-82bf-8133ed6db6e3.png)

**Comment by vikasrohit** [comment]
@fnisen Yes, this and #1133 are happening because of the same reason. In other product templates we don't make these text fields required when editing the project. They might be required when creating project, but not when editing. So, they don't trigger any validation error when you edit them. However, with chatbot template, I we added the `required:true` even for edit templates as well.
So, possible fixes are:
1. Either don't make them required, for editing, as we are doing for other project templates OR
2. Add validation error texts to each of these fields so that we can show that when validation error is triggered.

**Comment by vikasrohit** [comment]
@fnisen Fixed #1133 assuming first option to be consistent. Please let me know the validation errors which we should show for project creation form though.

**Comment by fnisen** [comment]
@vikasrohit thanks--I agree with the approach. For the copy, I noticed you were using this on other forms: 

![screen shot 2017-08-22 at 11 03 30 am](https://user-images.githubusercontent.com/12552247/29580066-8e9f71a8-8729-11e7-9ca9-633122bedcd9.png)

I like how specific the copy is (one note: let's say "please provide a description"), but I'm thinking that this won't be scalable as we keep adding new questions. We could use one generic phrase for all of them: "Please complete this section" or have two generic phrases: "Please complete this section" and "Please answer this question" (when we're asking a question, rather than asking them to complete a section such as Description). Do you like either of these approaches?

**Comment by vikasrohit** [comment]
@fnisen Developer inside me says use a generic copy so that we don't need to update it for every new question or new template. However, I guess for users it would better to have specific copy. We have the feature in product template rendering that allows you to specify custom validation error for every required question without altering the core code. e.g. https://github.com/appirio-tech/connect-app/blob/dev/src/config/projectQuestions/ibm_chatbot.v1.0.js#L168. So you can specify custom ones or just copy paste the generic ones in the validationError field for each required question. I didn't added those because it was not easy enough to prepare them like it was for simpler fields like 'name', 'description' etc. 😬

**Comment by fnisen** [comment]
@vikasrohit OK, I see. Let's go with the simpler approach. I think the main thing for the user is to draw their attention. We already tell them what to do as part of the question, so we don't need to repeat. "Please complete this section" would be sufficient. Plus, I want to be sensitive to making the code less manageable.

**Comment by vikasrohit** [comment]
Okay. Done.

**Comment by fnisen** [comment]
@vikasrohit something is wrong with the capabilities section. It gets stuck in a validation error when I create project while logged out: 

![screen shot 2017-08-24 at 12 35 18 pm](https://user-images.githubusercontent.com/12552247/29684984-cd553824-88c8-11e7-8305-69d6479dc8db.png)

Also, while you're at it, can you please delete this question entirely (Pat didn't think it was relevant from the business side): 

![screen shot 2017-08-24 at 12 36 43 pm](https://user-images.githubusercontent.com/12552247/29685060-1bc284e4-88c9-11e7-87b6-d84b6dff1dee.png)

**Comment by vikasrohit** [comment]
It was build issue, it was using cached dependencies.  Should be fixed now.

**Comment by fnisen** [comment]
@vikasrohit it's working now---thanks. One more thing, please, as I mentioned above: can you please delete this question: "Are you an existing Watson Virtual Assistant customer?"

**Comment by vikasrohit** [comment]
Oh Missed that. Should be in dev by EOD.

**Comment by fnisen** [comment]
Hmm... not seeing it yet. Maybe it got overwritten by the messaging updates deploy. OK, I can wait until messaging updates is pushed out.

**Comment by fnisen** [comment]
OK, now looks right--thank you.
