### ISSUE TITLE
Chatbot: spec page file upload is not showing files after upload

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#1132]
### Steps to reproduce the problem
- Create chatbot project while logged out
- When prompted, log in
- Upload files, either directly or using Filestack dialog
- Notice checkmark in Files section (in Specifications component in upper left); however, files are not shown in Upload section
- Reload page; files are now visible in Upload section

**Comment by vikasrohit** [comment]
@fnisen Tried to reproduce the error, but unable to do so. I have tried both ways, I mean first by uploading files for existing project and second by creating a project in logged out flow and then going to Specification tab to upload files. It worked both times. I think, it must be taking some time to render the uploaded file and as we are not showing and progress icon, it might confuse user that file has not been uploaded. Or the case might be that #1133 might be causing this, so fixing that could have fix if any issue was there because of it.

**Comment by fnisen** [comment]
@vikasrohit thanks for trying. I'm not able to reproduce myself either now, so maybe it was an API blip. Closing.
