### ISSUE TITLE
User's name is missing on team panel (Project 870)

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#1144]
Username: maxprize; admin tool is showing that he registered with a first and last name, but on Connect he comes up as "null null"

![screen shot 2017-08-24 at 2 22 45 pm](https://user-images.githubusercontent.com/12552247/29689378-db866e9a-88d7-11e7-83a1-c0f63de10c67.png)

fyi @talesforce

**Comment by vikasrohit** [comment]
@fnisen I tried to debug it and found that it could be handled like we are handling null values in feeds/messages i.e. showing 'Connect user' in such cases. However, the problem in this case is that the api is returning null values as string which we the code would not be able to identify because it has an non null value 'null'. One solution is to compare the strings to not to be 'null', 'undefined' as well, but that won't be a good solution.
I can try looking into API as well and see if the problem is with actual data in ES cluster or API is handling it in wrong way.

**Comment by fnisen** [comment]
Thanks @vikasrohit. Yes, can you please look into this more deeply? I'm seeing the user's name in the admin tool, so it exists in Informix. Maybe the issue is with the ES cluster.

**Comment by vikasrohit** [comment]
@fnisen @talesforce I looked into the ES cluster and found that it has 'null' values (as string) for the firstName and lastName fields. I have updated the record in the ES cluster to fix the issue. Please let me know if issue is still there or anything similar to this is happening for the same user.

**Comment by fnisen** [comment]
@vikasrohit yup, it's working correctly now. Well done!
