### ISSUE TITLE
Extend project specification with important data

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1173]
We want to collect budget and expected deadline - this helps to qualify projects

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-23

**Comment by vic-topcoder** [comment]
Test one two three

**Comment by vikasrohit** [comment]
@vic-topcoder I think we are already fetching budget and expected duration of the project via direct api. Is this something else?

**Comment by vikasrohit** [comment]
bump up @vic-topcoder  Do we need anything different from what we are showing for budget and duration?

**Comment by vic-topcoder** [comment]
We want new fields on project creation/specification to pass to SFDC. The existing fields from Direct are not useful for managers working on Connect + SFDC. I'll have to provide updated design, for the time being I think we have to add those as two text input fields above notes in project creation for all projects.

**Comment by vikasrohit** [comment]
Okay. Please let me know when we want to add the new fields. I think we just need to add these two fields to project questions templates for each project type and rest the framework would take care of it. I am afraid that we would be able to customize the look and feel of these two new fields.

**Comment by vic-topcoder** [comment]
Let's add it for the release. Have to confirm if we can send the data to SFDC.

**Comment by vikasrohit** [comment]
@vic-topcoder I think we need to decide on type of the those fields as well. I mean if we make them a textbox that would not serve the general purpose and people might fill it with bad data and further we won't be able to use this data in reporting. On the other hand we also need to allow users to fill some kind of flag value for the case they don't have any estimation on their budget or timelines.
I think we should have it as a dropdown where we can have range of values e.g. for budget we might have 5000-10000, 10000-15000, 15000 and above (I am not best suitable person for this range selection, I think Joey can help us here) and similarly for expected deadline we can have 1 week, 1-3 weeks, 3-5 weeks, 5 weeks or more. 

Also, do we need to map these two new fields to the corresponding fields in direct? If yes, it would require more discussion about synching values between the two.

**Comment by jpoarch** [comment]
Great timing -- we discussed this last week and here's what we would like to have as mandatory fields to _submit_ a project:

**Do You Have Budget?** 
Three options: a. I have no idea, that's why I'm here, b. I have a rough window in mind, c. I have an established budget to the penny

**Project Budget**
I would prefer to give them the ability to put in a budget vs. a range, but I could be convinced otherwise. We could potentially do: a. $500-5000, b. $5000-15000, c. $15000-30000, d. 30000-50000, e. 50000-100000, f. $100000+

**When do you want to get started?** 
Options: a. I Need to Start ASAP, b. In the next month or two, c. More than two months out, d. Just looking for an estimate

**When do you need the project to be completed?**
Options: a. 2 weeks, b. 1 month, c. 2 months, d. 3 months, e. Just looking for an estimate.

**Comment by vikasrohit** [comment]
Thanks @jpoarch for the update.

> I would prefer to give them the ability to put in a budget vs. a range

No issue with that if we are asking about having a budget in separate question. However, the current system does not support linked questions i.e. question which changes options or hide/show itself based on another response to other question by user. So, if we are okay with two questions per item (e.g. budget) which are not dynamic, we can implement these set of questions.

> Options: a. 2 weeks, b. 1 month, c. 2 months, d. 3 months, **e. Just looking for an estimate.**

I think we already have the **Just looking for an estimate.** option available in its previous question. We can in fact have this as text box if we ask users to put estimates always in weeks(or month).

**Comment by jpoarch** [comment]
I'm ok with that if we have the same answer for two -- because the other options for each are different. Getting started vs. having the project complete are two different things.

**Comment by vikasrohit** [comment]
Okay @jpoarch Are you okay with two unlinked questions for budget? Meaning changing option in `Do you have budget?` question would not affect the next questions `Project Budget`.

**Comment by jpoarch** [comment]
Yes - two unlinked questions will be fine.

**Comment by vikasrohit** [comment]
Cool. Would it be okay for you @jpoarch to have it released next week? There are two releases colliding this week, one is for mobility testing product being added to the catalogue and another is where this issue is allocated. I would like to have some testing before adding these new fields to all project templates.

**Comment by jpoarch** [comment]
Next week would be great. Does this mean we will go back to draft projects as well and have a "submit your project" along with these? We would like these to be required to submit, but not to create a draft.

**Comment by vikasrohit** [comment]
> Next week would be great.

Thanks, that would take some load off from me this week. 👍 

> Does this mean we will go back to draft projects as well and have a "submit your project" along with these?

We are bringing back draft project along with 'Submit for Review' button, this week only. We would be doing production release tomorrow for this.

> We would like these to be required to submit, but not to create a draft.

I think technically we can do that. However, I think basic idea for new project wizard to ask for the mandatory fields only. So, if these two fields are not mandatory, we can skip showing them in new project wizard, however, user has to set these when editing a project before submitting it for the  review.

**Comment by vikasrohit** [comment]
@vic-topcoder @mtwomey Moved to next week's release.

**Comment by vikasrohit** [comment]
@jpoarch If you get chance, can you please have a look at https://connect.topcoder-dev.com/projects/1905/specification? I have added the new questions for website projects and temporarily deployed it to dev.
If you have any suggestion to improve the intake for these new questions, please let me know.

**Comment by jpoarch** [comment]
How do I access that page? Gives me login, but my account doesn't work in Dev.










On Tue, Oct 24, 2017 8:22 AM, vikasrohit notifications@github.com  wrote:
@jpoarch  If you get chance, can you please have a look at 
https://connect.topcoder-dev.com/projects/1905/specification? I have added the
new questions for website projects and temporarily deployed it to dev.
If you have any suggestion to improve the intake for these new questions, please
let me know.

**Comment by vikasrohit** [comment]
@jpoarch I will ping the password on slack DM. Please try this link in private browsing so that cookies does not mess with your production account login

**Comment by vikasrohit** [comment]
Did you get chance to look into it @jpoarch ?

**Comment by vikasrohit** [comment]
@jpoarch are we good to replicate the same for other project types?

**Comment by vic-topcoder** [comment]
@vikasrohit @jpoarch great work on the feature. I would recommend we use radio buttons instead of drop-down. The drop-down (select) is the worst UX for a form, so we should avoid it at all cost. Also - coming up with a smaller range would be better - we have a bit too many options for a customer to pick from. Ideally it'll be a range between 3 and 5 options to pick from (going with 3 would be the best).

@vikasrohit please let me know if we need design for the feature as it is not very user friendly as it is, albeit functional.

**Comment by vikasrohit** [comment]
@vic-topcoder The problem with radio buttons is that they are wrapping into two lines which is not looking good. 

<img width="782" alt="screen shot 2017-11-01 at 3 40 28 pm" src="https://user-images.githubusercontent.com/2417632/32270241-113facda-bf1b-11e7-84bb-5ab44d0f41e2.png">

**Comment by vikasrohit** [comment]
@vic-topcoder do we have updates on this one?

**Comment by vic-topcoder** [comment]
Let's use a smaller range for the users (up to 4 options) and reuse the slider control. This makes it easier to read through.

![screen shot 8](https://user-images.githubusercontent.com/8484061/32475324-06f00b44-c326-11e7-8824-750e87977180.png)

If we need to refactor/restyle the control, let's use the community for that. Live spec is here: https://drive.google.com/drive/folders/1z52tVcNRlXYeaOAogBqtmrc2OvcIxSXj?usp=sharing

**Comment by vikasrohit** [comment]
> Let's use a smaller range for the users (up to 4 options) and reuse the slider control

I guess you are referring to the slider we used for Project Creation popup last year. If yes, that component was hard coded to 3 options because of inability to generate the background image dynamically based on number of options.
I think that component is not used anywhere now and we can create a new component from scratch instead. Using community would take more time because we have to complete the full challenge life cycle.  In any case, I think creating a new slider component would cause delay of couple of days in release.

**Comment by vikasrohit** [comment]
@vic-topcoder I think I got it. I found a good library for rendering the slider and added our customizations to it to make it look like designs. I think I would be able to get it done by tomorrow EOD.

**Comment by vic-topcoder** [comment]
Awesome :) 👍

**Comment by vikasrohit** [comment]
@vic-topcoder @jpoarch I am able to add these new fields to SFDC as well in following format.

<img width="266" alt="screen shot 2017-11-09 at 5 16 48 pm" src="https://user-images.githubusercontent.com/2417632/32603991-d840281c-c571-11e7-9636-77a06a8b0624.png">
Please note it save the id of the options we show on UI for budget type, when to start and deadline questions.

**Comment by vikasrohit** [comment]
Okay, I would take care of these issues today.

> Slider can't be activated/selected when the very first item (left most) is clicked. Once the slider has 1 element selected, the click event changes the selection. Please fix this.

@vic-topcoder This is happening because of one of the workaround I have made for configuring rc-slider component to behave like a radio button. Technically Sliders are not radio button or groups. The problem is that all slider libraries don't support null default value i.e. they always put slider to minimum position when we don't supply any value to them. To overcome this I did a CSS trick to hide the default selected value which in turn is causing the concerned issue. I would try to fix it, however, I am not sure how to do it without making changes in the library itself. The other solution is to create our custom component for this which require more time.

**Comment by vikasrohit** [comment]
> Modify the Notes label to read "Add any other important information regarding your project (e.g., links to documents or existing applications)"

@vic-topcoder I have updated notes section description as per suggestion. It is done for all project templates except mobility and real world testing because those two have different copy (`Please enter any additional information like requirements and/or test cases.  After creating                   your project you will be able to upload files.`) for notes. If you like to update them as well, please let me know.

**Comment by vic-topcoder** [comment]
Yes, that works for me. Closing the issue :) Thanks!
