### ISSUE TITLE
Main page/product select logo to be a link

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1206]
The logo on main page and category page should be a link to connect home page.

In the logged in state logo should behave as escape/close.

**Comment by vikasrohit** [comment]
@vic-topcoder I think it was actually a bug due to which it was showing topcoder logo in new project wizard modal for logged in user. I think we decided earlier to not have logo for logged in user in modal. Hence, I have fixed that bug as part of this fix.
Please let me know if you still we need the topcoder logo in project wizard modal. Please note logo was visible only for the first step of the wizard.

**Comment by vikasrohit** [comment]
Closing
