### ISSUE TITLE
Real World Testing project name isn't editable

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1209]
Can't edit the project name - probably the same issue with not displaying project type/name on dashboard?
![screen shot 5](https://user-images.githubusercontent.com/8484061/31006971-bd231f0a-a4b3-11e7-9f20-adc82b3423d0.png)

**Comment by vikasrohit** [comment]
@vic-topcoder Project Name is not an editable field once project has moved past 'draft' status.

However, I have fixed the issue with saving of testing project after any other field update. It was because of wrong template fields. Just for information, we should keep all dynamic fields, i.e. fields which are specific to the project type, should be kept under `details` json. Please check the updated project template now for reference. fyi @wdprice

**Comment by vikasrohit** [comment]
Closing
