### ISSUE TITLE
Generic chatbot project URL

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1223]
The new Chatbot project creation URL should be `https://connect.topcoder.com/new-project/chatbot`

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-73

**Comment by vikasrohit** [comment]
@vic-topcoder we already have `chatbot` project category support in our previous release for two tier menu. `chatbot` is a generic category for all chatbot products that we might support in future. Watson chatbot `watson_chatbot` is one of those products. And now we have a new generic chatbot product so it could be given an unique id something like `generic_chatbot`, so the URL would be `https://connect.topcoder.com/new-project/generic_chatbot` not `https://connect.topcoder.com/new-project/chatbot`.
FYI, we can not have two products or two product categories or mix of them, to have the same id because we have to determine the product or project from the URL.

**Comment by vic-topcoder** [comment]
Ok, thanks, I'll review with marketing for SEO. We can change the category URL to not take important text, right?

**Comment by vikasrohit** [comment]
>  We can change the category URL to not take important text, right?

Didn't understand. We can not change category URL now for any of the project because we are using id of the project category to fetch the correct category.

**Comment by vic-topcoder** [comment]
Ok, for Chatbot projects category I want the URL to be `/new-project/all-chatbots` and the generic chatbot to be `new-project/chatbot`, Watson chatbot should be the same URL. The URL should be free to be modified from the ID as this is SEO-focused. Please make it as the above

**Comment by vikasrohit** [comment]
> The URL should be free to be modified from the ID as this is SEO-focused

I don't think it is possible. In any case we have to include an id in the seo url. e.g. stackoverflow adds question id before making it seo friendly like this https://stackoverflow.com/questions/820493/can-an-seo-friendly-url-contain-a-unique-id

> Watson chatbot should be the same URL.

How can two different products have same URL?

>  I want the URL to be /new-project/all-chatbots

I am afraid it is possible now because we already have a category for chatbots and its id is `chatbot` so it would be `/new-project/all-chatbots` for showing all chatbots products. If we change it to anything else, we need to update production database manually for all chatbot projects which were created after our last release. If we don't have chatbot project in system after our last release, we can do this change. @mtwomey Please let me know your thoughts.

**Comment by vic-topcoder** [comment]
My bad - Watson URL is the same should read "the Watson URL shouldn't change".

We have a new URL for categories, and ideally we should use the same naming pattern. I would suggest we use `/all-categorytype` -  so design project category page will have URL as `~/all-designs`, chatbots: `~/all-chatbots`, development `~/all-development` to make it consistent. This would allow us to have a singular name for project templates and better SEO.

**Comment by vic-topcoder** [comment]
We did the modification to the project ID and category ID, so the things are as desired right now. I would strongly suggest to name any collection as plurals, to better represent it. That's why I renamed `chatbot` to `all-chatbots`. If we refactor other categories they would become `all-designs` and `all-software` (software is non-countable). The changes are in Dev and we figured out what is needed - in #1236.
