### ISSUE TITLE
Functions of the "Connect Logo", "Back", "Esc" buttons in logged in and logged out states

### ISSUE THREAD

**Issue by mtwomey** [appirio-tech/connect-app#1234]
## Solve along with #1035 ##

Note the below requirements refer to using the project creation screens:

* While the user is logged in
* While the user is logged out
* When the user has arrived at the project creation page (or sub-page) through the use of a direct (or deep) link

_Connect Logo Button_
The Connect Logo button in the upper left should appear during the first project creation view (selecting project type) when logged in. When the user clicks that button, nothing should happen.

_Back Button_
In the category and project creation views, the "Back" button should appear in the upper left.

* If the user clicks it while on the category view, they should be taken to the first project creation view
* if the user clicks it while on the project creation new, they should be taken to either the corresponding category view, or the first project creation page (as appropriate)

_Escape Button_

The "Escape Button" should appear (in the upper right) on all project creation pages. When the user clicks this button they should be taken to the connect home page (a page reload is fine if needed). 

Note: In the case of a logged in user, this will result in displaying the project list and in the case of a logged out user, this will result in the displaying  the connect landing / login page.

**Comment by vikasrohit** [comment]
@vic-topcoder @mtwomey I have updated the code so that now it would not use modal for project creation for a logged in user. So, it would be similar to the non logged in view. It solves #1035 as now without modal, URL changes would work fine.
However, I still need to fix few things around non logged in view though. Today I got stuck with a complicated issue in handling incomplete project screen and its after steps. I think it would take one more day to fix this issue and be able to release it.
I am pushing latest and greatest into dev so that you can play around with it and let me know your feedback.

**Comment by vikasrohit** [comment]
@vic-topcoder Did you get chance to play with it? Please let me know if you found any issue with it. I would be doing more testing today on dev.

**Comment by vikasrohit** [comment]
Verified on production. Seems to work fine to me.
