### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by vic-appirio** [appirio-tech/connect-app#124]
We need a super basic landing page. Speck is here https://drive.google.com/drive/folders/0B1LbmKnex41fR3BmLUR6Mzd3Tms?usp=sharing

**Comment by mahestro** [comment]
Hey @vic-appirio, landing is almost ready but I want to bring the same topic as the nav, breakpoints.

http://take.ms/9QEOV

Do we want to support full responsiveness now? As you can see in the video, we'd need to use different breakpoints if the content needs to be displayed properly.

A quick solution that follows the current guidelines (not responsive) is to show the 768 version (which has the panel width set at 720) starting from ~1240 but it would break too early, kind of same case as the nav.

Let me know what you think.

**Comment by vic-appirio** [comment]
I was thinking more of a scaling the image as the page gets smaller until it breaks into 1 column. We can break at 1024 for 2 columns and scale up.  See how the images scale here before the column count changes? I would assume we use the same mechanics: http://vic-tor.com

**Comment by mahestro** [comment]
Hey @vic-appirio, take a look a this solution.

[landingpage_v7.zip](https://github.com/appirio-tech/connect-app/files/491082/landingpage_v7.zip)

**Comment by vic-appirio** [comment]
Cap the maxi-width of the page to 1200px and we're good to go!
![screen shot 2016-09-26 at 5 42 10 pm](https://cloud.githubusercontent.com/assets/8484061/18856574/9f905d00-8410-11e6-8431-c2d4eb7c66cc.png)

Good job. Also - let's get this implemented.

**Comment by mahestro** [comment]
Perfect! Moved to implementation.

**Comment by mahestro** [comment]
In prod now. There are a couple of todos I need help with, maybe from @parthshah or @vikasrohit:
- Bind link action to "Register for free" and "Learn more" buttons - where to? @fnisen 
- Header should have only one button as shown here - http://take.ms/Pr1y2. The way the layout is composed right now made it tricky for me to complete this part since the overall structure adds both buttons separate from the landing page instance. I didn't want to mess it up, so Parth or Vikas, if you could please take a look at it I'd appreciate it.

With those two items done we close the issue.
