### ISSUE TITLE
Qualify projects flag

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1248]
There's a need to mark a project as qualified from SFDC (Salesforce), and it depends on project budget and expected timeline, amongst other things. The request is to allow a project to be qualified from Salesforce and this flag is transitioned to the Connect project. It should also be established in Connect - a way to modify the flag. The flag is binary (Yes/No).

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-24

**Comment by vikasrohit** [comment]
@vic-topcoder we need to do changes in salesforce for having qualified flag set on projects from salesforce. We can only do it the other way around from connect.

**Comment by vikasrohit** [comment]
@vic-topcoder There is already a flag called `MQL` in saleforce which is in fact what call Marketing Qualified Lead. So, I guess we can use that flag for this purpose. Can you please confirm with the feature requester about the same?

**Comment by vic-topcoder** [comment]
Ok, spoke with Joey today. The `MQL` field in SFDC should be synced with the Connect project. We want to show this flag only to managers. Let's pause this feature for the moment, I need some design on the dashboard to show to managers/admins.

**Comment by vikasrohit** [comment]
@vic-topcoder I am working on this issue from salesforce side. I mean I am working on updating connect data from salesforce whenever some one updates the MQL flag in salesforce lead. For propagating this flag from Connect to Salesforce, I would suggest not to add that functionality at all because we should make applications owners of their data i.e. data generated by Connect should be updated only by Connect and data generated by Salesforce should be updated only via Salesforce. In this particular case, MQL is owned by Salesforce and hence we should not update it from Connect unless until it is very critical. One rationale behind this is separate ownership makes it easy to understand/debug the flow of data and second rationale is to avoid any loop forming e.g. we update something in connect which triggers update in salesforce which in turn trigger unnecessary update back into Connect.

**Comment by vikasrohit** [comment]
Also, fyi, I am working on https://github.com/appirio-tech/tc-connect2sf/issues/22 simultaneously because it is becoming error prone to add new fields, which are to be synced to salesforce from connect,  into that integration application(`tc-connect2sf`).

**Comment by vikasrohit** [comment]
@vic-topcoder I am almost done with changes in Salesforce side for propagating the MQL flag from salesforce to Connect. Right now there is not visible changes in Connect which shows you the MQL flag being set, however, if we have UI for showing qualified flag and filtering projects on qualified flag, the changes would be visible.

**Comment by vic-topcoder** [comment]
Awesome. At the moment Joey & team couldn't justify the feature and the flow, so I will keep it on hold. According to Joey they need this flag in their SFDC workflow, not necessary on Connect. Ideally we would have project tags in the future that would help with search/filter.

**Comment by vikasrohit** [comment]
@vic-topcoder Do we have updates from Joey and team about this?

**Comment by vic-topcoder** [comment]
Not going to work on this for a while. Closing issue

**Comment by vikasrohit** [comment]
Okay, I have to revert the changes. :(
