### ISSUE TITLE
Navigation small updates

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1267]
It would be nice to update the Connect navigation to be a bit more user-friendly.

Design is here: https://drive.google.com/drive/folders/0B1LbmKnex41fcDc0eVFPcldLckU?usp=sharing

**Comment by vikasrohit** [comment]
@vic-topcoder There is a `+` icon just before the user dropdown in the navigation bar. I am not able to understand what it is for.

**Comment by vic-topcoder** [comment]
![transition-updates-dashboard-update](https://user-images.githubusercontent.com/8484061/32179273-3b4d1a2e-bd4c-11e7-9d78-aee1f1fa6f9e.png)

**Comment by vikasrohit** [comment]
But we didn't have the new project button on project details page earlier, so it is new feature, right? And should we show this button to customers as well or this should be there only for power users.

**Comment by vic-topcoder** [comment]
Show it for power users currently. Thanks!

**Comment by vikasrohit** [comment]
@vic-topcoder I have tried yesterday and today to get this new button on project details, however, I am facing a technical issue with it. It is because the way we have to manage the state of the container of the ProjectWizard. I am not saying that it is not possible at all, but it needs workaround to get it done. I might not have good product manager skills, however, ideally we should not have a link to new project from details page.

**Comment by vikasrohit** [comment]
Just for logging, following is the trail and fix for the problem faced because of new project button on details page.

In the CreateContainer we are validating `project.id` prop in the next prop to determine if a new project has been created by the wizard. This logic was causing redirecting back to details page when user clicks on the new project button from the details page because it thinks that a new project with id of the current project is created and redirects to its details page. As a fix, now we are checking if current property value for `project.id` is not defined and next property value is defined to determine that new project is created. Further, we have to clear the project from the redux state when CreateContainer is mounted.

**Comment by vic-topcoder** [comment]
Ok, sounds good. Let's have a solution that would allow us to create projects from different pages. Thanks!

**Comment by mtwomey** [comment]
@vikasrohit Can you advise if we still think this is doable by the end of the week? We're trying to wrap up Project Listing Updates milestone this week (sorry to pressure, just like your thoughts).

**Comment by vikasrohit** [comment]
@mtwomey yes it is mostly done. I am open for any issues or mismatch from specs.

**Comment by vic-topcoder** [comment]
Great progress so far. Small changes are still needed:
Project listing/main page - **Customer**
- [ ] Remove the underline on active tab
- [ ] Tabs should be flushed left to the logo (40px between logo and navigation)
- [ ] Let's bring back the create new project (circle with plus) button, copy from the project details page

Project details page:
- [ ] Title text is not up to spec - font size should be 20px
- [ ] new project return target should be project page (starting point) on Exit/Cancel

**Comment by vikasrohit** [comment]
> Remove the underline on active tab

**Comment by vic-topcoder** [comment]
- [ ] Project navigation should always be next to the logo (40px between logo and navigation). This can be done if we move the navigation within the logo container and space the 3 big containers evenly through flex layout. Small changes in the CSS would be needed - display: inline-block; vertical-align: top; to make sure all elements are correctly aligning as the screenshots below:

![screen shot 15](https://user-images.githubusercontent.com/8484061/32678487-64de1978-c617-11e7-9d21-2a9c8b85ed65.png)

**Comment by vikasrohit** [comment]
> Project navigation should always be next to the logo (40px between logo and navigation). 

Done, however, the css rules you mentioned didn't work somehow, may be you had made more changes to make it look like what you want. I guess my changes also achieves the same result. Please let me know if this is not the case.

**Comment by vikasrohit** [comment]
> new project return target should be project page (starting point) on Exit/Cancel

This is the only item pending, others are fixed. Let me know what exactly is wrong here.

**Comment by vic-topcoder** [comment]
- [ ] The project navigation is not changing when the customer enters a project
![screen shot 2](https://user-images.githubusercontent.com/8484061/32746301-0851a47c-c86a-11e7-97e1-11899c0d475a.png)

> new project return target should be project page (starting point) on Exit/Cancel

When you open the "New project" menu from within a project, escape should lead back to the point of origin/page where you clicked the button. Right now when you use cancel you go to home page instead of starting page (project)

**Comment by vikasrohit** [comment]
> The project navigation is not changing when the customer enters a project

@vic-topcoder The problem is that we have separate components for Projects tool bar and project tool bar and there is a separate container component which host one of these two components based on the route. Now, there are some common components which both tool bars show e.g. Logo and user dropdown menu. So, naturally, they reside in the container component. Now the trouble is that because we want very specific requirement for having this new menu bar inside logo wrapper (which is a common component and reside in the container component), it reflects in both tool bar. Now there are couple of solution to this:
- Move common components (Logo for now, but in future we might have some other specific requirement which requires all other common components to be replicated in both tool bars) to both tool bars.
- Add the logic of determining the context/route in container component which would inject the MenuBar only when there is appropriate route is loaded.

These both options are not as per best practices and can pose difficulties in debugging/enhancing these components in future. This is one of the examples where we have to deviate from standard practices to achieve some specific requirement.

**Comment by vikasrohit** [comment]
> new project return target should be project page (starting point) on Exit/Cancel

Done.

> The project navigation is not changing when the customer enters a project

Fixed this one too.

**Comment by vic-topcoder** [comment]
Ok, tested on Dev, seems good, closing
