### ISSUE TITLE
Watson chatbot content updates [priority]

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1297]
Need to update "IBM Bluemix" to "IBM Cloud"

Source: {Do you have an existing IBM Bluemix account?}

Should become: “Do you have an existing IBM Cloud (formerly IBM Bluemix) account?”

Can we update and release please? Thanks!

**Comment by vic-topcoder** [comment]
@vikasrohit Let's get this out as a Hot Fix to Production ASAP; legal issues with IBM.

**Comment by mtwomey** [comment]
Fixed.

**Comment by vikasrohit** [comment]
My sincere apologies @vic-topcoder as I missed to update you about this. Actually, I think I lost this in mails and actually the title of this issue is same as of other one where we added the disclaimer to the watson, so my mind made me believe that I have already taken care of this.

Thanks @mtwomey for helping out.

**Comment by vic-topcoder** [comment]
Thanks guys! It is in production and we should not lose it once we get DEV into Prod.
