### ISSUE TITLE
Load all active projects for customer card view

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1326]
Continuation from #1321 - we don't load all projects for users on first pass. Let's load all the projects for the customer card view (remove the hard limit of 20, let's monitor the data and see if there is performance penalty, if yes - lest's implement lazy load (similar to challenge listings on community-app).

**Comment by vikasrohit** [comment]
>  lest's implement lazy load (similar to challenge listings on community-app).

You mean infinite loading?

**Comment by vikasrohit** [comment]
@vic-topcoder  Added infinite scroll to the customer’s view. It was necessary to load projects in paged manner because API does not support loading all project at once. API has hard limit of 20 for loading projects. As of Infinite scroll is causing two load calls when user scrolls to bottom, hence we might need to go with a simple load more button.

**Comment by vic-topcoder** [comment]
Is it possible to hide the button at the end of the list and put a label "end of list" so people don't keep hitting the button? I mean - do we keep a counter of projects per person or not? If it is not possible, the feature is good to go.

**Comment by vikasrohit** [comment]
Yes, its possible. Done.
