### ISSUE TITLE
Navigation: Responsive breaks too early

### ISSUE THREAD

**Issue by vic-appirio** [appirio-tech/connect-app#135]
The navigation breaks into responsive too early and doesn't uses the full width of the space available effectively.

https://monosnap.com/file/Di2cwCULizqTKo6ncc1BOgAeJakgbP

**Comment by mahestro** [comment]
I saw this coming @vic-appirio :) Time to fix it. I have a doubt though.

That breakpoint had to be set that short because it was the only css possible solution for the particular case of the nav. Since they both, project and home, share the same markup/css, they're affecting each other. The home view has room to break later but the power owner project view needs to break that early (http://take.ms/5RMmf) because of the spacing, otherwise it would be visually broken.

A possible solution would be to use Js to assign a css class to the nav depending on the current state of the app (home or project) helping the nav behave properly.

**Comment by vic-appirio** [comment]
Also - resize the search bar to accommodate for space. I trust your decision. The break should occur around 1024 - on tablet size. I believe there is enough space around for full labels and title at 1024+ size; the same for search.
