### ISSUE TITLE
Project status mismatch on listing and dashboard

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1364]
Project shows canceled in list view (admin/manager), but active when you open the project. Active status is correct.
<img width="512" alt="screenshot_1024" src="https://user-images.githubusercontent.com/8484061/33349073-80c97d8c-d44d-11e7-9442-ffaf96729593.png">
<img width="430" alt="screenshot" src="https://user-images.githubusercontent.com/8484061/33349078-83bd8fce-d44d-11e7-93ba-65287174d351.png">

Let's try to figure out what causes the mismatch and fix it. This is important.

**Comment by vikasrohit** [comment]
@vic-topcoder  This happens when there was some error during project status update. It causes ElasticSearch not be updated with correct data but Postgres database gets updated. However, in this case, project was cancelled 3 months ago and was submitted for review again about a month ago. I was under impression that we were not allowing cancelled or completed project to be updated, may be I have false memory here.

**Comment by vikasrohit** [comment]
@vic-topcoder I know the issue is there, however, I am not able to reproduce it on local or dev as of now. I think better is to do the quick fix on production as I suggested above and observe if this issue happens to repeat itself often.

**Comment by vic-topcoder** [comment]
@mtwomey can you please chime in and help investigate: We have reports that projects get different status reported on project list and project dashboard. What would cause such a mismatch? How can we prevent such things happening? Is there a way to find how many projects we have with such a mismatch and fix them? We'll have to loop in Joey's team to validate which status is the correct one.

**Comment by vikasrohit** [comment]
@vic-topcoder @mtwomey  first cause of this mismatch is mis match between ES(ElasticSearch) and DB data. And most probably the reason behind that is a failure(most probably it should be a temporary error) in call to ES when trying to update it. However, we should still look into it to find the root cause of the error. I doubt there can be some issue with update schema of the ES which might be throwing error when trying to update it.

**Comment by vic-topcoder** [comment]
@vikasrohit Please review #1414 as well

**Comment by sachin-maheshwari** [comment]
@vikasrohit as tried on local system, **unable to reproduce it with normal/general scenarios** even concurrent requests with different status. I am only possible to reproduce by manually stopping publishing message through code. So looks like, in this case either message was not published or lost in MQ. 
Currently I am not sure about the possibility of lost in MQ on current deployment, need to further investigation on AWS. 

ES case you have already mentioned so I am repeating here the possibility of that. 

Also you have already suggested the quick way to resolve this case by changing status.

I didn't get any similar case on dev environment. I parsed all the records of dev environment with the help of a script which need project id and its status from DB - project listing status I can access it from listing API directly through this script. So if I get the production project id and status from DB, I can get the affected records.    

On concurrent request got following response - {"success":false,"status":500,"content":{"message":"could not serialize access due to concurrent update"},"debug":"SequelizeDatabaseError: could not serialize access due to concurrent update.....

**Comment by vikasrohit** [comment]
Thanks @sachin-maheshwari for looking into it. @vic-topcoder  May be we can close this one for now and revisit it later if we get new such instances.

**Comment by vic-topcoder** [comment]
Ok, closing. Thanks guys!
