### ISSUE TITLE
Allow Admins and Managers to add other Managers to a project

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1370]
Admins and Managers should be able to add other Managers to projects. Currently we support only Copilots and Members. This would require that we verify managers/admins to have a right to view who are Managers.

 

Suggested update:

- Move the user group selector on top of the user lookup input, and allow for lookup within the user group only.
- When I want to add a Manager, I would select the "Manager" and when typing it would show show members with Manager user role only. The same applies for Copilots (should show only from the Copilots pool).
- When I want to add a team member, I should not be able to add Copilots or Managers as Members (exclude them).

Design:

Screen Shot.png (https://topcoder.aha.io/attachments/6493676187103044787/token/f17810961f2e670a1d118fb858fb7df735e3745d756ff76a61838b506b7312d1.download?size=original)

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-109

**Comment by vic-topcoder** [comment]
From Vikas: Technical problem with automatically detecting role of the user being added, is that we don't have any API to get roles of a user who is not logged in and this is done for security. So, we can't determine the role of a non logged in user, hence can't automatically add a manager as manager. The other way is as Filipp described, to add a role selector for Manager role, however, user can add any user as manager in that case.

**Comment by vikasrohit** [comment]
@mtwomey Do you have any workaround for handling security issue in exposing the user roles?

**Comment by vic-topcoder** [comment]
It is required at some point for managers and connect admins to view all members and manage user roles in the app. We should approach the data the same way our current admin tool does, I assume it is quite secure. This should be platform-wide and standardized.

@mtwomey any ideas on how we can get around the block quickly?

**Comment by mtwomey** [comment]
@vikasrohit @vic-topcoder 

```https://api.topcoder.com/v3/roles``` get you the group names and IDs
```https://api.topcoder.com/v3/roles/4?fields=subjects``` gets you users that have a given role

(you need to send an auth header with these calls)

Do we still have a security issue if we only allow admins to use the box to add copilots or managers?

**Comment by vikasrohit** [comment]
Yes, @mtwomey These endpoints are there but they require token of an user with `administrator` role, I guess.

> Do we still have a security issue if we only allow admins to use the box to add copilots or managers?

I guess no, if only allow users with `administrator` role to add managers. That means people with `Connect Admin` role won't be able to add team members as managers. We have to add `administrator` role to all such `Connect Admin`(s) who we need to allow adding Managers. However, IMO, it would increase the confusion among users because some `Connect Admin`(s) would not be able to add managers while other will be.
And if we don't allow `Connect Admin`(s) to add managers to projects, that defeats the purpose of creating this role.
And if we allow `Connect Admin` role to be able to query the the roles via the APIs mentioned by @mtwomey it would make those endpoint weak as down the road we might need to add more roles (may be coming from different applications) which needs to access the roles of other users and it would continue on weakening those endpoints and we might end up with a serious security bug where hackers are able to determine role of a user or users with administrator roles and than try attacking only those users to break in to the system. I know I am too pessimistic here, but we should either be strict about restricting access to those endpoints to `administrator`(s) or should allow all users to query other users of their own roles.

**Comment by vic-topcoder** [comment]
@vikasrohit @mtwomey - we need to allow 
- `Connect Manager` role can view and add  `Connect Manager` and `Connect copilot` when in project; 
- `Connect Administrator` role can view and add other `Connect Manager` and `Connect Copilot` at all times;
- `Administrator` would be a special role that can access TC Admin to grant rights to users.

I want to have `Connect administrator` and `administrator` roles completely separated.

**Comment by mtwomey** [comment]
I would propose that we update the existing v3 api (or even create a new one) that specifically allows users that have the _Connect Admin_ role to query for users that have specific Connect related roles (such as roles starting with "Connect" or similar). I would not allow quering of other role types.

@vikasrohit What do you think of that?

**Comment by vic-topcoder** [comment]
Going to move this issue into a new milestone. Ideally we can split this into 2-part solution:

1. Provide functionality for all current `Administrator` holders to add managers and copilots to a project.
2. Rebuild the service API system to allow for the granular settings of user rights mentioned above.

**Comment by vikasrohit** [comment]
@mtwomey I think that is the only least exposing way of achieving the same. And I think we should create a new endpoint in existing api. I am not sure about the specifics though.

@vic-topcoder I didn't get what `Administrator` means in 

> Provide functionality for all current Administrator holders to add managers and copilots to a project.

Is it user with `Administrator` role or `Connect Admin` role. We have to avoid using `Administrator` keyword for `Connect Admin`.

And we should move this discussion to a private communication medium because we are discussing about security model in a public repo.

**Comment by vikasrohit** [comment]
> When I want to add a Manager, I would select the "Manager" and **when typing it would show show members with Manager user role only.** The same applies for Copilots (should show only from the Copilots pool).

Only bold portion is what we need to implement. I guess we already have the basic feature of getting managers added to the product.

**Comment by vic-topcoder** [comment]
Yes, we have the basic flow working. The feature update should actually limit the user suggestion list to the people that can be added within the role for a project.

For example - only Copilots can be shown when the manager is adding a copilot. Only Managers when a Manger/Admin is adding another Manager. Managers and Copilots can't be project members by default.

I've heard a feedback for limiting the people listed in a project, but that is not possible as there are no relationships established on regular connect members at the time being.

**Comment by vikasrohit** [comment]
Closing this as with new team management interface, now managers can invite other managers as well.
