### ISSUE TITLE
Handle null values for gclid - Google Click Id from Connect to Salesforce

### ISSUE THREAD

**Issue by harshitmehta123** [appirio-tech/connect-app#1403]
### Expected behavior
It seems like for implementation of #1227 we are getting "null" inserted into salesforce as a string for GCLID (Click ID)  We would like it to be empty.

<img width="1117" alt="screen shot 2017-12-04 at 14 34 45" src="https://user-images.githubusercontent.com/6296738/33544407-a7ae1f86-d900-11e7-8eba-b9c39971c6b4.png">

Thanks @vic-topcoder for helping out :)

**Comment by vic-topcoder** [comment]
@vikasrohit what is the status of this one? Please close if resolved.

**Comment by vikasrohit** [comment]
@vic-topcoder As I said on slack, we have to push the changes for https://github.com/appirio-tech/tc-connect2sf/issues/22 to get it resolved because I don't want to deploy tc-connect2sf every time we have something to map to or from salesforce. And https://github.com/appirio-tech/tc-connect2sf/issues/22 is waiting for https://github.com/appirio-tech/connect-app/issues/1248 which now seems to be closed. I have to revert the changes now.

**Comment by vikasrohit** [comment]
@vic-topcoder Just found another way of fixing this issue. I have made changes in front to fix this. May be we can add the fix at backend as well to be fool proof in future. Changes should be in dev by EOD.

**Comment by vic-topcoder** [comment]
Great. Please close this issue when we're done with it

**Comment by vikasrohit** [comment]
Yes, it is fixed and deployed with release [1.4.5](https://github.com/appirio-tech/connect-app/releases/tag/1.4.5)
