### ISSUE TITLE
Last Updated column should sort by a different criteria other than status update

### ISSUE THREAD

**Issue by mahestro** [appirio-tech/connect-app#1415]
### Expected behavior
I think it would be more benefitial to make the `Last Updated` criteria to follow this suggestion:
- Last time someone made a comment in the project.
- Last time someone modified the specifications page content.
- Last time someone attached a file in the specifications page.

### Actual behavior
It's `Last Updated` but right now it actually sorts by `last time the project state is updated`, which is not very useful. I think it's more useful to have the projects I'm interacting with at first sight, at a glance. Right now all the projects you see in the screenshot below are inactive for me, just because their status was updated to closed, cancelled, etc. While the projects that are actually active to me are from the second page.

### Steps to reproduce the problem
- Login.
- Go to projects list.

### Screenshot/screencast
- [Sample](http://take.ms/h2Qzh).

--

#### Environment
- OS: Mac
- Browser (w/version): Chrome
- User role (client, copilot or manager): Copilot
- Account used: mahestro

**Comment by vic-topcoder** [comment]
This depends on what data we have in Connect and would require some big rework. I'm pulling it into Feature Updates as we're planning to modify the sorting criteria in general. Further research is needed. Thanks for reporting @mahestro :)

**Comment by mahestro** [comment]
No probs, amigo. Glad to add my 4 cents to improve the platform :)

**Comment by vikasrohit** [comment]
@vic-topcoder @mahestro Today I spent significant time in debugging issues sorting of messages in a project and along with it also researched for sorting of projects. Project's `updatedAt` is updated only when there is some change in project spec. It is not updated when there is message or comment for the project OR when there is a user is added/removed from the project. So, I guess, specs for the project mentioned in #1414 was not updated since Nov 13.

@mahestro If even if count messages and attachments to update the `updatedAt` field of project, I am not sure how we can avoid getting a project (whose status is changed recently) to at top of the list.

**Comment by mahestro** [comment]
Hi @vikasrohit, thanks for going through this.

I think there might be a misunderstanding in my statement. My suggestion is to make the projects that have recent comments or spec changes come on top, not the projects who had a status change.

**Comment by vikasrohit** [comment]
Oh you mean we don't update the `updatedAt` at all for project status changes. That might be good question for @vic-topcoder.

**Comment by mahestro** [comment]
Yes, that's it!

**Comment by vic-topcoder** [comment]
Definition of "Last updated" should include all events that have user significance/are actionable. 

**Events that should force "updatedAt" timestamp change:**
- New post on the feed
- Post/comment is edited
- Response to a post in the feed
- Specification was updated
- Links are posted
- Files are attached
- Project is submitted for review (should show on top of the grid for managers to review) - Manager
- Project approved (should show on top of the grid for copilots) - they can pick up the projects; Customers know that their project is updated and work would start soon

All elements that are new since the last time I visited the interface are highlighted with a orange bar on the left side (currently new/edited posts). We will increase the breadth of the feature .

**Events that should trigger Notification dispatch** but should not change the "UpdatedAt". We're missing a more inclusive activity timeline for all events on a project, btw. I would still want to be able to see when the project status was changed in time (draft created -> submitted for review -> reviewed -> picked up -> activated -> completed). This timeline doesn't represent actionable items, just 


Manager only:
- Team member (customer) joined project
- Copilot joined project

The manager can't act upon those events, but it is important for her to observe progress. These are for monitoring purpose only.

**Comment by gondzo** [comment]
one way to solve this one would be to reuse our new event bus (Kafka) - we have all the events there (project updates, messages, etc) and we'd just need a service that subscribes to these events and updates project timestamps accordingly. 
@mtwomey @vic-topcoder

**Comment by vic-topcoder** [comment]
We discussed something like this for page updates/reload page and other interface changes with @mtwomey couple of hours ago. Using a unified approach in the system would be easier to manage in the long run, event-based updates is a good way to move forward, right @mtwomey?

**Comment by vikasrohit** [comment]
Just 2 cents, we are already having it event based, only difference is that it would be now using Kafka instead of current hosted RabbitMQ.

**Comment by vic-topcoder** [comment]
Ok, so what is the resolution for this ticket? Should we move it to tech debt and fix the sorting mechanism at once? @mtwomey @vikasrohit

**Comment by mtwomey** [comment]
@vic-topcoder @vic-topcoder @mahestro @gondzo 

At the risk of being unsophisticated, can't we just directly add a call to update the _latUpdated_ field in the project, to the services that are performing the actions Victor listed above?

I realize this isn't super scalable - but I don't think it needs to be and might be the simplest solution.

Thoughts?

**Comment by vic-topcoder** [comment]
Whatever gets this resolved fast without too much effort is great. I want us to think about cleaning dependency on too many different technologies at the back as well, though. It's your call @mtwomey
