### ISSUE TITLE
[$100] Remove dependency of old/obsolete technology

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1424]
We still have dependencies for Coffescript, Jade, etc. We should update the repo to not use any obsolete technologies

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-42

**Comment by maxceem** [comment]
Connect-app depends on [appirio-tech-react-components](https://github.com/appirio-tech/react-components/tree/feature/connectv2) which uses coffee scripts.

`appirio-tech-react-components` is being utilized in 58 places in the connect-app so we cannot stop using it.

It looks like the best way to go here is to implement building CoffeeScript to JavaScript inside `appirio-tech-react-components` and publish it as an npm module. So when it's being used as an npm module it only exposes js files. 
Or we can simply keep built js files in the git repo without publishing to npm.

What do you think?

**Comment by gondzo** [comment]
if we're still using coffescript then let's not remove the dependency at all for now.
@vikasrohit any drawbacks to publishing as npm module? can we make such a change to the repo, as there are other apps using it?

**Comment by vikasrohit** [comment]
First things first. I am not sure why we are considering coffeescript and jade as old and legacy. They in fact relatively new. And I found `jade` in particularly concise and helpful in development. `coffeescript` is good way to work on Javascript for `python` guys.

Now if we think it is still necessary, publishing it as npm module has one problem. We started this repo to have common components across all topcoder apps. But later on we deviated from having common and consistent components across topcoder applications. So, essentially it started to have separate branches for different applications. Right now it has two different branches which are used, one is master which is used for community facing apps and connectv2 branch used for Connect. So, if we publish it as npm module we might have to publish two different major versions e.g. 1.x for connect and 2.x for community apps.

**Comment by vic-topcoder** [comment]
@vikasrohit @gondzo @birdofpreyru @mtwomey Can we migrate towards the components used in Community-app, as it is actively under development, and unify with them? This would require us to evaluate both apps and synchronize the code between the two. I guess that would be a bigger project than just refreshing the component repo that we have right now. I would love if we end up with a npm module or component library which is unified across all apps. The fragmentation of space and languages used creates a lot of troubles maintaining and supporting the development.

As I see it, we can start the transition with unification of components in smaller batches, until we replace all components. This could be done in several bug hunts.

I'm interested to hear your thought on this guys.

**Comment by birdofpreyru** [comment]
Yes, I remember we talked about it a while ago with you; and then later I chatted about similar stuff with Trevor. On my side I have a clear view on how it should be done, but I still have not started to do it. I believe, it is a good moment to really start moving it :)

I'll try to do the following within this/next week, as the first step:

- I'll create "topcoder-react-utils" repo and npm package, which will hold generic re-usable ReactJS stuff for our projects (not necessarily related to the TC platform). From Community App I'll move there Babel and Webpack configuration, and all general code related to themeable buttons in Community App. I'll also take care that these are well documented and covered with unit tests.

- I'll create another, "topcoder-react-ui" repo and npm package, there I'll move the actual TC UI KIT themes for those buttons, and documentation on these.

Then you guys, as the first step, can refactor Connect App to use that Button code for all buttons and button-like links.

**Comment by vic-topcoder** [comment]
Yes, ideally we can also try to create a list of components that are shared between the two apps. I think these are:

- Avatar
- Avatar group
- Tooltip
- Modal window (would love to use something like this: https://tympanus.net/Development/DialogEffects/annie.html)
- Alerts (would love to update that to look and behave like this html demo: https://tympanus.net/Development/NotificationStyles/growl-genie.html)
- Form fields & forms (this is a big one)
- Buttons, checkboxes, switches
- React-select (styled)
- Dropdown
- Sticky side panel (utility)
- Progress bar
- File upload and file list
- SVG handler and animation/interaction classes - how do we modify the SVG for interactions, etc.

There are probably multiple smaller components (stateless) that we have to think through and evaluate. Ideally we can keep the list growing and document the cases and unify the components.

**Comment by birdofpreyru** [comment]
Yeah, that's right. Once we get it done for buttons, we just engage community to do the same with all other components, taking the button case as the example.

Btw, can you drop me the entire TC UI Kit? I still have only one page of it, that describes button styling.

**Comment by vic-topcoder** [comment]
All latest styles are at https://github.com/appirio-tech/tc-ui/tree/feature/connectv2/src/styles

**Comment by vic-topcoder** [comment]
The component library should be self-sufficient; we can create starter packs for styles of apps, but I don't want to mix the components with the UI. Ideally we can drop the dependency on an external style repo, and just keep the components as NPM module. There's a really interesting article on React blog https://reactjs.org/blog/2017/12/15/improving-the-repository-infrastructure.html and how we can use Rollup for our own libraries https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c.

**Comment by birdofpreyru** [comment]
> All latest styles are at https://github.com/appirio-tech/tc-ui/tree/feature/connectv2/src/styles

What about design specs, like this one: https://app.zeplin.io/project/5a0f186a6ea10efe5ba461e6/screen/5a1226996a64a912de6ac5ca
The way component theming is done in Community App, it is often easier to write a theme from scratch, looking into the original specs, that converting an existing stylesheet.

> The component library should be self-sufficient

That's why I mention two repos in my previous comment. One will contains self-sufficient components, like generic button, which can be used in any ReactJS project. The other one will contain themes for that button, that are defined specifically for the TC UI Kit. So, we'll be able to use the first repo, say, for a ReactJS project for a 3-rd party client, we'll only have to write new themes.

**Comment by birdofpreyru** [comment]
Beside the components, there is another thing we should span out of Community App and reuse: JS services for communication with TC APIs, and Redux actions / reducers that work with these services. At Community App side it will allow me to break it into several pieces, all using the same lib for communication with TC backend; on Connect App side it will allow to re-use the same code; and anybody else interested to talk with the TC backend (like hi4sandy and his custom-made mobile app for tracking challenges) will be able to use it as well.

**Comment by vic-topcoder** [comment]
Also - adding the document Sergey created a while ago: https://docs.google.com/document/d/1wOXH_FgO5Nz_Y2WGd4cZGI8PCj3zkNQeQ36iVyMKPG8/edit?usp=sharing

**Comment by maxceem** [comment]
Unifying components between these two projects is a great idea as for me.

Just want to add five cents from the point of view of challenge participant.
Usually, the hardest thing in reusing existent components are: 
- to find out which components already exist (looking to provided design)
- how they can be configured to fit a particular use case (if can)

I think it would help a lot if we have some component cookbook / live style-guide / kitchen sink. Something like this http://bluekit.blueberry.io/demo. Few other style guide generators are listed [here](https://github.com/davidhund/styleguide-generators#react).

Actually, [appirio-tech-react-components](https://github.com/appirio-tech/react-components/tree/feature/connectv2) has example page with components but it's made manually and it's half-broken, probably because wasn't kept up to date.

It would be useful to have style guide not only for separate npm modules but also for community/connect apps as well.

Though I think the only way it would work for community/connect apps if such style guides can be generated and updated automatically from the source code with comments. I'm not sure if any of listed generators above can do it, but I except some has to be able to do it.

All components in such style-guide have to be "dumb". So there could be a good side effect, that contributors will be forced to precisely split dumb/smart components. Otherwise, their newly created components won't work in live style-guide which can be easily spotted by reviewers during review.

**Comment by vic-topcoder** [comment]
I agree - once we start the component unification, providing live documentation with parameters and examples is a must for keeping people in sync with the component best cases/use. https://storybook.js.org and an example https://github.com/storybooks/storybook is quite popular to allow developers to interact with the components.

I like Bluekit a lot, but also we have to figure out what is the effort of building and maintaining the component library. Which one do you guys think is the best to go to? Also like the https://github.com/styleguidist/react-styleguidist as it lists the component name and other data that is important for the use of the component.

@birdofpreyru also did generate demo pages of the components in http://community-app.topcoder.com/examples/buttons/. How did you build the sample pages?

**Comment by birdofpreyru** [comment]
@maxceem yes, I totally agree with you: good documentation and live demos of the available components are crucial for success of the entire idea.

@vic-topcoder component and style demo pages in Community App are created manually as regular pages of the app. Although demands a bit more care, as it is manual, I like it because it allows to showcase each component it the best way, test how the current implementation of the component works in the real life, and also the source code of that page becomes an example, how these components should be used.

After we spawn out re-usable components from Community App into a separate repo, I have in mind to spawn out their demos into a separate demo app.

**Comment by vic-topcoder** [comment]
Moving to CF 7

**Comment by birdofpreyru** [comment]
@maxceem as promised, the standard buttons from Community App, along with some typography mixins, definitions of standard (Roboto) fonts, and constants (colors, screen sizes), are moved into https://www.npmjs.com/package/topcoder-react-ui-kit

I've already updated the dev deployment of Community App, and so far I see no problems with it :)

**Comment by gondzo** [comment]
closing this one and moving conversation to #1690
