### ISSUE TITLE
[$100] Add sanitization to Connect "links"

### ISSUE THREAD

**Issue by mtwomey** [appirio-tech/connect-app#1426]

**Comment by gondzo** [comment]
add sanitation to project links so text like `Javascript:alert(document.domain)` does not cause issues. the change should be added to https://github.com/topcoder-platform/tc-project-service

**Comment by chq-matteo** [comment]
I guess you are referring to the links you can add to a project card.
Project names have been sanitized since [topcoder-platform/tc-project-service@da7a313](https://github.com/topcoder-platform/tc-project-service/commit/da7a3132e0a3c833916160153272e5e137b7ad3a).  
When we choose a name like `sanitize me <script>...</script>` it gets stripped to `sanitize me`  
![virtualbox_topcoder_06_01_2018_21_14_52](https://user-images.githubusercontent.com/6654800/34643587-f32b4da4-f326-11e7-8918-346e0172989e.png)

The url field too is sanitized, you can see that html special character are escaped so you can't inject attributes

![virtualbox_topcoder_06_01_2018_21_23_25](https://user-images.githubusercontent.com/6654800/34643630-1510ca42-f328-11e7-9a6e-30fcd3236f93.png)

It is true that links like `javascript:` aren't escaped, but the script is executed in another tab because links are opened in a new page with noopener.  
![virtualbox_topcoder_06_01_2018_21_15_36](https://user-images.githubusercontent.com/6654800/34643649-52ee9ca4-f328-11e7-859e-747d6344e31a.png)

![virtualbox_topcoder_06_01_2018_21_15_06](https://user-images.githubusercontent.com/6654800/34643730-7ec37aba-f329-11e7-98e4-75de9d33dfea.png)

So what is a link that has to be sanitized? Any link that starts with javascript:? What about links to malicious sites?  
If @mtwomey has found an actionable xss vulnerability we should fix that, but otherwise we should probably think of another solution.  
@mtwomey @gondzo

**Comment by chq-matteo** [comment]
I'll just add the client side regex to server side?
```
/^(http(s?):\/\/)?(www\.)?[a-zA-Z0-9\.\-\_]+(\.[a-zA-Z]{2,15})+(\:[0-9]{2,5})?(\/[a-zA-Z0-9\_\-\s\.\/\?\%\#\&\=]*)?$/
```
If @mtwomey has found an actionable xss vulnerability we should fix that.
@mtwomey @gondzo

**Comment by gondzo** [comment]
in chrome it's opened in current tab and is a valid xss issue.
regex solution on server side is ok.

**Comment by chq-matteo** [comment]
The pull request is at https://github.com/topcoder-platform/tc-project-service/pull/61
