### ISSUE TITLE
Topics not shown

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#1434]
Some projects (in prod) don't display all topics on dashboard. I've observed three cases: no topics at all, two topics, all topics. Refreshing the page shows one of those three states randomly. There are no network or console errors. The bug seems to be in the tc-message-service -> it returns incomplete data.
Any ideas about the cause @vikasrohit @mtwomey 
The project in question is 4214 (prod).

**Comment by vikasrohit** [comment]
@gondzo it seems we are rate limited there because of too many calls as we were discussing in https://github.com/topcoder-platform/tc-message-service/issues/26. We are thinking for quick fix that can reduce the number of calls to discourse and reduce the load time of messages. If you have any idea or suggestion, please let us know.

fyi @mtwomey

**Comment by gondzo** [comment]
Is this rate limit being me -> tc api, or tc api->discourse?
Any chance we can increase this limit temporarily until we figure out how to decrease number of calls ? @mtwomey @vikasrohit

**Comment by vikasrohit** [comment]
I think both are in having combined effect here. We can avoid rate limit for ourselves by avoiding quick page refreshes.

**Comment by vic-topcoder** [comment]
@gondzo @vikasrohit - is this issue current?

**Comment by gondzo** [comment]
no, this was happening due to our discourse provider changes, we can close it now
