### ISSUE TITLE
Eliminate duplicate definitions in a JSON file

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1459]
Let's eliminate the duplicate structures in JSON - project creation and specification forms - this is extremely error prone.

 

Refactor the code as needed

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-129

**Comment by vikasrohit** [comment]
The reason of duplicating few sections in each template is that we need separate UI structures for project creation and specifications form e.g. for creation form, we group selected questions from different form sections of specification form. Also, all fields in creation form are required to enable the submit button while there are questions which are not required (of course they are required to submit the project for review) for enabling the submit button on specification form. IMO, it would make JSON more complicated if we try to reuse the same JSON config block with boolean flags.

**Comment by vikasrohit** [comment]
@vic-topcoder I think best way to eliminate the duplicate code blocks is to get rid of templates as JSON. We should start persisting them in database and create a basic UI for controlling the templates. For now we can allow only admins to do that but with introduction of organizations, we can allow organization admins to control the templates for their organizaiton.

**Comment by vic-topcoder** [comment]
That's what I want to achieve at the end, but we don't have the bandwidth at the moment to build the UI, so starting with a cleaner JSON would help immensely, and transition into an administrative interface.

**Comment by vikasrohit** [comment]
As I said earlier, it would make structure complicated for non technical person to create/edit templates because it would involve more flags and more flags mean more combinations of flags. Right now it is very simple for users to specify fields for project creation template, they just have to add the required fields in basicSections array and they can choose different set of properties in project creation form.

**Comment by vic-topcoder** [comment]
OK, go for it :) I trust in your expertise, the only requirement is to not have duplicate data, as editing the same data on 2 different spaces would make it extremely error-prone. I am talking from personal experience - editing content on one section and having a typo on the other is no go for me. I don't think a non-technical person is ever going to be creating the JSON, but they MIGHT have to edit some of the text. I prefer we make sure they can edit the created JSON content in only one place, and it would result in correct content being reused in creation form as well. All the JSON is for internal use and we have only people with sufficient knowledge working on it.

**Comment by RishiRajSahu** [comment]
@vic-topcoder @vikasrohit as per my understanding the more the inconsistency between creation(basicSections) and specification(Sections) template more are the number of boolean flags we need to add to have single point of config.
> all fields in creation form are required to enable the submit button while there are questions which are not required (of course they are required to submit the project for review) for enabling the submit button on specification form

I think the questions which are 'required' on creation should always be required, this will make things clean (Please, correct me here if I am missing anything)

Considering the above statement this is how we can divide questions - 
1.One which are required(mandatory) on creation form to enable submit button.
2.Others which are on specification and not required(mandatory).

Ideally these two sets should be non-intersecting, because a required question should always be required irrespective of whether its a creation page or specification page.(Is there any drawback in having it this way ?)

I will have offline discussion with @vikasrohit  more about it.

**Comment by vic-topcoder** [comment]
Yes. Let's plan this work with light of what is coming for Connect and the Project Plan section - split the product specification questions from the project scope. I left more comments on Slack and we can talk offline if that'll help move forward.

The way I imagine it is similar to your approach, @RishiRajSahu: 

- Scope section, required questions. Same on creation form and Project Scope (currently Specification).
- Extended sections - collect details about the scope. Can be required and 

Within both sections we can have Optional questions, so by default you need to indicate which questions can be skipped, rather than which are required. This would be easier to maintain as majority of the questions are required.

The project creation and scope header sections should be identical by all means.

On project creation we can have a secondary section that configures products in a project template. This section doesn't exist currently. The idea is to split project creation into 2 sections: Project scope and Project template settings.

Let me know if this makes sense

**Comment by RishiRajSahu** [comment]
@vic-topcoder 
> The project creation and scope header sections should be identical by all means.
by header section did you meant the section containing required questions only, right ?

**Comment by vic-topcoder** [comment]
Moved to Aha as Epic
