### ISSUE TITLE
[200$] Display the user email address to managers and administrators on the system

### ISSUE THREAD

**Issue by vic-tian** [appirio-tech/connect-app#1535]
### Expected behavior
The user tooltip should be able to display additional user information. Right now we want to display the email address of the user to Connect Managers and Connect Administrators.

Other data that will be needed in the future (think about it, if possible to fetch, let's discuss):
- [ ] Link to SFDC lead for the registered user 
- [ ] Number of projects on Connect
- [ ] Customer segment and Customer Organization (when we implement/support them).
- [ ] Last active

**Comment by gondzo** [comment]
I think this will require backend changes and it's better to handle it after we unify the user hover component in #1534

**Comment by vic-topcoder** [comment]
Agreed. Move to a CF 7 or as you see fit.

**Comment by chongluo** [comment]
I have looked into this issue and found that backend does not return email for project members (using members/_search api). We can instead call user profile api with user handle to get project members' email, but it will need much more api call. Do you want that or wait for BE to support email retrieving?  If there is any better API I can use, please let me know.

**Comment by chongluo** [comment]
After trying user handle, I found that a user can not read other users' email from API. Is there any plan to update the backend to support this feature?

**Comment by vikasrohit** [comment]
@gondzo @vic-topcoder I can already see emails in user tooltip on project listing page, when I am logged in with an administrator account. We have to think  how we can support the same feature to managers without exposing security risks and not making admin validation tightly coupled with particular app (connect in this case). fyi @mtwomey

**Comment by chongluo** [comment]
@vikasrohit Can you please tell me how I can have an  administrator account? I can only test with a manager account now. Thanks.

**Comment by gondzo** [comment]
@vikasrohit is that in dev? I'm not seeing any emails when logged in as pat_monahan

**Comment by vikasrohit** [comment]
Yes, in fact it is in production as well. I guess this was done as part of one of the bug bash. pat_monahan is not an administrator. So, it won't be visible to him.

**Comment by vic-topcoder** [comment]
@vikasrohit - can we extend the email visibility to Managers as well? The people that work in Connect need the user email most of the time, and they are not all Administrators. Ideally we should have the same results in Dev as well.

**Comment by vikasrohit** [comment]
@vic-topcoder It is again a security risk to open up emails of users others than administrators. At least we should not do it in our core services otherwise we would definitely leak it some day.

If this requirements is very critical, we can augment projects members data with emails of members in project service and use admin user (we should create a dedicated user for this, ideally it should be accessed via API key/secrets which has admin privileges, I think @mtwomey is going to have that feature very soon) credentials to fetch emails of the project members. I would have some impact on get/list project operations because of extra calls.

**Comment by vic-topcoder** [comment]
Ok, so the requirement is to allow Managers to view emails of registered users. We have a complete control of who the Managers are. They are only internal people and thus think of them as Admins in Connect. The Connect Admin has a super privileges and can control absolutely everything.

I don't know what the security risk is for our people to see the customers' emails, but it is not good for them to NOT SEE the emails. This is the whole reason we have different user levels and assign rights.

Managers should have access to the emails, as they have access to SFDC, and they need that data to contact customers and keep working with them. Our lack of providing this data severely hinders their experience.

Please consider what are the use cases and why do we need to s how advanced customer data to Connect Admins and Connect Managers.

Managers are the first people that go and verify if a project is ok. They need to understand who the customer is and determine if a project is valid. They use the email of the customer to search through the databases (SFDC, LinkedIn, etc.) to gain better knowledge of who the customer is.

If a project is abandoned for more than 5 days, they send emails and initiate a call with the customer. They need a lot more data in order to do the initial sale and project setup, which we do not currently collect. We have to build a better profile for the connect user, which would cover the sales & support team need for information.

Lastly, they use the email to search through SFDC and sync status of projects/customers on the other tools they have.

Copilots on the other hand, in theory should not see the customer email and contact them through anything but the interface. In practice they actually exchange emails, which is breaking the protocols. We want to stop this practice and thus we're building Connect to cover the gaps of the experience, so Copilots shouldn't communicate through emails.

I hope this explains what the user need is.

**Comment by vikasrohit** [comment]
@vic-topcoder I can understand all this, but thing is that we are not allowing non administrators to see the email data from our core API which is identity API because it is used by almost every other application in topcoder platform.

>Lastly, they use the email to search through SFDC and sync status of projects/customers on the other tools they have

Users can use the the Direct Lead link which we show in the side panel on the dashboard.

I would check if we can achieve the use case with approach I suggested above.

**Comment by vic-topcoder** [comment]
Yes, let's please work on separating Connect users from the rest of the ecosystem of apps. If you want to open a new stream of effort for this, let's focus all connected issues. The #1604 we resolved in a different way is part of this bigger issue.

@mtwomey - Please advise

**Comment by vikasrohit** [comment]
Emails are shown to admins only.
