### ISSUE TITLE
[$400] Notifications bundle

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#1544]
Add support for bundling notifications.

**Comment by gondzo** [comment]
do we need this for notifications in the app or just leave this for email notifications @vic-topcoder

**Comment by vic-topcoder** [comment]
We need this for in-app notifications as well. The bundling logic should be the same for all instances. While in the app, we can bundle the notifications before they're seen; while the user is not logged in we can bundle the notifications so when they are online, the user can see the total number of replies on a project (34 new replies on thread A, 23 new replies on thread B, etc.).

We currently poll every 60 seconds for new notification, so don't have enough time to bundle the notifications if the user is on the website and their notifications menu is opened.

If the use doesn't open her notification center, we can start bundling until she opens her notifications dropdown menu.

The same logic applies for notifications when the connect tab is inactive.

Please let me know if there are any questions on how we bundle the notifications for the in-app notifications.

**Comment by gondzo** [comment]
this will be purely view side bundling - we won't have them bundled in the database. when displaying notifications, group them by project and then group by the action (post created, project updated, etc) and create a bundle notification for each group. clicking the bundle notification should open the target page (it's the same for all bundled notifications). marking bundle as read will make api call to mark all bundled notifications as read

**Comment by vic-topcoder** [comment]
👍

**Comment by chq-matteo** [comment]
I'm opening this issue for pick up

Useful pointers for who wants to continue

1. https://github.com/topcoder-platform/tc-connect-notifications
2. https://github.com/topcoder-platform/tc-notifications

Also the development api for the connect-app seem broken (newly created users are not recognized, can't post updates on projects, no notifications...)

So you can either deploy everything locally or try to understand the application logic on production.

**Comment by maxceem** [comment]
If it's ok. I'll use a branch from the [PR](https://github.com/appirio-tech/connect-app/pull/1588) for the issue #1554. As I had to refactor a little bit notifications configs there and it would probably be difficult to merge with changes in this task.

**Comment by maxceem** [comment]
Should we bundle only the notifications which are marked in [this table](https://docs.google.com/spreadsheets/d/1tPwJObRdRHnOAs4uDGLZKieYV9fb1GF_moZxMJNnxQE/edit#gid=1990684812) in `Should bundle` column?

**Comment by gondzo** [comment]
yes

**Comment by maxceem** [comment]
Notifications like:
- `New project created`
- `Project was approved`
- `A project was completed`
most likely will happen only once per project lifetime. And we have to group notifications per project. So probably these notifications will be never bounded in real life. Could it be that I'm missing something?

Also, these notifications could happen only once, FYI:
- `A copilot joined your project team`
- `A manager joined your project team`

**Comment by gondzo** [comment]
you're right for the project status changes, doesn't make too much sense to bundle those (even though project can change status multiple times, but I guess that won't happen too often)

there can be multiple copilots managers in a team as far as I know??

**Comment by maxceem** [comment]
> there can be multiple copilots managers in a team as far as I know??
technically yes, not sure about real life though, can bundle them for now

Anyway, it will be configurable.

**Comment by gondzo** [comment]
thanks

**Comment by maxceem** [comment]
I've added to that [table](https://docs.google.com/spreadsheets/d/1tPwJObRdRHnOAs4uDGLZKieYV9fb1GF_moZxMJNnxQE/edit#gid=1990684812) column `Bundle message text` with the messages which should be displayed for bundled notifications. Could you please have a look?

**Comment by gondzo** [comment]
looks good, we can go with these for now. 
@vic-topcoder do we need any changes there?

**Comment by maxceem** [comment]
#### Bundling and notifications versions.

Before we introduced notification versions as we replaced in notifications `userHandle` with `userFullName`.

So for example for **New response to a post** notification we have two version:
- old: `[userHandle] responded to your post`
- new `[userFullName] responded to your post`

The question is should we bundle them ignoring version or no.

##### Ignore version
Ignoring version makes more sense, as basically, these are same notifications. But if bundle them together and after we want to show like `[ Who + Who + Who + ... ] created # new posts to [topic ID]` actually we cannot do that for both versions as old one doesn't have `userFullName` to show `Who`

##### Bundle only notifications with the same version
Makes less sense. As in this case, we can theoretically have two bundles for the same type of notifications, like:
- old bundled: `[ userHandle + userHandle + userHandle + ... ] created # new posts to [topic ID]`
- new bundled: `[ userFullName + userFullName + userFullName + ... ] created # new posts to [topic ID]`

##### Third way
We can introduce some workaround for this particular situation with user handles/name and ignore version. Because mainly bundled notifications have only bundle quantity so usually it's safe to bundle notifications with different versions.
And for this particular case with userHandle/userFullName I can add some **special case**.

**Comment by gondzo** [comment]
the third option looks best and we can go with the special case for now. 
if it turns out we'll have more similar cases in the future, we'll have to mark placeholders in the templates as [userHandle|who], [fullName|who] and then get all the placeholders with 'who' to render the complete message (this is just one idea, no need to do anything about it for now)

**Comment by maxceem** [comment]
From the initial task description, we are supposed to bundle notifications per project and per notification type.

From the provided bundled message text `[ userFullName + userFullName + userFullName + ... ] created # new posts to [topic ID]` it looks like we also have to bundle by `topicId`.
So responses to different topics have to be bundled separately. Correct?

Also, should I populate notifications with topic title? So we can display messages like:
`Victor, Samir, Maksym created 45 new posts to How to make a bicycle?`
I think displaying `topicId` is not desired. Or I can just replace it with a word `topic` instead of a particular title. Then bundling per topic is not mandatory also, as we can bundle all replies to all the topics to one notification like `Victor, Samir, Maksym created 45 new posts`.

**Comment by gondzo** [comment]
I think bundling all posts into a single notification is better - we don't want users to follow the project through notifications, they should be just a reminder that there is new activity in the project.

**Comment by vic-topcoder** [comment]
Agree - single bundle is preferred. I expect edge cases of `@handle` + `full name` to disappear quickly as the system would be cleaned up quickly.

**Comment by maxceem** [comment]
Done.

#### Notes
- Replaced custom templates with Handlebars. After some time of trying to make some clear code moving to handlebars appears to be the best solution.
- Handlebars can solve the issue with [`userHandle`/`userFullName`](https://github.com/appirio-tech/connect-app/issues/1554) by itself in an easier way than versions. So basically we don't need versions for now. Though I didn't replace versions with handlebars. I think we can check what are next requirements and if we need to get rid of versions or no.
