### ISSUE TITLE
[$150] User in notifications are listed with @handle instead of their name

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1554]
### Expected behavior
We should be consistent with how we list users in the interface. I'd like to see First and Last name for the user "Christina Underwood" as this is what is displayed on the chat interface.

Expected:
![screen shot 4](https://user-images.githubusercontent.com/8484061/34373362-75d9d78e-ea8f-11e7-83f3-16bb4f019a1c.png)

### Actual behavior
Notifications list users differently from chat interface.

![screen shot 5](https://user-images.githubusercontent.com/8484061/34373367-79fe8abc-ea8f-11e7-981e-e04e76ff1ea6.png)

**Comment by gondzo** [comment]
The task here includes updating connect app (notification templates) and updating tc-notifications to include full name in message contents https://github.com/topcoder-platform/tc-notifications/blob/735efe2a028c686c6c28f468b17b3d4c5d8a2972/connect/connectNotificationServer.js#L220

**Comment by maxceem** [comment]
To implement this task user full name has to be added to the DB when an event arrives.
So after this change frontend will expect DB to return user full name. But all the existent records in DB don't have a value for user full name.

Should I add a fallback to the frontend to show user handle instead of the full name for all old records that are stored in DB? Or DB will be reset and we start from the scratch?

**Comment by maxceem** [comment]
@gondzo the idea with the version suffix is the best I can think about.
The only drawback I see that our event config files will grow repeating configs for the same events with minor changes.

But still I think it's a good idea and if you confirm I'll implement it.

**Comment by maxceem** [comment]
@gondzo After give it a try I see that better slightly modify the approach.

It looks like it's better to add a `version` column to the `Notifications` table in DB rather than adding a suffix to the event types. The reason is that we also have notification settings which utilize event types. And we have notifications API to retrieve data, which also uses notifications settings to filter notification by their type. So if we add suffix we have to handle it in some way. And it looks quite complicated as we treat event versions as completely separate events if we use suffixes.

So it feels that adding version column and version property to the notification records will have the same benefits as a suffix way. We only have to edit the configuration and there will be backward compatibility. And we still can use the same Notification Settings logic without modifications. And also notification API to retrieve notifications also can stay without modifications.

**Comment by gondzo** [comment]
Agreed. Go ahead with that approach

**Comment by maxceem** [comment]
Just want to note, that it looks like dev notifications API https://api.topcoder-dev.com doesn't work currently.
There are no notifications on the dev site https://connect.topcoder-dev.com even if I make some actions which have to create notifications.

Also if I use `connect-app` on `bugBash06` branch with https://api.topcoder-dev.com URL for notifications API instead of the local instance, no notifications come from notifications API.
