### ISSUE TITLE
Double managers on project list cache.

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1556]
On the project list certain projects have the same manager repeated. Once I open the project and then reload the list, the managers are back to normal.

![screen shot 7](https://user-images.githubusercontent.com/8484061/34373881-b1e39262-ea92-11e7-811a-1a908b0e5a79.png)
![screen shot 8](https://user-images.githubusercontent.com/8484061/34373882-b1f4e508-ea92-11e7-96e9-956a6e0b315f.png)

After opening the project and reloading the list there's only 1 manager
![screen shot 9](https://user-images.githubusercontent.com/8484061/34373883-b205d67e-ea92-11e7-8e5a-c363dd7201c1.png)

@vikasrohit could this be an issue with elastic search?

**Comment by vic-topcoder** [comment]
The issue is persistent - the double managers still keep appearing after reloading.
![screen shot 10](https://user-images.githubusercontent.com/8484061/34373915-f6a13166-ea92-11e7-94dd-ac322db784cd.png)

**Comment by vic-topcoder** [comment]
@vikasrohit - reassign to CF 5.5 if this is a grid issue and not ES

**Comment by vikasrohit** [comment]
@vic-topcoder, @sachin-maheshwari did some investigation on this. And he [found](https://github.com/appirio-tech/connect-app/issues/1359#issuecomment-348083936) that we do have multiple records in database not only in ES. So, for now quick fix can be the same we applied to `AvatarGroup` component [here](https://github.com/appirio-tech/connect-app/pull/1395/files). Ideally, we should have reused the `AvatarGroup` component instead of creating a new one or at least compose the `AvatarGroup` in `ProjectManagersAvatar` component.

**Comment by vikasrohit** [comment]
Fixed in dev.

**Comment by vic-topcoder** [comment]
yes, reusing existing components is a must - I've opened an issue #1533 for that one. Thanks for the quick fix. What else causes the double records? Is that good? Do we need any further actions? @mtwomey @vikasrohit @gondzo
