### ISSUE TITLE
Messaging: unposted content alert

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#166]
We should notify the user when they're navigating away without posting content in the Dashboard or Discussions. This can happen in several cases: 
1. Completed status update, but not posted
2. Composed message, but not posted
3. Composed reply to status update or message, but not posted

@vikasrohit can you apply the same approach you used for detecting when users have unsaved content in their Specifications?

**Comment by vikasrohit** [comment]
@fnisen How do we want to handle the case where user hasn't completed the post i.e. either title or content is not filled yet but one of them has some content. This means user has something unposted but the post is yet to be completed.

**Comment by fnisen** [comment]
@vikasrohit good question. Let's prompt them in that case to the return to the post. The action in either case would be to take them back to the post itself, not to actually post on their behalf.

**Comment by vikasrohit** [comment]
Okay. Just to be clear, we would show the alert even if the user has only typed one of title and content of the post.

**Comment by vikasrohit** [comment]
@fnisen 
-- Implemented the required behaviour with Discussions page. Took liberty to implement the same behaviour when user has unposted content and tries to change the thread from the left panel of thread list or clicks on the + to create new thread.
-- Implemented the required behaviour with Dashboard page.

Please check the behaviour in dev and let me know if you find anything not working or not as expected. It took more than expected time because of possibility of different sequences of user actions with and without unposted contents.

**Comment by fnisen** [comment]
@vikasrohit yes, that was good thinking! Overall it's working well, but I'm seeing two edge cases: 
1. If I'm on the Discussions tab and click the Discussions tab again, the page will reload and the post will disappear w/o warning
2. I'm on a thread with earlier messages and click "Load earlier messages," the post will also disappear without warning. 

You can test on this project: http://connect.topcoder-dev.com/projects/438/discussions

**Comment by vikasrohit** [comment]
I see.
1 is because route didn't change. What should be the behaviour in this case? Don't reload the page on clicking the same page's link in nav OR show the unposted content warning in this case as well?

2 I can try handling this as well. I guess, we should just simply load more messages without  changing the unposted content i.e. we don't need show the unposted content alert in this case, right?

**Comment by fnisen** [comment]
Yes, agree with that approach for 2. 

For 1, we don't have polling or webhooks right now, correct? So, the user may be clicking on "Discussions" to reload and see new messages, in which case we should allow the click/reload and show the unposted content warning.

**Comment by vikasrohit** [comment]
@fnisen For me #1 is not happening i.e. when I am clicking on Discussions tab again, its not reloading the page at all. Are you facing this in any specific browser?

I have deployed the changes for #2 Please let me know your feedback.

**Comment by fnisen** [comment]
@vikasrohit that's weird. I can only longer reproduce #1. Oh well, forget it then. #2 is working fine, thank you.

**Comment by vikasrohit** [comment]
Closing.
