### ISSUE TITLE
[$50] Notification is not triggered for Response Edit

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1730]
_From @bikakk on February 18, 2018 12:18_

### Reported URL ###
https://connect.topcoder-dev.com/projects/2608

### Reproduction Steps ###
1. Open https://connect.topcoder-dev.com 
2. Login as pshah_customer
3. Open the project where post has been already created and response was posted
4. Now click on Edit comment against any post
5. Edit the comment and Save change
6. Make sure other team member page is already opened the with same project
7. Now goto other team member/manager page and observe the notification

### Expected Result ###

As per doc: https://docs.google.com/document/d/1OBUhMGUtqU-Eqpufaom_eAKDbLiR8mq6syb-PSavXDI/edit
Notification should be triggered for Response Edit

### Actual  Result ###

Notification is not triggered for response Edit. But if we post the new notification response is triggered.
Attache the detailed video.

### Screenshots ###

https://youtu.be/D_gvMRjjgm0

### Issue Information ###

Frequency: Always

Device: Laptop

OS: Windows 7 64 bit

Browser: Chrome 64.0

_Copied from original issue: topcoderinc/connect-test-cycle-1#218_

**Comment by vic-topcoder** [comment]
_From @sdgun on February 23, 2018 2:48_

@vic-topcoder

**Comment by vic-topcoder** [comment]
Valid

**Comment by Colinh84** [comment]
@gondzo Not sure if it is due to recent changes, but the whole posting system is broken for notifications, not just edits. Both posting new topics or comments and editing does not generate a notification to other project members. Also new comments are being flagged as "Edited". Also there is no longer a page reload suggestion when new posts/topics are added for other members.
