### ISSUE TITLE
[$50] No notification triggered for active status

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1740]
_From @bikakk on February 17, 2018 23:33_

### Reported URL ###
https://connect.topcoder-dev.com/projects?sort=updatedAt%20desc

### Reproduction Steps ###
1. Open https://connect.topcoder-dev.com/
2. Login as pshah_customer
3. submit a project for review
4. Login as manager and change the status of the project to Active
5. goto customer page and observe the notification

### Expected Result ###
Notification should be triggered for active status also.

### Actual  Result ###

Notification not triggered for active status.

### Screenshots ###

https://youtu.be/37JpyoumCLI

![image](https://user-images.githubusercontent.com/31851673/36346675-d9e9b92c-143a-11e8-9a7f-8d9b5393f874.png)

### Issue Information ###

Frequency: Always

Device: Laptop

OS: Windows 64-bit

Browser: Chrome 64.0.3

_Copied from original issue: topcoderinc/connect-test-cycle-1#102_

**Comment by narekcat** [comment]
@vic-topcoder @gondzo 
I have tred to reproduce this issue on live and on local too, api is same, but it doesn't show any notifications. Are there any problem with api or notification in backend?

**Comment by gondzo** [comment]
@narekcat notifications are now working properly

**Comment by Colinh84** [comment]
@gondzo this issue can only be fixed from the connect API repo, wherever that is. When a project status is changed, a status update is only sent to the endpoint `/v4/projects/{id}`. It looks like the notifications are generated by that endpoint.

**Comment by gondzo** [comment]
correct, the change should be made here https://github.com/topcoder-platform/tc-project-service/blob/dev/src/events/busApi.js

**Comment by Colinh84** [comment]
@gondzo I created a PR for both this and tc-project-service repos to address this issue. An additional step may be required for this to work which I cannot implement myself. A topic must be created in Kafka if it does not already exist for the new event type: `notifications.connect.project.active`. This is because the project update message is stored in the corresponding event type sent to the Kafka producer from `tc-bus-api` with the following code:

`const result = await producer.send({
    topic: `${config.KAFKA_TOPIC_PREFIX}${event.type}`,
    message: {
      value: event.message
    }
  })`
