### ISSUE TITLE
specification: last uploaded file name displayed on the upload section

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#196]
Steps:
1.) Open the application
2.) Login with username sweta.singh
3. go to specification 
4. go to project fiels
5. upload files

Expected Result: name should not be displayed
Actual Result: name displayed on the section

Environment: windows 7, chrome latest 

![image](https://cloud.githubusercontent.com/assets/16131461/18928340/38371684-85dd-11e6-9e4a-d7c135415c09.png)

**Comment by parthshah** [comment]
@vikasrohit - re-assigning to you.

**Comment by vikasrohit** [comment]
@parthshah I didn't found any configuration parameter to do this with FileStack. This seems to be a valid behaviour because most of the times, applications (which are using FileStack) does not duplicate the uploaded file information. We are showing the uploaded files in the list above the picker, hence it is looking odd to have file name in the file picker. However, IMO, its just an extra UI element to allow user to delete the last uploaded file.

**Comment by vikasrohit** [comment]
@parthshah I have create PR https://github.com/appirio-tech/react-components/pull/99 for this purpose. Please let me know if you think those changes are worth for fixing this issue.

**Comment by vikasrohit** [comment]
Changes are in dev now.
