### ISSUE TITLE
Toolbar filters count logic

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#1971]
@vic-topcoder @gondzo 

Currently, on Deskopt there is filter count in toolbar 

![filter](https://user-images.githubusercontent.com/146016/39115353-026dc4d6-4714-11e8-89fe-db6330368733.png)

Initially, by logic, it supposes to count the number of filter params in the URL. Though it looks like one by one it ignores params, and currently it only counts if there is `type` in URL param. So it only can be 0 or 1.

Mobile design suppose that the number has to show the quantity of selected project types:

![image](https://user-images.githubusercontent.com/146016/39115238-b6682c3e-4713-11e8-9d5e-7892902e2406.png)

Should I update for both Desktop and Moble, so that counter shows the number of selected project types instead of current behavior?

**Comment by vic-topcoder** [comment]
I'm not quite sure what the technical issue is here. I would assume the logic is based on the interface, not the URL, as if I change the URL while the interface is on, would that change the interface? I'm confused.

Regarding Filter counter - by default it should count how many DIFFERENT filters are engaged. If you have only 1 filter (currently) - the filter is "project type" - as soon as the filter can be hidden, we want to indicate there is a filter engaged, that's the reason for having the blue counter. The same should happen on mobile. In the second screenshot, the screen on the right should show 1 instead of 2, as there is only 1 active filter, instead of the count of project types being filtered at the moment (it is on as long as I have 1 or more project types in it).

**Comment by maxceem** [comment]
Thank you. I've got what you say how this counter should work. The same I can see in the code. So this is no mobile issue. Just probably existent issue.

Currently, this conunter is only can be hidden or show `1`. To reproduce:
1. Open https://connect.topcoder-dev.com/
2. Apply all the filters. But counter only shows 1 when filter by project type. Other filters are ignored by the counter.

![filters-wrong](https://user-images.githubusercontent.com/146016/39165117-62a29e48-47b5-11e8-84c4-6ae9ef943dc4.png)

From the code point of view it seems that filters were explicitly ignored from the counting one by one during some period of time. Not sure what were the reasons.

**Comment by gondzo** [comment]
this is working properly - we have only project type filter, so it can display only 1 or 0. This indicator is valid for hidden filters only, not project status and keyword search
