### ISSUE TITLE
Not all notifications are dismissed when the user visits the target page

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1985]
### Expected behavior
When I click/tap on a notification, and the target page loads, the notification should be dismissed.

### Actual behavior
Currently works for posts, but not for project status, members joining a project, probably others. Let's try to unify the behavior of all notifications in the system to be the same.

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-445

**Comment by maxceem** [comment]
Also, I see notifications are not dismissed for `added a link to your project`.

**Comment by vikasrohit** [comment]
@maxceem Do you think this issue is same as https://github.com/appirio-tech/connect-app/issues/2123

**Comment by gondzo** [comment]
We should implement this in a generic way so it's easy to extend when we add notifications for different target pages in the future (ex #2178). 
IMO a good approach would be to listen for route changes in react-router and dismiss notifications that match current route. Any better ideas @vikasrohit ?

**Comment by vikasrohit** [comment]
Yep, handling it in a generic way would be good, however, I am not sure what exactly that would be. How are we dismissing the notifications right now?

> IMO a good approach would be to listen for route changes in react-router and dismiss notifications that match current route

I am not sure if all notifications would have separate routes i.e. there might be multiple notifications sharing the same route, so it would be difficult to determine which notification has to be dismissed.

**Comment by vikasrohit** [comment]
But wouldn't it dismiss notifications for all phases when there are posts in multiple phases and user clicks on one of the notifications.

**Comment by gondzo** [comment]
@vikasrohit yes, it would dismiss notifications for all phases with the above approach. Would it make sense to add some kind of 'event emitter' logic to components that display the target for a notification? For example we can have Feed container emit "message seen" event for each displayed message, files list component would emit "file seen" event for all seen files. Then we would have some main logic to process those 'events' and dismiss notifications.
any other ideas?

**Comment by maxceem** [comment]
@vikasrohit @gondzo FYI
For implementing [Add notification visual cues to project plan cards](https://github.com/appirio-tech/connect-app/issues/2401) we have to mark post notifications as read, when user opens the tab with posts for a particular phase.

So far I've implemented some helper component to dismiss notifications for some mounted i. e. visible component: https://github.com/appirio-tech/connect-app/blob/issue-2401/src/components/NotificationsReader/NotificationsReader.jsx

Usage, see https://github.com/appirio-tech/connect-app/blob/issue-2401/src/projects/detail/components/ProjectStage.jsx#L188
```jsx
// get phase post notifications
const postNotifications = filterNotificationsByPosts(notifications, _.get(feed, 'posts', []))
// get unread one
const unreadPostNotifications = filterReadNotifications(postNotifications)

// when we open posts tab, this component is mounted and marks unreadPostNotifiations as read
// in case this component was already mounted and new unread notifications comes, it will mark them as read as well
<NotificationsReader unreadNotifications={unreadPostNotifications} />,
```

Cannot say that this is a super comfortable or universal way, but so far it looks like fit good for this particular case.

**Comment by gondzo** [comment]
The only issue I see here is that we have to pass notifications down to every component that can display notifications related content.

I don't have a better solution either, so we can go with this approach @vikasrohit ?

**Comment by vikasrohit** [comment]
> Would it make sense to add some kind of 'event emitter' logic to components that display the target for a notification? 

That is something I am looking for. Can we use Redux actions to trigger such events? That might be a scalable and easy solution.

@maxceem you approach of using `NotificationReader` is also amazing and I think it would work great for most of the cases, however, as @gondzo raised the concern of passing the notifications to the very deep in component hierarchy, I am thinking that might cause few more re-renders and that might be tricky when we have forms (e.g. post create/update form, phase edit form etc) involved. So, we might end up writing `shouldComponentUpdate` method in all such components to ignore changes in those passed notifications, right?

**Comment by vikasrohit** [comment]
Moving this issue out of community fix for now as it does not seem to have full specs for community to work on.

**Comment by maxceem** [comment]
@gondzo @vikasrohit 

**event-emitter**

> Would it make sense to add some kind of 'event emitter' logic to components that display the target for a notification?
> That is something I am looking for. Can we use Redux actions to trigger such events? That might be a scalable and easy solution.

This definitely sounds like a scalable and robust solution. Though I don't see any clear way of how to actually implement it. From the top of my head Redux actions also do not directly reflect the situations when we have to mark notifications as read.

**NotificationReader**

Regarding passing notifications down from the store and re-renders issues. We can `connect` `NotificationReader` directly to the store where it will get the list of notifications. And instead of passing `unreadNotifications` we pass the cretearia for selecting notifications to mark as read.

For example:
- for phase posts and dashboard posts, it would the list of `posts`
- for system notification, we can pass `notificationType`

To make sure this way is universal enough, first we have to think though all the current situations. If we need just a couple of such criterias to cover all the cases, than we can give it try. But if these createrias become to specific for each case, than better to avoid this way I think.

**Comment by vikasrohit** [comment]
> From the top of my head Redux actions also do not directly reflect the situations when we have to mark notifications as read.

When a related component is mounted or receives new props, it can dispatch that redux action e.g. in `PhaseFeedHoc` we can dispatch redux action to mark all posts that are going to be rendered by the component as read.
Also, I am thinking how about combine both approaches, i.e. insert a `NotificationReader` as we are doing right now, however, instead of passing it the notifications, pass it the relevant data e.g. in case of `Feed` pass it the actual feed and dispatch the mark as read action in its mount or receive props method. I know this would require the `NotificationReader` to be context aware i.e. it has to be updated every time we need to support dispatching read event for a new notification type but I guess that would be manageable. What do you guys think?

>We can connect NotificationReader directly to the store where it will get the list of notifications.

That is also acceptable solution and I think we should go with this for now.

**Comment by maxceem** [comment]
@vikasrohit I'll check if there are any cases missed.

**Comment by maxceem** [comment]
@vikasrohit I think I've got some idea how we can handle it generic way based on our discussion above.

We already have:
- When we click on notification we have to redirect user to the place where he can see the subject of notification. This is based on https://github.com/appirio-tech/connect-app/blob/dev/src/routes/notifications/constants/notifications.js#L14-L20

So we can connect `NotificationReader` directly to store and pass to it **only** the `GOTO` property and variables to fullfill goto path like `projectId`, `phaseId`, `postId`, `topicId`. After `NotificationReader` has to mark all notifications as `read` which has the particular `GOTO` path and match notification contents params like `projectId`, `phaseId`, `postId`, `topicId`.

Examples:
- For all notifications which has to be marked as read when user navigates to the particular phase https://github.com/appirio-tech/connect-app/blob/dev/src/routes/notifications/constants/notifications.js#L20
   We can add component `<NotificationReader goTo={GOTO.PHASE} contents={{ phaseId: 1234, projectId: 1234 }}>` inside each of Phase. As soon as such component is mounted (phase opened or just rendered) it marks all the related notifications as `read`.

- For all notifications which lead to Dashboard tab https://github.com/appirio-tech/connect-app/blob/dev/src/routes/notifications/constants/notifications.js#L14 same. 
   We add component `<NotificationReader goTo={GOTO.PROJECT_DASHBOARD} contents={{ projectId: 1234 }}>` to the Dashboard tab and as soon as tab is mounted it will mark all realted notificatons as `read`.

It feels like this way it would be quite solid. If we navigated some notification we'd like it to be marked as read, so there will be direct relation. Otherwise if use other creterias to mark notifications as `read` we may miss some cases.

What do you think?

**Comment by maxceem** [comment]
@vikasrohit in the future maybe we can continue the same convention and use this approach to target componentns very precisely. For example:
- We want to show user a particular comment in particular phase when he clicks notification about new comment in a Phase.
- For such notifications we can add addtional precise GOTO path `GOTO.PHASE_COMMENT` like `/projects/{{projectId}}/plan#phase-{{phaseId}}-comment-{{postId}}` and we can implement scrolling to such comment when user clicks the notification
- After inside every of the comment of the Phase we can add `<NotificationReader goTo={GOTO.PHASE_COMMENT} contents={{ postId: 1234, phaseId: 1234, projectId: 1234 }}>` which will mark such comment as `read` on render.

**Comment by vikasrohit** [comment]
> We want to show user a particular comment in particular phase when he clicks notification about new comment in a Phase.

@maxceem this is something we want at present as well, but didn't implement it because of constrained timeline. 😬 

However, your plan sounds promising to me. Only thing, I would like to tweak, if possible, can we emit redux actions to mark a notification read (payload containing the data like `goTo`, `projectId` etc) instead passing the actual notifications to the `NotificationReader`? That way it would be light weight and less intrusive. One step further, we can create HOC instead of adding the `NotificationReader` in the DOM and pass, while composing, all the notifications the composed component should mark as read when the component is mounted.

**Comment by maxceem** [comment]
> can we emit redux actions to mark a notification read instead passing the actual notifications to the `NotificationReader`

@vikasrohit I'm not sure if it will work for all the cases. One of the things I was thinking about, that `NotificationReader` will check new notifications and if there are any new which match the criteria, it will mark them as `read` as well. For this we have to connect `NotificationReader` to the store, so it always knows if there are any changes. Otherwise, we can only mark notifications as `read` at the mount time only. What do you think?

> can create HOC instead of adding the `NotificationReader`

Basically, we can, but I see there one limitation. This HOC component will get some predefined list of props: `goTo`, `projectId`, `phaseId` and so on, so if we want to pass these props, we have to define them with such names in the component we apply our HOC to:
```
// define some component
const Comment = ({ comment }) => (
    
)

export HOC(Comment)

// later we call
<Commnet comment='' goTo='provide goTo' projectId='provide ID' phaseId='provide ID' />
```

While if we have a separate component `NotificationReader` we can pass to it data from anywhere:
```
const Comment = (comment) => (
    <NotificationReader goTo={`feed-${comment.id}`} projectId={comment.projectId} phaseId={comment.phaseId} />
)

// later we call
<Commnet comment='' />
```
```

**Comment by vikasrohit** [comment]
> One of the things I was thinking about, that NotificationReader will check new notifications and if there are any new which match the criteria, it will mark them as read as well.

Yes, that is the purpose. However, I am not sure if using REDUX actions won't enable us for this. I think we can just simply dispatch a generic `MARK_NOTIFICATIONS_READ` action with all required parameters and if the the reducer of that action finds any notification in the state which fulfils the criteria (by comparing each field of the action payload to the notification params) and mark them read. That way it never needs to know if there is any new notification or not in the system.
Yes, once mounted it won't be able to mark any new notifications as read until next mount. May be we can get it working by doing this in `componentWillReceiveProps` and listen to the store for any new notifications (we won't need the exact notifications though, we just need a flag that new notification is available) and we would dispatch our action to mark notifications read. If the new notification meets the conditions of the dispatched action, it would be marked as read.


for `HOC` can we prepare hoc in calling component instead of exporting the the component as HOC composite component? I mean when we have to enable `Comment` component to be able to read notifications in `FeedContainer`, we can create HOC there and here we know what exact properties we need to pass to the HOC.

**PS:** @maxceem I am just trying to refresh my knowledge about React/Redux, and not trying to force a solution. So my way might not be necessary a solution. 😬

**Comment by maxceem** [comment]
> Yes, that is the purpose. However, I am not sure if using REDUX actions won't enable us for this. I think we can just simply dispatch a generic MARK_NOTIFICATIONS_READ action with all required parameters and if the the reducer of that action finds any notification in the state which fulfils the criteria (by comparing each field of the action payload to the notification params) and mark them read. That way it never needs to know if there is any new notification or not in the system.

Yes, for this case we can handle it with REDUX actions only and component doesn't need to know about notifications.

> Yes, once mounted it won't be able to mark any new notifications as read until next mount. May be we can get it working by doing this in componentWillReceiveProps and listen to the store for any new notifications (we won't need the exact notifications though, we just need a flag that new notification is available) and we would dispatch our action to mark notifications read. If the new notification meets the conditions of the dispatched action, it would be marked as read.

Yes, I guess we can do like that, though I'm not sure if there are benefits in comparision with checking if there are new notifications or no and dispatching `MARK_NOTIFICATIONS_READ` if needed. As anyway we have to connect to store.

> for HOC can we prepare hoc in calling component instead of exporting the the component as HOC composite component? I mean when we have to enable Comment component to be able to read notifications in FeedContainer, we can create HOC there and here we know what exact properties we need to pass to the HOC.

Not sure I've got it correctly. Do you mean creating a new HOC with different sets of properties for different situations?

> PS: @maxceem I am just trying to refresh my knowledge about React/Redux, and not trying to force a solution. So my way might not be necessary a solution. 😬

Ok :-)

Though I thing there is a way to handle this issue with Redux actions only. Without connecting component to the store.
- Every time `NotificationReader` is mounted it fires some action `START_REDING_NOTIFICATIONS` with criteria for notifications in payload `{ postId: 1234, phaseId: 1234, projectId: 1234 }`. This action does two things:
   - mark notifications which fits the creteria as read
   - add the criteria to the list described below
- In the redux store we keep a list of all places where we are currently listen to notifications:
   ```
   listenNotifications: [
      { postId: 1234, phaseId: 1234, projectId: 1234 },
      { projectId: 1234, type: 'system' },
      ...
      { postId: 1234, projectId: 1234 }
   ]
   ```
- Every time we load notifications, means action `GET_NOTIFICATIONS_SUCCESS` happens, we check if there are any notifications has to be read using list of creterias above
- When component `NotificationReader` is unmounted is has to remove its createria from the list by firing `STOP_REDING_NOTIFICATIONS`.

**Comment by vikasrohit** [comment]
> Yes, I guess we can do like that, though I'm not sure if there are benefits in comparision with checking if there are new notifications or no and dispatching MARK_NOTIFICATIONS_READ if needed. As anyway we have to connect to store.

I am not much as well, however, my intent is to stay away from the array of notifications in every instance of the `NotificationReader` to reduce the memory footprint of it, reduce the number of fields to manage and make it simple to detect the changes in the state.

> Not sure I've got it correctly. Do you mean creating a new HOC with different sets of properties for different situations?

Yes, kind of. More specifically I mean, call `HOC(Comment)` when using it, not when exporting it.

> Though I thing there is a way to handle this issue with Redux actions only. Without connecting component to the store.

It looks good to me. However, it seems this approach will pull away the capability of rendered components to react based on incoming new notifications, e.g. we want to show the `Reload the content` button to refresh the discussions page when there is a new topic or post. I guess, this approach would mark the notification as soon as it comes and would not give `FeedContainer` an opportunity to react.

**Comment by maxceem** [comment]
@vikasrohit @RishiRajSahu let's decide when we want to dismiss notifications. Check the sheet, is my understanding is correct or you'd like to adjust something https://docs.google.com/spreadsheets/d/1olFRCgXyZy6DTBWmFCJF-MXuhxh80y5JWOKvlSpgguU/edit#gid=1005864840

@vikasrohit FYI I'm working on this issue. I guess I can incorporate all your recommendations except for HOC.

**Comment by RishiRajSahu** [comment]
@maxceem I traversed through the list, looks good to me, have a questions though - 
`notifications.connect.project.submittedForReview` & `notifications.connect.project.approved` was there any reason for keeping their path `undefined` , I think we can keep `/projects/{{projectId}}`. Correct me If I am missing anything here.

**Comment by maxceem** [comment]
> was there any reason for keeping their path `undefined`

Don't see any reason for that, will update path to dashboard

**Comment by maxceem** [comment]
@RishiRajSahu I guess for `notifications.connect.project.member.left` and `notifications.connect.project.member.removed` we can also put link to the project `/projects/{{projectId}}`. As both of these events see a member who is still IN project.

**Comment by RishiRajSahu** [comment]
@maxceem okay let's add the link for them as well.

**Comment by RishiRajSahu** [comment]
Closing pushed to dev.
