### ISSUE TITLE
[$40] Bring back the welcome post to the customer upon project creation

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2011]
When the user lands on the dashboard after their new project is created, the system used to create a welcome post from Coder.

It is really important to maintain the welcome feel of the user experience, thus let's reinstate the initial post that drives the user to go and complete their specification, and explains what they should expect next.

**Comment by vikasrohit** [comment]
@gondzo Some changes are needed in the backend to enable the posts from coder bot, I would take care of that or may get it resolved via tasks. Purpose of this issue is to show those message again on the front end. The question is that how can we determine which coder bot message to show because the currently front end is simply hiding all the system user's messages to reduce the noise. I don't think we can determine specific topic of system user to hide, so most probably we need to do this in backend again.
Let me know what do you think? I am removing it from the cf09 for now, please add it back if you think we can get it handled on the front end once the backend starts posting the coder bot message again.

cc: @rmjmccormick

**Comment by vikasrohit** [comment]
@gondzo @rmjmccormick backend changes are done for the issue. Now we need to think over how to hide specific system messages.

**Comment by gondzo** [comment]
OK, we will just disable checks for system messages when fetching posts/topics from message api

**Comment by jankyzhang** [comment]
I am working on this - please assign when provided access.

**Comment by jankyzhang** [comment]
Please add the "Ready for Review" label
I cant assign myself.
Thanks

**Comment by jankyzhang** [comment]
![printscreen](https://user-images.githubusercontent.com/2173685/42934321-6a6b56d0-8b79-11e8-947e-41b8f784270b.png)

**Comment by gondzo** [comment]
@jankyzhang you need to accept the invite (sent via email) to get access to the repo

**Comment by jankyzhang** [comment]
@gondzo ,thanks.
I just find it.
