### ISSUE TITLE
[$40] Notification dismissal on notification center not working properly when multiple project exist

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2089]
### Expected behavior
When on the notification center, and there are multiple projects, when the user selects a certain project from the right-hand menu, and dismisses the project, the "no more notifications" message is shown, instead of showing the main notifications tab.

Attached is a recording of the behavior described.
[notification dismissal.mov.zip](https://github.com/appirio-tech/connect-app/files/2135406/notification.dismissal.mov.zip)

###Expected:

When a project is selected from the right-hand menu, and upon "Mark All" the notifications are empty, we should reload the main view (unfiltered) as to show all notifications.

**Comment by maxceem** [comment]
I see the issue. It's because we filter notifications by some particular project and after we mark all the notifications of that project a `read`. As filter stays, we don't have anything to show for the particular project, see the demo video, it's slightly changed since this issue was initially created: https://monosnap.com/file/nFBoMgEp3Pxjr7BSYN5x8ygMtfzlvj

So in case we first filtered by some project and after marked all the notification as read for that project we should:
- make sure project name with `0` is NOT displayed at the filter tab
- reset filter to `All notifications`, so we can see all notifications.

**Comment by vigneshTheDev** [comment]
I would like to work on this issue

**Comment by maxceem** [comment]
Sure, it's on you.

**Comment by maxceem** [comment]
Hi @vigneshTheDev I've review the PR, please have a look https://github.com/appirio-tech/connect-app/pull/2764#pullrequestreview-195876429

**Comment by vigneshTheDev** [comment]
Hi @maxceem, created a new PR with a different approach here: https://github.com/appirio-tech/connect-app/pull/2784.

**Comment by maxceem** [comment]
To all the participants of the **Topcoder Connect - Bug Bash 14** https://www.topcoder.com/challenges/30079880

Please, don't forget to submit a file with a list of issues you were working on during this challenge (even if not yet accepted) on the challenge page https://www.topcoder.com/challenges/30079880
This would speed up the payment process. 

cc @vigneshTheDev @afrisalyp @gets0ul @cagdas001 @rashmi73 @Gauravseta @saikat041 @PrakashDurlabhji @KevinLeigh @suppermancool
