### ISSUE TITLE
Main progress and phase progress mismatch

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2117]
Looks like there is mismatch in how progress is calculated for ProgreeBar and Phase progress

<img width="828" alt="progress-mismatch" src="https://user-images.githubusercontent.com/146016/42142382-948847de-7de1-11e8-908a-df4168e49818.png">

There is only one phase which shows `20%` done, while global progress shows `10%` done. If there is only one phase they suppose to match, as I understand.

See project http://connect.topcoder-dev.com/projects/6448/plan

cc @RishiRajSahu

**Comment by RishiRajSahu** [comment]
@maxceem yes there is difference between the progress calculated at two places, as there is an additional field at phase level which is used to manually update the progress of phase. I will give you more details on this offline, but yes the logic is different once the progress field is populated manually.

**Comment by vikasrohit** [comment]
@RishiRajSahu I think there is still some issue with the logic. In the example project shared by @maxceem the phase has auto calculated progress of 20% (which should be 10% as of today IMO because it has only one day past in the scheduled duration of 10 days) but the overall progress is 10%. Ideally, with one phase in the plan, it should match with overall progress.

**Comment by vic-topcoder** [comment]
These numbers should differ by design, unless you have 1 phase in the project and the progress is based on time. In the case of manual progress for a phase vs. time-based progress for project, the two would almost always have different numbers, and that's fine. That's the whole point of reporting 2 different progresses. Hope that helps.

**Comment by vikasrohit** [comment]
@vic-topcoder Just to be on the same page, we discussed that the progress number shown in the right side of the overall progress bar is simple arithmetic average of individual phases' progress. Each phases' progress is calculated based on custom progress or time based progress in order. So, technically the numbers should not differ. However, if a user calculates the progress by dividing the days elapsed out of total scheduled duration (which we are showing the left portion of the progress bar), that would come different than the number we are showing in the right side of the bar.

@rmjmccormick 
If we like to use the day based progress, instead of arithmetic average of individual phase progress, for the overall progress of the project, let us know.

**Comment by rmjmccormick** [comment]
@vikasrohit Let's stick with arithmetic average please.

**Comment by vikasrohit** [comment]
Okay, Thanks @rmjmccormick for the confirmation.

**Comment by RishiRajSahu** [comment]
@vikasrohit i think here only thing to be taken care of is to correct the logic in case of single phase and validating again in case of multiple phases as per

> arithmetic average of individual phase progress

I am picking this up.

**Comment by RishiRajSahu** [comment]
Fixed the bug in progress bar logic for single phase and pushed to dev.
