### ISSUE TITLE
New posts do not trigger dashboard/page reload

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2176]
### Expected behavior
When a new post is created the system should auto-reload the screen, or display a suggestion to reload the page (if scrolled down).

### Actual behavior
This functionality was implemented before, not with the new post cards it is broken.

**Comment by maxceem** [comment]
Fixed by https://github.com/appirio-tech/connect-app/commit/125f0bc3309ab5bce93937ec1a3501a62a4ee362

Note, that if a user is not a member of the project, this feature won't work for him. As this feature is based on notifications and non-memeber doesn't get notifications. This is how it has been implemented since the begininng.

**Comment by vikasrohit** [comment]
> Note, that if a user is not a member of the project, this feature won't work for him. As this feature is based on notifications and non-memeber doesn't get notifications. This is how it has been implemented since the begininng.

Good to point out that @maxceem so that all are on the same page. Thanks.

**Comment by RishiRajSahu** [comment]
Closing as pushed to dev . fyi @vikasrohit @rmjmccormick
