### ISSUE TITLE
Specification tab info not saving in Development integration & Front end dev phases

### ISSUE THREAD

**Issue by rmjmccormick** [appirio-tech/connect-app#2192]
When I add and save data to the specification tab in a Development integration or front end dev phase, the specification tab resets itself to default view (the specs data disappears) when I toggle to another tab and then return into specification.

Tested with Pat Monahan account

**Comment by RishiRajSahu** [comment]
Found the issue, it was due to absence of `"hidden": true` flag for scope questions under product templates. Iterated over other products as well to check for the same issue, found two more products `Backend-Dev` and `other-design` apart from `Development integration` and `front end dev` product.

Fixed all of them.

**Comment by rmjmccormick** [comment]
Good job @RishiRajSahu Appreciate it!
