### ISSUE TITLE
First post in a topic

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#2216]
At the moment we allow users to delete all posts in a topic so we can end up with an empty topic, but our UI breaks with no posts. I think we should just disable deleting the first post - user should delete the topic instead. Alternative is to disable deleting a post if it's the only one in the topic (this might lead to having different topic author and first post author).
What do you think @vic-topcoder @rmjmccormick ?

**Comment by rmjmccormick** [comment]
@gondzo Agreed. We should be prompting the user to delete the topic rather than the post if there intention is essentially to remove both.

**Comment by vic-topcoder** [comment]
If a topic is empty, we might display a message "No posts in this topic yet" but I'd love to think we never have a topic without posts. Agreed with @rmjmccormick - let's check if they want to delete the only post and substitute the "delete post" with "delete topic" on the post edit menu - shouldn't be that hard of a change.

**Comment by vikasrohit** [comment]
It should not be hard, however, the question is should we consider the first post of the topic or the only post of the topic as non deletable?
> Alternative is to disable deleting a post if it's the only one in the topic (this might lead to having different topic author and first post author)

Not UX expert but as a user of the product, instead of changing the button in the edit menu, I think prompting user with reason of deleting topic, would be better as it won't confuse user that for some posts they are seeing 'Delete Post' button and for one they are seeing 'Delete Topic'.

**Comment by RishiRajSahu** [comment]
@vikasrohit I think changes to not allow the user to delete the first post of a topic are in place. can we close this ? or we still have to decide on `first post` or `the only post` ?

**Comment by vikasrohit** [comment]
Yes, it can be closed now.
