### ISSUE TITLE
Update values for default texts of existing milestone templates - Website and VD

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2228]
The milestones templates currently present in backend needs to be updated with text provided [here](https://docs.google.com/spreadsheets/d/1SXZjX5TlbfFa7IuifOseCKqvqkytxeXUEH3A1rL0CCw/edit#gid=0)

**Comment by vikasrohit** [comment]
@vic-topcoder @rmjmccormick @acshields just to make all on same page, the sheet linked in the issue description, describes the texts for milestones based on new product catalog which works on `iteration` based products while right now our catalog on production does not have that. We have all different sorts of products i.e. website, app, chatbot etc. So, the scope of this issue is not to incorporate the new product catalog rather we would use the same text for all products in the same category e.g. we would be using milestone texts provided in the sheet for `Design Iteration` product for all current products which are in `design` category.

fyi @RishiRajSahu

**Comment by RishiRajSahu** [comment]
@vikasrohit exactly !

**Comment by amitpatra** [comment]
I am picking up this issue. I have sent a request to let me access the provided google docs document.

**Comment by gondzo** [comment]
@amitpatra document attached here
[Product milestones - connect.xlsx](https://github.com/appirio-tech/connect-app/files/2228730/Product.milestones.-.connect.xlsx)

**Comment by amitpatra** [comment]
@gondzo Thanks :)

**Comment by RishiRajSahu** [comment]
@amitpatra wait before starting on this issue.

**Comment by RishiRajSahu** [comment]
Its done for website and VD. Closing the issue.
