### ISSUE TITLE
Need of recall button for review milestones

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2236]
We might need a new button, Recall Review in that case which would enable manager to recall the customer review option in case they had clicked on the Mark for Review button accidentally.
Continuing from https://github.com/appirio-tech/connect-app/issues/2231#issuecomment-407693144
fyi @rmjmccormick @acshields @RishiRajSahu

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-463

**Comment by vic-topcoder** [comment]
While a milestone is send for customer review we can't ask for extension. Those two should be mutually exclusive.

Here's the thought process:
1. The milestone becomes active;
  - Customer sees a progress bar
  - Copilot sees "Complete milestone" button to be able to close the milestone early (if supported by the milestone), "Add designs" if the milestone is design review or final designs, and "Request for extension" if we might need more time to complete the work. Requesting for extension is considered a bad practice and we aim to eliminate it.
2. The milestone work is completed and the customer has to take a decision (review, accept delivery);
  - Customer sees the decision interface - select designs (review, final designs) or accept final delivery (accept, or request final fixes).
  - Copilots have no control when the customer is in control with the exception of completing the design review (select which 5 design variants are taken to finish). This is a work-around to speed things during review. All other actions must be performed by the customer! If any delays are caused by the customer that is their responsibility. This is the "self-service" model we're working towards. As copilots you can only contact the customer and urge them to complete the step, but not do execute the step for them.

**Customer view**:
![screen shot 2018-07-27 at 11 55 36 am](https://user-images.githubusercontent.com/8484061/43341540-b2b7df00-9194-11e8-8662-cdc12648bdf1.png)

**Copilot view**:
![screen shot 2018-07-27 at 12 00 11 pm](https://user-images.githubusercontent.com/8484061/43341555-bf2f998a-9194-11e8-8b87-b5eb2f06bb50.png)


I don't see a way we can mix review and extension at the same time. Hope this helps.

**Comment by vic-topcoder** [comment]
moved to productboard
