### ISSUE TITLE
Fix phase time calculation of the phase

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2286]
Fix phase time calculation of the phase - right now the logic is still broken and we do not update the days left/elapsed.

I was talking about this duration of days calculated. It should point to how many days the phase would take to be completed. By the way, when there is a single day, it should say 1 day instead of 1 days. Once we complete all the milestones the duration would change if we delivered the work earlier. If we started with 28 days, but delivered 5 days earlier, this day count should say 23 days • Month 1-23 • # posts.

![image](https://user-images.githubusercontent.com/146016/43673428-998d6cc2-97f5-11e8-8c2e-41771fa7c2a0.png)

Comes from https://github.com/appirio-tech/connect-app/issues/2268

**Comment by maxceem** [comment]
There are two ways to accomplish this one.

1. We can just calculate days based on the length of all the milestones inside. And ignore the duration which is defined inside phase.
    This way it's done now for progress. Progress bar shows 76% based on the accomplished milestones while the percentage inside phase is set to `0`.
    <img width="588" alt="progress" src="https://user-images.githubusercontent.com/146016/43673480-5dc28014-97f6-11e8-9aa4-cb44e7db4eca.png">

2. We can actually update the duration of phase based on the duration of timeline and after just show the duration of phase which will match the duration of timeline. This ways looks more right for me, but I could miss something.

    If we chose this way, we will probably want to fix this for progress also.

**Comment by vikasrohit** [comment]
@maxceem 1 is better way for us because we don't want keep syncing one more field between phase and timeline/milestone and we are using the pristine state of `progress` field as indicator of user not setting it explicitly, so we can use user set value of the progress to override all other calculated values.

One additional thing  I would to get done is that disable the progress field as well for Edit phase form when the phase has timeline and milestones attached just like we are doing for `duration` field. That would make things simpler for users and us.

> In the left section of milestone so far we only show startDate for each milestone. Could you please clarify how should we show completionDate?

Oh yes, that was my thoughts last time I checked this issue, but forgot my thoughts. 😬 Can you please check what might be the reason of Vic not seeing correct dates for the milestones in that case? I think it must be because of timeline not being refreshed which you already have captured as separate issue.

**Comment by vikasrohit** [comment]
@maxceem when do you expect this one to be in fix branch?

**Comment by maxceem** [comment]
@vikasrohit tomorrow till the EOD if that is ok.

**Comment by maxceem** [comment]
Done.
For testing:
Example of a project with timelines http://local.topcoder-dev.com:3000/projects/6375/plan
Example of a project without timelines http://local.topcoder-dev.com:3000/projects/6375/plan

**Comment by vikasrohit** [comment]
@maxceem closing this one and created new issue #2324 for pending work.
