### ISSUE TITLE
Add `info` icon to tooltips for disabled phase fields

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2338]
## Task

There are disabled fields at phase form, like `duration` and `progress` with a help tooltip.

![image](https://user-images.githubusercontent.com/146016/43935266-c13d39de-9c85-11e8-9381-4f9ffc5bae71.png)

We have to add a help `icon` indicating there is a tooltip with help.

![image](https://user-images.githubusercontent.com/146016/43935305-e06e4028-9c85-11e8-8b91-1a28e35a2c9b.png)

## Note

The whole component for displaying label + input = `<TCFormFields.TextInput>` comes from `appirio-tech-react-components`:

<img width="675" alt="label_input" src="https://user-images.githubusercontent.com/146016/43935386-5c259a72-9c86-11e8-8476-3c84729d6bcd.png">

As you can see above if we just try to add an icon directly, it can only be placed on the edges of the whole component `<TCFormFields.TextInput>` which looks not good.

So to implement it, most likely I'll need to update `<TCFormFields.TextInput>` in `appirio-tech-react-components` OR partially reimplent it in `connect-app`.

## Question

To choose the best way to implement it, please advise where you woud like the help icon to be placed?

<img width="678" alt="untitled-2" src="https://user-images.githubusercontent.com/146016/43935765-11013b44-9c88-11e8-83ea-9995e1915bd0.png">

@vikasrohit
Continues https://github.com/appirio-tech/connect-app/issues/2248#issuecomment-411692163

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-318

**Comment by vikasrohit** [comment]
I think 3 is better. But I would wait for @vic-topcoder to suggest the best way.

From technical point of view, I think we should add tooltip feature to form components in react-components repo. We should show tooltip if tooltip content is provided and should give option to place it at two places, one is after label (which option 2 in above image) and another would be after value (option 3).

Anyway, we would take care of it later, for now adding it to the list of 2.4.5.

**Comment by vic-topcoder** [comment]
Option 4 is the best - it does provide help target, but not associate the explanation with the days themselves. On 3 I assume the user would understand the question mark to explain why there are exactly 17 days, not what controls the duration.

Let's go with option 4. I'll attach some design guidelines for helper icon - this was always a tertiary option/feature and it never had the chance to leave the drawing board (but I have ideas about it!).

**Comment by maxceem** [comment]
@vikasrohit Should I just follow 4th case advised by @vic-topcoder or any new design will be provided?

**Comment by vikasrohit** [comment]
@maxceem I think we need capability of having tooltip like option 3 as well because in this case, we are showing tooltip only when the field is disabled and its value is controlled by timeline, so essentially we are showing tooltip to let user know from where the value is coming, we are not describing the the duration field itself where we need option 4.And last thing, for option 4 we don't need change in the react-components because we can achieve that by adding tooltip component after the formsy component, right?

**Comment by vikasrohit** [comment]
To be more specific about the scope @maxceem I think following needs to be closed in this scope:
1. Update react-components repo to support tooltips(with configuration for placement of the tooltip) in formsy components (wherever possible)
2. Use the capability developed in 1 to show tooltip for `duration` field OR
3. if we still have strong argument in favour option 4 for this particular use case, show the tooltip after the formsy component.
In nutshell, whether we go with task 2 or 3, it would be better to have 1 done so that in future we can get tooltip support just we like.

**Comment by maxceem** [comment]
@vikasrohit correct, for option 4 we don't need to updated react-components.

**Comment by vic-topcoder** [comment]
info icon
[round-e-help.svg.zip](https://github.com/appirio-tech/connect-app/files/2311395/round-e-help.svg.zip)

**Comment by maxceem** [comment]
I've put a wrong comment for this commit https://github.com/appirio-tech/connect-app/pull/2447/commits/7fe567afdb58c7a0b2cd410b623b93e3396b12d0 it's has to be for this issue, not 2339.

This fix depends on the [PR 292](https://github.com/appirio-tech/react-components/pull/292) to react-components.

**Comment by RishiRajSahu** [comment]
Working fine on dev.
