### ISSUE TITLE
Add the file attachments to the scope section for all projects.

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2357]
### Expected behavior
Customers and managers alike should be able to add files to the scope section of each project. Each file added should be visible in the files list on the dashboard sidebar.

I know that we are concerned about the anonymous people adding files during project creation; this would change in one of the next releases (only authenticated users would be able to create projects); and we can simply hide the file upload during project creation (filter it out).

This feature is high priority due to customer and manager communication that almost always involves file exchanges (and we want that to be Connect).

### Actual behavior
File section/uploads is missing from scope

@acshields FYI

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-335

**Comment by vikasrohit** [comment]
Will try to incorporate this after the release, as it mostly changes in templates which have to do via API. We were waiting for #2161  and #2162 to be decided so that we don't have to make the repetitive efforts of updating all templates. However, I think those two are going to take more time, so I would rather do that double efforts to close this issue.

Also, now we have the ability to hide the file upload section from project creation wizard while keeping it at project scope level, so we should be able to add the file upload to all project templates now without worrying about anonymous access to the file upload endpoint.

@vic-topcoder @acshields we are already discussing this in https://github.com/appirio-tech/connect-app/issues/2106, so let me know if we can close this one and continue our discussion there because that issue has more details and discussions around the requirements and implementation details.

**Comment by vic-topcoder** [comment]
yes, scope and specification are really going to take a while before completed, so let's try to incorporate the files into Scope. Given the fact we're hiding specification tab for customers, they'll have no way to upload files after the release, so I think we should address it as a quick follow up mini-release just for the file upload.

**Comment by vikasrohit** [comment]
We don't need a release for that @vic-topcoder. We would do that most probably with this release as all this is matter of correct data entry and as we have to update almost all templates in this release, we would try to incorporate this as well. If not, we would do that immediately after successful release.

**Comment by vic-topcoder** [comment]
thanks @vikasrohit

**Comment by vikasrohit** [comment]
Added file attachment section for all visible project templates on production. Let me know if you are not seeing it for any specific one.
