### ISSUE TITLE
Impossible to add phases to older project

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2398]
### Expected behavior
I should be able to add the latest phases (iterations) to any project that already has a project plan.

### Actual behavior
On an old project with phases, opening the menu would display the correct phases, but clicking on any of them does nothing (the phase is not added to the project). 

### Steps to reproduce the problem
- Open https://connect.topcoder-dev.com/projects/6966/plan
- Click on "add a phase"
- Try to add any phase

**Comment by vikasrohit** [comment]
@vic-topcoder @acshields Fixed and deployed to both dev and production.

**Comment by vikasrohit** [comment]
For the records posting the investigation results:
There are two cases when it is failing. For the project you mentioned in the ticket, it is failing because the incorrect data in database, we didn’t have milestone templates for all products when those phases were added in the project which in turn causes the empty milestones and failing to calculate the start date of the next phase.
Second use case is where the existing phase is not planned yet, in this case logic is unable to determine the start date of the new phase because dates on the existing phase is not set yet.
