### ISSUE TITLE
Show topic by id

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#2464]
Update RedirectToProject component to show the exact topic (by topic id) in one of these screens
dashboard - already works as expected
discussions tab (for old projects) - already working
project plan (route projects/:projectId/plan#feed-<feedId>)

related changes are in #2306

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-429

**Comment by vikasrohit** [comment]
@gondzo do we really need this now? I mean as we are not using the URL `discussions/{topicd}` anywhere now (we used to use this in discourse), we might not need to handle that URL. I think we never shared that URL with any other external system or person, so we should be safe to discard that URL. Let me know if you think there might still be some application or person using that URL.

On the other hand, we might need to fix the `projects/:projectId/plan#feed-{feedId}` route to work correctly when it is not routed from within the application i.e. when this URL is directly loaded in the URL. It does not work in that case because the `#feed-{feedId}` element is not rendered in the DOM at that time. However, I managed to get it work around via URL `projects/:projectId/plan#phase-{phaseId}-posts` which actually load the plan tab, expands the particular phase and opens the `Discussions` tab which is essentially doing what `projects/:projectId/plan#feed-{feedId}` is expected to do because we have only one topic per phase. I think we still need to do some work to render the specific post of that topic though.

fyi @maxceem

**Comment by vikasrohit** [comment]
Related issue https://github.com/appirio-tech/connect-app/issues/2177

**Comment by RishiRajSahu** [comment]
@vikasrohit @gondzo @maxceem can we close it ?

**Comment by gondzo** [comment]
yes, I think we have everything working correctly here

**Comment by RishiRajSahu** [comment]
@gondzo okay, closing this as we also have one more similar issue #2177.Another thing to mention phase post notifications right now are not taking to specific post under a phase on project-plan page.
