### ISSUE TITLE
Discussions not displaying on Dashboard sidebar

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#2465]
### Expected behavior
I expect to see the same summary list of discussions shown in the left sidebar of the Dashboard and Project Plan.

### Actual behavior
The sidebar in the Project Plan are showing discussions.  However, the sidebar in the Dashboard are not showing the same list of discussions.

![screen shot 2018-08-31 at 12 55 49 pm](https://user-images.githubusercontent.com/41118149/44933234-3f275800-ad1d-11e8-8438-469e9a17140e.png)

![screen shot 2018-08-31 at 12 55 42 pm](https://user-images.githubusercontent.com/41118149/44933240-43ec0c00-ad1d-11e8-9be1-a4f8d1d4a3a7.png)

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-430

**Comment by vikasrohit** [comment]
That is a technical limitation @acshields. Our left panel `Discussions` links are expected to scroll to the particular discussion on the dashboard and if we show the discussion about project plan (i.e. discussions specific to the phases) on the dashboard, we won't be able to do that and use would feel stuck there. And if instead open the project plan tab on click of phase discussion from the dashboard, it would make a page change which might not be the user's intent and they might feel confused as they clicked on `Dashboard` and we took them to project plan page.

If we are okay with page shift for phase discussions from dashboard to project plan, we can implement that. Let us know your thoughts.

**Comment by acshields** [comment]
I am okay with the page shift from dashboard to project plan. @vikasrohit

**Comment by vikasrohit** [comment]
Okay.

@RishiRajSahu We can take this in CF.

**Comment by maxceem** [comment]
This task heavily depends on https://github.com/appirio-tech/connect-app/issues/2464. After that issue is done we can easily handle this one. I'm marking this as blocked until then.

**Comment by vikasrohit** [comment]
@maxceem I don't think we are dependent on #2464 for this as the simple hyperlink `https://connect.topcoder-dev.com/projects/7248/plan#phase-2097` in `LinkMenu` component with custom `onClick` method, which we are already doing on project plan tab, would work as is. All we need to do is the render the phase topics list on the dashboard left panel as well.
Let me know if I am missing something here.

**Comment by maxceem** [comment]
@vikasrohit if understand correctly this has to work like this in total:
Add links for the phase topics to the dashboard sidebar as requested above. These links should lead to `projects/:projectId/plan#feed-${feed.id}`. When we click them, the project plan tab has to become active, browser window has to be scrolled to the phase related to the topic and Discussions tab of the phase has to be opened.

So the described behaviour is now implemented by the custom `onClick` method on the project plan page, and it has to also work from the dashboard page. And the task which is described in https://github.com/appirio-tech/connect-app/issues/2464 looks like general case for such behavior: "navigate to the conrete topic including topic of the phases". So looks like issue #2464 will also replace custom `onClick` method on the project plan page.

Let me know if I'm overthinking here.

2. Btw, should we also add links to the Dashabord topics on the Project Plan page sidebar?
    As I understand it was requested in the issue description but later not sure if it was canceled or no:
    > I expect to see the same summary list of discussions shown in the left sidebar of the Dashboard and Project Plan.

**Comment by vikasrohit** [comment]
> Btw, should we also add links to the Dashabord topics on the Project Plan page sidebar?

And yes, we need to show the same list of topics in the left panel of both dashboard and plan tabs.

**Comment by vikasrohit** [comment]
@maxceem I think we are done with the fix for this issue, right?

**Comment by maxceem** [comment]
@vikasrohit no, it wasn't included in the recent CF as didn't have time to clarify it for myself. I'll update on it soon, and will fix myself if it's needed asap.

**Comment by vikasrohit** [comment]
Okay. It would be great if we don't have anything pending in terms of requirements and you can close it by tomorrow morning.

**Comment by maxceem** [comment]
@vikasrohit most of things are clean and I'm currently implementing it.

Only two things: so far we don't pre-load feeds for dashboard and always reload them when we come to the dashboard. It causes two undesired behaviours:
1. on the Project Plan tab we don't have feeds loaded, so now we have to change it, and loads all the feeds to show their list on the Project Plan tab
2. we have to stop reload feeds when we come to dashboard page otherwise it would be like this https://monosnap.com/file/OS7hVZj9obyLtTXLbw1w8GFt72zsYN

Does it make sense? I do both of these changes?

**Comment by vikasrohit** [comment]
> on the Project Plan tab we don't have feeds loaded, so now we have to change it, and loads all the feeds to show their list on the Project Plan tab

Isn't this `projects/:projectId/plan#phase-${phaseId}-posts` url automatically taking care of this?

> we have to stop reload feeds when we come to dashboard page otherwise it would be like this https://monosnap.com/file/OS7hVZj9obyLtTXLbw1w8GFt72zsYN

Didn't completely understand the issue here. You mean, there would be an extra load or there would be an error?

**Comment by maxceem** [comment]
@vikasrohit let me start from the beginning to make sure we are on the same page here.

Our goal: show list of `Discussions` (from dashboard) and `Phase Topics` together in one list on the sidebar for both tabs: `Dashboard` and `Plan`, like this:

![sidebar](https://user-images.githubusercontent.com/146016/45751276-787c2500-bc44-11e8-838b-5c2cac9315af.png)

We can easily achieve it on Dashboard tab as on the dashboard page we have `Discussions` loaded. And we have phases loaded everywhere.

1. On the Plan tab we have phase loaded. But we don't have `Discussions` loaded, so we have to load them too here.

This is the first point, please let me know if it's clreat for now, while I'm preparing description for the second point.

**Comment by maxceem** [comment]
@vikasrohit 

Point 2.
Imagine if point 1 from previous comment is resolved now.
Let's say we are on the Plan tab and we want to click to the link, which leads to some topic in the `Discussion` on the Dashboard tab.

So far, evey time when we switch to Dashboard tab, `Discussions` are being re-loaded. That's why when we click on the some link on the sidebar from Plan tab it will look like this: https://monosnap.com/file/pv92XeI03cXO9KWaC1Bt3rDuJYjIy9

**Comment by maxceem** [comment]
@vikasrohit done via PR https://github.com/appirio-tech/connect-app/pull/2533

Dome video https://monosnap.com/file/Bop71SmiPM7QSDYY6DjdxZRWlTlITL

Note. The only one major change was done to existent behavior. 
Before: every time we go to the Dashboard tab - feeds are reloaded.
After: when we go to the Dashboard tab - feeds are NOT reloaded.
It's done so the navigation between these two tabs is smoother, otherwise, every time we click a dashboard topic on the Plan tab it will look like this: https://monosnap.com/file/pv92XeI03cXO9KWaC1Bt3rDuJYjIy9

**Comment by RishiRajSahu** [comment]
Closing as working fine, verified on dev.
