### ISSUE TITLE
Changing welcome post for newly created project until scope page doesn't have additional fields to submit

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2479]
Make sure the welcome post for a new project actually makes sense. The current scope section doesn't have additional data to submit, and we don't want our customers to reach out to support via email.

> Coder the Bot2:17 pm
> Hello, Coder here! Your project 'App design sample test project' has been created successfully. For your next step, please head over to the Scope section and answer all of the required questions. If you already have a document with your requirements, just verify it against our checklist and then upload it. Once you're done, hit the "Submit for Review" button on the Specification. Get stuck or need help? Email us at support@topcoder.com.

continued from https://github.com/appirio-tech/connect-app/issues/2301

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-452

**Comment by RishiRajSahu** [comment]
@acshields @vic-topcoder We only have files as the additional field to be submitted on scope page, so should we update the post content accordingly ?

**Comment by vikasrohit** [comment]
@vic-topcoder @acshields customer has still go to `Scope` section and click on the `Submit for Review` button to let their projects in review by topcoder. So, IMO, the message still makes sense to me as customer.
And there might be a day where have extra questions in scope section of projects, and we might forget on that day to update the message back to reflect the same. So, IMO, it is better to keep this and lets get more specific questions in the project templates as soon as possible.

**Comment by vic-topcoder** [comment]
I'm a bit confused as of why we have to submit for review at this point. Probably let's make sure we have a unified flow for all project types, and update the welcome message text to represent that. @acshields assigned for your input on the issue.

**Comment by acshields** [comment]
Let's talk this over tomorrow morning, as this step is confusing me as well.  IMO, once a customer submits a new project intake form (where they answer scope questions), the project should automatically be submitted for review.  I want to make sure I am not misunderstanding the flow.

**Comment by acshields** [comment]
Also @vikasrohit, I understand your point above about potentially having additional scope questions after intake in the future.  I think the outcomes of the Connect product summit from last week (that I will share tomorrow morning) will help cover some of the strategy we hope to see in the future for this type of scenario.  In short, on this topic there are two questions: 1) Why is the project not auto-submitted for review today after the intake form is complete? 2) Do we need the text, given conversation on Question 1 and what I will be sharing with you tomorrow.

**Comment by vikasrohit** [comment]
> I'm a bit confused as of why we have to submit for review at this point.

The reason we are confused here is because we haven't thought complete picture when we did changes for separating the old Specification form into Scope and Phase Specification. Even we are not yet done with #2161 and #2162 which are essentially what makes the logic of `Submit for review` button, realistic. I am not in support of hide UI elements in one release and bring it back in near future releases just because we don't have the complete picture.
We already our training [videos](https://youtu.be/kOGMk_7thbk?t=119) which mentions that how to submit project for review by topcoder. So, changes like this invalidates them and irrelevant. We can change changes in UI with moderate frequency, but I don't think we should play with process too often.

> 1) Why is the project not auto-submitted for review today after the intake form is complete?

Because it introduces ton of spam projects to our slack channel for managers. They get overwhelmed with the spam projects and miss some real leads. We have done experimenting this in past (@vic-topcoder might recall that) and we have to roll back this change within couple of weeks because managers were overwhelmed with the spam.
The current way is very efficient for bringing in quality leads for review. Our CoderBot message clearly says that just review your specification/scope and submit your project for review to proceed further. And if someone is really interested in getting work done, he/she is most likely to read the only message on their dashboard after project creation and follow the mentioned process. Any spam project creator would miss that in most of cases.

> 2) Do we need the text, given conversation on Question 1 and what I will be sharing with you tomorrow.

I think our content of the message is good right now, at least what I personally feel as general user.

**Comment by vic-topcoder** [comment]
Ok, so project submit after creation would have to be removed alongside the new project creation flow. Going forward we are requiring all users to be identified (registered) before they can complete a project. This means we must cover the cases of existing TC members creating a new project (not customers), and existing customers without business details. Given the fact we collect this information from every user during project creation, we should be in a good standing to not have to ask customers to submit twice (eliminate submit after project creation).

**Comment by acshields** [comment]
@vikasrohit - Thanks for the explanation above.  That helps.  I definitely understand the desire to not overwhelm managers with spam projects.  Given @vic-topcoder's point above regarding the new registration process, do you think this will help to deter spam projects? (i.e. we can determine business customer vs. TC users).

Also, Vic raised two good points to me separately. 

1. For existing customers that have not gone through the new registration process, is there a way for us to capture new information (company name, phone number) that were not previously captured? Can we have a notification trigged on next customer login to update/provide the information in their profile?
2. How does this impact members? If I am correct, there isn't a way to separate customers vs. members today.

**Comment by vikasrohit** [comment]
>  Given @vic-topcoder's point above regarding the new registration process, do you think this will help to deter spam projects? (i.e. we can determine business customer vs. TC users).

I don't think new registration process is going to reduce the  spam if remove the `Submit for review` button. Its all about having a second step to confirm the project before we post it to the slack channel for managers. Otherwise, we have to just be ready for spam projects because it is very easy to give fake details in registration form and fake answers in project intake form. It is a trade off, if we increase the questions or complexity of initial project intake form, we loose the overall intake and if we ease it with less questions and complexity, it would increase the spam.

For the 1 and 2, I need some time to analyze it after we have the new registration process in place.

**Comment by acshields** [comment]
Hi @vikasrohit - Understood on your point regarding the need for review after project submission.  I am trying to think if there is anything we can build into the process to help pre-screen submissions prior to sending data to Salesforce/Hubspot that would reduce the screening workload/timeline.  Let's talk through this and Pts. 1 & 2 from above tomorrow.

**Comment by acshields** [comment]
Hey there - Recapping our conversation:

1. We are going to modify the welcome language.
Coder the Bot2:17 pm
Hello, Coder here! Your project 'App design sample test project' has been created successfully. If you already have a document with your requirements, just verify it against our checklist and then upload it on the Scope section. Once you're ready, hit the "Submit for Review" button on the **[Location dependent on Vikas's findings - Ideally, Dashboard]**. Get stuck or need help? Email us at support@topcoder.com.

2.  There preference is that this message is displayed as a notification on the dashboard, vs. a post.

3.  We are going to keep the 'Submit for Review' button and process, and will not make any changes regarding this process that will impact our managers.

4. @vikasrohit - Will review and provide options for moving the Submit for Review button to the dashboard.

5. A long-term research goal for this team should be to identify valid ways of automating the submission review process to more quickly identify valid leads vs. "junk" projects.  However, this should not delay the release of the features mentioned above.

**Comment by vikasrohit** [comment]
Closing the issue as its requirements are done under #2559.
