### ISSUE TITLE
[$30] Remove extension request for under review milestones

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2481]
Extension can't be requested during design review. Please remove the button while we're in review.

![screen shot 2018-09-07 at 3 08 31 pm](https://user-images.githubusercontent.com/11248478/45211455-f4bf5180-b2af-11e8-83f2-94b8ee5d68aa.png)

Please check all milestones which could be in review state to be consistent.

https://github.com/appirio-tech/connect-app/issues/2301

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-454

**Comment by maxceem** [comment]
Ok, so there are two milestone types for design review `final-designs`, shown on the screenshot above and `checkpoint-review` which looks like this:

![image](https://user-images.githubusercontent.com/146016/45216135-25b07e00-b2d2-11e8-8661-73e781c1e846.png)

Note, that only user with manager privilages like `phase_manager` can see this button for the extension.

**Comment by maxceem** [comment]
@RishiRajSahu FYI, just to be clear, customer doesn't have button for extension at all.

**Comment by vic-topcoder** [comment]
@acshields - this is a question about process. Please correct me if I'm wrong, but we don't want to add extensions to customer-specific interaction. The customer just HAS to do the selection, they can't ask for extension, as we record WHEN they did the selection. So - for selecting designs, there is no extension for any user role.

**Comment by acshields** [comment]
I would agree, @vic-topcoder

**Comment by Gauravseta** [comment]
@maxceem  any more open for pickup anytime soon? thanks

**Comment by maxceem** [comment]
@Gauravseta We don't plan to open for pick issues soon as current Bug Bash is almost finished.

**Comment by vikasrohit** [comment]
@vic-topcoder @acshields first thing is that we are not showing the `Request Extension` button for customers. And the reason why managers/copilots might need the extension button is that we are using the `checkpoint-review` and `final-designs` milestones in two different ways, one is where we are asking manager/copilot to add the design links to review and another where we add `add-links` milestone before these milestones. So, in first case we have the probability of manager asking extension because he/she is not able to collect all the designs for review because of the delay in the challenge.

That being said, I think for closing this issue, I have a solution. @RishiRajSahu @maxceem we should hide this button specifically for `checkpoint-review` and `final-designs` milestones when we are waiting for customer input (i.e. the flag `waitingForCustomer` is set to true which we are implementing via #2471 ). In that way even manager/copilots won't see this button if there is a `add-links` milestone before these milestone and it would be visible to them if they have to add the links in this milestone itself.

**Comment by rashmi73** [comment]
@maxceem can u please assing to me thanks

**Comment by rashmi73** [comment]
@ThomasKranitsas PR #2603

**Comment by maxceem** [comment]
@rashmi73 made PR review, please have a look https://github.com/appirio-tech/connect-app/pull/2603#pullrequestreview-164484612

**Comment by rashmi73** [comment]
@maxceem raised a new PR #2630

**Comment by maxceem** [comment]
@rashmi73 Please, let me know your Topcoder handle so I can process a payment for you for completed issues. Thanks.

**Comment by rashmi73** [comment]
@maxceem  my topcoder handle: rashmi73

**Comment by RishiRajSahu** [comment]
Closing merged to dev.
