### ISSUE TITLE
[$20] Hyperlink text should be blue instead of black in Discussion posts of a connect project

### ISSUE THREAD

**Issue by JayaDhaka** [appirio-tech/connect-app#2584]
Issue description: The links within Discussion posts on Connect projects does not show up in blue colour and looks same as other text, basically limits the viewer to avoid inferring it as a clickable link. Please check and fix.

Connect project link: https://connect.topcoder.com/projects/7222 

Screenshot:
<img width="375" alt="screenshot 2018-10-03 at 10 29 15 pm" src="https://user-images.githubusercontent.com/34749364/46468485-2ca5b000-c7ee-11e8-93db-a8a4ba692bc4.png">

**Comment by vikasrohit** [comment]
@maxceem this could be wrapped in upcoming CF challenge. I think we need to relax the CSS rule for making the hyperlinks blue to not compulsory have `<p>` as parent. Right now, it is showing correct color for hyperlinks for some other messages in the same project and the reason is that hyperlink is contained within a `<p>` in those message while it is not in this particular case. So, I guess relaxing the CSS rule to make blue hyperlinks even if it is not in a `<p>`, should fix the issue.

**Comment by iversonLv** [comment]
@maxceem can I assign this?

**Comment by iversonLv** [comment]
@maxceem It’s done and ready for review
Thanks.

**Comment by RishiRajSahu** [comment]
Closing merged to dev.
