### ISSUE TITLE
[$50] When we mark notifications as read in Notification dropdown it becomes closed

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2607]
When we mark notifications as read in Notification dropdown it becomes closed, but I think it has to stay open until we click outside of it.
See screencast https://monosnap.com/file/sknvpM0NBU0l5y02X8kYvUc1loldUD

@RishiRajSahu could you please confirm? I think we can include to the CF-13 if it's a valid issue.

**Comment by RishiRajSahu** [comment]
@maxceem yeah agree, how are you planning to handle it ? should we erase the notification once marked as read, keeping the container open ?

**Comment by maxceem** [comment]
@RishiRajSahu hmm, good question. As we hide notifications marked as `read` it looks like we have to hide them for consistency, though it could not feel nice when one notification disappears and all the others notifications move because of that.

On the Facebook for example, notifications never disappear when we mark them as read or even hide. Maybe we need input from Victor on this?

**Comment by RishiRajSahu** [comment]
Yup, @vic-topcoder could help us here definitely.

**Comment by vic-topcoder** [comment]
Ideally we can start thinking about a localized transitions/interactions instead of monolithic updates to a component. The example here would be to break the interaction into smaller steps:

1. Open the notifications drop down menu
2. Dismiss a notification
3. Receive a new notification while the drop down is active
4. Close the notifications drop down menu
- - - 

Dismissing a single notification would ideally just remove the notification without interfering with the rest of the interface. In essence you're just removing a single element from the list. Ideally we can just lower the opacity and reduce the height to 0 so the elements below would slide up in the menu.

> On the Facebook for example, notifications never disappear when we mark them as read or even hide. Maybe we need input from Victor on this?

We have a different approach to notifications than Facebook - we do not keep a history of viewed notifications. Our pattern is similar to the GitHub implementation - once you see a notification, it is no more relevant; thus we do not store them in the system. The notification is really just a notification - take a look at this new thing - so keeping a history in high-volume system (for managers and copilots) makes no sense.

**Comment by maxceem** [comment]
So I guess we can start with this particular case of dismissing notifications. For this issue we can do the next:
- When we mark a notification as `read` drop-down should stay open
- A notification has to be removed from the list using visual effect: lowering the opacity and reduce the height to 0 so the elements below would slide up in the menu
- To implement this visual effect we can use https://github.com/reactjs/react-transition-group `v 2.x`, later we can use it for other visual effects. Note, we already using this module in https://github.com/appirio-tech/react-components/blob/feature/connectv2/components/Tooltip/Tooltip.jsx

@RishiRajSahu let me know if you think we are ready to include it to CF-13.

**Comment by nahidshahin** [comment]
@maxceem I want to work on it, please

**Comment by maxceem** [comment]
As the issue hasn't been completed during 12 hours and no comment was provided, this issue is now open for pick up.

**Comment by zjuasmn** [comment]
work on it

**Comment by zjuasmn** [comment]
done, please review #2628

**Comment by maxceem** [comment]
@vic-topcoder @RishiRajSahu here is a demo of the implementation which I've also tried locally it looks really great as for me https://monosnap.com/file/kDVMQI1NIsEy4HDrbFalC7tRODb0Gx

There is only one moment which we missed to decide on. To mark notifications as `read` we are making a request to the server. So currently notification dismissed not immediately but after some time. I see there two ways to go:
1. hide notification without waiting for the end of server request (if it fails we can show red alert popup and show notification back)
2. or when we click the mark as `read` button, we can dim notification and show loader indicator instead of `checkbox` button

IMHO first way would be better, what do you think?

**Comment by RishiRajSahu** [comment]
@maxceem yeah I saw that looks good, but I have one question, Shouldn't we update the count at the bottom about older notifications as well once some notification is erased ?
>IMHO first way would be better, what do you think?

Yeah, 1 looks a better approach to me as well.

Regarding notifications page, I think we can keep it as it is because then we have other use-cases as well such `mark all as read` on **notifications page** and on **notifications dropdown**, and those instantly cleans it up all. So this slowly erasing of a notifications should be unique as per for marking single notification as read.

**Comment by vic-topcoder** [comment]
Let's go with option 1 please! The user should perceive the UI as instantaneous.

Also yes - update the number of notifications when manipulating/dismissing them.

**Comment by maxceem** [comment]
To sum up:
To make it looks smoother we have to additionally implement `hide notification without waiting for the end of server request (if it fails we can show red alert popup and show notification back)`
For consistency, we have to implement it for cases when we show animation and we don't show animation:
1. Notifications dropdown: mark one notification as read
2. Notifications dropdown: mark all notifications as read
3. [Notifications page](http://local.topcoder-dev.com:3000/notifications): mark one notification as read
4. [Notifications page](http://local.topcoder-dev.com:3000/notifications): mark all notifications of one project as read

**Comment by RishiRajSahu** [comment]
@maxceem first to understand it, so your point is if we toggle `read` state of notification again in case of failure from backend it will have effect on other components as treating them as new notifications, right ? and using approach 1 we can avoid it, right ?

**Comment by maxceem** [comment]
> @maxceem first to understand it, so your point is if we toggle read state of notification again in case of failure from backend it will have effect on other components as treating them as new notifications, right ? and using approach 1 we can avoid it, right ?

yes, that's right, though for now I think we don't have such cases, but theoretically it's possbile to add code like this:
```
componentWillReceiveProps(nextProps) {
   if (_.filter(this.props.notifications, 'read').length === 0 && _.filter(nextProps.notifications, 'read').length > 0) {
      // do something in case there are new unread notifications appears
   }
}
```

> what are the other components sharing the notifications with notification drop-down ?
- Notification page
- https://github.com/appirio-tech/connect-app/blob/dev/src/projects/detail/components/PostsRefreshPrompt/PostsRefreshPrompt.jsx
- https://github.com/appirio-tech/connect-app/blob/dev/src/projects/detail/components/ProjectStage.jsx
- https://github.com/appirio-tech/connect-app/blob/dev/src/projects/detail/containers/DashboardContainer.jsx

**Comment by RishiRajSahu** [comment]
Closing merged to dev.
