### ISSUE TITLE
Invalid progress data in left panel

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2642]
<img width="1280" alt="screen shot 2018-10-18 at 11 00 20 am" src="https://user-images.githubusercontent.com/2417632/47133149-08090800-d2c5-11e8-998b-c996fee95a77.png">

Project: https://connect.topcoder-dev.com/projects/7210

@maxceem @RishiRajSahu it might be because of bad data during testing, however, it would be great if we can have a quick look into it by debugging this project in local env.

**Comment by maxceem** [comment]
@vikasrohit looking into it.

**Comment by RishiRajSahu** [comment]
fyi @maxceem it is actually happening because of phase are delayed, and its considering the duration so far(till today) if phase is active and gone beyond its expected endDate.
Also, I found one more issue, that is with backend, For `App Design` the correct duration is 31 while the backend is returning 33

**Comment by maxceem** [comment]
@RishiRajSahu as I see the reason is, that it takes data from `phase.duration` for completed phases instead of using milestones to calculate the actual duration of the completed phases.

By current logic actual duration is restricted by planned duration of the phase. So let's say some active phase is delayed. The actual duration for such phase will be returned as a planned duration for that phase, not as time until today.

![image](https://user-images.githubusercontent.com/146016/47134516-a5713580-d2df-11e8-8283-fdf10faa265e.png)

This leaves the question open how should we calculate current duration? If we include delayed time the value will be bigger than planned duration. I guess in such cases we should update the progress bar to show delayed time instead `x days of y`, what do you think?

**Comment by RishiRajSahu** [comment]
@maxceem Agree, looked more into it, it has been due to old data, right now backend is working fine, Tested by adding new phase to the project and its duration is coming out to be correct. So to handle it changes we need are 
1. Show the message `Delayed by (109-41) days` having progress bar as red coloured

**Comment by maxceem** [comment]
@RishiRajSahu so we shouldn't restrict the maximum duration of phases by its planned endDate as it's done now, correct? When we calculate the total spent time.

**Comment by maxceem** [comment]
@RishiRajSahu I think we have to agree on a few moment regarding calculating the total duration:
1. **Planned duration**
   1. Imagine we have 2 planned phases with a gap between them:
       - Sep 1 - Sep 3 (3 days)
       - a gap
       - Sep 5 -Sep 7 (3 days)

       I expect that total project duration should be calculated since Sep 1 till Sep 7 (8 days) including the gap, rather than just sum phases times. And this is how it's done now.

2. **Actual duration**
    1. We should include delayed time for active phases (not done now)
    2. We shouldn't include overlapped time twice (not done now)
    3. Same like for planned duration we should include gaps between phases which are used to calculate actual time (active and completed phases). (not done now)

3. In case actual duaraion is bigger than planned duraiton we show the progress in red.

**Comment by RishiRajSahu** [comment]
@maxceem Yes for all. yeah, we should include gaps for both planned/actual durations

**Comment by maxceem** [comment]
@RishiRajSahu it's fixed and PR raised https://github.com/appirio-tech/connect-app/pull/2643

If you deploy fix locally you can see the next.
#### For the project which provided as an example it's good now:
- before https://connect.topcoder-dev.com/projects/7210/plan
   ![image](https://user-images.githubusercontent.com/146016/47147807-9d29f200-d301-11e8-9923-8d3796d65e35.png)
- after http://local.topcoder-dev.com:3000/projects/7210/plan
   ![image](https://user-images.githubusercontent.com/146016/47147833-a915b400-d301-11e8-8406-808244316dbb.png)

#### Here is an example of a project with delay:
- before https://connect.topcoder-dev.com/projects/7226/plan
   ![image](https://user-images.githubusercontent.com/146016/47147845-b337b280-d301-11e8-96e4-2a9a309fd9e7.png)
- after http://local.topcoder-dev.com:3000/projects/7226/plan
   ![image](https://user-images.githubusercontent.com/146016/47147865-bdf24780-d301-11e8-8748-64545ed518b8.png)

I think the main difference is that we don't include overlapped time in phases anymore.

**Comment by vikasrohit** [comment]
@maxceem looking good. However, how the value `58` is obtained in the last one? I think we should say `Delayed by x days` when we know that project is running late.

**Comment by maxceem** [comment]
@vikasrohit oh, I've missed the message text. Will fix it now.

`58` is calculated like in this case like this: there is an active phase which started on `Aug 22` and still active. Since `Aug 22` till today `58` days.

**Comment by maxceem** [comment]
@vikasrohit fixed

For project http://local.topcoder-dev.com:3000/projects/7226/plan
![image](https://user-images.githubusercontent.com/146016/47149186-6950cb80-d305-11e8-83ea-8722ad7d0e03.png)

**Comment by vikasrohit** [comment]
Great. So, `14` is the number of days actual duration is spilling over the planned duration of the complete project, right?

**Comment by maxceem** [comment]
> Great. So, 14 is the number of days actual duration is spilling over the planned duration of the complete project, right?

yes 14 is equal to `planned duration - actual duration`

**Comment by maxceem** [comment]
@RishiRajSahu added some wiki regarding project duration and progress https://github.com/appirio-tech/connect-app/wiki/Durations-and-Progress

**Comment by vikasrohit** [comment]
Thanks @maxceem for the documentation.

**Comment by RishiRajSahu** [comment]
Fixed and pushed to dev.
