### ISSUE TITLE
Should we include phase payment udpates to show visual cue on phase card

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2660]
So far we have discussed about considering phase tabs - `timeline, specifications, discussions` to show visual cues for a phase card, as per me `phase payments`  is also a potential candidate for showing visual cues.

fyi @vikasrohit @vic-topcoder

**Comment by maxceem** [comment]
Also, we can consider to trigger a red cue by these events which are related to phases:
- `notifications.connect.project.phase.transition.active`
- `notifications.connect.project.phase.transition.completed`

**Comment by vikasrohit** [comment]
Lets not show visual cue for phase payments events as it is not being used actively and seems like we are going to get rid of it next set of changes for project plan.

@maxceem we might get red cue on the timeline tab for `notifications.connect.project.phase.transition.active` and `notifications.connect.project.phase.transition.completed` events after changes for #2455. If yes, then we are good and we won't need to show red cue for these two events, otherwise we have to think how we want to show user that something has changed in the phase status.

**Comment by maxceem** [comment]
@vikasrohit at the moment we don't show red cue for these `notifications.connect.project.phase.transition.*` events.

We can show a red cue for the phase for them - it would be a quick solution. 

In general, I think we may consider improving the way we show the places which have been updated as has been proposed here https://github.com/appirio-tech/connect-app/issues/2966. We can think about some common approach to highlight changed place in some way, for example as it's done when using a link to some particular answer in StackOverflow see a demo video https://monosnap.com/file/LzPwWoZvBGyfaX5e8OoWPaZSIlltZe and example link https://stackoverflow.com/a/27815509.

**Comment by vikasrohit** [comment]
Yes, makes sense. Lets do this and #2966 together in next release.

**Comment by vikasrohit** [comment]
Lets close this issue as the way project plan works right now with phases is going to change significantly so we have to rethink over almost all events again.
