### ISSUE TITLE
Console error on api 403

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#2683]
Accessing a project that I don't have permissions to see used to show the coder bot error screen with details. Now it throws a console error and loading spinner is always shown. Here is an example in prod

![image](https://user-images.githubusercontent.com/3051646/48085075-981ddb80-e1f9-11e8-9dc7-ee72474d2501.png)

**Comment by maxceem** [comment]
Thanks @gondzo ! I'm looking into it, so far very strange...

**Comment by maxceem** [comment]
@RishiRajSahu @vikasrohit 

It's fixed and hotfix PRs provided 
- PROD https://github.com/appirio-tech/connect-app/pull/2684
- DEV https://github.com/appirio-tech/connect-app/pull/2685

### The reason

The error happens here due to unreliable order of rendering `ProjectDetail` and `DashboardContainer` components in the the next code:
```
   <ProjectDetail>
      <DashboardContainer />
   </ProjectDetail>
```

`ProjectDetail` should prevent `DashboardContainer` to be rendered at all, if there is error during project loading. But as `DashboardContainer` is connected to the store using `connect()` function, it could happen that `DashboardContainer` is rendered first, so `ProjectDetail` couldn't stop it to be rendered in such cases, see a related issue in `react-redux` https://github.com/reduxjs/react-redux/issues/509.

To make sure that rendering order doesn't depend on any side conditions, I've refactored the code.

**Comment by RishiRajSahu** [comment]
Closing merged to dev and prod
