### ISSUE TITLE
Can't add newly registered members to project

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#2730]
There is some issue which prevents adding newly registered members to a project - members suggest api returns no results so we get a message `This username doesn’t exist on Topcoder.`

Can we try to call `http://api.topcoder.com/v3/members/<handle>` - this seems to return the correct info so would be helpful when I know the full handle of a user I'm trying to add.

**Comment by gondzo** [comment]
how about we enable the add member button all the time and on click we can check the handle?
at least that would create less support tickets to add members

**Comment by acshields** [comment]
Hi @vikasrohit - Let's talk this through on Thursday with @vic-topcoder

**Comment by vic-topcoder** [comment]
I would suggest we change the default behavior of adding users through their email instead of handle, as most of the customers would be used to that pattern - user email == user ID (handle). As the email has the same validity, I would expect the business users to operate predominantly with emails - inviting user to a project via email would work fine with both cases:
- send an invite to registered user
- send an invite to non-registered user, depending on the system check. 

We can think for a case where the user already has an account registered with Topcoder and they are being invited via secondary email - that's where adding multiple emails to an account could be a solution. Resolution for that edge case would be:
- allow user to log in through existing account, replace the invitation email with account email during login, add the user to the project; or
- register the new (invitation) email as secondary in the system.

As we do not currently support secondary emails, I would suggest we use the first approach for that edge case when we decide to deal with it.

**Comment by vic-topcoder** [comment]
thanks @vikasrohit

**Comment by vikasrohit** [comment]
Closing as it was fixed as patch and new team management allows addition of users by handle and emails both without need of auto suggest.
