### ISSUE TITLE
[Team Management 2.0] New Login view for unregistered customers

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2739]
### Expected behaviour

1. When a non-registered user is invited from the connect.
2. User receives the mail with register link
3. Pre-filled(non-editable email only) login form should open without the select solution in left bar
4. User fills the remaining details
5. User verifies the pin and lands on listing page being added as member to invited project

### Actual behavior
1. When a non-registered user is invited from the connect.
2. User receives the mail with register link
3. Login form opened is **_not pre-filled_** with email and that too **_with_** the select solution in left bar
4. User fills the remaining details
5. User verifies the pin and **_lands on select solution page_**

fyi @acshields @vikasrohit @gondzo

**Comment by maxceem** [comment]
After additional discussion with @vikasrohit the details are next.

If a user comes to the registration page with `retUrl` like `https://accounts.topcoder-dev.com/connect/registration?retUrl=https://connect.topcoder-dev.com/projects/1234` then:
- Email should be prefiled with user email and non-editable.
- User email should come from coockie `registerEmail` which we will add using browser dev tool during testing (otherwise email field would be empty but still disabled)

  ![image](https://user-images.githubusercontent.com/146016/50891701-dc1aa000-1437-11e9-9465-25896ee96e7d.png)
- Hide the content (except the Topcoder logo) in the left panel of **connect registration** and **pin verification** pages

   ![image](https://user-images.githubusercontent.com/146016/50890997-45011880-1436-11e9-895c-c0fe9f218503.png)
- User fills the remaining details
- User verifies the pin and after being redirected to `retUrl`

**Comment by vikasrohit** [comment]
Looks good to me @maxceem

**Comment by maxceem** [comment]
It's done with PR for two repositories:
https://github.com/appirio-tech/react-components/pull/307
https://github.com/appirio-tech/accounts-app/pull/207

I've tested while mocking PIN verification and login responses, works well.
Though before merging them to dev I would prefer to test them with real responses when indentation service sends the email with PIN.

**Comment by RishiRajSahu** [comment]
verified on dev by inviting un-registered member working fine. Closing.
