### ISSUE TITLE
[Team Management 2.0] After inviting team members they should show on the sidebar as well

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2743]
### Expected behavior
When I invite new members to a project, they should be added to the sidebar as well.

### Actual behavior
Invited members show only on the team management popup. 

### Design the cases
- Member is invited, how the avatar is displayed on the sidebar (we have only email and invitation info {date, status})
  - What is the avatar style (transparent, icon overlay?)
  - What is the tooltip style 

Once design is done, hand over to Vikas

**Comment by maxceem** [comment]
> Overlay a small icon on top of the user avatar, and display the status of the invitation on the user tooltip as per #2785

So far as per my understanding we can complete only the second part from that issue
- > 2\. next to the invited person's name in the pop-up it should say "Invited."

   Looks like this is done:

   ![image](https://user-images.githubusercontent.com/146016/52455542-7ed75300-2b8b-11e9-8090-f8d116e8c2ef.png)

- > 2\. when a user hovers over the image it should say "Invited."

    So far we show user tooltip like this:

    ![image](https://user-images.githubusercontent.com/146016/52455572-9ca4b800-2b8b-11e9-99a7-8e1524d7f7fe.png)

    For invited user we have only email or handle. Is there any particular requirement on how to show this tooltip for invited users?

   For example we can show handle or email instead of the user name. And show "Invited" instead of user handle in such a tooltip. But it feels like not a good idea to show differen kind of infomation with the same design.

**Comment by RishiRajSahu** [comment]
@maxceem yeah agree and I am not able to find any new design here https://marvelapp.com/48cdhjg/screen/51457020 as mentioned by @vic-topcoder regarding transparent avatar style and tool tip.

**Comment by vikasrohit** [comment]
I guess https://marvelapp.com/48cdhjg/screen/52723943 is what @vic-topcoder was trying to share.

**Comment by maxceem** [comment]
@RishiRajSahu I guess another screen was meant https://marvelapp.com/48cdhjg/screen/52723943/handoff

This one has a small icon as described by @vic-topcoder:
> Overlay a small icon on top of the user avatar

So it looks like instead of making avatars transparent we are adding this small icon.

**Comment by RishiRajSahu** [comment]
thanks @vikasrohit and @maxceem, yeah but still not sure about tooltip design as mentioned by him in the description of the issue. Maybe, @vic-topcoder can confirm on your approach of re-using existing tooltip or some other design if he has got ?

**Comment by vikasrohit** [comment]
for tooltip, for user invited via handle, we can render it as usual as we can fetch the data of the user. For users invited via email, we can either fetch their user account if exists and show details accordingly or fetching user for the email seems heavy operation or tricky for now, we can pass the email as `firstName` and empty string as `handle` to the UserTooltip component which would result  in a basic tooltip with only email being rendered in place for full name.

**Comment by maxceem** [comment]
@vikasrohit 

> we can render it as usual as we can fetch the data of the use

So far we also don't show name and a real avatar of the invited user in the dialog even if we invited by the handle

![image](https://user-images.githubusercontent.com/146016/52461352-a50beb80-2ba9-11e9-832c-2215e6610aa7.png)

Just want to confirm this moment if it's intentional. I mean in one place we show only handle while in tooltip we are going to show the whole info. Is there any reason not to show the same whole info in the dialog? Should we keep dialog and tooltip in sync showing the same amount of data?

**Comment by vikasrohit** [comment]
Nopes, it is not intentional I guess. Yes, we need to keep both places in sync. @RishiRajSahu thoughts?

**Comment by maxceem** [comment]
So far it's shown in the designs this way https://marvelapp.com/48cdhjg/screen/51457024

**Comment by vikasrohit** [comment]
> So far it's shown in the designs this way https://marvelapp.com/48cdhjg/screen/51457024

I think in that screen the we can utilize the same layout for tooltip for users invited via email. For users invited via handle, we can just use our standard way to show the tooltip for a normal user.

**Comment by RishiRajSahu** [comment]
There is no reason except to keep it in sync with the design of project-team here https://projects.invisionapp.com/share/M7P2N375BUN#/screens/330878326 in which we are not showing all details until the invite has been accepted , we don't have any specific design for Topcoder-team with invites.

**Comment by RishiRajSahu** [comment]
I think we are good with what we have right now for Topcoder-team view which @maxceem has shared.

**Comment by maxceem** [comment]
Let's conclude the requirements.

If we invite by email:
- in the dialog, we show the only email as it's done now
- in the tooltip, we show the only email instead of the user name and show "invited" text on the top right corner of the tooltip

if we invited by email:
- in the dialog, 
  - a) do we show like now? 
  - b) or we show the user name and handle same like for already members?
- in the tooltip, 
  - a) do we show only handle instead of the user name and the text "invited" on the top right? 
  - b) or we show the full tooltip with a user name and handle and the text "invited" on the top right?

**Comment by vic-topcoder** [comment]
> So it looks like instead of making avatars transparent we are adding this small icon.

Correct. The icon overlay will indicate that an invite to the user has been sent.

**Comment by vikasrohit** [comment]
Email invite understanding looking fine to me.

For invite by handle,
use full avatar and tooltip at both places i.e.

> if we invited by handle:

* in the dialog,
  
  * a) do we show like now?
  * b) or we show the user name and handle same like for already members? **Use this**
* in the tooltip,
  
  * a) do we show only handle instead of the user name and the text "invited" on the top right?
  * b) or we show the full tooltip with a user name and handle and the text "invited" on the top right? **Use this**

**Comment by vikasrohit** [comment]
@maxceem I guess we need to validate how our logic behaves when the invited handle actually does not exist in topcoder.

**Comment by maxceem** [comment]
@vikasrohit as per my previous testing error happens during the invitation request and the alert with error is shown.

**Comment by vikasrohit** [comment]
We are good then.

**Comment by maxceem** [comment]
To sum up:
- This should be implemented for both types of members: **Project team** and **Topcoder team**
- When we invite new members to a project, they should be also shown on the sidebar together with existent members:

   ![image](https://user-images.githubusercontent.com/146016/52517177-262eb580-2c72-11e9-9795-094a3e70ad07.png)

- invited members on the sidebar should be shown with a small icon 
    
   ![image](https://user-images.githubusercontent.com/146016/52455044-4898d400-2b89-11e9-915c-3dcb67225c9d.png)
   
   It can be found on this marvel screen https://marvelapp.com/48cdhjg/screen/52723943/handoff

   We have an icon for the arrow included in the Connect App source https://github.com/appirio-tech/connect-app/blob/dev/src/assets/icons/icon-direct-arrow.svg. I guess we can style the rest with CSS to achieve the same look as in the provided design.

- When we hover with mouse the avatar of inviter member in the sidebar, we should show same tooltip as for existent members with a slightly different information:
   - For users invited by email, we show tooltip like this:

     ![image](https://user-images.githubusercontent.com/146016/52517295-773fa900-2c74-11e9-9339-6928af45e786.png)

     - email insitead of the full name
     - `invited` label, have same style like `IBM-17-Chatbot` on this screen https://marvelapp.com/48cdhjg/screen/51457022/handoff

    - For users invited by handle, we show tooltip like for existent members + `invited` label:
       
       ![image](https://user-images.githubusercontent.com/146016/52517338-0d73cf00-2c75-11e9-9361-6c01b0a5d6a8.png)

- Note, that in the dialog, currently we list invited members like this, only handle, but we should show the full information same like for existent members:
   
    ![image](https://user-images.githubusercontent.com/146016/52517374-a0146e00-2c75-11e9-9047-70bfffee0de0.png)

- Note. When we invite users by handles we already load data for such members and put it to the redux store `members.members` object. So we can use it to show avatar and full name for users invited by handles:

   ![image](https://user-images.githubusercontent.com/146016/52517459-8de6ff80-2c76-11e9-8588-53fcd3f72b2e.png)

**Comment by RishiRajSahu** [comment]
Done and pushed to prod. Working fine.
