### ISSUE TITLE
[Team Management 2.0] - Show exact reason for error during invitation

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2758]
When we invite **Topcoder** or **Project Team** members, there are various reasons why members couldn't be invited. 

### Actual Bahiour
Now we always show very general error alert `YOU ARE UNABLE TO INVITE MEMBERS SUCCESSFULLY`. 

### Expected Bahiour
It could be helpfull to see the exact reason why we cannot invite a member. Server usually retuns the exact error reason why we cannot invite a particular member which we can show instead of a general error message.

### Steps to reproduce
For example. I'm trying to invite `pshash_customer` user as a `Manager`:

![image](https://user-images.githubusercontent.com/146016/51453370-0f372a80-1d7a-11e9-9fcb-839781c9cac7.png)

`pshah_customer` doesn't have enough rights to be a Manager, so server rejects inviting him and we see the next error:

![image](https://user-images.githubusercontent.com/146016/51453283-743e5080-1d79-11e9-95ac-8a7b0115aaaf.png)

While server returns the next response:
```json
{
  "id": "21e38f17-cc41-41bf-9979-77af23705516",
  "result": {
    "success": false,
    "status": 403,
    "content": {
      "message": "40152922 cannot be added with a Manager role to the project"
    },
    "debug": "..."
  }
}
```

So we can show the particular error meesage `40152922 cannot be added with a Manager role to the project`. 

**Note**<br>
It would be better to also update project service to use in the error message the data we typed into the fieled. Like if we add user by handle `@pshah_customer` server should format error message using handle `@pshah_customer cannot be added with a Manager role to the project`. If we invited user using email like pshah_customer@topcoder.com, server should format error message using email: `pshah_customer@topcoder.com cannot be added with a Manager role to the project`.

@RishiRajSahu what do you think?

**Comment by RishiRajSahu** [comment]
@maxceem yeah I am too aware of this, we should show correct error as per returned by server. So there are multiple things to be taken care - 
1.In the error on UI instead of userId we have to show handle or email as the per invite
2.We have a support of adding multiple users at same role as per new feature, so suppose if someone is trying to adding 4-5 members with handle at manager role and one of them is normal topcoder user in that case the red popup will be overwhelmed with too much handles present in error text.
3.Should we have this kind of behaviour instead, showing `generic reason` in the red popup like -
`User(s) cannot be added with a Manager role to the project` and also showing a error below the invite text area with user handles or email in red ?
4.Could you also write all the possible invite scenarios to not miss any error message ?

**Comment by RishiRajSahu** [comment]
For eg. some of the possible invite scenarios - 

1.Adding manager user as copilot - success
2.Adding manager user as manager - success
3.Adding manager user as observer - success

1.Adding topcoder user as copilot - success
2.Adding topcoder user as manager - Show correct error
3.Adding topcoder user as observer - Show correct error

1.Adding connect-admin user as copilot - success
2.Adding connect-admin user as manager - success
3.Adding connect-admin user as observer - Show correct error

FYI - Currently only managers could be added at observer roles

**Comment by maxceem** [comment]
> 1.In the error on UI instead of userId we have to show handle or email as the per invite

I guess this should be fixed server side, right? As the client doesn't have information to match userIds and emails/handles.

> Also, we can use handles and emails details here to be passed to reducers and later used for displaying correct error.

I'm not sure I got the idea. As the server returns an error message containing userIds, but the client doesn't have information on how to match userids and emails/handles. See the error message from the server for a several users `40152922,40035291 cannot be added with a Manager role to the project`.
Also, server returns only error message in text format `40152922,40035291 cannot be added with a Manager role to the project` so we don't have list of users which were added successfully and which had errors.

I guess we have to update project service to include data about successfull and failed invites when we invite multiple users.

**Comment by RishiRajSahu** [comment]
>I guess we have to update project service to include data about successfull and failed invites when we invite multiple users.
That's a different case to be taken care , as right now project service don't create partial invites, it either creates all or none.

>how to match userids and emails/handles
On UI side we already fetch members details [here](https://github.com/appirio-tech/connect-app/blob/dev/src/projects/actions/projectMember.js#L76) I am planning to use this details for matching instead of making the same call on backend again to fetch the data.

**Comment by maxceem** [comment]
> On UI side we already fetch members details here

Thank you for pointing it. 

As the server doesn't return failed invites only text error message, do you think we should parse error message to get userIds? Or better to update project service to return a list of failed/successful userIds?

**Comment by RishiRajSahu** [comment]
Other than scenarios mentioned here https://github.com/appirio-tech/connect-app/issues/2758#issuecomment-455949830 , there are few other cases to be thought on  - 
1.Partial invites are not getting created right now. for eg -  if inviting multiple member on particular role and few doesn't fit for that role then the invite is not getting created for any of them.
2.Server returns just the id's of non fit members for that role with status 403.
3.Should we handle it server side to create a correct error error message OR should we just return handles instead of IDs from server OR  should we map IDs returned by server, as its right now, on UI only and create a correct error message ?
4.Where should the error to be shown, should the detailed error be shown in the invite model only around the text area and popup with generic error only ?

fyi @maxceem @vikasrohit

**Comment by RishiRajSahu** [comment]
My Thoughts on above four points :)

**Comment by maxceem** [comment]
@RishiRajSahu this issue is handled by two PRs:
https://github.com/topcoder-platform/tc-project-service/pull/258
https://github.com/appirio-tech/connect-app/pull/2877

**Comment by maxceem** [comment]
@RishiRajSahu 

I've merged the dev branch into the PR https://github.com/appirio-tech/connect-app/pull/2877 so you can check it out now and possible merge to dev.

This PR should be merged together with PR to the project-service as API response format has been changed https://github.com/topcoder-platform/tc-project-service/pull/258

**Comment by RishiRajSahu** [comment]
Thanks @maxceem !

**Comment by vikasrohit** [comment]
@RishiRajSahu we can close it now, right?

**Comment by RishiRajSahu** [comment]
Yep, its done. Closing.
