### ISSUE TITLE
Only allow users with role `Connect Copilot Manager` to assign copilot to Connect project

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2775]
We have created a new role for connect user named as `Connect Copilot Manager` , only users assigned with this role are allowed to assign copilot to the project going forward.

changes needs to be done to have the above said functionality.

fyi @vikasrohit @acshields

**Comment by RishiRajSahu** [comment]
To handle this, for non `Connect Copilot Manager` users -
1.We won't be showing the copilot option in dropdown
2.We won't be allowing changing role of added member to copilot.

fyi - @maxceem

**Comment by maxceem** [comment]
@RishiRajSahu do I understand it right, that if current user doesn't have role `Connect Copilot Manager`
we should remove these two options from the **Topcoder Team** dialog:

![image](https://user-images.githubusercontent.com/146016/51598669-fde84c80-1f38-11e9-9b10-d38012ff1257.png)

**Comment by acshields** [comment]
Hi @maxceem @RishiRajSahu -  

In my ideal workflow, I would still like for a Copilot to see the option to invite another to a project - However, if they did so, then a message could appear saying "Your request has been sent to the Connect Copilot Manager for review. If the Connect Copilot Manager approves the assignment Copilot X will be invited to the project." and then had an email/notification triggered to the Connect Copilot  Manager(s) saying that Copilot X has requested that Copilot Y be added to the project. If the Connect Copilot Manager approves the assignment, then an invitation to the project should be sent to the new Copilot. Further, if a Connect Copilot Manager invites a Copilot to a project directly then there should be no further approval process - the invitation should be sent immediately.

Additionally, we would not want this new role (Connect Copilot Manager) to be displayed as an option to invite a team member in the "Invite Team Members" section of Connect. Since this role is intended for existing admins, think of it as an admin role with the special capability of assigning Copilots to a project.

**Comment by RishiRajSahu** [comment]
@acshields 
>Connect Copilot Manager invites a Copilot to a project directly then there should be no further approval process

Only this is achievable as of now,

Regarding the other flow you mentioned is  tricky and a new feature which needs quite some time we can discuss more about this in our next call.

Also, `Connect Copilot Manager` - Yes this role won't displayed as an option as this is admin kind of role with special capabilities.

**Comment by maxceem** [comment]
@vikasrohit I guess this is already in DEV branch.

**Comment by vikasrohit** [comment]
Yes, it is.
