### ISSUE TITLE
[$40] Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2899]
Random error being logged in Sentry, last recorded on March 6, 2019. 

Cannot read property 'push' of undefined

```
/main.fe931b7dda1cbbe4c391.js at line 84:83392
/main.fe931b7dda1cbbe4c391.js in v at line 47:197027
/main.fe931b7dda1cbbe4c391.js at line 28:182112
1
/main.fe931b7dda1cbbe4c391.js at line 89:56398
/main.fe931b7dda1cbbe4c391.js at line 84:118801
/main.fe931b7dda1cbbe4c391.js at line 89:52110
/main.fe931b7dda1cbbe4c391.js in dispatch at line 84:84545
/main.fe931b7dda1cbbe4c391.js at line 89:52586
```
More details from Sentry:

```
{snip} _SUCCESS:var ne,re=o()({},e);return(ne=re.project.invites).push.apply(ne,a()(t.payload)),re.processingInvites=!1,re.error=!1,re;case M.INVIT {snip}
```

**OS**: Windows 10
**Browser**: Chrome 68.0.3440

**Comment by vikasrohit** [comment]
@maxceem can we do anything to fix this issue?

**Comment by maxceem** [comment]
@vikasrohit yeah, we can try to fix this, though without having a reproducible example we can do it only guessing the root of error, fixing it and waiting if the issue happens again.

**Comment by maxceem** [comment]
Sum up: 
- Looks like line of the error is here https://github.com/appirio-tech/connect-app/blob/dev/src/projects/reducers/project.js#L517 or here https://github.com/appirio-tech/connect-app/blob/dev/src/projects/reducers/project.js#L531
For this issue it would the best to do two things:
- find out the possible root of this issue and add it as a comment to the issue for future references
- instead of hiding the error at the line where this error has been logged, fix the issue as close to the root as possible

**Comment by khushimehta03** [comment]
@maxceem i want to work on this

**Comment by maxceem** [comment]
sure, it's on you since your comment

**Comment by khushimehta03** [comment]
@maxceem not able to find root cause, releasing it. this is open if anyone wishes to take it

**Comment by rashmi73** [comment]
@maxceem kindly give this to me thank you started working on it

**Comment by rashmi73** [comment]
@maxceem ready for review https://github.com/appirio-tech/connect-app/pull/2947

**Comment by rashmi73** [comment]
@maceem can please change asignee label on top right inside project container.so that it is with me

**Comment by maxceem** [comment]
@rashmi73 thank you for pointing it out - changed.

**Comment by rashmi73** [comment]
@maxceem updated MR
