### ISSUE TITLE
Duplicate Invitations on connect (case sensitivity on emails)

### ISSUE THREAD

**Issue by m-yadav** [appirio-tech/connect-app#3002]
### Expected behavior
The invitation module should check for the email address irrespective of the case sensitivity and prevent duplicated invites being sent to the user.

### Actual behavior
The invite module consider email with different cases as two separate entity and send over invitation to same email twice. The email with case matching the database asks the user to accept the invite where as the other one asks the user to register to topcoder and then accept the invite. Although its not a security concern as both the emails are going out to the intended recipient only.

### Steps to reproduce the problem
Go to any connect project for which you are having the rights to invite people.
Invite the user via email address , once with noraml convention and another one with some  letters being made capitalized. The user will receive two mailers for invitation.

**Comment by vikasrohit** [comment]
@maxceem Do you think, considering that it would require changes in `tc-notifications`, we can handle it as bug bash?

**Comment by maxceem** [comment]
@vikasrohit I would prefer to run a F2F for this. As during CF it feels most people are more comfortable with client-side. And this task may also require some local setup.

**Comment by maxceem** [comment]
@vikasrohit got a good idea from a member of the challenge:

> Do you need the gmail validation too? Because in gmail `example@gmail`, `ex.ample@gmail.com`, `exam.ple@gmail.com`, etc are actually the same email

What do you think?

**Comment by vikasrohit** [comment]
We can include this if we can make it in a way that is easy to disable this feature in case there are troubles because of this check in future. I know right now it is not going cause issues but I am just trying to do things specific to the mail providers. However, as gmail is one of the largest mail provider, we can have this check in place in a plug and play way.

**Comment by maxceem** [comment]
The current issue is fixed in branch https://github.com/topcoder-platform/tc-project-service/tree/feature/fix-email-duplicated-invites

I've noticed one more potential issue:
- we can invite `existent` user by email with another lattercase, which may also trigger an email to invite the user to the Topcoder, instead of inviting user by `userId`, see code https://github.com/topcoder-platform/tc-project-service/blob/feature/fix-email-duplicated-invites/src/routes/projectMemberInvites/create.js#L71

Will fix that case also together with adding checking for Gmail emails via private task to the winner.

**Comment by maxceem** [comment]
@vikasrohit PR is created in project service for this issue https://github.com/topcoder-platform/tc-project-service/pull/303

After it's merged and deployed to dev, I can make e2e smoke testing to verify the original issue.

**Comment by vikasrohit** [comment]
@maxceem I think we need to update the behaviour here. When I tried to invite a user, who is already invited to the project, via email (with case being different), API returned  `201` but the UI didn't say anything. I mean, if user invites only one email (with different case of already invited user), we should either convey to the user upfront that the email is already invited just like we do when user types exactly same email address. And when user types multiple emails which contains one email in different case of already invited user, we can show aggregated status of the request.

**Comment by vikasrohit** [comment]
Verified, working fine now.
