### ISSUE TITLE
Don't show project timeline and estimate component when project can not be estimated

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3009]
### Expected behavior
We should not show any question and project estimate section etc after we have identified that the project with given input can not be scoped automatically i.e. when we show the message `Wow! We love your idea....`, we should not show questions/sections and project estimate section after that.

### Actual behavior
As of now, it is showing both the message `Wow! We love your idea....`  and the project estimate section which creates confusion to the user.

### Steps to reproduce the problem
- Try to create new project using new app form
- Choose multiple devices as target device, with one Mobile/Tablet and another being Web browser
- Choose Responsive Web App for web browser
- Notice that we are showing the message `Wow! We love your idea... ` immediately after answering the last question
- Hit `Next` one more time, and notice that it is showing the project estimate section in inconsistent state.

### Screenshot/screencast
<img width="891" alt="Screen Shot 2019-05-07 at 2 15 19 PM" src="https://user-images.githubusercontent.com/2417632/57286437-d88be280-70d2-11e9-81d9-74b3f7b65a9f.png">

--

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): Any
- Account used:  N/A

**Comment by vikasrohit** [comment]
fyi @maxceem @RishiRajSahu

**Comment by maxceem** [comment]
To create a new project with such feature we can use this link https://connect.topcoder-dev.com/new-project/app-new-updated-designs-4

**Comment by maxceem** [comment]
@vikasrohit what if achieve this using conditions?

So far we use condition to show this message:
![image](https://user-images.githubusercontent.com/146016/57666546-e8f01000-7632-11e9-8fdd-b22d90046b1b.png)

I guess we can move this condition to `preparedConditions` as `IS_CUSTOM_SOLUTION`, and after hide `intermediate-summary`, `add-ons` sections and `estimation` question on the final summary section using this predefined condition.

Also, we would need to move question with this custom message to the final summary, where it would be displayed.

We can also introduce some custom logic instead, but it could become too specific. In particular, we somehow should define which button to show instead of `Next` when we come this custom quote question. At the moment button for creating project is defined on the final-summary screen so it's better to reuse it, rather then duplicate.

**Comment by vikasrohit** [comment]
Makes sense. Let me try achieving this with `condition`.

**Comment by vikasrohit** [comment]
@maxceem I am able to achieve it through `condition`, however, it requires me to add condition field to every sub section. Can we add the same field to the section as well?
Also, if all of the sub sections of a section are hidden by condition, shouldn't the section be hidden as well? I noticed that even if all subsections of the `intermediate-summary` screen were hidden, it was rendering the section with `Configure my project` button. I have to add condition field to every addon sub section as well (which I need to do anyway), to get it stop rendering the intermediate screen.

Also, I did't add a new variable in preparedConditions for `IS_CUSTOM_APP` because the current condition already has variables `MORE_THAN_ONE_TARGET_DEVICES && IS_WEB_RESP_APP` and we can not add prepared condition with variables and adding a new variable `IS_CUSTOM_APP` with actual conditions of `MORE_THAN_ONE_TARGET_DEVICES` and `IS_WEB_RESP_APP` would be more error prone, I guess

**Comment by vikasrohit** [comment]
@maxceem bumping up for your views.

**Comment by vikasrohit** [comment]
@maxceem I am closing this issue, however, would like to get couple of things improved:
1. Support for `condition` at section level
2. As I said, I had to add condition field to every sub section of add on section to completely get rid of the intermediate summary screen despite the fact that all sub sections of the intermediate summary screen had the condition which should hide the complete section even if 1 is not implemented.
