### ISSUE TITLE
[$50] Radio group option style breaks when there is very long text for the radio group option

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3100]
![Screen Shot 2019-06-07 at 5 10 11 PM](https://user-images.githubusercontent.com/2417632/59101615-23558000-8947-11e9-9cde-c1a2c5aeb08e.png)

fyi @maxceem we can take this in our next CF

**Comment by maxceem** [comment]
To reproduce this issue can use the next link for creating project https://connect.topcoder-dev.com/new-project/subtitle-skills-api

Choose only `Design` option, so question with issue is visible:

![image](https://user-images.githubusercontent.com/146016/60379748-f3dbf400-9a6a-11e9-9843-d96ce1b69455.png)

Expected: the radio should be displayed correctly in front of the first line of the text.

This should be fixed in general, so maybe fixing component inside `react-components` repo could be required to fix this issue.

**Comment by iversonLv** [comment]
@maxceem could I take this?
Thanks.

**Comment by maxceem** [comment]
It's on you @iversonLv

**Comment by iversonLv** [comment]
@maxceem I have created a PR at react-components
https://github.com/appirio-tech/react-components/pull/320

Thanks.

**Comment by maxceem** [comment]
@iversonLv please, have a look on the review here https://github.com/appirio-tech/react-components/pull/320#pullrequestreview-258587311

**Comment by iversonLv** [comment]
@maxceem done
updated at that PR
[![Screenshot from Gyazo](https://gyazo.com/f22b19287e90001cc8adf1e5198b83a0/raw)](https://gyazo.com/f22b19287e90001cc8adf1e5198b83a0)
Thanks.

**Comment by vikasrohit** [comment]
Sorry to jump in @maxceem however, can we update the position of the circle of the radio to be vertical middle of the label? As of now it is top aligned.

**Comment by iversonLv** [comment]
@vikasrohit @maxceem 
Then I think we just need to merge my first commit 
  https://github.com/appirio-tech/react-components/pull/320/commits/d9a1b37d93f3c67492a6bf76f47f1f75b8fe086b

**Comment by maxceem** [comment]
Ah, ok @vikasrohit I've asked to move it to the top from the middle 😬

Thanks, @iversonLv, yeah, will use your first commit.

**Comment by vikasrohit** [comment]
Oh, I didn't notice that. 😬 Its my personal preference to have that in middle. Its not coming from a designer, so lets keep whatever we have in the final PR. No need to pick old/first commit from the PR.

**Comment by vikasrohit** [comment]
Verified, working fine on production.
