### ISSUE TITLE
[Metadata Management] Support form, priceConfig and planConfig versioning

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3108]
### Overview

[Recently](https://www.topcoder.com/challenges/30086308/?type=develop&noncache=true&tab=details) we've extracted `form`, `priceConfig` and `planConfig` from `ProjectTamplates` and `ProductTemplates` into separate models and implementing versioning support for them server-side.

We have to support new functionality in the **Metadata Management** tools.

Each of the new objects `Form`, `PriceConfig` and `PlanConfig` support two type of versioning.

- `version` - is something for people. When we want to make some new version of some form, we could manually click a button to create a new version. We will be aware of what exact version we are working at the moment and what version is being used inside templates.

- `revision` - is kind of history of changes or “Ctrl + Z” of changes we saved to the DB. Sometimes we accidentally save broken data into DB and finding issues could be quite hard in big JSONs. So every time we save a particular object instead of updating it we would create a copy with updated data and increased revision number. This would happen without user notice and we don’t need to know what is the number of revision we are seeing at the monent. Though a user could be able to press some button to come to the previous revision.

### Requirements

- Editing "old" `ProjectTemplates` and `ProductTemplates` which don't use separate models should work like before without changes.

   ![image](https://user-images.githubusercontent.com/146016/59256523-b9024f80-8c66-11e9-8edf-09afba019a86.png)

- If some fields like `form`, `priceConfig` and `planConfig` is defined for `ProjectTemplates` or `ProductTemplates` for such fields we would improve editing functionality and additionally show `Version` and `Revision`:

    ![image](https://user-images.githubusercontent.com/146016/59258268-38455280-8c6a-11e9-84ac-fd18f6d6a8d3.png)

### Question

If we choose some `Version` we would load the respective JSON from that version. When we save the ProjectTemplate we would update the value of the version to the one which we choose. So for example, initially 
   ```js
    projectTemplate.form = { key: 'dev', version:5 }
   ``` 
   after we choose version `3` and save it would become 
   ```js
   projectTemplate.form = { key: 'dev', version: 3 }
   ``` 
   This part is clear.

We should agree on how we would like to work with `revision`.

For example, the current revision is `14` and the form object looks like this:
```js
    projectTemplate.form = { key: 'dev', version:5 }
``` 
so `14` is the last revision.
We would like to come back to some previous revision `8`. We choose the revision `8` and we can see now the JSON of the 8th revision. We click `Save` and what I think should happen is, the new revision `15` should be created which would be equal to revision `8` or it can have some changes if before clicking `Save` we updated code of JSON of the 8th revision.
Data inside the template would stay the same:
```js
    projectTemplate.form = { key: 'dev', version:5 }
```

But at the momenet, we would get the latest revision which is `15` when we render such template.

@vikasrohit is my understanding correct? So we only use `version` to define versions of the templates, and we use revisions just to revert some bad changes.

**Comment by maxceem** [comment]
@vikasrohit This question regarding `revision` is also important during the rednering of templates. As I understand we should always render using only `key` and `version`, and retrieve the latest `revision`.

**Comment by vikasrohit** [comment]
I have couple of suggestions for the overall UI as well before coming to the point of `revision`:

1. I guess, we don't need to show the editable JSON editor on the `ProjectTemplate` and `ProductTemplate` create/edit screens. They would always use an existing version of the `planConfig`/`priceConfig'/'formConfig'. We even don't need to show the revision number of the target config object because we would always use the latest revision.
2. For each of the new metadata entities `planConfig`/`formConfig`/`priceConfig`, we would show `version` and `revision`, both in non editable form. `version` would be increased and kept as non editable value when user clicks on `Create new version` button on edit screen of these entities and `revision` would be updated automatically on every `Save` click as you said. We can show the `revision` as dropdown of already existing revisions, and if user selects some old version while editing, it would update the JSON from that `revision` in the JSON editor and hitting Save after that would create new `revision` automatically with any changes that user made before hitting the save and after choosing an old revision from the dropdown.

So, essentially, you are right. `version` is for using different versions of the same template in different project templates and `revision` is to revert bad changes.

For reverting a bad change for a project template, user has to go to the specific referred entity (plan/price/form config) and revert to the revision as described in 2. It would automatically cause all the project templates using the specific version to use the corrected JSON config.

**Comment by maxceem** [comment]
Thanks @vikasrohit I think our understanding of `revision` is in sync.

1. This means that we should add 3 more tabs to edit `Forms`, `PlanConfigs` and `PriceConfigs` right?

2. Should we be able to edit not the latest `version` somehow?

**Comment by vikasrohit** [comment]
1. Yes
2. Yes, and the way is that don't have `PATCH` endpoint for these new entities. Always call `POST` with version details and the backend would automatically increase the revision from the latest revision in the database while saving the new object.

**Comment by vikasrohit** [comment]
Only confusion to me in not having `PATCH` endpoint is that even when the user wants to change the non JSON fields e.g. name, key etc, we have to create new entities every time. But I think that should be okay because we would allow a very limited number of revisions e.g. 20 is my best guess for having maximum number of revisions per object in our database.

**Comment by maxceem** [comment]
As per discussion should the UI be like?

![image](https://user-images.githubusercontent.com/146016/59320119-bef83f00-8cff-11e9-873e-48f69c2c7fde.png)

Maybe we should keep `version` next to the `key`. As it's like an identifier of an object same like the `key`.

- When we select any `version` we would be redirected to the page like
   ```
    https://connect.topcoder-dev.com/metadata/milestoneTemplates/scoped-solutions/3
   ```
   Which has `key=scoped-solutions` and `version=3` inside URL.
- When we select any `revision` we would replace all the data inside the form with the data of the `revision` we choose. Or only the JSON?

**Comment by vikasrohit** [comment]
If UI is for the new metadata entities like `formConfig`, `phaseConfig` and `planConfig`, I think that is good to move forward. I liked the suggestion to move the version to the top and next to the key/id field.

When user select any `version`, do you think simply reloading the content would also work as we are planning for doing when user changes `revision`? If you think, redirection to specific version URL makes sense, we should redirect to URL like ` https://connect.topcoder-dev.com/metadata/formConfigs/app/version/3`.

> When we select any revision we would replace all the data inside the form with the data of the revision we choose. Or only the JSON?

I think we should reload all data not only JSON as now we have the data.

**Comment by maxceem** [comment]
> When user select any version, do you think simply reloading the content would also work as we are planning for doing when user changes revision?

It feels that we should have a separate URL for each `key`/`version` pair like `https://connect.topcoder-dev.com/metadata/formConfigs/app/version/3` as each of such template is kind of independent entity. Also, later, in Project and Product templates, we can add direct links to the particular template with `key`/`version`. As we wouldn't have ability to edit form, planConfig, priceConig inside project and produc templates, it would be handy to have a direct link to move to editing the particular version.

The `revision` would just update the data of the currently opened template, as an equivalent of pressing `Ctrl+Z`. The only thing I don't like in such an approach as that `vesion` and `revision` selects visually look the same, but they would perform different actions by nature. But I guess we could refine it later after we try this UI in real usage and would see how it feels.

**Comment by vikasrohit** [comment]
Makes sense for the separate URL for key/version combo.

For revision ui, may be we can show revision always as read only text instead of a dropdown and give a small link next to it saying `See history` (just like google docs) and show a modal popup where we would show all the available revisions and against each revision give an option in form of another link, saying `load this revision` clicking on which would load the data from that revision. However, user has to still hit Save button to save a new revision with that content.

**Comment by maxceem** [comment]
@vikasrohit what about the next view for the form:

![image](https://user-images.githubusercontent.com/146016/59818374-38bea700-9356-11e9-8262-f4ec6c4b2aca.png)

I'm thinking about keeping **Duplicate** button and adding **Create New Version** button.
- **Duplicate** button should turn the page to create a new entity page with the prefilled **config** and empty **key**. **Version** and **revision** fields should be hidden as during creating.
- **Create New Version** button should turn the page to the create a new entity page with the prefilled **config** and prefilled read-only **key**. **Version** and **revision** fields should be hidden as during creating.

**Comment by vikasrohit** [comment]
Looks good to me. Go ahead.

**Comment by maxceem** [comment]
@vikasrohit this issue is done. We can manage Forms, PriceConfigs and PlanConfig separately. Now we only have to support creating/editng Project and Product templates using these external models.

This would be tracked in a separate issue https://github.com/appirio-tech/connect-app/issues/3236 while this one I think can be closed.
