### ISSUE TITLE
"Save Changes" button is not enabled when we change project Scop

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3119]
When we change values in Scope of this project https://connect.topcoder-dev.com/projects/8103 **Save Changes** button is not got enabled.

Expected behavior: **Save Changes** button should get enabled if we make any changes to the form, and should get disabled if there are no changes in the form.

**Comment by maxceem** [comment]
I've made further testing. Looks like this issue can be only reproduced on PROD https://connect.topcoder.com/projects/11089/scope. But if I create a new project with the same template on DEV https://connect.topcoder-dev.com/projects/8178/scope the issue is not reproducible anymore. Probably it has been fixed on the DEV already with some other changes.

The only one small issue I see on DEV - if we change some field, the **Save Changes** button got enabled as expected. But is after I revert the change back the button **Save Changes** still stays enabled, so we can save form without making any changes.

@vikasrohit should we fix the other issue which keeps the **Save Changes** button enabled?

**Comment by vikasrohit** [comment]
May be its the difference in the template? I mean production might have some difference than the dev one. Could you please compare and ascertain that it is not because of template itself.

Yes, we should fix the issue you are seeing now because essentially it would cause Unsaved changes alert as well even if we don't have any.

**Comment by maxceem** [comment]
> May be its the difference in the template? I mean production might have some difference than the dev one. Could you please compare and ascertain that it is not because of template itself.

Good idea @vikasrohit.

There is some difference:

![image](https://user-images.githubusercontent.com/146016/60332752-0e11c580-99ca-11e9-9a0b-4960c8a5490d.png)

Though I've created a projectTemplate using the data from PROD, and it still cannot reproduce the issue on DEV. Here is a project I've created with a projectTemplate which is a copy from PROD https://connect.topcoder-dev.com/projects/8179/scope.

**Comment by maxceem** [comment]
> it would cause Unsaved changes alert as well even if we don't have any.

If I revert changes the alert is not shown even button looks enabled.

Regarding the main issue, there is an issue which so far can be reproduced only for one project.
These two projects on PROD were created with the same template, but button work for one of them, but doesn't work for another one:
- https://connect.topcoder.com/projects/9439/scope (button got enabled on changes)
- https://connect.topcoder.com/projects/11089/scope (button is not got enabled on changes, but I still get alert if I try to leave the page after making some changes, see https://monosnap.com/file/L3gOfusbxJGEKUtVWDwrZ0RDxQBfvb)

**Comment by vikasrohit** [comment]
@maxceem I think I go the reason of `Save` button not being enabled. It is essentially one or more required fields does not have answer in such projects. e.g. https://connect.topcoder.com/projects/11089/scope does not have answer for `goal` question which is required for that project. If you enter a value in that field, it starts working after that as expected.

Now the question is `how the project got saved without having values for the required fields. The only reason, I can understand is that field was not mandatory at the time of project creation but template was updated later on to make that field required. If this is the case, we should be good and don't need any fix for the issue, otherwise we need to ascertain that there is no possible way to skip required questions at the time project creation.

**Comment by maxceem** [comment]
@vikasrohit I've tested out the create form for this type of project, and I don't see any way of creating it without defining the `goal` field https://connect.topcoder-dev.com/new-project/visual_design_prod_from_prod_max.

Also, I've tried to edit project scope and save without `goal` but also don't see a way to do so.

So I think we should watch it if we ever come across similar issues

**Comment by maxceem** [comment]
I've created a separate issue for the case when the button stays enabled https://github.com/appirio-tech/connect-app/issues/3149.

While this issue can be closed I guess.

**Comment by vikasrohit** [comment]
I think the link in #3149 is pointing to production which members won't be able to access.

**Comment by maxceem** [comment]
> I think the link in #3149 is pointing to production which members won't be able to access.

Thank you @vikasrohit for catching it, updated the link.
