### ISSUE TITLE
[$60] Invited users disappears when the project is updated

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3126]
### Expected behavior
Invited user list should remain as is

### Actual behavior
All invited members disappears immediately after we do any kind of project update (e.g. change in scope or status of the project)

### Steps to reproduce the problem
- Open a project which has at least one member invite
- Now, either update some question in the scope tab or just change the project's status
- Observe the Team section for member invite

--

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): Any
- Account used: N/A

**Comment by maxceem** [comment]
Here is a project to demonstrate the issue as it has one member invited. The issue is most likely in the reducer.

I guess we keep invited members inside the object inside redux state which is got overwritten when we update the project scope. So we should make sure we persist invited users list. We had simmilar issues for other things which we store in the project object inside redux so there should be some examples of fixes for other things in the reducer source code.

**Comment by PrakashDurlabhji** [comment]
@maxceem please assign this to me thank you

**Comment by maxceem** [comment]
@PrakashDurlabhji assigned.

**Comment by PrakashDurlabhji** [comment]
@maxceem can you please provide me the project where this can be observed?

Comment above says "Here is the link" but i dont find any such link to project. kindly confirm

**Comment by maxceem** [comment]
Here is an example project https://connect.topcoder-dev.com/projects/8036 @PrakashDurlabhji

**Comment by PrakashDurlabhji** [comment]
@maxceem it says project not found, can you please confirm if project working, I  logged in pshah_copilot

**Comment by maxceem** [comment]
Please, use pshah_manager to access this project.

**Comment by PrakashDurlabhji** [comment]
@maxceem PR ready https://github.com/appirio-tech/connect-app/pull/3143

**Comment by vikasrohit** [comment]
Verified.
