### ISSUE TITLE
[$30] Confirmation dialog for cancelling a project is positioned incorrectly at the the top of the side bar

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3206]
<img width="305" alt="Screen Shot 2019-07-22 at 5 58 36 PM" src="https://user-images.githubusercontent.com/2417632/61632384-59a64f00-acaa-11e9-929c-7af801273216.png">

fyi @maxceem

**Comment by maxceem** [comment]
Sum up:
1. Use user `pshah_manager`.
2. Open project https://connect.topcoder-dev.com/projects/7442
3. In the left sidebar click `Project is active` and choose `Cancelled`
4. The confirmation dialog would be shown on the top of the left sidebar where we not always can see it. Instead of that we should show confirmation dialog under the status select dropdown. Confirmation dialog should "push" content bellow when opened, not shown on the top.

![image](https://user-images.githubusercontent.com/146016/64674554-c1db0b00-d479-11e9-8e09-50ab0da5da6e.png)

**Comment by PrakashDurlabhji** [comment]
@maxceem I would like to try this one thank you

**Comment by maxceem** [comment]
Of course @PrakashDurlabhji

**Comment by PrakashDurlabhji** [comment]
@maxceem PR ready https://github.com/appirio-tech/connect-app/pull/3307

**Comment by PrakashDurlabhji** [comment]
@maxceem PR updated

**Comment by PrakashDurlabhji** [comment]
@maxceem code update done and working

**Comment by PrakashDurlabhji** [comment]
@maxceem PR update done

**Comment by RishiRajSahu** [comment]
Closing. Pushed to prod.
