### ISSUE TITLE
[$70] Messaging on mobile

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#3213]
Composing a message in mobile is broken (at least on android). Can't use the editor at all - ex type "thank you." and the text displayed is "t ." and there is no way to delete that text either. I'd suggest just using the raw textarea in mobile

**Comment by vikasrohit** [comment]
Thanks @gondzo it seems with new UI changes, it started to render the draft js editor for mobiles as well which was not intended despite the fact that we didn't work on mobile designs for the new UI.

fyi @maxceem

**Comment by vikasrohit** [comment]
@gondzo I can see that it is still rendering the plain text editor instead of draft js editor for me. It works fine when trying to create new thread, however, when creating new post, it seems like the the new post modal is hidden behind the drawer and the drawer itself is having horizontal scroll.

![Screenshot_2019-08-26-11-16-28](https://user-images.githubusercontent.com/2417632/63668052-8abaf780-c7f3-11e9-9e6c-95a0145e3c13.png)

**Comment by maxceem** [comment]
Sum up:

1. Drawer should open with 100% instead of hardcoded value on the screens with width less than [$screen-md](https://github.com/appirio-tech/tc-ui/blob/feature/connectv2/src/styles/_variables.scss).

   - It should also start from the top of screen without space on the top.

2. When we click `Write post` we open the window to write a post. It should open on TOP of the drawer. Now it's opened, but behind the drawer so we cannot write a new post on mobile device.

3. In general we have to make sure that we can create new topics and posts on the `Messages` page, see [example project](https://connect.topcoder-dev.com/projects/8363/messages).

**Comment by suppermancool** [comment]
@maxceem pls assign this to me

**Comment by maxceem** [comment]
Done @suppermancool

**Comment by suppermancool** [comment]
@maxceem done in https://github.com/appirio-tech/connect-app/pull/3313

**Comment by RishiRajSahu** [comment]
@lakshmiathreya could you please test this issue on PROD and confirm ?

**Comment by vikasrohit** [comment]
Verified on production and it seems to working for me. Closing.
