### ISSUE TITLE
Post editor: don't allow to render arbitrary HTML

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3249]
If we insert some HTML code to any post, the HTML is rendered but I think it shouldn't be and it should be displayed as a text with encoded HTML symbols.

I guess we have it rendered because we support richtext editing.

For example, create a post with the next content:
```
The following error has occured- 502:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd"> <HTML> <HEAD> <TITLE>Error Page</TITLE> </HEAD> <BODY BGCOLOR="#FFFFFF"> <CENTER><H2> Upstream server is not available </H2></CENTER> </BODY></HTML>
```

It would be rendered like this:

![image](https://user-images.githubusercontent.com/146016/62674268-4bf40780-b9d4-11e9-9a07-140f3a754f77.png)

Also, when I copy/paste such text into the post editor, I see there is an error in browser console:

![image](https://user-images.githubusercontent.com/146016/62674306-6cbc5d00-b9d4-11e9-8e7d-2fa74ef76a80.png)

**Comment by vikasrohit** [comment]
IMO, we should be good to render the HTML because we are already sanitizing the content for dangerous content. If user wants to past the HTML as code, they can do that by including code block.

Further, the error you saw is appearing in many other cases as well @maxceem which I think is appearing because of some other reason just like we had the weird issue because of NPE in `draftjs-helper` module after the previous release.

**Comment by maxceem** [comment]
Oh yeah, your are right.

We can insert the HTML code as code in text editor by using the code style button:

![image](https://user-images.githubusercontent.com/146016/62676937-0db01580-b9df-11e9-8f0a-b75d03b66eb0.png)

it would be rendered as expected:

![image](https://user-images.githubusercontent.com/146016/62676953-16085080-b9df-11e9-8712-990ddf121fb5.png)

I'm closing this issue for now. As anyway, we are thinking about replacing this editor with the one which supports mobile devices. The current one works good enough for now.
