### ISSUE TITLE
Registration & Profile Page Updates - Part I

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#3278]
1. Registration & Profile Pages: **Update Business Phone Entry**
- [x] Move country code dropdown from the right-side of the field to the left-side of the field (where the code would logically be placed when entering)
- [x] Label the dropdown "country code"
- [x] Update business phone entry on Profile page to match registration page 

2. Registration & Profile Pages: **Remove 'Company Size'**
- [x] Remove "Company Size" question & answer from the Registration form
- [x] Remove "Company Size" question & answer form the Profile page

3. Profile Page: Remove 'Business Address'
- [x] Remove "business address" entry from My Profile page in Connect.

4. Registration Pages: **Modify 'Marketing opt-in' Behavior** https://github.com/appirio-tech/connect-app/issues/3295
- [x] Update the message wording at the bottom of the intake form to read: "I do not want to receive marketing communications from Topcoder." Therefore, if they do not check this box, they are agreeing to receive marketing communications.
- [x] Update registration submission behavior to enable customers to complete registration, whether they choose to opt-in or opt-out of marketing communications.

5. Registration Pages: **Update Left Sidebar Title & Steps**
- [x] Update section title to read: "Registration"
- [x] Update Step 1 description to read "Profile" (this should be the active step when the user is entering their personal contact information, and should be marked complete when they click 'Continue')
- [x] Update Step 2 description to read "Validation" (this should be the active step when the user is validating their account with PIN entry, and should be marked complete when they enter the PIN)
- [x] Update Step 3 to read "Registered" (this should be the active step when the customer is shown the page showing their account creation confirmation).
Remove the steps referring to project creation from being displayed in the left sidebar.

**Comment by lakshmiathreya** [comment]
@vigneshTheDev @RishiRajSahu @vikasrohit pls clarify if the fix for this Issue has been completed - since I notice these to be missing during Registration Process:
1. Country code drop down continues to be on the right.
2. Company size question is still there.
3. Marketing opt-in behavior is same as earlier - the above message is not implemented.
4. Left side bar titles have also not been updated as per requirement above.

**Comment by RishiRajSahu** [comment]
@lakshmiathreya the changes are removed from dev due to deployment of some other feature branch, let me know when you plan to test I will build the changes again on dev

**Comment by lakshmiathreya** [comment]
Verified all requirements listed here. Except:
"Update business phone entry on Profile page to match registration page".

Pls note that this cannot be verified in Dev since Profile page comes up blank due to Member service issue. Hence there is no prepopulated Business phone entry in the Profile to match with.

**Comment by RishiRajSahu** [comment]
@lakshmiathreya yeah I agree the data is not pre-populated for now just test that for the pages show same UI

**Comment by RishiRajSahu** [comment]
Pushed to prod.
