### ISSUE TITLE
Use handle instead of first and last name for creating avatars in Connect

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3289]
After recent changes in `_search` api endpoint, we started to miss the `firstName` and `lastName` for the users searched by this endpoint even though the user is authenticated. We should be able to pick the user's handle instead of first and last name if they are not available. This would make the application more fault tolerant as well.

fyi @RishiRajSahu @maxceem

**Comment by nithyaasworld** [comment]
@vikasrohit @maxceem Can you please tell me the steps to verify this issue? I am not able to understand what does _`Use handle instead of first and last name for creating avatars in Connect`_   mean. Thanks!

(I am in the process of triaging the old bugs and I am starting with all P0 bugs. )

**Comment by maxceem** [comment]
@vikasrohit the first and last name now are always populated by Project Sevice. Should we still change letters in avatars to user handles?

> Can you please tell me the steps to verify this issue? I am not able to understand what does Use handle instead of first and last name for creating avatars in Connect mean.

@nithyaasworld at the moment if some user doesn't have a photo, instead of the photo we ar showing first letters of the first name and last name:
![image](https://user-images.githubusercontent.com/146016/74506403-7d75fe80-4f34-11ea-8383-e8c1a3650d8e.png)

As some time ago we had problems with getting first and last name for users, we didn't have anything to show inside avatars if users don't have a photo and first/last name. Though now, I think it's not an issue anymore as we suppose to always have at least first and last name.

**Comment by vikasrohit** [comment]
> @vikasrohit the first and last name now are always populated by Project Sevice. Should we still change letters in avatars to user handles?

I guess, it would be better to have it in place to close the chain of missing information from member api.

**Comment by maxceem** [comment]
Sure. Currently, we are formatting avatar using 2 first letters of first and last name. How should we format it if only the handle is available? Should we show only 1 first latter of the user handle?

**Comment by vikasrohit** [comment]
Can we have avatar with first two characters of the handle?

**Comment by lakshmiathreya** [comment]
@vikasrohit @maxceem whats the resolution for this? cc @drasticdpk

**Comment by maxceem** [comment]
This wasn't implemented at the moment. As now I see it has `P0` label, should we do it as a hotfix @vikasrohit?

**Comment by vikasrohit** [comment]
It would be better if we can take it as patch release combining with other changes, if any - otherwise we can take it in next release. I added P0 to make sure that we don't have issues when member api stops returning first name and last name for _search endpoint for which I don't have timelines yet.

**Comment by maxceem** [comment]
@vikasrohit this appears to be already implemented, though it only shows one first letter:

![image](https://user-images.githubusercontent.com/146016/75515800-e762cd80-5a35-11ea-970f-62e1af7815a4.png)

The thing is why we may still see `Connect User` instead of user handle, is that because we usually know only `userId` and to get user first name, last name and user **handle** we have to call Member Service. So if Member Service fails, we don't get anything, even user **handle**.

**Comment by vikasrohit** [comment]
Great!!

If members service fails to return anything for the user for whom we only have userId, I think we can not do anything. But I just wanted to make sure that, if member api returns successfully but does not have anything other than handle, our system should not fail, which I think is the case as per your understanding. So, closing the issue. Thanks
