### ISSUE TITLE
P0: Update Draft to In Review Project Status Logic

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#3301]
**Overview:** Remove the additional step of users needing to move project from 'Draft' to 'In Review' to send lead data to SFDC by converting projects to be in 'Draft' status only when the intake form is incomplete and 'In Review' status immediately after intake submission/project creation and leveraging the objective flag to route leads to SFDC appropriately.

<p></p>

**Requirements**

- **Draft**: Projects are only considered 'draft' when the intake form is incomplete and not submitted.

- **In Review:** All projects with a completed intake form should automatically be changed into 'In Review' status upon intake form submission/project creation. However, only projects with the intake form objective flag answer of: "I need work done," "I am exploring my options," or "Submitting Client Request" should have the intake information routed immediately to SFDC.  Projects created with the objective flag with 'Internal Project' or 'Demo/Test/Other' should not have lead data sent to SFDC.

<p></p>

**Comment by ajefts** [comment]
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/1671082

**Comment by maxceem** [comment]
As I understand, we would not have a separate API request for converting project from `Draft` to `In Review`. So for this task we should do the next things:
##### In Connect App:
- remove `Draft` option from the status dropdown if the value of `intake form objective flag` is one of "I need work done," "I am exploring my options," or "Submitting Client Request". Otherwise we keep value `Draft` in the list, as demo/text project may have `Draft` status.
##### In Project Service:
- when new project is created we should check the value of the `intake form objective flag`, and if its value is one of "I need work done," "I am exploring my options," or "Submitting Client Request", then we directly create project in status `In Review`, so project would never be in status `Draft`. Otherwise, we create project in `Draft` status as usual.
- also, we should send the BUS EVENT `BUS_API_EVENT.PROJECT_SUBMITTED_FOR_REVIEW` which is sent when project status is changed to `In Review`

**Comment by maxceem** [comment]
@vikasrohit this issue is marked with `tcs_Paid` label. Is this issues already done and paid?

**Comment by vikasrohit** [comment]
@maxceem I think the language of the task is bit confusing and I got confused with it as well. All we need for this task is to get rid of `draft` status completely from every where i.e. no project would ever assume this status from the day we push the changes to production. By default project would be created in `in_review` status.
Second change is when the answer of the `objective` question is not from "I need work done," "I am exploring my options," or "Submitting Client Request", it should not go to the SFDC. As of now we [don't send lead to the SFDC](https://github.com/appirio-tech/tc-connect2sf/blob/master/consumer/src/services/ConsumerService.js#L71) when a project is created by a topcoder employee or better said by a non customer user. So, I guess, we need to check the answer of the new question now instead of checking the member role to create lead in the SFDC.

**Comment by vikasrohit** [comment]
> @vikasrohit this issue is marked with `tcx_Paid` label. Is this issue already done and paid?

These are carried forward from the design tasks of the same story.

**Comment by maxceem** [comment]
It looks like local setup of `tc-connect2sf` for testing could be quite complicated. As I think the change would be small, do you think we would be able to make this change and after deploy `tc-connect2sf` service to DEV for testing instead of testing locally?

**Comment by vikasrohit** [comment]
Yes, I guess that is the only possibility for us because we have very fewer changes for this repo. So, it does not make sense to educate community about this repo and invest time in setting this on local. Let me know if you think you are comfortable with the changes or I can do that as well.

**Comment by maxceem** [comment]
Yes, I'll handle it after adding intake flag in https://github.com/appirio-tech/connect-app/issues/3281

**Comment by maxceem** [comment]
>All we need for this task is to get rid of draft status completely from every where

@vikasrohit what should we do with the existent project which currently have status `draft`? Should we create a migration script to move all of them to `in_review` status? Or should we keep them as they are? In such case we should hide `draft` status in the dropdown unless it's not currently selected. And as soon, as we select another status, the `Draft` option should disappear from the dropdown.

**Comment by vikasrohit** [comment]
@maxceem I think you are working on this one yourself, right? Do you think we can apply it as hotfix immediately after the release?

**Comment by maxceem** [comment]
> @maxceem I think you are working on this one yourself, right? Do you think we can apply it as hotfix immediately after the release?

yes, I think we can apply a hotfix after release. Is that ok, to also hotfix https://github.com/appirio-tech/tc-connect2sf or it's better to update that service during the scheduled downtime?

**Comment by vikasrohit** [comment]
we can make it as hofix but for `tc-connect2sf` we can push it as regular release as we didn't make any release for this repo this time.

**Comment by maxceem** [comment]
@vikasrohit would be great if could confirm the sum up, and there are couple of questions regarding changes in `tc-connect2sf`.

Sum up:

#### In Connect App
1. Remove the option `Draft` option from the project status select unless project is currently in `Draft` status:

   ![image](https://user-images.githubusercontent.com/146016/66292962-1dcd6e00-e918-11e9-9206-d3cc74bacb3f.png)

   - If the project is currently in draft status we still show the `Draft` option. But we have to remove it after we move the project to any other status.

2. We mistakenly use `PROJECT_STATUS_DRAFT` in two places:
    - https://github.com/appirio-tech/connect-app/blob/dev/src/projects/actions/project.js#L278
    - https://github.com/appirio-tech/connect-app/blob/dev/src/projects/actions/project.js#L292

    We have to use constant `PHASE_STATUS_DRAFT` instead. As in these two places we define status for phases, not projects.

#### In Project Service
1. By default create projects with status `in_review` instead of `draft`.
2. Don't allow to update project status to `draft`.

#### Connect 2sf
1. The current logic is to throw an error (which causes not sending the lead) when we cannot find the primary customer, see https://github.com/appirio-tech/tc-connect2sf/blob/master/consumer/src/services/ConsumerService.js#L71-L77.
     @vikasrohit the current way it's done is throwing error 'Cannot find primary customer'. I don't understand why we throw an error here rather than simply not sending the lead. But as we are going to perform this change blindly, can we keep the current logic? I. e. can we throw an error `We don't send a lead to SFDC for internal or test/demo projects` in case the value of intake question is 'Internal Project' or 'Demo/Test/Other'.
2. Should we send the lead to SFDC in case the intake question value is not provided or no?

**Comment by vikasrohit** [comment]
@maxceem Thanks for nice sum up. 

**Connect App:**
1. You are right here.
2. I am not sure if I understood it correctly, but I can see it is using constant in both places.


**In Project Service**
Correct for both.


**tc-connect2sf**
1. I guess the reason of throwing the error was to `NACK` the `Unprocessable Errors` generically in the RabbitMQ message handler. So, I think till the point we are using RabbitMQ (i.e. before releasing v5), we can keep throwing the error to `NACK`  such event messages where we can not proceed further.
2. I guess we should not create lead when the objective flag question is not answered. However, there is a catch, we are [working](https://github.com/appirio-tech/tc-connect2sf/tree/feature/event-based-salesforce-integration) on simplifying the `tc-connect2sf` in way that it would always send events data to the salesforce without any business logic and then it is upto salesforce to act on it. So, in that case this logic should reside within salesforce. But I would double check this with product managers.

**Comment by vikasrohit** [comment]
@maxceem for the `tc-connect2sf`, we don't need any change for this now. It should be handled by the Salesforce.

**Comment by maxceem** [comment]
> I am not sure if I understood it correctly, but I can see it is using constant in both places.

Right, it uses constants in both places. But the current code uses constant `PROJECT_STATUS_DRAFT` for **project**, while it has to use `PHASE_STATUS_DRAFT` for **phase**. The values of these constants are same so there is no issue. But as we are going to get rid of project draft status, it's better to update this code, just to see that it doesn't depend on the **project defat status**, but on **phase** draft status.

**Comment by vikasrohit** [comment]
Ohk, Got it.

**Comment by maxceem** [comment]
This issue has been implemented by two PRs:
https://github.com/appirio-tech/connect-app/pull/3372/files
https://github.com/topcoder-platform/tc-project-service/pull/408

They both have been merged to `dev` branches.

**Comment by vikasrohit** [comment]
@lakshmiathreya @nithyaasworld can we close this?

**Comment by vikasrohit** [comment]
Closing as it seems to work fine to me. Need to reduce the number of open issues to manage the next release properly.
