### ISSUE TITLE
Local Timezone

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#3359]
**Objective:** During registration and on the profile page of Connect capture user's local timezone, which will aid in level-setting availability and responsiveness for all users.

<p></p>

**Requirements:**

- For Connect registration, include a required question and answer for user to indicate their local timezone. Below describes the question and answer format:

  - Question: Local Timezone (*marked as required on the form)

  - Answer: User can type an entry, which should filter options for selection from a dropdown list of world timezones.

- For the Connect 'My Profile' page, display 'Local Timezone' as an editable field. Users should be able to update their local timezone by saving a new timezone from the dropdown list and saving changes. Further, users should be able to update and save their local timezone in their profile with out having to update any other fields.

<p></p>

Note: Inside a Connect's project space, this field of data will be included as an enhancement to the 'team' view.

**Comment by ajefts** [comment]
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/2794134

**Comment by RishiRajSahu** [comment]
@vigneshTheDev would you like to pick this up ?

**Comment by RishiRajSahu** [comment]
@lakshmiathreya could you please verify this in dev.

**Comment by lakshmiathreya** [comment]
Verified in Dev. TZ field updates seem to happen successfully. However, possibly due to member service issue, the Profile fields are not visible - hence not able to completely verify this feature. -- --- Other fields including TZ appear blank post updates in User profile.
-- TZ not visible in Team view.
-- TZ not visible in Member profile view.

<img width="1436" alt="Screenshot 2019-10-31 at 2 09 58 PM" src="https://user-images.githubusercontent.com/51733042/67931579-33b51280-fbe8-11e9-93af-6e6cc943a11a.png">

<img width="1417" alt="Screenshot 2019-10-31 at 2 14 43 PM" src="https://user-images.githubusercontent.com/51733042/67931899-d79ebe00-fbe8-11e9-9c47-fc94fd35c6f7.png">
<img width="1480" alt="Screenshot 2019-10-31 at 2 13 57 PM" src="https://user-images.githubusercontent.com/51733042/67931907-df5e6280-fbe8-11e9-99bd-10cf26616d88.png">

**Comment by RishiRajSahu** [comment]
@lakshmiathreya okay will check for old users, please verify it by creating new user. Also community profile page is out of scope for this ticket.

**Comment by lakshmiathreya** [comment]
-- TZ capture and display in Profile is now working for Old and New users. 
-- TZ not visible in Team view though - Issue pending closure until then.

**Comment by nithyaasworld** [comment]
> -- TZ not visible in Team view though - Issue pending closure until then.

I am not able to verify this because of https://github.com/appirio-tech/connect-app/issues/3437
