### ISSUE TITLE
Some Projects missing in Copilot's All Projects view

### ISSUE THREAD

**Issue by lakshmiathreya** [appirio-tech/connect-app#3401]
### Expected behavior
All Projects view should list all Projects as per User privilege. 

### Actual behavior
In v5, All Projects listing even misses some Projects that the User is a Copilot for.

### Steps to reproduce the problem
- Login as a Copilot user lakshmiacopilot to https://connect-test01.topcoder-dev.com
- View All Projects Listing - Project "LA-Test" is missing 
- Load the Project with Direct url - the Project page is seen https://connect-test01.topcoder-dev.com/projects/8136
- Viewing the Project via v4 Connect shows that lakshmiacopilot is listed as Copilot for this project

### Screenshot/screencast
<img width="1471" alt="Screenshot 2019-12-10 at 9 14 16 AM" src="https://user-images.githubusercontent.com/51733042/70493877-4435a280-1b2f-11ea-8135-ac3ccc47089f.png">
<img width="1477" alt="Screenshot 2019-12-10 at 8 33 41 AM" src="https://user-images.githubusercontent.com/51733042/70493899-56afdc00-1b2f-11ea-99f4-82aab9f441df.png">
<img width="1478" alt="Screenshot 2019-12-10 at 8 32 46 AM" src="https://user-images.githubusercontent.com/51733042/70493937-7941f500-1b2f-11ea-9752-31739f179848.png">

--

#### Environment
- OS:
- Browser (w/version):
- User role (client, copilot or manager):
- Account used:

**Comment by lakshmiathreya** [comment]
cc @nithyaasworld

**Comment by RishiRajSahu** [comment]
@lakshmiathreya @nithyaasworld not seeing the project on listing page even being part of it could be because of Elastic search indexing issue, try changing some data of project on scope tab (for example - description, name, ref-code etc.) which will trigger the reindexing of project and it should show up on listing page after refresh.

**Comment by maxceem** [comment]
I agree with @RishiRajSahu that most likely this project hasn't been properly updated in ES. Though triggering updating project details in ES most likely wouldn't fix this issue. As when we update the details we still keep the current list of members and invites, thus copilot would be still not a member of the project after reindexing and still wouldn't have access to it and wouldn't be listed in the list.

The copilot still can see the project by the direct link because when we load one project page, the permissions are checked using data from the DB not ES. And on the listing page, permissions are checked using data in ES.

@RishiRajSahu could you please have a look on the log of the `project-processor-es`? Are there any recent errors? As it looks like we have several issues connected with errors during indexing data in ES.

**Comment by vikasrohit** [comment]
Similar to #3402 , reindexing fixed the issue and the same [rationale](https://github.com/appirio-tech/connect-app/issues/3402#issuecomment-564928773) applies here to fix such issues in future.
