### ISSUE TITLE
[$80] Topcoder member Invite dropdown is not showing suggestion list for the Account Manager

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/connect-app#3424]
1. Login as Account Manager to the Test Environment
2. Join any project
3. Click on 'Manage' to open the Topcoder Member invite popup
4. In the 'Enter one or more handles', start typing a handle name and observe

Actual:
Its not showing the suggestion list.

Note: This works if logged in as Admin user

![image](https://user-images.githubusercontent.com/5114190/70762216-d4652900-1d75-11ea-981f-08348614adba.png)
![image](https://user-images.githubusercontent.com/5114190/70762243-ecd54380-1d75-11ea-8a51-b4aa2899cf91.png)

**Comment by nithyaasworld** [comment]
cc: @lakshmiathreya @maxceem

**Comment by nithyaasworld** [comment]
This issue is also noted for Copilot Manager role. But NOT for Manager role.

**Comment by vikasrohit** [comment]
@maxceem is it because of security constraints imposed by member api on `_suggest` endpoint?

**Comment by maxceem** [comment]
Reference https://github.com/appirio-tech/connect-app/issues/3225

I will check what is the reason for Copilot Manager.

**Comment by vikasrohit** [comment]
Moving to next release.
@maxceem I think in #3225 we stopped suggestion calls for customers because members api does not support for non topcoder roles for security purposes. However, `Account Manager` role is a topcoder role so it should have the suggestions. What I think is that, we might have only `Manager` role is whitelist of `suggest` endpoint. @RishiRajSahu can you please check and coordinate with @maxceem to close this issue?

**Comment by maxceem** [comment]
@vikasrohit at the moment in most places in the code `isCustomer` is defined as a user who doesn't have any powerful roles like `ROLE_CONNECT_COPILOT, ROLE_CONNECT_MANAGER, ROLE_ADMINISTRATOR, ROLE_CONNECT_ADMIN`, see https://github.com/appirio-tech/connect-app/blob/dev/src/projects/detail/containers/TeamManagementContainer.jsx#L232

So I guess this should be a wider task, to update all the `powerRoles` lists with new roles so the current logic works properly. Until we refactor permissions as per https://github.com/appirio-tech/connect-app/issues/2841

**Comment by vikasrohit** [comment]
Okay. I guess event after the changes in front end, we might need to add the role in member api to allow calling suggest endpoint for `Account Manager` role.

**Comment by maxceem** [comment]
@vikasrohit we have the next Topcoder roles https://github.com/appirio-tech/connect-app/blob/feature/bulk-milestone-updates/src/config/constants.js#L645-L657

Should all of them be able to get suggestions? So only customer users (without any roles except `Topcoder User` role) wouldn't get suggestions.

I guess we should sync this with Member Service.

**Comment by vikasrohit** [comment]
> Should all of them be able to get suggestions? So only customer users (without any roles except Topcoder User role) wouldn't get suggestions.

Yes, ideally. However, we can not do any change in member service for this. If the way we are using member service right now to suggest the endpoint does not allow some of the topcoder roles, we have to analyze the situation or if we are using m2m calls (which I think is not the case) to suggest endpoint via project api, we can add the new roles to our endpoint.

**Comment by maxceem** [comment]
Sum up:

There are 2 parts in this issue:
1. Find out which users can get suggestions from the Member Service suggestion endpoint
2. Update connect app code so that we show suggestions for users with all the roles, who can see them.

### 1. Find out which users can get suggestions.

Complete this table be following the guide below the table.

| Topcoder Role (User handle) | Token Roles | Can get ✅or ❌|
|--|--|--|
| `administrator` (`max.admin`) | ![image](https://user-images.githubusercontent.com/146016/79328771-449bdb00-7f1f-11ea-8bb1-9882f12f46b2.png) | ✅| 
| `Connect Admin` (`TCConAdmin`) | ![image](https://user-images.githubusercontent.com/146016/79328634-0acad480-7f1f-11ea-84b2-36002f961dbc.png) | ✅| 
| `Connect Manager` (`TCConManager`) | ![image](https://user-images.githubusercontent.com/146016/79326642-dd305c00-7f1b-11ea-9ae1-fb8736577a3f.png) | ✅ |
| `Connect Account Manager` (`TCConAccountMgr`) | ![image](https://user-images.githubusercontent.com/146016/79326975-60ea4880-7f1c-11ea-8899-1f484a0dc824.png) | ✅ |
| `Connect Copilot` (`TCConnCopilot`) | ![image](https://user-images.githubusercontent.com/146016/79326466-8c206800-7f1b-11ea-9191-05c00f5f240f.png) | ❌|
| `Topcoder User` (`pshah_customer`) | ![image](https://user-images.githubusercontent.com/146016/79327342-f685d800-7f1c-11ea-8eac-24c1ffa75d94.png) | ❌|
| `Business Development Representative` (`pshahbusdevrep`) | ? | ? |
| `Presales` (`pshahpresales`) | ? | ?  |
| `Account Executive` (`pshahaccex`) | ? | ? |
| `Program Manager` (`pshahprogmanag`) | ? | ?  |
| `Solution Architect` (`pshahsolarch`) | ? | ? |
| `Project Manager` (`pshahprojmanag`) | ? | ? |
| `Copilot Manager` (`pshahcopmanag`) | ? | ? |

#### How to fill the table

1. Login with user to https://connect.topcoder-dev.com/
2. Get user token from the Network tab:

     ![image](https://user-images.githubusercontent.com/146016/79327618-72802000-7f1d-11ea-9599-a40fce0de2b4.png)
3. Verify that token has correct role by pasting token to https://jwt.io/ and make a screenshot for proof

4. Run the next request with user token:
    ```sh
    curl 'https://api.topcoder-dev.com/v3/members/_suggest/psha' -H 'authorization: Bearer <USER_TOKEN>'
     ```
     - if response is `You don't have permission to perform this operation`, it means user don't have permission to this endpoint, so put ❌in the table
     - if the response returns a list of user like, then user has permission, so put ✅, see example output
        ![image](https://user-images.githubusercontent.com/146016/79328011-110c8100-7f1e-11ea-9944-bff3ad8851f0.png)
    - if response is different from 2 situations above, probably the token is expired so you have to get a new one, or it was not copied/pasted properly, try again, or let me know

### 2. Update Connect App code to show suggestions to all user roles who can get them

- add a new permission `SEE_MEMBER_SUGGESTIONS` as per https://github.com/appirio-tech/connect-app/blob/dev/docs/permissions-guide/permissions-guide.md
- and after use it to determine when to request suggestions and when don't request suggestions

   ![image](https://user-images.githubusercontent.com/146016/79329028-b1af7080-7f1f-11ea-8194-3558d54e1ab2.png)

- note: we shouldn't send a request for suggestions if user doesn't have permissions

**Comment by Giri-Suman** [comment]
@bug-bash-helper assign

**Comment by Giri-Suman** [comment]
@bug-bash-helper unassign

**Comment by Giri-Suman** [comment]
@bug-bash-helper assign

**Comment by maxceem** [comment]
This issue is now open for pickup.

**Comment by romitgithub** [comment]
PLease assign

**Comment by romitgithub** [comment]
@bug_bash_helper assign

**Comment by romitgithub** [comment]
@bug-bash-helper assign

**Comment by romitgithub** [comment]
@maxceem how to edit this table?

**Comment by maxceem** [comment]
@romitgithub I've added the table to your comment above.

**Comment by romitgithub** [comment]
@bug-bash-helper https://github.com/appirio-tech/connect-app/issues/3424 is ready for review

**Comment by maxceem** [comment]
@romitgithub the review is ready, please have a look https://github.com/appirio-tech/connect-app/pull/3924#pullrequestreview-395983496

**Comment by romitgithub** [comment]
@maxceem Done with changes and pushed the code. Please check.

Also, wanted to ask if the prize money could be increased for this because this one involved a manual task of updating the table as well.

**Comment by romitgithub** [comment]
@bug-bash-helper This issue is ready for review

**Comment by maxceem** [comment]
> Also, wanted to ask if the prize money could be increased for this because this one involved a manual task of updating the table as well.

Sorry, I think I cannot increase the prize money in this case as the task to manually update the table with permissions was included from the beginning and the prize was set including the work for filling the table.

**Comment by codejamtc** [comment]
Fixed 🆗 https://monosnap.com/file/xgkT2GThrWhqDi888V74jUfQpCCsCi

**Comment by lakshmiathreya** [comment]
Verified Invite Dropdown in Prod for Account Manager account - showing suggestion list for Customer and Topcoder team invites.
