### ISSUE TITLE
Invite disappear when if we invite on Dashboard and switch to other section

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3431]
### Expected behavior
Invite should be still shown.

### Actual behavior
Invite disappeared.

### Steps to reproduce the problem
- Open Dashboard page of any project, for example https://connect.topcoder-dev.com/projects/8574
- Invite any user using Team of Topcoder section.
- Switch to **Messages** page of the project.
- Obser that just invited user disappeared.

### Screenshot/screencast
Demo video https://monosnap.com/file/RdzWbJXTGAVxgNYW9UxdDlVA0PcqcL

**Comment by maxceem** [comment]
Fixed via https://github.com/appirio-tech/connect-app/commit/3acd97e14a58cbd6ae90cd306aeedfe0d4a1f5e9 and pushed to DEV.

**Comment by nithyaasworld** [comment]
This issue is not reproducible in Dev environment. However its reproducible in Test environment.

@maxceem Can we still close this?

**Comment by nithyaasworld** [comment]
cc: @lakshmiathreya

**Comment by maxceem** [comment]
@nithyaasworld I cannot reproduce it in TEST env. If you still could do this, could you please share a video, user, and project you've tested with.

If this can be reproduced on TEST, we have to fix it before closing.

**Comment by nithyaasworld** [comment]
@maxceem 

Please let me know if the below info did not help. I am marking this as 'QA Fail' for the below reason. But if you think, the below issue has to be addressed in a new ticket, please let me know, I will raise a new tickets instead of marking this one with 'QA Fail'


I added the users: nithyaasworld, tonyj and mess to the project https://connect-test01.topcoder-dev.com/projects/8588 as topcoder members. Then I logged into nithyaasworld from another browser window and updated the timezone.
Then again when I checked back in the first window, the newly added users nithyaasworld, tonyj and mess were missing. When I tried to add them back, I was able to add only nithyaasworld. When trying to add tonyj or mess, it says they are already part of the team, but it's not showing them.

Please check this video:
missing members.zip

In this video, observe that at the time 1:11, there are 3 members in the Team section of the left panel.
And observe that at the time 1:57, there are only 2 members in the Team section.

**Comment by nithyaasworld** [comment]
Another way to reproduce:

1. Being logged in as Admin user, Go to https://connect-test01.topcoder-dev.com/projects/8596
2. Try to invite Copilot user topcoderconnect+Copilot@gmail.com to the project
3. Observe that it says this user is already invited but this user's name is not displayed under the Team

![image](https://user-images.githubusercontent.com/5114190/71057999-64471080-2184-11ea-8ab0-e458b3056659.png)

**Comment by maxceem** [comment]
Regarding the issue pointed in this comment https://github.com/appirio-tech/connect-app/issues/3431#issuecomment-566868893. This was 99% the issue with ES/DB V4/V5 inconsistency. 

Also, I can see invitations for Tony and Mess on the list:

![image](https://user-images.githubusercontent.com/146016/71058396-af6c1e00-219a-11ea-8cfc-7a2e81c05a58.png)

Regarding 
> Another way to reproduce:

The copilot is already invited, it can be see if we click **Show All** to list all the members and invites:

![image](https://user-images.githubusercontent.com/146016/71058128-c4947d00-2199-11ea-9545-560da7ae7181.png)

Sum up:
- if this issue could be reproduced for a new project, than it's valid
- we shouldn't use existent project on TEST/DEV to reproduce this issue, as any existent project may not have inconsistencies which has been brought up by testing 2 envs together with one DB. I would ask to reindex project on DEV so we would have all existent projects fixed, and will let you know, but so far we have to create new projects.

**Comment by nithyaasworld** [comment]
Verified that issue is not reproducible in Dev. Verified by creating a new project.

**Comment by vikasrohit** [comment]
@nithyaasworld can we close this?
