### ISSUE TITLE
Project creation notifications seem to have been sent multiple times

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/connect-app#3454]
1. Login as Account Manager or BDR in Dev Environment
ex: topcoderconnect+accountmanager@gmail.com
topcoderconnect+bdr@gmail.com
pw for both the users: appirio123

2. Check the Notifications received

Actual:
Project creation notifications are received multiple times. 

Note: This is not reproducible for newly created projects. Not sure why some of the notifications are repeated several times.

![image](https://user-images.githubusercontent.com/5114190/71211111-73d56f00-22d4-11ea-8992-2533f4cac0db.png)

**Comment by nithyaasworld** [comment]
cc: @lakshmiathreya @maxceem @vikasrohit

**Comment by maxceem** [comment]
The project which has this issue has id `6` so it was created locally while using Bus API from DEV. Also, I can see that each notification has different timestamps:

![image](https://user-images.githubusercontent.com/146016/71338350-7e209300-258a-11ea-87bb-b5f4a4d64e42.png)

Locally we can create and remove the same project several times, and get a notification each time.

So this issue is safe to close, it appears because of the mixing of Local and Dev environments.

**Comment by vikasrohit** [comment]
Agreed with @maxceem. The project id is very low in the value, which suggests that this notification refers to a project which was created somewhere on a developer machine. If it was created on dev env, it would have project id in the range of 10k+.

@nithyaasworld @lakshmiathreya it is safe to close. Let me know if you still have any query.

**Comment by vikasrohit** [comment]
Closing. Please feel free to create new issues for any regression.
