### ISSUE TITLE
Incorrect time difference for New_York timezone.

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#3457]
### Expected behavior
Time difference should be UTC-5 for New_york

### Actual behavior
Time difference after setting timezone to New_York under profile giving difference of UTC-4 under team's section

### Steps to reproduce the problem
- Open Connect's User Profile page.
- set timezone to New_York.
- Check your user details under Team's section of any project you are part of.

### Screenshot/screencast
<img width="645" alt="Screen Shot 2019-12-24 at 7 52 48 AM" src="https://user-images.githubusercontent.com/11248478/71389451-6d236080-2622-11ea-8181-46c145e02548.png">

<img width="267" alt="Screen Shot 2019-12-24 at 7 52 32 AM" src="https://user-images.githubusercontent.com/11248478/71389459-7a404f80-2622-11ea-9597-9ac5a066c33c.png">

--

#### Environment
- OS:any
- Browser (w/version):any
- User role (client, copilot or manager):any
- Account used: any

**Comment by RishiRajSahu** [comment]
FYI - @maxceem

**Comment by maxceem** [comment]
The issue is caused by the fact, that New Your supports "Daylight Saving Time", so the timezone offset vary during the year from GMT-4 to GMT-5:
![image](https://user-images.githubusercontent.com/146016/71389937-4886b300-2639-11ea-9a65-8217c5275100.png)

While we are using static list of timezones with respective time shifts:
![image](https://user-images.githubusercontent.com/146016/71389967-681ddb80-2639-11ea-8dfe-56d0d871a242.png)

So we have to use a smarter way to calculate the current time in timezones. We have to use [moment-timezone](https://www.npmjs.com/package/moment-timezone) extension for `moment` library which we already use.

The most tricky thing here is to validate somehow, that `moment-timezone` can understand our list of timezones https://github.com/appirio-tech/react-components/blob/feature/connectv2/constants/timezones.js. So we don't come up with the situation, when for some timezones in our list `moment-timezone` cannot properly calculate the local time.

@RishiRajSahu would you like to handle it faster via F2F, or we can include it in CF?

**Comment by RishiRajSahu** [comment]
@maxceem can we add a new time_zone entry simply for quick solution - i.e. `New_york_DayLightSaving` ? then user can pick out of these two and will see correct time.

**Comment by maxceem** [comment]
@RishiRajSahu Yes, we can do that. I've checked it out, Member Service let us save such a value.

More than that, I guess what we can do for the quick fix is change the gmtOffset for the current `New_York` record. So it would just work automatically for all the users, and we don't have to ask them to change timezone back.

**Comment by RishiRajSahu** [comment]
@maxceem yep I thought of that as well, but we will have to revert it later after winters, or am I missing something ?

**Comment by maxceem** [comment]
> @maxceem yep I thought of that as well, but we will have to revert it later after winters, or am I missing something ?

I think before that we have to implement the correct solution which would take into account "Daylight Saving Time" and don't use that static config at all.

**Comment by RishiRajSahu** [comment]
@maxceem Okay, I'm good with either because we have to keep track of things we do now to be fixed, Let's create an issue with the requirements for that and run a F2F so that with next connect release that's pushed to PROD and meanwhile just update the value to make it 5 hours, I think that would be `18000`.

**Comment by maxceem** [comment]
Created a follow-up issue https://github.com/appirio-tech/connect-app/issues/3458

**Comment by maxceem** [comment]
Hotfix is done. Tested locally.
DEV https://github.com/appirio-tech/connect-app/pull/3460
PROD https://github.com/appirio-tech/connect-app/pull/3461

**Comment by RishiRajSahu** [comment]
Patched to prod. Working Fine.
