### ISSUE TITLE
Project Estimate Total is mentioned as 0 Days when Estimate is of 16 days

### ISSUE THREAD

**Issue by kalindipandey** [appirio-tech/connect-app#3614]
### Expected behavior
Project Estimate should be correct

### Actual behavior
Project estimate is mismatched 

### Steps to reproduce the problem
Open the application
1. Login as copilot Role
2. Click on "view Solutions" in "On Demand" option
3. Click on Select in Buy Capacity Option
4. Project name - Testing; Description: testing
5. Click Next
6. Select Design and Quality Assurance options
7. Click Next
8. Click Next
9.  Click "Save My Project"
10. Click on "Go To Project Dashboard"
11. Check "Total" which is 0 Days 

### Screenshot/screencast
![Bug7](https://user-images.githubusercontent.com/46349625/73368929-d52b2d80-42d7-11ea-8f95-77f0d4690265.jpg)

--

#### Environment
- OS: micromax LI351568W ; Windows10
- Browser (w/version): Chrome Version 79.0.3945.130
- User role (client, copilot or manager): copilot
- Account used:  topcoderconnect+Copilot@gmail.com

**Comment by kalindipandey** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P1

**Comment by SathyaJayabal** [comment]
@kalindipandey , accepted

**Comment by nithyaasworld** [comment]
@maxceem I am able to reproduce the issue stated in this ticket in the updated Catalog UI as well, by selecting the Talent as a Service option. Kindly check.

**Comment by vikasrohit** [comment]
@nithyaasworld couple of things:
1. Timeline and cost estimator is enabled only in dev, so you can ignore any issue related to the estimator until you see that in prod.
2. Phase's time line and project estimate timeline are not going to be linked even when enable the estimator on production because estimator just estimates on project creation while phases are actual delivery plan and they might differ.

**Comment by vikasrohit** [comment]
Issue can be closed.
