### ISSUE TITLE
[$40] In Safari Browser , clicking on Ondemand project skips one page and takes user Selection page

### ISSUE THREAD

**Issue by akultalwar89** [appirio-tech/connect-app#3666]
Expected behavior
Skipping page is not a good behavior in compare to other browser like chrome.

Actual behavior
it skips the page

Steps to reproduce the problem
Create a new project
https://connect.topcoder-dev.com/new-project/
click on On demand view solution - it skips the selection page

Environment
OS: Macbook Air 10.15.2
Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit) also Safari browser
User role (client, copilot or manager): topcoderconnect+CopilotManager@gmail.com
Account used: topcoderconnect+CopilotManager@gmail.com

Screen shot
![Screen Shot 2020-01-30 at 10 03 33 PM](https://user-images.githubusercontent.com/57220292/73469673-c06c9980-43ac-11ea-85f7-f86051b4be51.png)

**Comment by akultalwar89** [comment]
NOT ABLE TO ADD VIDEO, 
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P3

**Comment by SathyaJayabal** [comment]
@akultalwar89 , accepted

**Comment by lakshmiathreya** [comment]
This issue continues to be seen with TAAS now ...

**Comment by vikasrohit** [comment]
It was a feature where we skip the the project template selection page when the number of templates under the category is 1. This was to save one user click. However, recently we removed that feature as well for the sake of consistency but somehow that change is overridden.

**Comment by maxceem** [comment]
@vikasrohit do I understand it correctly when we click "Talent as a Service" category 
![image](https://user-images.githubusercontent.com/146016/76186031-0b7b9700-620c-11ea-883c-1b8719fe64bd.png)

we should see a list of templates to choose, same as when we click "Solution", but there would be only one template to choose. Right?

**Comment by vikasrohit** [comment]
Yes, that was the feature I guess we added very long time back. I discussed with product managers while discussing new UI of the catalog and we ended up in removing that logic now and instead start showing the wizard steps as usual we are showing in case where number of templates for a category is greater than 1.
@maxceem do you think if keep this configuration in template itself, would that make the logic more complex?

**Comment by maxceem** [comment]
> @maxceem do you think if keep this configuration in template itself, would that make the logic more complex?

If we don't have plans to use such an option in the near future, I'm inclined towards removing this option rather than having a flag to keep less logic which is not in active use.

**Comment by vikasrohit** [comment]
I can not estimate any thing about its usage, but if that is not tricky to implement go with it, other wise remove the logic for now. One more reason to keep that functionality with flag is that if we remove it today, and then some other day in future we have to include it again, bringing that logic back might be more tricky at that time.

**Comment by maxceem** [comment]
Ok. Would you like this to be determined by the **Project Template** or **Category**?
- **Project Template** - we set flag to the project template, so in case such project template is the only one in a category, then we automatically open template form when choosing a category
- **Category** -  we set flag to the category, so in case such a category has a single template, the template should be chosen automatically when we choose the category?

**Comment by vikasrohit** [comment]
I think having it on `Category` makes more sense to me.

**Comment by maxceem** [comment]
Sum up:
- Currently, if category has only one Project Template inside, like "Talent as a Service", when we choose such a category we don't show the list of Project Templates, but directly open form from the single Project Template. Check this on the next page https://connect.topcoder-dev.com/new-project by selecting "Talent as a Service". While if on the same page you click "Solutions" you would see the list of project template to select from, because we have several project templates.
- We want to keep this behavior but we want to control it.
  - We should still proceed to single project template when we click category, but only if flag `metadata.autoProceedToSingleProjectTemplate` inside category is set to `true`
   - If it set to `false`, then we should show the list of project templates, even if there is only one project template inside the category.
- For demo, we set `metadata.autoProceedToSingleProjectTemplate === false` for the "Talent as a service" category, so we expect after this task is done, when we click "talent as a service" category to see a list of Project Templates - there would be only one Project Template.

![image](https://user-images.githubusercontent.com/146016/76383828-08adad00-6398-11ea-9e39-d1a4ddd4be33.png)

![image](https://user-images.githubusercontent.com/146016/76383892-3c88d280-6398-11ea-9544-4522c14830a4.png)

**Comment by maxceem** [comment]
This issue is now open for pickup.

**Comment by rashmi73** [comment]
@bug-bash-helper assign

**Comment by rashmi73** [comment]
@bug-bash-helper https://github.com/appirio-tech/connect-app/pull/3782 is ready for review

**Comment by maxceem** [comment]
@rashmi73 provided fix causes some error, please have a look https://github.com/appirio-tech/connect-app/pull/3782#pullrequestreview-373279326

**Comment by rashmi73** [comment]
@bug-bash-helper https://github.com/appirio-tech/connect-app/pull/3782 is ready for review

**Comment by maxceem** [comment]
@rashmi73 please, check feedback https://github.com/appirio-tech/connect-app/pull/3782#pullrequestreview-374215120

**Comment by rashmi73** [comment]
@bug-bash-helper #3782 is ready for review

**Comment by drasticdpk** [comment]
Verified on dev env by setting **autoProceedToSingleProjectTemplate** true and false on https://connect.topcoder-dev.com/metadata/projectTypes/talent-as-a-service
[3666_verification.mp4.zip](https://github.com/appirio-tech/connect-app/files/4337851/3666_verification.mp4.zip)

**Comment by codejamtc** [comment]
@maxceem I need help to test this one too. Can't see  `autoProceedToSingleProjectTemplate`  https://connect.topcoder.com/metadata/projectTemplates/70

**Comment by maxceem** [comment]
We should set to the project type https://connect.topcoder-dev.com/metadata/projectTypes/talent-as-a-service

At the moment it's not set, so when we click "Talent as s Service" the list with one template is opened instead of directly opening template. We don't have any example where we currently set it.

**Comment by vikasrohit** [comment]
@codejamtc it is working fine on production, I have doubled checked it.
