### ISSUE TITLE
[$100] Extra / characters after message update

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3743]
Carried forward from https://github.com/appirio-tech/connect-app/issues/3456#issuecomment-586017601

> The main issue of line-disappearing-while-editing is gone. But seeing the below issue. Please confirm if this is okay or should we improve it.
when "Bold, italic, underline, unordered" items are wrapped inside a code, it produces extra slashes on every save. Video:
[extra slash.zip](https://github.com/appirio-tech/connect-app/files/4201882/extra.slash.zip)

**Comment by vikasrohit** [comment]
@maxceem potential candidate for CF.

**Comment by sanju-singh** [comment]
@bug-bash-helper assign

**Comment by sanju-singh** [comment]
What is the expected output for this?
Should it produce only one slash irrespective of edits, or no slash at all? 
Should the special characters for bold, italic, underscore be shown inside code block in preview mode as shown now just after creating?

**Comment by maxceem** [comment]
> What is the expected output for this?

no slash at all

> Should the special characters for bold, italic, underscore be shown inside code block in preview mode as shown now just after creating?

Can we always show it with styles like this?

   ![image](https://user-images.githubusercontent.com/146016/76286642-a7c19e80-62dd-11ea-93b8-504d6ab2810c.png)

**Comment by sanju-singh** [comment]
Markdown doesn't support styling inside code-block, only language specific styling can be done, that's why even in edit mode inside code-block we are disabling the styling icons, what best we can do is to remove those styling on save and show these text as simple text without special character, after all those styling character inside code-block doesn't help the user, and user also won't be interested in styling inside code-block.

**Comment by maxceem** [comment]
So the message would look like this after saving, right?

![image](https://user-images.githubusercontent.com/146016/76298836-0c3c2800-62f5-11ea-9be3-fc0616a7743e.png)

That's ok, let's go this way.

**Comment by sanju-singh** [comment]
that is also possible, I was saying, let's drop those special character as well, so it will display as

Bold, italic, underline, unordered items are wrapped inside a code

no **, __ or ++.

**Comment by maxceem** [comment]
I'm afraid if we just drop them, then if someone enters code which would contain them, we would loose it. So I think it's better to keep them.

**Comment by sanju-singh** [comment]
No, we are adding that in the code(those special character), to construct the content with markdown syntax, from the editor we get the style, i.e whether its a bold, italic or underscore. So, for code that will come as content not style, and will work without a problem.

**Comment by maxceem** [comment]
Ok, if we still can enter text **bold**, _itcalic_, +underline+ inside **code** bock, then yes, we can remove adding **, __ or ++ when we make the text bold, italic or underline using editor buttons.

**Comment by sanju-singh** [comment]
@bug-bash-helper https://github.com/appirio-tech/connect-app/pull/3760 is ready for review

**Comment by maxceem** [comment]
@sanju-singh there is some situation when escape character is still added, see https://github.com/appirio-tech/connect-app/pull/3760#pullrequestreview-373265672

**Comment by sanju-singh** [comment]
@bug-bash-helper #3760 is ready for review

**Comment by satkanhub** [comment]
Issue still exists. Video for your reference.
[3743.zip](https://github.com/appirio-tech/connect-app/files/4326407/3743.zip)

**Comment by sanju-singh** [comment]
@satkanhub , I think you haven't taken my changes provided in the pull request. I am able to see it working in two different machines and all the browsers.

**Comment by maxceem** [comment]
Sorry @sanju-singh found an issue in the latest implementation so I had to revert the pull request https://github.com/appirio-tech/connect-app/pull/3796. Please, create a new one.

Everything works good if we enter text using buttons to style the text:

![image](https://user-images.githubusercontent.com/146016/76612445-4dcc0d80-6557-11ea-8d10-20fcc4ffbbb7.png)

Then after saving it would look like this:

![image](https://user-images.githubusercontent.com/146016/76612493-663c2800-6557-11ea-9487-15fb280d102e.png)

- all the styles are kept except styles inside the `CODE` block because the styling features should be compatible with Markdown format, and in Markdown format, we generally cannot style text inside the `CODE` block

But if we enter the same using markdown format which we support:

![image](https://user-images.githubusercontent.com/146016/76612680-c0d58400-6557-11ea-8c0e-305cf3b8ad9e.png)

we would get the next result:

![image](https://user-images.githubusercontent.com/146016/76612912-26297500-6558-11ea-98ab-671251ccff4b.png)

So markdown format is not applied not only inside the `CODE` block, but also inside other blocks.

**Comment by maxceem** [comment]
Also, there were lint issues in the PR:

![image](https://user-images.githubusercontent.com/146016/76613238-ba93d780-6558-11ea-9e22-f456e5a59126.png)

**Comment by sanju-singh** [comment]
@maxceem , I also reverted my changes and checked the given scenario, looks like it was not working earlier too, i.e styling through character ex: \*\*bold\*\* (this is not converting to **bold**) earlier too.
could you confirm that?

**Comment by maxceem** [comment]
Ah, you are right @sanju-singh. Sorry, I was sure we support it. Everything works great then, thanks!

**Comment by drasticdpk** [comment]
Verified on dev env.
[3743_Verification.mp4.zip](https://github.com/appirio-tech/connect-app/files/4337317/3743_Verification.mp4.zip)

**Comment by coderhacker** [comment]
https://connect.topcoder.com/projects/14178/messages/48053
CustomerUser/appirio123
Verified on prod, working as expected.

[3743-prod.zip](https://github.com/appirio-tech/connect-app/files/4421675/3743-prod.zip)
