### ISSUE TITLE
Enable user level reporting on project listing page

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3862]
Just like project level reports, we should be able to see the reports link for user level reports.

**Comment by drasticdpk** [comment]
verified on prod mode :
![image](https://user-images.githubusercontent.com/25297859/78903455-ded0ce80-7a9a-11ea-9507-f3dd45dac79d.png)
Note: When clicking on no. of users, it gives `No Drill Available`. Please confirm if it is not our expected behavior. cc @vikasrohit 
![image](https://user-images.githubusercontent.com/25297859/78903674-37a06700-7a9b-11ea-80cc-8aabde3a5a9d.png)
.

**Comment by vikasrohit** [comment]
That should be okay @drasticdpk . But still, we would try to disable the links.

**Comment by lakshmiathreya** [comment]
@vikasrohit can we move this Issue to 2.8 milestone?

**Comment by lakshmiathreya** [comment]
cc @drasticdpk

**Comment by vikasrohit** [comment]
> @vikasrohit can we move this Issue to 2.8 milestone?

We can, but didn't understand the rationale behind that. If you are trying to avoid the confusion of release vs milestone mismatch, only solution I can see is to have dummy or empty releases when certain issue is fixed in another repo and we don't have to make a release of the reporting repo.
