### ISSUE TITLE
No point of having a "Save Changes" button in QA Iteration > Specification tab

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3890]
### Expected behavior
Should remove the "Save Changes" button from QA Iteration

### Actual behavior
No point of having a "Save Changes" button in QA Iteration > Specification tab

### Steps to reproduce the problem

- Login as Manager
- Select a project from the list {https://connect.topcoder-dev.com/projects/9074}
- Go to 'Dashboard' > Expand a phase (QA Iteration)
- Go to 'Specification' tab
- Upload a file {CSVFile_119kb (1).csv} with "Restrict access to" > TCConnCopilot
- Check the "Save Changes" button, it never enables

### Screenshot/screencast

![image](https://user-images.githubusercontent.com/42398485/79057929-829db400-7c2c-11ea-9c77-afd5da95ad8f.png)

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** FF 75 | Chrome 80.0.3987.163
**- User role (client, copilot or manager):** Manager
**- Account used:**  `topcoderconnect+Manager@gmail.com`

**Comment by vikasrohit** [comment]
Thanks @codejamtc however, I think it is okay to have that button because this form keeps on changing frequently and there can be another form element in the form which needs the Save button and I think adding a logic to handle this specific case would make logic bit complicated with not much benefits.
