### ISSUE TITLE
Project creation: disable top navigation when in Project creation

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#39]
As shown in the design

**Comment by vikasrohit** [comment]
@parthshah we two options for this, one is to have redux state for layout and another is to just create the new topbar  (with only connect logo and wizard title) and position it absolutely on topbar. Which one you think is better?

**Comment by parthshah** [comment]
@fnisen I understand the need to remove any distractions but removing a primary nav interaction seems a bit much. 

@vikasrohit if we absolutely have to do this, I would alter the properties on the nav component to show hide nav links. I believe this would impact topcoder-app as well?

**Comment by vikasrohit** [comment]
Agree @parthshah about removing primary nav.

For hiding nav links in nav component, I am bit reluctant to do that as it would require some if-elses in the component and further, we have to pass the data (title as of now) from a child component(projects/create/CreateView) to its parent component(Topbar).

**Comment by fnisen** [comment]
@parthshah, @vikasrohit it's designed to look like a page takeover modal... that's why there's an "x" in the corner. I would not hide links... we either need to hide the entire nav or not do this.

Let me talk to Vic to get a more explicit mockup for the design or see if there's another option.

**Comment by mahestro** [comment]
I think I understand the why of removing the nav temporary. As a new client, I think it's less distracting, allowing him/her to focus on the conversion (since he probably doesn't have anything else to do in the page at that point).

As a PM / dailyuser it might be useful to have the nav.

Either case, the header has changed. Now it's one-level navigation. I think just moving the x/close to the top for the project creation would help here, maybe?

My 5 non requested cents :) ...

![nav2](https://cloud.githubusercontent.com/assets/729632/18428581/0973e572-78cf-11e6-9ebb-548659f5cc96.png)

**Comment by fnisen** [comment]
All right, chatted with Vic. @mahestro your intuition is correct. This is supposed to be a page-takeover modal. User opens it, focuses on the action, closes it. It's analogous to registration in InVision: https://projects.invisionapp.com/d/signup?redir=. The way to access the nav is to close the modal. So, we're not trying to change options on the nav, but hide it entirely.

The way you have the design is a good option: effectively the nav is not there--it's replaced with a heading and the close option. However, it may be harder implement because in a functional sense, we're just redoing the nav options. So, we could also have a design that fully "covers" the nav. Would you want to mock that up quickly? 

Also, we should follow this same approach with the feature picker, as well.

**Comment by mahestro** [comment]
Yes, no problem. Glad you liked the suggestion.

Didn't follow the final part though. Do you want to keep the x/close icon in the original position, which was inside the the white background of the wizard content?

**Comment by vic-appirio** [comment]
I'm good with either removing the top navigation altogether on the modal page, or keeping it as per design with the close "x" mark on the top right. It is up to you @vikasrohit which one would be easier. Assigning to @vikasrohit to continue working on this issue.

**Comment by vikasrohit** [comment]
@fnisen @vic-appirio  I have converted the create project page to a modal over the project listing page. This has allowed us to hide the top bar. This is the same approach we are following with feature picker. Right now wee don't have the header bar with connect logo and wizard title. However, if required, I can add that as well by creating a completely new component for rendering that header bar. IMO, it doesn't make sense to reuse the navigation bar here because it would just increase the complexity of the nav bar component.

cc: @mahestro @parthshah

**Comment by fnisen** [comment]
Thanks @vikasrohit. This implementation looks good.
