### ISSUE TITLE
Error when Customer Accepting / Decline an invitation

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3948]
### Expected behavior
Should not display an error

### Actual behavior
Error when Customer Accepting / Decline an invitation

The manager sends an invitation to TopConnCustomer and accepted by the TopConnCustomer. I can see another popup after pressing the join button for the first time, and then we press the join button again 404 error displayed

### Steps to reproduce the problem

- Login as Manager
- Select a project from the list {https://connect.topcoder-dev.com/projects/9149}
- Go to Client Team > Manage Invitations > Send invitation to `TopConnCustomer`
- Login as Customer
- Accept it

```
api.topcoder-dev.com/v5/projects/9138/:1 Failed to load resource: the server responded with a status of 403 ()
main.05e97bdb06757b545e47.js:130 Uncaught (in promise) Error: Request failed with status code 403
    at e.exports (main.05e97bdb06757b545e47.js:130)
    at e.exports (main.05e97bdb06757b545e47.js:223)
    at XMLHttpRequest.f.<computed> (main.05e97bdb06757b545e47.js:130)
api.topcoder-dev.com/v5/projects/9138/invites/2136:1 Failed to load resource: the server responded with a status of 404 ()
```

### Screenshot/screencast

[Accepting](https://monosnap.com/file/dQTLWGACoobAqFk0QgkGOKnB2ZhATs) / [Decline](https://monosnap.com/file/MArxvennHWq1filaVjvS18KnpyVEsI) an invitation ❌ 

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** FF 75 | Chrome 80.0.3987.163
**- User role (client, copilot or manager):** Manager
**- Account used:**  `TCConManager`

**Comment by vikasrohit** [comment]
@maxceem is this still happening?

**Comment by maxceem** [comment]
Yes, didn't cover it yet.

**Comment by sumitdaga** [comment]
@maxceem  few things here     

firstly when a customer is invited to a project and they try to open the project (upon which they can see the `Cancel`  `Join Project` modal )  ...the `LOAD_PROJECT` action fails ...i guess customer does not have permission and hence the api fails which does not happen for a `copilot_manager` for ex

next in the  [project reducer](https://github.com/appirio-tech/connect-app/blob/dev/src/projects/reducers/project.js)  the `project` and `nonDirtyProject` objects are inconsistently reset to seomtimes  `{}` and `null` and `{ invites: [], members: [] }`   which is causing an issue in this case because [accept_or_refuse_invite_success](https://github.com/appirio-tech/connect-app/blob/dev/src/projects/reducers/project.js#L248) action changes the `invites` array and in this case since `LOAD_PROJECT` failed it reset `project to null` which then throws an error

as a fix i have reset `project` and `nonProjectDirty` to a consistent  `{ invites: [], members: [] }` wherever it needs to be reset which has fixed this issue .... (i am not sure if it can cause an issue somewhere else)  

also this is why if customer accepts/declines invitation on dashboard there is no issue becasue `project` in reducer is `{ invites: [], members: [] }`  

PR #3953

**Comment by maxceem** [comment]
This is fixed in DEV and ready for QA.

#### QA Guidelines

1. Invite customer user and accept on dashboard page
2. Invite customer user and decline on dashboard page
3. Invite manager user and accept on dashboard page
4. Invite manager user and decline on dashboard page
5. Invite customer user and accept on project listing page
6. Invite customer user and decline on project listing page

**Comment by codejamtc** [comment]
@maxceem Fixed

**Test Users used:** `TopConnCustomer`, `TCConManager` and `pshah_manager`
**URL:** https://connect.topcoder-dev.com/projects/9149

- Invite customer user and accept on dashboard page: 🆗 
- Invite customer user and decline on dashboard page: 🆗 
- Invite customer user and accept on project listing page: 🆗 
- Invite customer user and decline on project listing page: 🆗 

- Invite manager user and accept on dashboard page: 🆗 
- Invite manager user and decline on dashboard page: 🆗 
- Invite manager user and accept on project listing page: 🆗 
- Invite manager user and decline on project listing page: 🆗 

https://monosnap.com/file/VBt6fcQfz7kRhSLymKFhdTNWlKws0W

**Comment by lakshmiathreya** [comment]
Verified on Prod - For Topcoder Team invites:

-- Accept, Decline, Join and Leave on Project Listing and Dashboard pages for - Connect Admin, Connect Account Manager, Manager users.

-- For Admin - verified Join and Leave on Dashboard page. For this user, Invite is not seen on Project listing Page.

- For Copilot Manager - invite to Topcoder team is not allowed for any role.
