### ISSUE TITLE
Direct and Salesforce Links are not visible to the Account Manager after joining to the project

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3959]
### Expected behavior
Should be visible and should be able to access them without an issue

### Actual behavior
Direct and Salesforce Links are not visible to the Account Manager after joining to the project

### Steps to reproduce the problem

- Login as Account Manager
- Select a project from the list {https://connect.topcoder-dev.com/projects/9173}
- Go to Topcoder Team > Join Project > Join Project button
- Check the Administration section Direct and Salesforce Links

### Screenshot/screencast

https://monosnap.com/file/8eOPc2rbeoFD9P3WkB52YxVmciA7Gz

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** FF 75 | Chrome 80.0.3987.163
**- User role (client, copilot or manager):** Account Manager
**- Account used:**  `TCConAccountMgr`

**Comment by maxceem** [comment]
@vikasrohit should we fix this?

**Comment by vikasrohit** [comment]
We can do this.

**Comment by maxceem** [comment]
- We should additionally allow seeing the salseforce and Direct link to the users with **Project Role** `account_manager`
- Instead of just adding another role to the existent code https://github.com/appirio-tech/connect-app/blob/dev/src/projects/detail/containers/ProjectInfoContainer.js#L428-L444 we have to rewrite this code using our new way of defining permissions. 
   - Add a new permission `VIEW_DIRECT_AND_SALSEFORCE_LINKS`. See [Permissions Guide](https://github.com/appirio-tech/connect-app/blob/dev/docs/permissions-guide/permissions-guide.md) on how to do it. Also, you may check similar issues to learn how to refactor code to use new permissions https://github.com/appirio-tech/connect-app/issues/3774 or https://github.com/appirio-tech/connect-app/issues/3858.
- If some `props` or variables are not in use anymore after this change, please, remove them as redundant code.

**Comment by lakshmiathreya** [comment]
This is fixed due to the Project Role change. All managers joining the Project are required to have an additional Connect Manager Role. 
<img width="1647" alt="Screenshot 2020-09-25 at 3 17 43 PM" src="https://user-images.githubusercontent.com/51733042/94253062-62e01b00-ff42-11ea-949f-1eb2cffeae75.png">

**Comment by lakshmiathreya** [comment]
The above screenshot shows Direct and Salesforce links for Account manager - handle - lakshmiaconacmg.

**Comment by lakshmiathreya** [comment]
Fixed as part of #4101
