### ISSUE TITLE
Don't allow users to change roles which they are now allowed

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3962]
### Expected behavior
Topcoder Team members can only switch to roles they are allowed to.

### Actual behavior
Any Topcoder Team can switch to any other role, even if member doesn't have permissions.

### Steps to reproduce the problem
- Use user with `Program Manager` Topcoder Role
- Try to Join to any project as a `Manager`. `Program Manager` couldn't join project as a `Manager` as per our requirements, see [Roles Matrix](https://htmlpreview.github.io/?https://github.com/topcoder-platform/tc-project-service/blob/feature/permissions/docs/permissions.html#roles-matrix)
- Now try to join as `Program Manager`. It would be successfull which is correct.
- Now open Topcoder Team dialog and switch role to `Manager` - it would be successfull, which is incorrect.
- As a result of this workflow, user with `Program Manager` Topcoder Roles who cannot Join project as a Manger, becomes a `Manager`.

### Screenshot/screencast
https://monosnap.com/file/SQ3nux0w9vKDsWcVYX6MSxW5Se5QKF

**Comment by maxceem** [comment]
This has been fixed in server-side by https://github.com/topcoder-platform/tc-project-service/pull/555.

Now if user tries to change to the role they are not allowed, the error message would be shown, see a demo video https://monosnap.com/file/ir4B3T1vl6Cov5rkVkYOAptAY7w23y

Now we have to fix the error message to directly indicate what is the problem as now it's to general:

https://files.slack.com/files-pri/T03R80JP7-F01253T1DHD/image.png

**Comment by codejamtc** [comment]
@maxceem Checked: 🆗 A User with `Program Manager` Topcoder Role tries to join to a project as `Manager` will get an error. And the same user joined to a project as `Program Manager` and tried to change the role to `Account Executive`, `Solution Architect`. `Manager` or `Project Manager` role will get an error.

He can either switch to `Connect Account Manager` role and back to `Program Manager` without an error.

https://monosnap.com/file/jYrkF5Wzf1D4eZT408iAhSVhOKmGgJ

**Comment by codejamtc** [comment]
## Complete test on 'Roles Matrix'.

![image](https://user-images.githubusercontent.com/42398485/81026018-55fd4680-8e3e-11ea-81a4-bf35645b2aa4.png)


**Tested:** `Dev Environment`
**Users:** `TopConnCustomer`, `TCConAccountMgr`, `TCConnCopilot`, `TCConManager`, `TCConAdmin`, `pshah_manager`
**Project URL:** https://connect.topcoder-dev.com/projects/16514
**Roles Matrix Ref:** https://htmlpreview.github.io/?https://github.com/topcoder-platform/tc-project-service/blob/feature/permissions/docs/permissions.html#roles-matrix

## User Role: `Connect Manager:` ⚠️ 

1. I think the Account manager box should have a blue background because Manager can Join as `Account Manager` using the 'Join' button inside the project.
2. All the other permissions are checked out with the 'Roles Matrix'.

https://monosnap.com/file/87AgFHSF5deN58edIO8gFeGDqjTbxA


## User Role: `Connect Admin:` 🆗 

- All the permissions checked out with the 'Roles Matrix'

https://monosnap.com/file/38hseELZkn8lvVMV8FOc1ZwV3OeleA


## User Role: `Connect Account Manager:` 🆗 

- All the permissions checked out with the 'Roles Matrix'

https://monosnap.com/file/HRDPG8ayTvoJsRAM5YVCx4ryQZIugh

## User Role: `Connect Copilot:` ⚠️ 

1. I think the Copilot box should NOT have a blue background because Copilot can't Join as `Copilot` using 'Join' button inside the project because the all projects are not visible to Copilot. Copilot Manager should approve because it appears on the Copilot project list.
2. All the other permissions are checked out with the 'Roles Matrix'.

https://monosnap.com/file/d10PsDCpog9X8KegKw3ZkRXCWnQ2Sd

## User Role: `Connect Customer:` ⚠️ 

1. I think the Customer box should NOT have blue background because Customer can't Join as `Customer` using 'Join' button inside the project because the all projects are not visible to Customer + There is no 'Join' button present in 'Customer team' area.
2. All the other permissions are checked out with the 'Roles Matrix'.

https://monosnap.com/file/y45RJN5U4opeJdbTJpOi6pttAxxlgf

**NOTE:** 'Roles Matrix' doesn't have any info about `Copilot Manager` role. And all the other roles `Account Executive`, `Solution Architect`, `Program Manager` or `Project Manager` are skipped. (Refer the comment from Ariel)

@maxceem @drasticdpk @lakshmiathreya @acshields @vikasrohit

**Comment by maxceem** [comment]
@codejamtc Thanks, for detailed testing. 

> I think the Account manager box should have a blue background because Manager can Join as Account Manager using the 'Join' button inside the project.

Blue box means the default Project Role when user with corresponding Topcoder Roles joins the project. For the user with `Connect Manager` Topcoder Role the default Project Role would be `manager`. User with `Connect Manager` can still join as `account_manager` if they want, but it's not the default role.

Regarding Customer and Copilots:
The thing is this matrix comes from server side (API) and API has more functionality than we use client-side in Connect App. In some situations we might use these blue default roles for Copilot and Customer users.

**Comment by vikasrohit** [comment]
@maxceem do we need any development work here? 
@codejamtc let us create new issues if any specific use case fails for this issue.

**Comment by maxceem** [comment]
> @maxceem do we need any development work here?

This is done server-side. Client-side there is a space for improvement: 
1. don't show roles which members cannot choose. Though technically it's not straightforward, as we don't load members Topcoder Roles to decide which Project Roles they can choose and which roles they cannot choose.

   ![image](https://user-images.githubusercontent.com/146016/81168878-80ffab80-8fa0-11ea-9d63-11bb7b2e0713.png)

2. don't show or disable roles which users cannot choose when they join the project directly:

    ![image](https://user-images.githubusercontent.com/146016/81168908-907ef480-8fa0-11ea-9396-48d84b082195.png)

    - this can be done quite straightforward as we know roles of the logged in user

**Comment by vikasrohit** [comment]
okay. Lets not start working on it yet. I think already have a role clean up planned in couple of months.

**Comment by lakshmiathreya** [comment]
Roles permissions need to be fixed overall. Possibly in 2.10? Hence reopening the Issue and moving to 2.10.
<img width="1260" alt="Screenshot 2020-05-07 at 3 05 59 PM" src="https://user-images.githubusercontent.com/51733042/81286272-67349600-907e-11ea-86b2-51c8fe515e16.png">
<img width="1317" alt="Screenshot 2020-05-07 at 3 18 53 PM" src="https://user-images.githubusercontent.com/51733042/81286288-6c91e080-907e-11ea-9090-7b8567e6ca02.png">

**Comment by lakshmiathreya** [comment]
Related to #3989

**Comment by maxceem** [comment]
@lakshmiathreya in this issue we've implemented it as per the current matrix in https://github.com/appirio-tech/connect-app/issues/3962#issuecomment-623789899.

And as per testing, this works well with such requirements. The matrix now has to be updated as per clarifications from Ariel which is tracked under the new issue https://github.com/appirio-tech/connect-app/issues/3989. 
If you don't mind I would suggest closing this issue as it was done as per requirements listed in this issue and track the updated requirements in a new issue.

**Comment by lakshmiathreya** [comment]
Working for Connect Manager - when invited with handle as per correct case. So closing this Issue since the other requirements are being tracked in #3989. 
<img width="1345" alt="Screenshot 2020-05-07 at 4 45 46 PM" src="https://user-images.githubusercontent.com/51733042/81288545-774e7480-9082-11ea-8da7-445ee803349e.png">
