### ISSUE TITLE
Project Plan: Phase Set-Up & Editing

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4057]
### Summary Notes
- Only Topcoder Employees and Copilots has visibility to the list-view screen.
- Only Topcoder Employees and Copilots has the capability to set-up phases.
- All templated phases in the previous version of project plan should be removed once the new generic phase template and set-up capabilities are supported.

### Phase Set-Up Workflow
1. User is on the list-view screen of project plan.

2. User clicks **[Add Phase]** button, which is displayed in the "Draft" section.

3. A generic template is opened, and the user sees this information presented:
**Title** [Required Input]: A free text field to input a title for the phase.
**Phase Start Date** [Required Input]: A calendar date selection.
The user should see an indication that the phase start date is just a reporting milestone.
**Phase End Date** [Required Input]: A calendar date selection.
The user should see an indication that the phase start date is just a reporting milestone.
The user should be able to change this default for the phase end date to another milestone type, by selecting from a dropdown menu.

4.  Once this required information is entered, the user has three options:
-Clicking an **[Add Milestone]** button, which will add a milestone to the phase timeline.
-Clicking a **[Save Draft]** button, which will save the phase as an unpublished draft that is displayed in the "Draft" section of the list-view and shown only to Topcoder Employees and Copilots on the calendar view.
-Clicking a **[Publish]** button, which will save the phase and either display it in the Planned or Active section of the list-view depending on the start date and display on the calendar-view as well. The button will only be enabled once all required answers have been provided on the phase, including the required information for an added milestone.

### Adding a Milestone to the Phase Workflow
When a user clicks the **[Add Milestone]** button on a phase, they will perform these actions:
1.  Select milestone type from a dropdown list of these options
-Reporting
-Deliverable Review
-Final Deliverable Review

2.  _If "Reporting" is selected, then the user can:_
**Title** [Optional Input]: Retitle the milestone in a text field. If no title is provided, then "Reporting" will be used as the default.
**Due Date** [Required Input]: A calendar date selection.

2.  _If "Deliverable Review" is selected, then the user can:_
**Title** [Optional Input]: Retitle the milestone in a text field. If no title is provided, then "Deliverable Review" will be used as the default.
**Start Date** [Required Input]: A calendar date selection.
**Due Date** [Required Input]: A calendar date selection.

2.  _If "Final Deliverable Review" is selected, then the user can:_
**Title** [Optional Input]: Retitle the milestone in a text field. If no title is provided, then " Final Deliverable Review" will be used as the default.
**Start Date** [Required Input]: A calendar date selection.
**Due Date** [Required Input]: A calendar date selection.

_Note: If a milestone is added to a phase, all required answers must be provided for a user to be able to click the **[Save Draft]** or **[Publish]** buttons on the phase._

### Editing a Draft Phase
- A user can edit a Draft phase at any time by clicking on it in the List View.
- At the bottom of a phase in Draft status, the user can click one of two buttons once changes are made:
[Save Draft]
[Publish]

### Editing a Published Phase
- A user can edit a Published phase at any time by clicking on it in the List View.
- At the bottom of a phase in Published status, the user can click a [Save Changes] button once their changes are complete.
- The [Save Draft] and [Publish] buttons should no longer display on a phase that has been published.

**Comment by maxceem** [comment]
1. During creating a new phase, the user can choose a phase Type. How this would affect the phase behavior? Should it create some predefined list of milestones for such a new phase as we do now?

   ![image](https://user-images.githubusercontent.com/146016/99957804-f3937580-2d90-11eb-914a-e2211cfe0147.png)

**Comment by acshields** [comment]
@maxceem - I just updated the requirements listed above - Actually, in the latest designs, I have removed "Type" selection altogether because, in this evolution that we are planning for the project plan, the "type" didn't serve anything more than just serve as a label on the phase for a quick visual reference.

And as a note, although you didn't directly ask about it: One of the biggest changes we are looking to achieve with this new version of the project plan is to actively get away from the templated phase model, where the # and kinds of milestones are preassigned based on the type and the user performing set-up can't change these attributes. What we've almost universally heard is that the person completing set-up needs more flexibility, in both:
- Adding/removing milestones from a phase
- Choosing the milestone type needed

Just for your reference on one of the big goals that we are working towards :)

**Comment by maxceem** [comment]
Thanks, @acshields for sharing the big perspective it helps to understand the requirements.

You've mentioned the design, do we have a design for this functionality of adding generic phases?

**Comment by acshields** [comment]
@maxceem - I do have designs for desktop and mobile. Rishi & Vikas have seen them - currently, there are a few final fixes being made to the designs, but they should be ready to go by the end of this week. As soon as I have them, I will share them over so you can visualize the changes we are looking to make.

**Comment by maxceem** [comment]
@acshields I've checked the design you've shared with me.

The main question I've got: For already existent phases/milestones would we keep the current UI as it is? Or would you like to update already existent phases/milestones too, so they have a new design?

![image](https://user-images.githubusercontent.com/146016/100793793-5934d100-3425-11eb-8e25-8b3d3be74034.png)

**Comment by acshields** [comment]
@maxceem - I am not entirely sure what's possible for backward UI compatibility with existing project plans. My perspective is: if we can make it backward compatible and it doesn't add work, then that's great. If it's going to add more effort, than I don't think it's that important.

@RishiRajSahu - what are your thoughts?

**Comment by RishiRajSahu** [comment]
@acsheilds doing backward compatible is bigger work, let's keep old projects as it is @maxceem.

**Comment by RishiRajSahu** [comment]
@maxceem @vikasrohit I think its time to move to V4 from V3, what say ?

**Comment by vikasrohit** [comment]
> @acsheilds doing backward compatible is bigger work, let's keep old projects as it is @maxceem.

@RishiRajSahu keeping the old projects as is without being backward compatible, would require redundant code on front end because we have to keep multiple components for the timeline UI, one for old one and one for new ones. And that is not going to be good from maintenance perspective.

> @maxceem @vikasrohit I think its time to move to V4 from V3, what say ?

You mean project version? If yes, I guess that depends on if we want to keep the old timelines to render in old way which I just described that would be a nightmare to maintain in future.

**Comment by RishiRajSahu** [comment]
@vikasrohit Yep agree, but making backward compatible is more time consuming and I doubt the timeline we have at hand. I had a plan of doing it in next increment once we are done with new project plan UI though.

**Comment by acshields** [comment]
@vikasrohit @RishiRajSahu - let's settle on the move forward direction for this today in our call. Personally, I am in favor of going with Rishi's proposal of splitting the effort into two parts: New UI/capabilities notes 1st, backwards compatibility 2nd. However, I still think it's worthy of discussion/consensus.

**Comment by maxceem** [comment]
Just a wild idea:
1. Implement new requirements using the old UI. This should keep backward compatibility as we don't remove old milestone types, and just add functionality for adding a few milestone types and generic phrases. This also would give us the outcome the faster way.
2. After that we could see what we've got and decide on how to move on to the new design from here.

**Comment by RishiRajSahu** [comment]
@maxceem that's the plan.

**Comment by maxceem** [comment]
@acshields There are a few moments to clarify. I know the current design is not final, but I would use it just for reference.

1. As I understand, when we are creating a phase, there would be one milestone by default `Reporting` and we should be able to choose another type for this milestone. As per design, we don't see it:

    ![image](https://user-images.githubusercontent.com/146016/101277884-38230600-37c0-11eb-857b-95a30eafb87b.png)

    ![image](https://user-images.githubusercontent.com/146016/101277890-42dd9b00-37c0-11eb-8012-9ca6e72f025c.png)

    So I suggest:
    - When we create a new phase we should show the `Reporting` milestone in the milestone list by default.
    - When we change the dates of the phase, we should automatically adjust the dates of this milestone.
    - User could change the type of this milestone as for any other milestone in the list.

2. Should we allow create a new phase without milestones? Or there should be at least one milestone in a phase?

3. Should we allow creating milestones with overlapping dates like:
    - 1 Milesonte: Dec 5 - Dec 10
    - 2 Milestone: Dec 7 - Dec 12
    - so they overlap on Dec 7 - Dec 10

4. Should we allow creating milestone with gaps between them like:
    - 1 Milestone: Jan 7 - Jan 10
    - 2 Milestone: Jan 15 - Jan 20
    - so there is a gap on Jan 10 - Jan 15 which is not covered by any milestone

**Comment by maxceem** [comment]
@RishiRajSahu @acshields 

5. Previously we manually controlled if the phase is "planned" or "active" (in progress) by changing the status. But in the new UI we have only one button "Publish". Do I understand it correctly, that now we show phase as "active" or "planned" only based on the current date. If phase today is between "start date" and "end date" we show phase as active, otherwise we show it as planned.

    ![image](https://user-images.githubusercontent.com/146016/101280586-a244a680-37d2-11eb-98ae-37b39a3189ab.png)

   - NOTE for Rishi: in such case, technically we wouldn't change the status of the phase, it would be always "active" and just visually client side we would show it as "active" or "planned". Because otherwise, we would have to implement some scheduler service to automatically change the status of the phases in the DB and ES.

**Comment by maxceem** [comment]
Here is my suggestions on how to use the current design for showing the new workflow:

### Edit existent phase

![image](https://user-images.githubusercontent.com/146016/101280755-88f02a00-37d3-11eb-8b58-089202bea259.png)

### Edit existent milestone

![image](https://user-images.githubusercontent.com/146016/101280774-a6bd8f00-37d3-11eb-9112-76da05ed3fba.png)

### Create generic phase with milestones:

![image](https://user-images.githubusercontent.com/146016/101280784-b8069b80-37d3-11eb-982e-7f94b3da80e9.png)

**Comment by maxceem** [comment]
Challenge specification draft is till in progress and would be clarified based on the answers to the questions above

# Topcoder Connect - Redirect to TaaS App

*Welcome to the Topcoder challenge. You may implement this task and submit your solution until the deadline. Reviewers would score it and 2 people with higher scores (not less than minimal) would get the prizes. Learn "[How to compete](https://www.topcoder.com/community/development/how-to-compete)" and read the task below.*

## Context

### Project Context

[Topcoder Connect](https://connect.topcoder-dev.com/) - the client-facing application of Topcoder. Customers may create Topcoder projects there and Topcoder managers and copilots pick it up from there.

### Challenge Context

In **Topcoder Connect** we can already manage **Project Plan** (see [screenshot](https://monosnap.com/file/lp6iTxdGpF6iLSxeiiV6ByLIAWiro0)). **Project Plan** consists of  **phases** which represent some pieces of work to do (for example one **phase** can mean running a challenge like this one). Each **phase** may contain several **milestones** to represent some key points of the **phase**. At the moment we can only create **phases** with predefined set of **milestones** (see [screenshot](https://monosnap.com/file/tDSz89gR7DaFFlXJBpjXIDx62XBTST)). But we would like to replace this functionality and be able to create **phases** with arbitrary set of **milestones**.

## Expected Outcome

We should be able to create **phases** with arbitrary set of **milestones** and edit **milestones** inside existent **phases**.

## Challenge Details

### Technology Stack

- React
- Redux
- CSS Modules

### Code access

To work on this challenge use the next repository:
- Topcoder Connect repo https://github.com/appirio-tech/connect-app branch **feature/custom-project-plan** commit **5be8d079e9308a659678f7ea9c62ca1764a45294** or later.
> - For local setup, please follow the [Quick Local Setup Guide]() on the forum (you can access it after registration). *If you have any issues during running project locally, please, let me know on the forum.*

### Individual requirements

#### Edit Existing Phases

When we click "Edit" button for any phase we are showing the form ([screenshot](https://monosnap.com/file/Di1e6XCNn8TNGX50h0ix66DCwTx8uD)). We have to update edit form as per [screenshot](https://monosnap.com/file/IuLPMFfm8pPoy9FWEIEadKaOgmm2cx):
- Remove fields "DURATION", "PAID TO DATE", "PRICE", "PROGRESS", "STATUS" ([screenshot](https://monosnap.com/file/E0s8FT1gsa9c2VbaFx72CAfegAhOMC)) with the corresponding logic which is not in use anymore
- Add "End Date" field next to "Start Date"
- Rename "Update Phase" button to "Save Changes"
- If phase status is "draft"
- "Title", "Start Date" and "End Date" should be required. "Save Changes" should be disabled if any field is not filled. If user clears some field, show validation error like on the [User Profile Page](https://connect.topcoder-dev.com/settings/profile) ([screenshot](https://monosnap.com/file/DIccfdb4fkomNz8VLpMRSOYdP3PSjp)).

#### Edit Existing Milestones

When we click "Edit" button for any milestone we are showing the form ([screenshot](https://monosnap.com/file/zRbENu7qnURGGudtrSCvTvVJwM8G7E)). We have to update edt form as per [screenshot](https://monosnap.com/file/0DvNsN0LCCrMk3IVcVeIJu8g1VvkIW)
- Add "Type" Select dropdown to choose a type of milestone.
  - It should be disabled if milestone status is not **draft**.
  - It should have the next options: "Reporting" (value 'generic-work'), "Deliverable Review" (value 'add-links'), "Final Deliverable Review" (value 'delivery-dev')
  - If current milestone has another type not listed above add one more option: "Deprecated type '{value of type}'"
- Replace "duration" filed with 2 fields one by one: "Start Date" and "End Date".
- As we cannot make date fields empty using our calendar, so no need to add any validation here.

#### Create New Phases

- Remove the current way of creating predefined list of phases which is available on https://connect.topcoder-dev.com/projects/8406/add-phase ([screenshot](https://monosnap.com/file/bhMxK4FLBDYgj34twU3RtfVFkYX0QT)) together with the corresponding logic which is not in use anymore.
- Instead, when we click **Add Phase** button, hide the button and show the same form which we show during phase editing together with timeline list as per [screenshot](https://monosnap.com/file/1zGJ4hgEORukG5TOT2wEYY2Y47U9ng).
- Instead of "Update Phase" show "Save Draft" and "Publish" blue buttons.
- Don't show delete warning when creating.
- Show the **Timeline** with one `Reporting` Milestone by default:
  - During creating we should be able to edit only 4 fields
  - We should be able to remove milestones by clicking "delete" icon. But we should hide "delete" icon when only one milestone left (on screenshot we show delete icon for one milestone only so you can see the icon).
  - "Type" should have 3 options as explained in "Edit Existing Milestones" section.
  - "Start Date" and "End Date" are required. "Title" is optional and initially filled with the milestone "Type".
  - "Add Milestone" button show one more new milestone form: "Type" empty, "Title" empty, "Start Date" = "End Date" of previous milestone, "End Date" = "Start Date" + 3 days.
  - When select "Type" if "Title" is empty the fill "Title" with the text of "Type".
- Clicking "Save Draft" should create a new phase with status "draft".
- Clicking "Publish" should create a new phase with status "active" if phase "Start Date" is already passed or it's today. If "Start Date" is in the future, then create phase with status "reviewed".

## General requirements

- Use React and Redux best practices.
- Properly structure code in components/services/actions/reducers and split code into meaningful functions and components.
- Lint should pass.
- Existent unit tests should pass.

## Scorecard Aid

Review guidelines:

- All the functionality should work as described above. If issue breaks some some functionality it's a major issue.
- If issue doesn't break functionality, but make the experience poorer, it may be treated as minor issue.
- As we don't have design, the choice of the design should not be scored down, but it could be marked as "recommended". If something is broken in design, it could be treated as minor issue.

**If you have any questions or concerns, feel free to raise a question on the forum.**

## What To Submit

- Submit a zip file which would include a [Git patch](https://stackoverflow.com/questions/5159185/create-a-git-patch-from-the-changes-in-the-current-working-directory) with changes you’ve made to the code in our repository.
- Additionally, the winner would be required to raise a pull request to the repository after the challenge is completed.

**Comment by RishiRajSahu** [comment]
1. Let's make reporting as the default milestone, with startDate same as phase startDate by default.
2. Let's not update dates of milestones based on phase, but I think its users responsibility to take care of that
3. Reporting milestone should be the first one, and its type shouldn't be changeable
4. **we show phase as "active" or "planned" only based on the current date.** - _Yes_
I think once the milestone is published its active in backend, its the UI which moves from planned to active based on dates. Also, I don't see any drawback in this approach as our UX depends upon dates we either have to put a schedular or used the mentioned approach, and If we consider the reverse experience, Suppose user has put the start date to late one after the phase is being active already in that case also UI should be adaptable to status changes of milestones and we don't have to take care of any backend check.
5. All the dates management should be end user's responsibility now, whether its phase or milestone

@acshields fyi

**Comment by maxceem** [comment]
Challenge for this issue is launched 2 days ago https://www.topcoder.com/challenges/d57c6f7c-2e17-4021-8d5e-5f6c2cc7c97f?tab=details
- Due date `16 Dec`
- The challenge doesn't include adding milestones to already existent phases to keep the score clear and avoid possible merge conflicts with the [parallel challenge](https://www.topcoder.com/challenges/eb107e10-19e0-40d5-a1a4-ada8ae2fc25a). It would be handled as a private task after this or both challenges are completed.

**Comment by drasticdpk** [comment]
1. Label of button  **[Add New Phase]**  instead of  **[Add Phase]** 
2. Getting Error while publishing the drafted phase.

**Reference** 
Project : https://connect.topcoder-dev.com/projects/16820
User : **TCConnCopilot**

![image](https://user-images.githubusercontent.com/25297859/102980357-9295c380-452f-11eb-8b98-82f27602bb4f.png)
![image](https://user-images.githubusercontent.com/25297859/102980655-ffa95900-452f-11eb-9a8d-03ab5187cf40.png)

**Comment by maxceem** [comment]
Thanks @drasticdpk we would check this issue. Note, this only would happen if the project is not activated yet.

To continue testing with copilot user, please, activate the challenge using `Connect Manager`. After that, you should be able to publish the draft phase succesfully.

**Comment by drasticdpk** [comment]
Thank you @maxceem.

**Comment by maxceem** [comment]
@drasticdpk fyi this issue https://github.com/appirio-tech/connect-app/issues/4057#issuecomment-750031790 is fixed now.

If copilot publish phase, and project is not active yet, project stays not activated. I've logged in separate issue to track it https://github.com/appirio-tech/connect-app/issues/4225

**Comment by drasticdpk** [comment]
Prod verified.

![image](https://user-images.githubusercontent.com/25297859/103527664-cddaaf80-4eaa-11eb-955a-dcb157b6c36e.png)
