### ISSUE TITLE
Retrieve & Display Connect Project Billing Account from SFDC

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4058]
**Current Version:** The Connect Project's Billing Account is not displayed inside the Connect Project.

**Desired Updates:**
- Retrieve the Billing Account Name and ID associated to the Connect Project ID in Salesforce.
- Display the Billing Account Name underneath the Administration label in the left sidebar of a Connect Project, as follows:
-Field Title: Billing Account
-Pre-Populated Result: [Billing Account Name]

Additionally, we need to reconfirm that there are no present barriers for a billing account to be set-up/associated to an internal (Topcoder) Connect project.

**Comment by vikasrohit** [comment]
@acshields I think it would be tricky to fetch the billing account name without a data model change which I would not prefer to implement just for rendering the billing account name. The reason is that we just want to keep the reference of the billing account which is the id of the billing account and we never want to store other metadata of such external entities unless critical. The other way to show the billing account name without the model change is to make an API call to billing account api from front end (who needs this information) but the api is very private in nature and we don't want to expose it, again, unless critical.
So, I would suggest to show some generic text like we are showing for the direct project link e.g. `Billing Account` and have it linked to SFDC.

**Comment by acshields** [comment]
@vikasrohit @RishiRajSahu - proceeding with just the ID and the field name [Billing Account] is workable for now :)

**Comment by RishiRajSahu** [comment]
![Screenshot 2020-09-01 at 6 28 52 PM](https://user-images.githubusercontent.com/11248478/91854212-03fbee80-ec81-11ea-803e-f0ed7b32d1bb.png)
@acshields please confirm if this looks good to you.

**Comment by acshields** [comment]
@RishiRajSahu - that looks good to me for the time being!

**Comment by RishiRajSahu** [comment]
In dev we don't have billingaccount added to the projects, so I have manually attached one to a single project for testing

https://connect.topcoder-dev.com/projects/16605
