### ISSUE TITLE
Project Plan: Milestone Types

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4083]
### Summary
Projects App will support three types of milestones, which a user can choose from:
- Reporting
- Deliverable Review
- Final Deliverable Review

Additionally, there will a fourth type of milestone, "Final Fixes," which will get triggered if a user selects [Request Fixes] during the Final Deliverable Review milestone. 

### Reporting Milestone Data Attributes
- **Title** [Optional Input During Milestone Set-Up]: User-created milestone title, which would display on the phase timeline in place of the default "Reporting" text.
- **Due Date** [Required Input During Milestone Set-Up]: A due date for the milestone, which would be presented on the phase timeline.
_Note: The "Reporting Milestone" will not have a duration. It will be a point in time, which is reflected on the phase timeline as a due date._
- **Delivery Update** [Required Input During Milestone Interaction]: A large free text field labeled "Delivery Update," which could be used by the Topcoder Employee or Copilot to provide an update to the client. 

### Deliverable Review Milestone Data Attributes
- **Title** [Optional Input During Milestone Set-Up]: User-created milestone title, which would display on the phase timeline in place of the default "Reporting" text.
- **Start Date** [Required Input During Milestone Set-Up]: A start date for the milestone, which would be presented on the phase timeline.
- **Due Date** [Required Input During Milestone Set-Up]: A due date for the milestone, which would be presented on the phase timeline.
- **Delivery Update** [Optional Input During Milestone Interaction]: A large free text field labeled "Delivery Update," which could be used by the Topcoder Employee or Copilot to provide an update to the client. 
- **Feedback** [Optional Input During Milestone Interaction]: A field labeled "Feedback," which could be used by the Topcoder Employee or Copilot to share a document where they want to capture the client's feedback.
- **Submissions** [Required Input During Milestone Interaction]: A field labeled "Submissions," which could be used by the Topcoder Employee or Copilot to upload one or more submissions.
- **"Review Complete" Button** [Required Action During Milestone Interaction]: A [Review Complete] button, which when clicked by a Topcoder Employee or Client, datestamps the data and marks the milestone complete.

_Note: The current functionality of submission rankings will be turned off for now, and this activity will be managed in the feedback document._

### Final Deliverable Review Milestone Data Attributes
- **Title** [Optional Input During Milestone Set-Up]: User-created milestone title, which would display on the phase timeline in place of the default "Reporting" text.
- **Start Date** [Required Input During Milestone Set-Up]: A start date for the milestone, which would be presented on the phase timeline.
- **Due Date** [Required Input During Milestone Set-Up]: A due date for the milestone, which would be presented on the phase timeline.
- **Delivery Update** [Optional Input During Milestone Interaction]: A large free text field labeled "Delivery Update," which could be used by the Topcoder Employee or Copilot to provide an update to the client. 
- **Feedback** [Optional Input During Milestone Interaction]: A field labeled "Feedback," which could be used by the Topcoder Employee or Copilot to share a document where they want to capture the client's feedback.
- **Submissions** [Required Input During Milestone Interaction]: A field labeled "Submissions," which could be used by the Topcoder Employee or Copilot to upload one or more submissions.
- **"Accept Deliverables" Button** [Required Choice Option During Milestone Interaction]: An [Accept Deliverables] button, which when clicked by a Topcoder Employee or Client, datestamps the data and marks the milestone complete.
- **"Request Fixes" Button** [Required Choice Option During Milestone Interaction]: A [Request Fixes] button, which when clicked by a Topcoder Employee or Client does the following:
-Records a datestamp
-Opens a text field where the user can describe the required fixes, or provide a link to a document.
-Adds a "Final Fixes Milestone" to the phase timeline.

_Note: The current functionality of submission rankings will be turned off for now, and this activity will be managed in the feedback document._

### Final Fixes Milestone Data Attributes
- **Due Date** [Required Input During Milestone Set-Up]: A due date for the milestone, which would be presented on the phase timeline.
- **Delivery Update** [Optional Input During Milestone Interaction]: A large free text field labeled "Delivery Update," which could be used by the Topcoder Employee or Copilot to provide an update to the client. 
- **Submissions** [Required Input During Milestone Interaction]: A field labeled "Submissions," which could be used by the Topcoder Employee or Copilot to upload one or more submissions.

**Comment by maxceem** [comment]
@acshields

1. For all the milestones, should we show 2 buttons **Mark as Completed** and **Request Extension** as we do now?

    ![image](https://user-images.githubusercontent.com/146016/99958259-bb406700-2d91-11eb-96c6-88f5a6389ee2.png)

2. **Reporting Milestone**. When Topcoder Employee or Copilot enters **Delivery Update** should the milestone be ended immediately? Or we can enter deliver update and it would be visible to the client without ending the milestone. So we can update **Delivery Update** several times?

3. **Deliverable Review** Do I understand it correctly, that here we have the next workflow:
     1. Topcoder Employee or Copilot provide `Delivery Update`, `Feedback` (link), `Submissions`. Should they click some button after entering such information so Clients are notified that action is needed on their side?
     2. As soon as Topcoder Employee or Copilot provide information above and clicked some button. All these fields should become read-only and now Topcoder Employee or Client can click "Review Complete" Button to accept the delivery.
     3. As Topcoder Employee also can click "Review Complete" Button, should they got notification when milestone got delivery information provided?

4. **Deliverable Review** Should we be able to upload submissions directly here? Or should we only enter links as we have implemented now?

**Comment by acshields** [comment]
Hi @maxceem - thank you for asking & clarifying.

### Question 1
No, the actions required (and buttons) will be different by milestone type. 
- **Reporting Milestone:** This milestone will be used simply as a way to convey an update to the client by the delivery team. It is up to the client whether they choose to read it. This milestone also has no "duration," it is just a point of time on the calendar. As a result, no buttons are needed for this milestone.
- **Deliverable Review Milestone:** This milestone will be set up when a review action is required from the client. This milestone does have the concept of a "duration," essentially a start date and an end date shown on the calendar. Because the action is required but this isn't the final deliverable review, the only button that should be shown is [Review Complete].
- **Final Deliverable Review Milestone:** This milestone will be set up when a final review action is required from the client. This milestone does have the concept of a "duration," essentially a start date and an end date shown on the calendar. Because an action is required and this is the final deliverable review, two buttons should display [Accept Deliverables] and [Request Fixes].

### Question 2
The reporting milestone should:
- Give the Topcoder Employee or Copilot the ability to provide the client with a point in time update in their delivery plan.
- The Topcoder Employee should be able to save their update, which will then immediately become viewable to the client and can return to edit the update if needed.
- It is assumed that because the reporting milestone is intended to be used to provide a point-in-time update to the client, that if the Topcoder Employee or Copilot wanted to share another update with the client at a different point in time that they would simply add another reporting milestone to the phase on a different date. Therefore, this milestone can "end" when the Topcoder Employee/Copilot provides an update and the ability to provide multiple updates per reporting milestone is not needed.

### Question 3
The deliverable review milestone:
i.  Yes, good suggestion. When the Copilot/Topcoder Employee is adding things to the milestone, they should have a [Save Changes] button that saves the links, etc. to the milestone, and publishes them immediately to the client view. For notifying the client of pending/required action, I am thinking of using the actual scheduled dates on the phase to provide the notification (Ex. deliverable review is live in 1 day, etc.). However, I do think that clicking [Save Changes] here should also be a published event, because then when I look at improving notifications overall not only can I have the notification say something like, "Deliverable review in now live. Here is what your delivery team just shared for you to review. Link x, y, z.
ii. I am okay if the links become read-only so that the Topcoder Employee/Copilot can click "Review Complete," but they should have a method to activate "Editing" of the milestone again (in case they shared the wrong link, or something).
iii. @maxceem - I need more clarification - did you mean the Topcoder Employee/Copilot should get the notification, or the Client?

### Question 4
Submissions retrieval:

- The long answer to your question: I do want to get to a point where submissions for a project are automatically retrieved/shared in the project. However, I am both unclear on whether we have a current version of the API & process that can support this, and what the development effort would be.
- The short answer to your question: For those reasons, that's why I chose to keep the sharing of submission links manual copy/paste for now.

**Comment by maxceem** [comment]
> I need more clarification - did you mean the Topcoder Employee/Copilot should get the notification, or the Client?

I mean the next situation:
- generally saying copilots are the ones who is sharing deliverables with Clients and Topcoder Employees
- so let's say a copilot added deliverables in the **Final Deliverable** milestone
- at this moment we should send a notification to the clients that the deliverable was provided, so the client may review  and accept it or request fixes
- the question is, should Topcoder Employee also get a notification when the copilot adds deliverable? I have this question because Topcoder Employee also can accept deliverable or request fixes

**Comment by maxceem** [comment]
> The long answer to your question: I do want to get to a point where submissions for a project are automatically retrieved/shared in the project. However, I am both unclear on whether we have a current version of the API & process that can support this, and what the development effort would be.

@vikasrohit @RishiRajSahu what do you think about this?

From the first view, it looks like we can achieve it with moderate efforts by updating Project Service:
- update `ProjectAttachment` model to support `reference` and `referenceId`
- all existent records would have `reference=project` and `referenceId=<project.id>`
- to support uploading submissions we would use `reference=milestone` and `referenceId=<milestone.id>`
- the only place where we can have issues is handling permissions. Though so far it shouldn't be an issue:
  - we only add submissions to the active phases
  - active phases are visible to all the people who can access the project
  - so submission attachments would be accessible to all the people who can view the project which we support at the moment

**Comment by maxceem** [comment]
@acshields we've checked the current designs and there is no UI for file uploading so far, so for now we would only allow providing submissions as links as per design https://marvelapp.com/prototype/b8ja33g/screen/74683346

**Comment by acshields** [comment]
Yes, the file links can just be pasted into the fields. that's fine.

**Comment by RishiRajSahu** [comment]
@acshields thanks for confirming on that. @maxceem so we are good to get this in progress too.

**Comment by RishiRajSahu** [comment]
@acshields 

- For "Reporting Milestone" no button - OK
- For "Deliverable Review Milestone" show "Review Complete" - this button might also change the status
- For "Final Deliverable Review Milestone" show "Accept Deliverables" and "Request Fixes" which also can change the status

Another Scenario - 
Imagine that today is 10 Dec

- We have a milestone "Deliverable Review Milestone" which ends on 15 Dec
- Copilot adds links on 10 Dec
- Client see the links and clicks "Review Complete" on 10 Dec.
- The next milestone still starts only on 15 Dec so as we are showing active milestones based on time we are still showing "Deliverable Review Milestone" as active, even though client already clicked "Review Complete".

To handle the above scenario, I suggest - 
**let milestones complete based on their scheduled dates or manually based on user action.**

FYI @acshields

**Comment by acshields** [comment]
@RishiRajSahu - thanks for asking these questions. I will share my thoughts now, but let's discuss it on the call too.

- **Question:** For the Deliverable Review & Final Deliverable review milestones, what "status" are we referring to? The phase "status," or the milestone status?
- **Scenario Feedback:** The way I am looking at the Deliverable Review & Final Deliverable Review Milestones (which have "durations"), is that the duration is an indication of the time the milestone stakeholders have available to complete it. If they complete it early, that's great, but it doesn't need to automatically affect the next milestone's date. In my perspective, I would like to keep the logic simple (for now, at least) and see how people respond. In the scenario you highlighted, the user managing the next milestone (Copilot/Expert Services team member) may want that next milestone date to move up, or they may not. If they do want the date of the next milestone to move up, they can go update the start/end dates of it at any time and if they do, the next milestone would go to active on the new start date that they set. If they don't change the next milestone's date, then the start will remain as-is and it won't go to active until that originally planned date.

**Comment by RishiRajSahu** [comment]
@acshields :) those were actually @maxceem  questions which came out as we were finalising the specs for challenge,I think what you suggested makes things easier also


fyii @maxceem

**Comment by maxceem** [comment]
@acshields, @RishiRajSahu thank you for clarifications.

A couple of more concerns:

1. When we complete some milestone do we activate the next milestone as we do now?
    If we don't update the start date of the next milestone then, when we activate the next milestone it could look active, though the start date would be in the future

    ![image](https://user-images.githubusercontent.com/146016/101802450-1acf9e00-3b18-11eb-8953-b868fe6dba04.png)

2. So far I'm going to keep backward compatibility for old milestone types as much as possible.
    At the moment, when "mark as completed" old milestones we are moving the next milestone date to today (and move all other milestones accordingly).
    As we are not going to move dates for the new milestone types, I suggest applying the same approach for old milestone types too. So if don't move dates for new milestones when completed, we should not move dates for old milestone types when completed too.

**Comment by maxceem** [comment]
Challenge draft

# Topcoder Connect - New Milestone Types

*Welcome to the Topcoder challenge. You may implement this task and submit your solution until the deadline. Reviewers would score it and 2 people with higher scores (not less than minimal) would get the prizes. Learn "[How to compete](https://www.topcoder.com/community/development/how-to-compete)" and read the task below.*

⚠️ **IMPORTANT**: This challenge has shortened timeline. Submission phase: **96 hours**. Review phase: **24 hours**!

## Context

### Project Context

[Topcoder Connect](https://connect.topcoder-dev.com/) - the client-facing application of Topcoder. Customers may create Topcoder projects there and Topcoder managers and copilots pick it up from there.

### Challenge Context

In **Topcoder Connect** we can manage **Project Plan** (see [screenshot](https://monosnap.com/file/lp6iTxdGpF6iLSxeiiV6ByLIAWiro0)). **Project Plan** consists of  **phases** which represent some pieces of work to do. Each **phase** may contain several **milestones** to represent some key points of the **phase**. We have milestones of different types which enables different functionality inside them for example see [screenshot](https://monosnap.com/file/feIgM7h7o2pDYrE4MfrdYHKWqIxwdR). At the moment we have 7 main types of the milestones, see [the folder with them](https://github.com/appirio-tech/connect-app/tree/dev/src/projects/detail/components/timeline/milestones).

## Expected Outcome

Create 4 new types of the milestones.

## Challenge Details

### Technology Stack

- React
- Redux
- CSS Modules

### Code access

To work on this challenge use the next repository:
- Topcoder Connect repo https://github.com/appirio-tech/connect-app branch **feature/new-milestone-types** commit **e8bf3b2be3051d52221113fe74d69e6ec48f90ef** or later.
- For local setup, please follow the [Quick Local Setup Guide](https://discussions.topcoder.com/discussion/671/quick-local-setup-guide#latest) on the forum (you can access it after registration).

### Individual requirements

#### Create "Reporting" milestone type

Create a new milestone type="reporting". This milestone would be used by **Topcoder** and **Copilot** members to provide updates to the **Customers**. Once Reporting is published it can be seen by Customers. Topcoder and Copilot can edit reporting after publishing any time.

- When milestone is **active** Topcoder and Copilots should be able to provide report https://monosnap.com/file/SYCg9biSlTaLkM2bROwPoLR3Bg74i2. And Customers should not see "Provide Report" button https://monosnap.com/file/p2TNgo7waFYgFM9aPojPPWXuLY5CzA.
- When clicking "Provide report" Topcoder and Copilots should see https://monosnap.com/file/ATgZEELRrBTQkJWN6gWgWl5wIJb1Ei. Once clicked "Publish report" we have to save the report inside milestone "details.content.report" and change the status to "completed".
- Once Reporting milestone is **completed** Customers should see the reporting text https://monosnap.com/file/brb6Qk8UjyDEjtr5ggZK9sPmocIeLj.
- Topcoder and Copilots should also see "Edit" button https://monosnap.com/file/jvdpQkV4xJGPH9sGKUXp7rmVnmvUmn. When clicking "Edit" show edit form https://monosnap.com/file/zx2IZpmQbedRkuomXn97HJhZPRPUv5 with button "Save Changes" instead of "Publish report".

#### Create "Deliverable Review" milestone type

Create a new milestone type="deliverable-review". This milestone would be used by **Topcoder** and **Copilot** to provide deliverable update and submission for to the customer to review.

- When milestone is **active** Topcoder and Copilots should be able to provide "Delivery Update", "Feedback link" and a list of links to submissions: https://monosnap.com/file/0VrDEBfsiVKLo8d3vYHggPuHnVnapO.
  - "Add Deliverable Update" should work the same as adding report above (show textarea with "Cancel" and "Save Changes" buttons). No publish button and marking milestone as completed needed here.
  - "Add feedback link" should show UI for entering link, the same like "phase-specification" milestone type https://monosnap.com/file/kslD4oaWjyideN0hPT0YaaM7jpcj35 (just different title).
  - "Add submission link" should work the same like "checkpoint-review" milestone type https://monosnap.com/file/8C6RMP7aPKAOSZ5XB68oe4osUHFwLa (just replace "Design" with "Submission" everywhere)
  - So if we click all 3 buttons it may look like this: https://monosnap.com/file/nmmBs70q5fRKOcK8veQDv4ckFPVkl8
- Any information saved by Topcoder and Copilots users should be visible to Customers immediately in read-only mode https://monosnap.com/file/11oE9o30hz6EFCwPMB7br3clv5e3IW.
- "Review Complete" button should be visible to Topcoder and Customer members but not Copilots. Clicking this button should change milestone status to "completed".
- Topcoder and Copilots users should be able to edit any data even after milestone is completed: https://monosnap.com/file/BG0pkLp0SUtmxzUqeSU4w38FfOSjMr

#### Create "Final Deliverable Review" milestone type

Create a new milestone type="final-deliverable-review". This milestone would be used by **Topcoder** and **Copilot** to provide deliverable update and submission for to the customer to review. Customer would be able to review and ask for the final fixes.

This milestone type work exactly the same as "Deliverable Review" but instead of showing button "Review Complete" it should show 2 buttons "Accept Deliverables" and "Request Fixes": https://monosnap.com/file/FxFeYUL9whvhZ59wvzHnUswM4K1umI
- Clicking "Accept Deliverables" should just change status of milestone to "completed"
- Clicking "Request Fixes" should show a textarea for entering final fixes request: https://monosnap.com/file/oRVKlWiuI9MLE8hsYdNmDXI9MOtLdj
- If we click "Submit Request" we should also mark current milestone as completed, and add a new milestone to the timeline after the current one:
  - "type" = "deliverable-final-fixes"
  - "startEnd" = "endDate" of "Final Deliverable Review" milestone
  - "endDate" = "startDate" + 3 days
  - "status" = "reviewed"
  - "details.content.finalFixesRequest" = text form the textarea

#### Create "Deliverable Final Fixes" milestone type

Create a new milestone type="deliverable-final-fixes". This milestone would be used by **Topcoder** and **Copilot** to provide deliverable update and submission for to the customer based on the Customer review.

- It should work exactly the same as "Deliverable Review", but show the final fixes request text on the top https://monosnap.com/file/Y37DfCIxaYIcxqsz21zWVS38z8cAR3

## General requirements

- When creating/updating milestone use [Bulk Update endpoint](https://github.com/appirio-tech/connect-app/blob/dev/src/api/timelines.js#L65). So we can update several milestones at once.
- For the design reuse existent components and styles.
- When we do any operations with milestones show success alerts like these ([screenshot](https://monosnap.com/file/iPgwEUoLjKrsZjc6nE0J6nX6PxpCYl)). And show red error alerts if there is any error during create/update operation.
- Use React and Redux best practices.
- Properly structure code in components/services/actions/reducers and split code into meaningful functions and components.
- For styling use ONLY colors from the https://github.com/appirio-tech/tc-ui/blob/feature/connectv2/src/styles/_variables.scss.
- Avoid using multilevel nesting in SCSS. As we use CSS Modules we don’t have to add prefixes or nest class selectors.
- Don’t use `:global` in CSS Modules unless you have to change some global styles. New styles shouldn’t use `:global`.
- As we are running a parallel work, we would like to avoid merging conflicts later for this. So don't change code formatting anywhere. If you need a change for the functionality, feel free to change it. But if you just want to change formatting, please, don't.
- Lint should pass.

## Scorecard Aid

Review guidelines:

- All the functionality should work as described above. If issue breaks some some functionality it's a major issue.
- If issue doesn't break functionality, but make the experience poorer, it may be treated as minor issue.
- Provided design screenshots are just for reference. We have to reuse existent styles to implement UI. Reviewers, please, don't score down for design in this challenge, unless something is really broken.

**If you have any questions or concerns, feel free to raise a question on the forum.**

## What To Submit

- Submit a zip file which would include a [Git patch](https://stackoverflow.com/questions/5159185/create-a-git-patch-from-the-changes-in-the-current-working-directory) with changes you’ve made to the code in our repository.
- Additionally, the winner would be required to raise a pull request to the repository after the challenge is completed.

**Comment by maxceem** [comment]
Challenge for this issue is launched https://www.topcoder.com/challenges/eb107e10-19e0-40d5-a1a4-ada8ae2fc25a:-
- Due date `18 Dec`
- It doesn't include updating milestone "showing" logic to keep the score clear. Updating "showing" logic would be handled as a private task after the challenge is complete.

#### Update milestones "showing" logic

At the moment, we are showing milestones as **planned**, **active** and **completed** based on milestone status, see [screenshot](https://monosnap.com/file/ddbvaMn6izY7efehSURZrlmGTtngQu).
We have to change this behavior.
- Milestone should be still shown as **completed** when having "status == completed". But if milestone has another status we should ignore it, and show milestone based on the current date:
- Show milestone as **active** if "status != completed" and if milestone "startDate" <= todayDate <= "endDate".
- Show milestone as **planned** if "status != completed" and if todayDate < "startDate" or "endDate" < todayDate.
- When compare dates convert them to the same timezone.
- Compare dates only using day, i. e. "10th Dec 10am" == "10th Dec 6:30am" because we ignore time.
- Note, that milestones behave different based on how we show them **planned**, **active** and **completed**. Not only they change the color of blue circle, but they also have different functionality when they are **planned**, **active** and **completed**, see [screenshot](https://monosnap.com/file/m5vXRLRNTMaKmeim48fZrwCVf56Y6d). So after this update, the functionality should depend not only on "status", but also on start/end dates as described above.

**Comment by drasticdpk** [comment]
**Verification** 

 milestone type:  "Reporting"


![image](https://user-images.githubusercontent.com/25297859/102991956-67689f80-4542-11eb-9d2f-d86f470271a5.png)

![image](https://user-images.githubusercontent.com/25297859/102991833-1f497d00-4542-11eb-97b4-20df960e03c3.png)

**Comment by maxceem** [comment]
@RishiRajSahu at the moment for new milestone types we are still showing planned/active/completed text.
For now we add milestones with dummy texts:

![image](https://user-images.githubusercontent.com/146016/102995887-a985e700-452a-11eb-9529-9f8930306036.png)

We also, allow editing these texts for backward compatibility:
![image](https://user-images.githubusercontent.com/146016/102995931-c3272e80-452a-11eb-963e-d1cb6bdd6a5f.png)

There are few ways to go with this for new milestones:
1. Replace dummy texts with meaningful texts for all 3 states: planned/active/completed for all 4 new milestone types.
2. Hide planned/active/completed for new milestone types and don't allow editing it for new milestone types, while keep it for old milestones.

**Comment by RishiRajSahu** [comment]
@acshields we would like your input on above, in new designs I don't see these texts used though.

**Comment by drasticdpk** [comment]
@maxceem ,

 
-  I could not find submission, feedback link on  **Deliverable Review**  please help me on that ?
   
![image](https://user-images.githubusercontent.com/25297859/103001790-c5eb4900-4555-11eb-8ac6-56608c7f5c6e.png)

There is some mismatch on **Deliverable Review** , start date and end date please confirm. 

**Reference**  
Project : https://connect.topcoder-dev.com/projects/16820
User : TCConnCopilot

https://monosnap.com/file/qvhX1TkjzRrIAYFnTXbpyAAdsTJw77

**Comment by maxceem** [comment]
@drasticdpk could you please, clarify what is the mismatch?

By the way, did you create this milestone just now, or you created it some time ago? Because we have validation so we should not be able to choose start date after end date:

![image](https://user-images.githubusercontent.com/146016/103008241-7e58c300-453d-11eb-971d-0769e10cac24.png)

But in your video start date somehow after the end date.

**Comment by acshields** [comment]
@maxceem @RishiRajSahu - Let's keep the different state texts for now. Use this default language:

**Reporting Milestone**
Default Text: The delivery team will provide an update on your progress.

**Deliverable Review**
Planned Default Text: The delivery team plans to share in-progress deliverables on this date for your review.
Active Default Text: Your review and feedback on in-progress deliverables is required. 
Blocked Default Text: Your in-progress deliverables have been blocked. Work with your delivery team to understand the next steps.
Completed Default Text:  Thank you for your review of the in-progress deliverables. Your feedback will inform your final deliverables.

**Final Deliverable Review**
Planned Default Text: The delivery team plans to share the final deliverables on this date for your review.
Active Default Text: Your review and feedback on the final deliverables is required. 
Blocked Default Text: Your final deliverables have been blocked. Work with your delivery team to understand the next steps.
Completed Default Text:  Your final deliverables are complete.

**Comment by drasticdpk** [comment]
> @drasticdpk could you please, clarify what is the mismatch?
> 
> By the way, did you create this milestone just now, or you created it some time ago? Because we have validation so we should not be able to choose start date after end date:
> 
> ![image](https://user-images.githubusercontent.com/146016/103008241-7e58c300-453d-11eb-971d-0769e10cac24.png)
> 
> But in your video start date somehow after the end date.

@maxceem , 
I just created all milestone.

**Comment by maxceem** [comment]
Thanks, @drasticdpk. This is now fixed by 871099c1835b57e2db855d7368cc592a5b6de5e1. Could you please, check this now.

**Comment by maxceem** [comment]
Thank you @acshields for texts for the milestones. There is one more milestone type **Final Fixes**. When customer already provided feedback and copilot prepares the final-final deliverables:

![image](https://user-images.githubusercontent.com/146016/103076355-39349f80-45d6-11eb-8878-d283288dc1dc.png)

Would you like too use different text for this milestone?

**Comment by lakshmiathreya** [comment]
Date Issue is now fixed ... Verifying the other items ...

**Comment by acshields** [comment]
@maxceem - the language used for the final fixes milestone shown above is fine. Thanks!

**Comment by drasticdpk** [comment]
@maxceem  There is console error at Review complete!

**Reference** : 

Project : https://connect.topcoder-dev.com/projects/16831 

User Use.
**Copilot :** TCConnCopilot
**Customer :** TopConnCustomer


Video : https://monosnap.com/file/CCDwo0pLm4lTsBhN6inkXKmO5T9Z38 

![image](https://user-images.githubusercontent.com/25297859/103201336-c8fc8580-4917-11eb-9e0d-d957cfbee22e.png)

**Comment by drasticdpk** [comment]
**Suggestion** 
What if fixation was not done at first request, Customer can make re-request, right ?
 https://snipboard.io/RaHyrO.jpg

**Comment by maxceem** [comment]
> @maxceem There is console error at Review complete!

This is fixed via e26fe83639ee8704d5d3ae103f4b7b65814759c5 and read for QA.

Details:
- We had the next logic: when any user completes the last milestone, we automatically change the current phase status to `completed`. But customers cannot change phase status in API so the error happened. As per new requirements we would track phase status using current time instead of the actual status see https://github.com/appirio-tech/connect-app/issues/4203. So to fix this issue I removed code to change phase status `completed`.

@RishiRajSahu fyi.

**Comment by drasticdpk** [comment]
Verified. 
https://monosnap.com/file/Qk9Ik11VdXQTtyfFDXNhqI4lbOeoRY

**Comment by drasticdpk** [comment]
Prod Reference 

![image](https://user-images.githubusercontent.com/25297859/103527302-3d03d400-4eaa-11eb-953e-525f35d43ab1.png)
