### ISSUE TITLE
Sunset Projects App Account Registration & Release Projects App Progressive Registration

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4093]
For tracking purposes...

1. Sunset Project App's standalone account/profile registration process.
2. Release Project App's progressive registration feature.

**Comment by vikasrohit** [comment]
Actual work for sunsetting the pages would be done in Account app, https://github.com/appirio-tech/accounts-app/issues/354
> Release Project App's progressive registration feature.

It is already enabled in Projects App. It is only the Salesforce connector that has to be released now.

**Comment by RishiRajSahu** [comment]
@acshields The places where the account specific pages get triggered - 
1. Log in - Home page when user is logged-out and clicks 'Log in' button
2. Register - Home page when user is logged out and clicks 'Start a project' button
3. Reset Password  - on profile page, when user clicks 'Forgot password'

Above three could be replaced and released in tomorrow's release, another place where we need to updated account app page is invite mail template as mentioned by you. So currently we have this kind of structure for for url we send in the mail - 

`https://accounts.topcoder.com/connect/registration?retUrl=https://connect.topcoder.com/projects/{projectId}`
i.e. we send the actual project url as return url so that once user is registered, user is redirected to the invited project.

but with new way of logging we don't have support of providing return url to new registration page, we can only provide regSource with value `tcBusiness` for the url to be identified coming from Connect, therefore new link which we will be sending in the mail is 
`https://accounts.topcoder.com/member/registration?regSource=tcBusiness"`

The difference which will arise here is that  - 
a. User will click the `Register` button in invite mail
b. User will be redirected to new registration page with source `tcBusiness`
c. User fills the form
d. User receives the link to activate and clicks it
e. **User is represented with connect login page to login go to dashboard, there the invited project would be present for joining/decline.**

**Comment by RishiRajSahu** [comment]
Earlier instead of step **e**, user was redirected to project page with a pop-up asking to join/decline. Doesn't look much breaking UX to me still needs your heads-up

**Comment by acshields** [comment]
@RishiRajSahu - Thank you for letting me know. I think the new workflow with step "e" is fine :) to reconfirm, all of these changes will be a part of tomorrow's release?

**Comment by lakshmiathreya** [comment]
1. New User Registration, Login, Logout and Password change working fine. Registration email format is TBD.
2. For SSO user - there is an issue in Dev redirecting to Wipro. Same issue when tried with Accounts App dev. 
3. Country field responsive test doesnt work well with country names that are substrings of other country names - again this is an Accounts App issue.

**Comment by RishiRajSahu** [comment]
Updated the template in dev https://github.com/topcoder-platform/tc-notifications/commit/c6c6a2003f6091f424f6c00d0989e49ce2c7bdac

**Comment by lakshmiathreya** [comment]
@acshields @RishiRajSahu would like to go over the new Reg flow during our call before I close this Issue.

**Comment by lakshmiathreya** [comment]
Move to TC registration form is verified. This has led to User experience change for the Connect User as opposed to the earlier flow - that is - inability to redirect to the Project page upon completion of Registration. 

This would be logged as a new Issue and fixed via changes to Accounts App to support return urls. Therefore closing this one.
