### ISSUE TITLE
Remove "Project Role" Selection from Topcoder Team Invitations

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4101]
### Updates - Desired Workflow

1. User clicks "Manage" next to Topcoder Team
2. User enters one or more user handles
3. User clicks "Invite Users"

### Updates - Removed Step
Moving forward, the selection of invited user's 'project user role' should no longer be included as a step in the Topcoder Team invitation process.

**Comment by RishiRajSahu** [comment]
@acshields as per our last discussion If we want to remove selecting different roles while inviting a project, below is the best we could do to achieve this objective - 
1. We have notion of Topcoder and Project Roles Currently
2. Whenever a user is invited in Topcoder Team, and if that user posses any of the Topcoder manager role, including `Connect Manager` the user would be assigned as Manager (Project role) to the project
Note : Connect Manager is a minimal role to have Project role Manager 
3. The ability to change the user roles which we have currently in the Topcoder Team dialog will be removed and it would be implicitly considered that all users in Topcoder Team are managers

**Pro** - Roles dropdown can be removed

**Con** - If some user want to all other roles of self/others i.e. if other person is Actually a Account manager or Solution Architect that won't be possible via UI

fyi @vikasrohit

**Comment by RishiRajSahu** [comment]
@acshields Just for everyone to be on same page I am putting our discussion yesterday here again as final requirements -
1. From now we are going to have single project level manager role
2. Only managers will be invited from Topcoder Team
3. Remove the role switching option from the UI
4. Remove the dropdown of roles when inviting manager
5. We have to check Roles/Visiblity table of ours to verify first if there are anything which visible/hidden if we keep common role for all Topcoder employee for a Project
6. Same goes for the notifications also.

**Comment by acshields** [comment]
@RishiRajSahu - thank you!

**Comment by maxceem** [comment]
@RishiRajSahu

1. Should we keep all the specific project roles, or should we completely remove them? This would require us to update project data in the DB and reindex all the projects.

    - `Solution Architect`
    - `Account Executive`
    - `Account Manager`
    - `Project Manager`
    - `Program Manager`

2. (If 1. is NO) Currently, we are showing specific project roles as `Solution Architect`, `Project Manager`, `Manager` and so on. Should we keep showing these specific roles, to remove these labels?

    ![image](https://user-images.githubusercontent.com/146016/92907494-0c48ec00-f42e-11ea-8a4c-60c782563ca4.png)

3. (If 1. is NO) From now on, should we treat all the various manager roles the same? So all the permissions and notifications should be the same for all manager roles.

4. We also have some specific Topcoder Roles which cannot become "managers" but can only become "Account Managers". What role should such users get when we invite them to Topcoder team "managers" or "Account Managers"?

    ![image](https://user-images.githubusercontent.com/146016/92909887-3bf8f380-f430-11ea-9bc6-fdd81068c380.png)

**Comment by maxceem** [comment]
5. There are some notifications which are sent to the specific manager roles:

   - When project is created, `Account Managers` and `Business Development Representatives` get notifications
   - When project is ready for review, `Account Managers` and `Business Development Representatives` get notifications

6. On the other hand, `account_executive` Project Role doesn't get any notifications at the moment.

**Comment by RishiRajSahu** [comment]
@maxceem 
1. Let's keep our frontend code backward compatible instead of doing DB updates i.e. if any of such older roles found we have  treat them as new common project-manager role. 
2. We don't have to show separate roles now on, in-fact we don't have to show any role as the dialog itself defines the roles of the members present under it.
3. Yep unless they have some different permissions/notifications associated with them.
4. Still have to clarify this out !
5. Yes we have to update front-end config and backend to honour this still based on Topcoder role of the user
6. same as 5

**Comment by maxceem** [comment]
@RishiRajSahu to sum up, I guess the logic here would be the next:
- we keep all the **Project** and **Topcoder** roles as they are internally, but never show these roles to the users
- when we invite a user manager, the manager is invited using they DEFAULT role as per matrix:

    ![image](https://user-images.githubusercontent.com/146016/93311742-0d539200-f80f-11ea-9016-c44c29a5fbf7.png)

- this way all the current permissions and notifications would work the same as before, as all the users would have the same **Project** and **Topcoder** roles

7. There is only one thing we have to update in the Project Service. Currently, when we are inviting manager users, we can invite several users, but we should invite them with the same role:

     ![image](https://user-images.githubusercontent.com/146016/93312124-80f59f00-f80f-11ea-9884-85bf46db38a5.png)

     We have to update Project Service so we can invite users with multiple roles, for example, `maxceem1` as `Manager` and `maxceem2` as `Account Executive`.

      These is needed, so if user enter multiple managers to invite, for each user we detect they default **Project Role** and invite each user using this default role, which can be different for each user.

What do you think?

**Comment by RishiRajSahu** [comment]
@maxceem a user could have more than one Topcoder roles attached that's why I mentioned that when any user is invited via Team Manager dialog, that user should atleast have Connect Manager(other Manager roles may or may not be present).


| Task           | Could be Assigned Project Manager   | 
|----------------|---------------|
|'Connect Manager'|&check;|
|'Connect Account Manager'|_|
|'Connect Admin'|&check;|
|'administrator'|&check;|
|'Connect Copilot Manager'|_|
|'Connect Copilot Manager', 'Connect Manager'|&check;|
|'Business Development Representative'|_|
|'Business Development Representative', 'Connect Manager'|&check;|
|'Presales'|_|
|'Presales', 'Connect Manager'|&check;|
|'Account Executive'|_|
|'Account Executive', 'Connect Manager'|&check;|
|'Program Manager'|_|
|'Program Manager', 'Connect Manager'|&check;|
|'Solution Architect'|_|
|'Solution Architect', 'Connect Manager'|&check;|
|'Project Manager'|_|
|'Project Manager', 'Connect Manager'|&check;|

8. Yep that's what I preferred that we have notifications based on Topcoder roles only 

also, regarding permissions I guess as we refactor code to have single project manager role those would be handled.

**Comment by maxceem** [comment]
Thanks for the table @RishiRajSahu it helps.

From this table, it follows that if some user has the only a role like `Project Manager` or `Connect Account Manager` then such a user cannot join the project as Manager to the Topcoder Team. Though, previously such users could join a project to the Topcoder Team with a specific Project Role like `project_manager` or `account_manager`.

2 questions raise from here:

9. If some user with the role `Connect Account Manager` (without `Connect Manager`) is invited to the **Topcoder Team** should such invitation be refused?

10. We already might have projects where some user with only `Connect Account Manager` is a member of the project and has `account_manager` role. Should such a user still be a member of the project? Because as per the table above, such user cannot be a member of the **Topcoder Team** because doesn't have `Connect Manager` role.

**Comment by RishiRajSahu** [comment]
@maxceem , yes Connect Manager role is must now, any other Role(s) could be there or not doesn't matter.
9. updated the table
10. Existing members should be shown under Manager Team only with any role label, should that be an issue ? I guess existing members could be rendered as it is, its only the new member invited who are going to affect , that's what I mean't by backward compatible earlier. Please let me know if I am missing anything here ?

**Comment by maxceem** [comment]
@RishiRajSahu this is done via PR https://github.com/appirio-tech/connect-app/pull/4128. It's merged to the September branch and ready for testing.

**Comment by lakshmiathreya** [comment]
Observations - pls clarify:
1. All roles except 'Manager' are now functionally redundant.
2. Existing Manager team members are being shown without role label.
3. Join Project dropdown shows all Previous roles - this seems redundant: 
<img width="1338" alt="Screenshot 2020-09-23 at 5 41 55 PM" src="https://user-images.githubusercontent.com/51733042/94010874-2686b080-fdc4-11ea-9fc7-760d1ec21d4b.png">
4. Manager role should have 'Manage' button for Copilot section - this is missing. Only Admin has it. 
![Uploading Screenshot 2020-09-23 at 5.43.48 PM.png…]()

**Comment by lakshmiathreya** [comment]
<img width="1635" alt="Screenshot 2020-09-23 at 5 48 05 PM" src="https://user-images.githubusercontent.com/51733042/94011434-f855a080-fdc4-11ea-866c-a4d1046a68c2.png">

**Comment by lakshmiathreya** [comment]
5. After Project Roles removal - Only Admin, Connect Admin and Connect Mgr have higher privileges such as Project edit privileges which is the same as current Prod.

**Comment by maxceem** [comment]
> 3. Join Project dropdown shows all Previous roles - this seems redundant:

Good, catch! Role selection is removed now, please check.

> 4. Manager role should have 'Manage' button for Copilot section - this is missing. Only Admin has it.

Manager only has this button **after** joining the project. Only admins can manage users without joining a project.

> 5. After Project Roles removal - Only Admin, Connect Admin and Connect Mgr have higher privileges such as Project edit privileges which is the same as current Prod.

Actually, currenlty, users might edit projects even without joining. So users with roles like `Account Executive` or `Business Development Representative` can editr projects without joining.

**Comment by lakshmiathreya** [comment]
@maxceem Since we no longer are able to add roles like Account Executive or Business Development Representative  - how can such Roles edit projects - with or without joining - regardless of that - these roles dont exist now right.

**Comment by maxceem** [comment]
> 4. Yet there is no Manage button for Copilot Section.

As per requirements for `Copilot` section https://github.com/appirio-tech/connect-app/issues/4102 `Only TC Copilot Assignment Managers and Admins should see this "Manage" button`. So regural managers shouldn't see `Manager` button for copilots.

> 5. Since we no longer are able to add roles like Account Executive or Business Development Representative - how can such Roles edit projects - with or without joining - regardless of that - these roles don't exist now right.

These roles still exist. We don't remove them, but so far we just don't let them join the projects. Regarding the fact that they still can edit projects, I'm not sure if we should do anything regarding it. @RishiRajSahu should we change anything here?

**Comment by lakshmiathreya** [comment]
4. Who is a "TC Copilot Assignment Manager"? I assumed this would be Connect Manager since we dont have any other Manager role now.

5. So Account Executive and BDR can edit all Projects in Connect now?

**Comment by lakshmiathreya** [comment]
> > 1. Join Project dropdown shows all Previous roles - this seems redundant:
> 
> Good catch! Role selection is removed now, please check.
> 
--- Verified this.

**Comment by maxceem** [comment]
@lakshmiathreya

> 4. Who is a "TC Copilot Assignment Manager"? I assumed this would be Connect Manager since we dont have any other Manager role now.

We have a special Topcoder Role **Connect Copilot Manager** who has the ability to manage copilots. Such users should see `Manage` button to manage copilots without joining the project.

> 5. So Account Executive and BDR can edit all Projects in Connect now?

Right. It was like this before, we didn't change anything here.

**Comment by lakshmiathreya** [comment]
Verified - Connect Copilot Manager is able to see the Manage button - without having to join the Project. Connect Manager does not see the Manage button. Clarified this is as expected by @acshields 
<img width="1631" alt="Screenshot 2020-09-24 at 10 16 53 PM" src="https://user-images.githubusercontent.com/51733042/94175185-f28ab880-feb3-11ea-9b98-def49b345d9d.png">

**Comment by lakshmiathreya** [comment]
Verified in Prod: 
-- All manager Roles can be added only with the addition of Connect manager role. 
-- Copilot Manager and Admin can see Copilot team manage button without joining the Project. 
-- All Role labels are removed from Manager team display
-- Manager team members now have Project Edit privileges due to the addition of Connect manager role.
