### ISSUE TITLE
Copilot Invitations to Projects

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4102]
### Update 1
In Topcoder invitations, exclude copilot handles from being returned as a match to the responsive character entry.

### Update 2
Underneath "Client" and before "Topcoder" in the team section of a project's left sidebar, add a section labeled "Copilot"

### Update 3
In the "Copilot" section, include a button that says "Request Copilot"
1. This button will be hyperlinked to this Google Form: https://docs.google.com/forms/d/e/1FAIpQLSeZ7UXDd4XGOISHLs-zLaZwKliTySlbfso5px71tRTePfRj3Q/viewform
2. When clicked, this Google Form should open in a new browser tab

- All Topcoder Employee users should see this button
- No Clients or Copilot users should see this button

### Update 4
In the "Copilot" section, next to the "Copilot" label include a "Manage" button
1. When clicked, this button should open the invitation pop-up window
2. The user can type a Copilot handle into the responsive text-entry field and see character-matching Copilot handles returned
3. The user can select the correct Copilot handle
4. The user can click "Send invitation"
5. The invited Copilot should immediately receive the invitation notification in email and see the pending invitation to the project appear in their Projects App projects list

- Only TC Copilot Assignment Managers and Admins should see this "Manage" button
- Other Topcoder Employees users, Copilot users, and Client users should not see this "Manage" button

**Comment by RishiRajSahu** [comment]
@acshields
Update 1 - 
1.  I had followed up with member service team and they don't support role filter on the suggest endpoint actually the don't store any role info with them right. Also, having such an endpoint with role level filter could be potential security flaw as we are giving an option to fetch user based on roles. Fyi @mtwomey 
2. what if we leave it as its, I mean, as we are anyway updating Topcoder Team section to be just for managers and removing role selection dropdown, if user is not having required role, the invite would be unsuccessful with valid error message.

Update 2 - 
Clear

Update 3 -
Clear, but does this means the `Request mechanism we have in place right now is no longer required ? should we remove the logic from the frontend and backend for the same or let it be there ?
- Maybe instead of Google-Form we can update UI in case of Request mechanism, so there is a better UX in case of Request Flow ? maybe on click of request we can show the dialog only with some marker shown for requested copilots ?

Update 4 - 
1. Again its same as 1, we can't have just copilot users being filtered from suggestions, and anyway one must be already aware about the initials of any copilot name so respective names would only come in suggestions
2. Visibility could be managed easily

**Comment by RishiRajSahu** [comment]
@acshields as per latest discussion
Update - 1
Not required, as not feasible currently

Update - 2
Clear

**Update 3 -** 
Clear, but does this means the `Request mechanism we have in place right now is no longer required ? should we remove the logic from the frontend and backend for the same or let it be there ?

Maybe instead of Google-Form we can update UI in case of Request mechanism, so there is a better UX in case of Request Flow ? maybe on click of request we can show the dialog only with some marker shown for requested copilots ?

Update 4 -
all doable, except we are removing filter of users based on roles from requirement.

**Comment by acshields** [comment]
@RishiRajSahu - Thank you for recapping and I will provide the follow-ups/required updates here.

**Update 1** - Agreed, we will not pursue this at this time.

**Update 2** - Noted that this is clear. Please proceed with creating the "Copilot" section in the left sidebar.

**Update 3** - Let's proceed with the guidance I provided above (I am reposting here). Although we may be able to manage the request process in the app and not use the Google Form, my main concern on why I would like to continue to use the Google Form, for now, is actually more due to the notifications/emails that we send to notify Tony & Glenn of the request. In future quarters, I plan to improve all forms of notifications, but for now, I do not want to tackle this work and with how busy Tony/Glenn are with TaaS I am concerned that the current versions of "Copilot request" notifications/emails they may receive from Projects App may get lost as "noise," whereas they are used to using the Google Form. So, down the road, I think we could build in the optimized request flow after we improve our notifications, but for now I just want to keep it easy for us and them.

_Again, here is the changes need for Copilot Requests:_
In the "Copilot" section, include a button that says "Request Copilot"
1. This button will be hyperlinked to this Google Form: https://docs.google.com/forms/d/e/1FAIpQLSeZ7UXDd4XGOISHLs-zLaZwKliTySlbfso5px71tRTePfRj3Q/viewform
2. When clicked, this Google Form should open in a new browser tab

- All Topcoder Employee users should see this button
- No Clients or Copilot users should see this button

**Update 4** - Noted we will pursue these updates to Copilot Requests, minus the filtering:
In the "Copilot" section, next to the "Copilot" label include a "Manage" button
1. When clicked, this button should open the invitation pop-up window
2. The user can type a Copilot handle into the responsive text-entry field and see character-matching handles returned
3. The user can select the correct Copilot handle
4. The user can click "Send invitation"
5. The invited Copilot should immediately receive the invitation notification in email and see the pending invitation to the project appear in their Projects App projects list

- Only TC Copilot Assignment Managers and Admins should see this "Manage" button
- Other Topcoder Employees users, Copilot users, and Client users should not see this "Manage" button

**Comment by lakshmiathreya** [comment]
'Connect Project Link' field length needs to be fixed :-
<img width="957" alt="Screenshot 2020-09-23 at 2 24 57 PM" src="https://user-images.githubusercontent.com/51733042/93990640-fed61f00-fda8-11ea-8f44-d31c735febcd.png">

**Comment by lakshmiathreya** [comment]
1.Update 1 - not applicable.
2.Update 2 - Copilot section verified.
3.Update 3 - Copilot Request form verified - pls fix field length as noted above.
4. Update 4 - Copilot invitation verified. Copilot section visibility verified for Copilot, Customer and TC Roles.

**Comment by RishiRajSahu** [comment]
@lakshmiathreya this google form is created by tony/glen I guess and in used since long by them we have just provided the link of that on Connect. Please ignore the form features when QA-ing this git issue.
Also, you can convey about this length thing to Ariel/Tony.

**Comment by lakshmiathreya** [comment]
Verified in Prod: Copilot Section, Copilot Request form, Copilot invitation, Copilot Manage button visibility only for Copilot manager and Admin roles.
