### ISSUE TITLE
Sanitize the content of Topic/Message to avoid XSS

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#4115]
Sanitize the content of message's topic and body to avoid possible XSS

Fyi @vikasrohit @acshields

**Comment by maxceem** [comment]
## Overview

The **message topic** is safe.

The **message text** indeed allows rendering any arbitrary HTML, for example here is a red rectangular outside of the message, using `position: fixed`:

![image](https://user-images.githubusercontent.com/146016/92609913-c40bbb80-f2bf-11ea-84a7-1ca49ff7c172.png)

This issue happens only during **viewing** the message. Editing is safe, as during editing all HTML is shown as plain text:

![image](https://user-images.githubusercontent.com/146016/92610050-ef8ea600-f2bf-11ea-9f16-d738074eacec.png)

This happens due to the fact, that we explicitly enable rendering `html` here https://github.com/appirio-tech/connect-app/blob/dev/src/helpers/markdownToState.js#L216.

If we disable this flag, then we would be totally safe, and all HTML would be shown as plain text, like this:

![image](https://user-images.githubusercontent.com/146016/92610381-4dbb8900-f2c0-11ea-8213-d61d3d855666.png)

Though, I guess we cannot just disable this flag, as it looks like we might have old messages saved as HTML in the DB. See the commit message where this flag has been added https://github.com/appirio-tech/connect-app/commit/91b678d2a56012ae8fe7c3835bccd71c77551bf6.

## Solutions 

There are 2 possible solutions:

### Quick 

- During rendering, we have to sanitize HTML tags, and only allow the small subset of tags without attributes.

   - **advantage**: We keep allowing rendering HTML to support old messages. And the fix is quick and easy.
   - **disadvantage**: We have to add one more library and executing sanitizer is quite a heavy operation, it could happen that when there are many messages in one topic we could start noticing a delay

### Not-Quick

- Disable support for HTML at all, to be completely safe.
- But as we might have messages in DB which already using HTML markup which we need, we have to process all the messages in DB and replace good HTML tags with Markdown. Bad tags we can keep as it is and it would be rendered as text.

**Comment by maxceem** [comment]
@vikasrohit @RishiRajSahu created a hotfix base on the Quick solution described [above](https://github.com/appirio-tech/connect-app/issues/4115#issuecomment-689597620):
- only the next tags are allowed `'blockquote', 'p', 'a', 'ul', 'ol', 'li', 'b', 'i', 'strong', 'em', 'strike', 'abbr', 'code', 'br', 'pre'`
- all other tags would be displayed as text without attributes:

   ![image](https://user-images.githubusercontent.com/146016/92615785-2a93d800-f2c6-11ea-821b-7d712f589cb3.png)


PRs:
- PROD https://github.com/appirio-tech/connect-app/pull/4116
- DEV https://github.com/appirio-tech/connect-app/pull/4117

**Comment by vikasrohit** [comment]
@maxceem @RishiRajSahu I think we should put sanitizing in tc-message-service as well. What do you suggest?

**Comment by maxceem** [comment]
@vikasrohit I would suggest sanitizing client-side only.

IMHO message service should allow storing any text message. Somebody might discuss attacks and include examples of XSS code like `<img src=x onerror=alert("xss") />` so in some context such text would be absolutely legit.

The only thing all such code suppose to be rendered as text, and not to be rendered as real HTML. 

The problem we have here is that we have to render some HTML code to support backward compatibility to the times when we stored HTML instead of Markdown in the message service. And this is forcing us to use selective sanitizing.

**Comment by RishiRajSahu** [comment]
@vikasrohit are we concerned here about someone directly accessing message-service endpoints with XSS contents ?

**Comment by lakshmiathreya** [comment]
- Verified that tags other than the list above are rendered as plain text.
- Verifying the entire sanitizing is beyond the scope of this Issue testing.
- Verified that old messages are rendered correctly in Prod.
