### ISSUE TITLE
Project: Billing Account Management

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4214]
We need to improve the billing account workflow, to remove the necessity of managing billing accounts in Direct for the project and its challenges/tasks.

**Proposed Solution:**
- Inside the project (Connect), the user views a field labeled Billing Account
- Underneath this field, the user views a dropdown menu with these options:
-If a billing account is already associated with the project in SFDC, then this billing account (ID and Name) should be displayed as the default selected option. The user can open the dropdown menu and select an alternate billing account (any billing account they have access to) if necessary.
-If no billing account is associated with the project in SFDC, then the user can open the dropdown menu and select any billing account they have access to.
- The user should click a "Save Changes" button if changes are made.

**Proposed Visibility:**
- This capability of billing account selection should only be enabled for Topcoder Employees. 
- The Copilot should be able to view the selected billing account, but does not have the ability to assign one to the project.
- The Client should not see the billing account.

**Proposed Data Management Necessities:**
- The project should be able to retrieve data from SFDC on all billing accounts associated with the project ID.
- If the default billing account is changed, this data should be published as an event that can be consumed by SFDC.
- If there was no default billing account (from SFDC data) and one (i.e. one the user has access to) is selected from the list dropdown list, this data should be published as an event that can be consumed by SFDC.
- The selected billing account associated with the project should be published as an event that Work Manager can consume, and effectively pass-through and apply this data to all challenges/tasks created for the project.

**Comment by acshields** [comment]
@RishiRajSahu @mtwomey @vikasrohit - Please review my proposed updates to the billing account workflow in projects, and let's be prepared to talk this through this week.

**Comment by mtwomey** [comment]
There is a couple of additional pieces of data that may be relevant:

1. We _do not_ need to support more than one billing account related to a single project (e.g. all challenges in the project will use the one billing account). I think this is in line with what you said above.
2. It's unclear to me if we need to pass back selected billing account information to SFDC? When challenges close and are changed, something is passed back that shows the money consumed, so maybe this is enough?

On this: "The selected billing account associated with the project should be published as an event that Work Manager can consume" It might not quite work that way, but I understand what you're going for here.

Curious to hear thoughts from @vikasrohit as well.

**Comment by acshields** [comment]
@mtwomey - thanks for reviewing. Yeah, I didn't know how to describe "make sure the billing account for the project gets to applied to that project's challenges/tasks" in a technical term, but glad you got where I was going!

**Comment by RishiRajSahu** [comment]
@acshields @mtwomey mind jumping me here before @vikasrohit , first of all we would have to add support to call SF endpoints in order to retrieve billing accounts for a project as we no more directly call SF after we put event mechanism in place, having stated that, below are the next points from my side - 
1. There could be more than one billing account eligible to be attached to project
2. Currently in Direct we can associate multiple billing accounts to a project and during challenge creation user gets option to pick from those associated billing account to be used for challenge to be launched
3. Currently in Direct while launching a challenge, user is able to switch between the eligible billing accounts, and in work-manager we don't have that option of choosing billing account, I don't know the logic behind there, in WM, to pick the account for challenge - fyi @vikasrohit 
4. Challenges always gets launched today with billing account only, we can definitely pass this info to SF when challenge is closed/changes but that work shouldn't fall under Connect's bucket
5. For project management - for updates we can do events flow to SF from Connect and viceversa also, we have to also take care of the case when project is managed from Direct as we are not getting rid of it immediately and users might update billing from there also.
6. Also, we have to check how currently Directly/SF communicates
7. I think the solution we decide here could help us for the new intake flow update here https://github.com/appirio-tech/connect-app/issues/4188

<img width="1342" alt="Screenshot 2020-12-15 at 5 24 51 PM" src="https://user-images.githubusercontent.com/11248478/102213311-9193df00-3efc-11eb-8a43-1af7ecd62fb6.png">
<img width="1363" alt="Screenshot 2020-12-15 at 5 25 06 PM" src="https://user-images.githubusercontent.com/11248478/102213325-96589300-3efc-11eb-8ddb-74402d0a1cfa.png">

**Comment by vikasrohit** [comment]
Thanks @mtwomey and @RishiRajSahu for your inputs. I agree for most of the things. My observations are as follows:

- @mtwomey you are right about `The selected billing account associated with the project should be published as an event that Work Manager can consume`, we don't need any event for this. Work Manager can read the billing account details from wherever we store it. Right now it is reading it from Direct project, but it should not be difficult to read it from v5 project. All we need to agree on is cardinality of billing account per project.
- Personally I am reluctant to pull any data from SFDC because as @RishiRajSahu mentioned it would be against our efforts to decouple Salesforce and Platform. Further, owners in both systems are different. I mean in SFDC billing account are managed through Sales and Finance team but they are not likely to open Work Manager for any purposes and hence syncing any data back from Platform to SFDC can cause confusions to such users and SFDC has to be updated as well to accommodate all such data pushes to SFDC.
- Having said that, we can still pull a list of available billing accounts for the user by calling our platform api for billing accounts. That api is still v3 but it is better to use it instead of SFDC as SFDC is already talking with that API on billing account lifecycle events.
- For @RishiRajSahu 's concern of having ability to select billing per challenge level, I guess @acshields we have such capability in new designs, right? If yes, we would be using the same billing account api that I suggested in previous point.
- >This capability of billing account selection should only be enabled for Topcoder Employees.
This can be done on UI but controlling it at API level is bit tricky. We have tried to restrict the API capability as well in past but Topgear team (who acts as customer to us) need to set billing accounts for their projects and hence we have to revert that back. In my opnion solution to that problem would be introducing Orgs and Org specific roles.

**Comment by acshields** [comment]
Recapping next steps coming from this morning's conversation:

**Clarification 1**
It has been reconfirmed through many layers of the company by both Matt and Ariel that although today in Direct we support the option for having multiple billing accounts on a project, we do not need to with Projects App/Work Manager flow in the future. Moreover, the working idea of having a 1:1 relationship between a project and an active billing account, will simplify the overall experience (because, in addition, the billing account will not need to be selected for every challenge/task run for a project). 

As a note, having the 1:1 relationship between a project and billing account is our long-term goal. However, if it is easier in the short-term to copy the billing account selection process used today in Direct and replicate it in Connect/WM, then we will do that in order to remove this step from needing to be done in Direct as fast as possible, and then we will work towards the long-term goal.

**Clarification 2**
It seems like SFDC is our ultimate source of truth for billing accounts.

**Next Steps**
@mtwomey is going to make a diagram of all potential billing account flows (ex. client project vs. internal project, etc.) to aid in our final discussion on this subject.
@RishiRajSahu @vikasrohit - If there is anything that we can learn on how Direct gets/stores billing account data today to aid in our solution planning, that would be great.

**Comment by vikasrohit** [comment]
> However, if it is easier in the short-term to copy the billing account selection process used today in Direct and replicate it in Connect/WM,

I guess it is rather doing wrong thing first and then correcting it later. I mean we are already having 1:1 relationship in v5 projects so if we go backwards to support multiple ones, it would be more difficult to reach the ultimate goal in future.

If we are now sure that we need 1:1 mapping between project and BA, solution is pretty simple. Just update the challenge api to read BA information from v5 projects instead of v3 and have some way in Projects Apps UI to update BA because as of now it is supported only via API.
