### ISSUE TITLE
TaaS Intake: Update "Duration" to be Weeks

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4284]
### Update 1
On the TaaS intake form, update the "Duration" input to read:

Field Label: "Duration (Weeks)"
Field Input: No changes

![image (26)](https://user-images.githubusercontent.com/41118149/105784592-b7ba8f00-5f3e-11eb-9b84-220236718e9c.png)

**Comment by maxceem** [comment]
Done via https://github.com/appirio-tech/connect-app/commit/6139dffb3b1105512cdca9e7582f1bd0edffc7ea

Ready for QA on DEV by link https://connect.topcoder-dev.com/new-project/taas-jobs

@acshields, FYI I've changed the release date to the earlier `2/26` as the fix is trivial and it would be good to have for the TaaS App release on `2/26` as this field would be used in TaaS App since `2/26`.

cc @RishiRajSahu

**Comment by drasticdpk** [comment]
Verified on Dev 

**Reference** 
 
![image](https://user-images.githubusercontent.com/25297859/108303012-35378f00-71cd-11eb-9dec-8c325298e9fd.png)

**Comment by vikasrohit** [comment]
@maxceem can we close this?

**Comment by maxceem** [comment]
@vikasrohit yes, closing it.
