### ISSUE TITLE
Project Plan Bug: "Actual Start Date" Overriding Subsequent Dates

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4285]
### Bug Description
**Project:** https://connect.topcoder.com/projects/26349
**Recreation Steps**
1. Create a new phase
2. Did not change the first milestone (Reporting) date(s), which were 1/26-1/29.
3. Added a second milestone (Deliverable Review) with the dates, 2/1-2/4.
4. Saved phase as draft
5. Published phase
6. End result: The first milestone's dates did not change. However, the second milestone's dates changed to begin on 1/30 and not as 2/1 as designated.

### Bug Solution
I think the date override is being triggered when a user publishes a phase, and also has something to do with the "Actual Start Date." IMO, I don't think the "Actual Start Date" is necessary. When a phase is published, the dates should remain as the user established them, and should not be overridden.

**Comment by vikasrohit** [comment]
@acshields I think our timeline always assumes there would be no gap between two milestones i.e. as soon as one milestone is ended, the next one starts. Hence, it might be setting the start of second milestone to be immediately next to the first milestone's end date. Logically it does not make sense to me to have buffer spaces between two milestones durations. Timeline is a continuous  pattern of milestones. Similarly, until recently we didn't allow the overlapping of milestones as well, I am not sure with the new milestone add/remove capability, if we also get the capability to overlap milestones.

**Comment by maxceem** [comment]
@acshields @vikasrohit in general I agree with Vikas, that having buffers between milestones don't feet our logic quite well. Also, our current design doesn't reflect such buffers between milestones and we are only showing the start date of each milestone which also visually indicated the end of the previous milestone.

![image](https://user-images.githubusercontent.com/146016/109491992-f63def00-7a92-11eb-9918-273e15f14450.png)

For the particular case, which is described by Ariel in this issue. I think we can make this fix and it would not break our logic. So what we can do is like this:
- User can create milestones with gaps, as they can do now:

  ![image](https://user-images.githubusercontent.com/146016/109492220-4fa61e00-7a93-11eb-9d1b-f3e2bfff4525.png)

- When we activate the phase, we can still keep milestone with gaps that are not yet active:

    ![image](https://user-images.githubusercontent.com/146016/109492297-6d738300-7a93-11eb-8e99-152fbda41860.png)
    
    - at the moment when we activate the section milestone Start Date is updated (not "Actual Start Date). We can fix it so non-active milestones keep they start date:
    
        ![image](https://user-images.githubusercontent.com/146016/109492399-9d228b00-7a93-11eb-82e2-df47c40ffeb3.png)

   - but as soon as we activate milestone, the start date would be updated with the current date (because "Actual Start Date" would be set). And this part we have to keep as we have a lot of logic based on this fact. If we eventually want to get rid of such behavior we can discuss it separately, as it would require more effort.

- But the issue as per current description could be fixed, and I don't see drawback. We can keep gaps for the milestones which are not yet activated.

**Comment by vikasrohit** [comment]
@maxceem it requires more thinking around the phase and its timelines and I think we have a pitch for clearing up the phase timelines, so we can handle it at that time.
@acshields Moving it out of current bug fixes projects

**Comment by acshields** [comment]
@vikasrohit - noted.
