### ISSUE TITLE
Project listing/Search: typeahead not working

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#43]
I think this was planned, but is not working. If we can't have it for this release, that's OK.

**Comment by mahestro** [comment]
Yep, not working.

I'll add make "My projects only" clickable to active the respective checkbox.

**Comment by fnisen** [comment]
@mahestro don't understand your comment. What do you mean?

**Comment by mahestro** [comment]
Clicking this text http://take.ms/ZnWi9

**Comment by mahestro** [comment]
Challenge live, merged with #42 https://www.topcoder.com/direct/contest/detail.action?projectId=30055194

**Comment by parthshah** [comment]
Thanks.. also can you make that checkbox active by default.

**Comment by fnisen** [comment]
@mahestro got it, yes good call. 

@parthshah I wouldn't make it active by default. User may not realize that it's on and miss information. I would show more and let them filter.

**Comment by parthshah** [comment]
I mostly care about projects that I am a part of and every once in awhile go exploring for all projects. Pretty soon we should be broadcasting / notifying interested parties copilots & managers of new projects (recently activated , or created).

**Comment by mahestro** [comment]
I think I understand the why of removing the nav temporary. As a new client, I think it's less distracting, allowing him/her to focus on the conversion (since he probably doesn't have anything else to do in the page at that point).

As a PM / dailyuser it might be useful to have the nav.

Either case, the header has changed. Now it's one-level navigation. I think just moving the x/close to the top for the project creation would help here, maybe?

My 5 non requested cents :) ...

![nav2](https://cloud.githubusercontent.com/assets/729632/18428581/0973e572-78cf-11e6-9ebb-548659f5cc96.png)

**Comment by fnisen** [comment]
Not necessarily--if you're a manager or copilot, you care about all projects, so that you can screen new ones. Anyway, the option should be persistent--so we start out without not selected by default, so that the user knows what information is available. After that, they can switch it on and it stays. To me it's more important that they know the data is there and try to figure out how to filter, rather than not realizing they're seeing filtered data.

**Comment by mahestro** [comment]
Done! Will merge.

http://www.topcoder.com/direct/contest/downloadSoftwareSubmission.action?projectId=30055194&submissionId=231066

**Comment by mahestro** [comment]
BTW, the main reason why it's not behaving properly is because the data is hardcoded, not pulled from API yet.

For this task I focused in cleaning the search component, fixing a couple of bugs it had and preparing it for the transformation for the new nav. If we want to address the data binding we'd need to create another issue.

**Comment by fnisen** [comment]
@mahestro seems like it was updated, but is not behaving properly. This is all I'm seeing: 

<img width="642" alt="screen shot 2016-09-13 at 8 12 41 pm" src="https://cloud.githubusercontent.com/assets/12552247/18498825/9078b58c-79ee-11e6-97f8-13f489b82d40.png">

**Comment by vikasrohit** [comment]
@fnisen typeahead is using hardcoded check as of now. It returns all challenges that have 'LUX' in their name. We don't have API ready for this. So, I guess for now we should disabled the typeahead.

**Comment by mahestro** [comment]
It shouldn't have that "popular" on top. Can you try reinstalling the modules in your local environment? Or if this in prod, needs nodules reinstallation, since the react-components#feature/connectv2 was updated.

**Comment by mahestro** [comment]
Just checked online and it's looking as expected :) @vikasrohit did the magic with the modules, I guess. Thanks.

https://gyazo.com/210a519d5939a35e850b9539815830b7

**Comment by vikasrohit** [comment]
@mahestro I would not mind the credit, however, I haven't done any magic there. Might be the latest build deployed on dev did the trick. 😬

**Comment by fnisen** [comment]
@mahestro can you please take out the hardcoded results? It makes it seem broken. If we can't have the typeahead by launch, that's OK.

**Comment by mahestro** [comment]
Yes, for demo purposes it's not good. I'll take it out.

**Comment by mahestro** [comment]
Done. Deleted the demo projects and added a TODO.
