### ISSUE TITLE
Phase UI Layout (Non-Set-Up/Editing View)

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4350]
Here's a very poorly drawn indication of the UI layout updates:
<img width="959" alt="Screen Shot 2021-04-14 at 3 24 19 PM" src="https://user-images.githubusercontent.com/41118149/114788002-94310480-9d35-11eb-9654-f56304a0b623.png">

Update 1
Remove the word "Status" from above the project plan phases

Update 2
Only display the description field if the user added a description during phase set-up. 

Update 3
Show the start/end date fields similar to how they look during phase set-up

Update 4
Show duration next to the start/end date fields

**Comment by vikasrohit** [comment]
> Show the start/end date fields similar to how they look during phase set-up

We can not show editable text boxes here @acshields. We can show the disabled text boxes however I won't prefer them as well because they can confuse other forms on the same page. So, I would suggest a simple UI for showing the dates, we can show them in the same format which we are using while editing but we should not use text boxes.

**Comment by acshields** [comment]
@vikasrohit - sorry if my poorly drawn diagram was confusing. Wasn't trying to suggest using text boxes.

Was just trying to indicate the visual layout, and the fact that I would like the dates to be more prominent/easy to read (like it is when you are setting up the phase). I will leave it in your hands - the image was just meant to be directional.

**Comment by vikasrohit** [comment]
@mirzailhami I saw the changes for this issue. It seems like you update the edit form of the phase while the issue actually requires the layout to be updated for ready only view of the phase card. Also, the duration in the edit form deviates from the duration in phase card.

<img width="806" alt="Screen Shot 2021-04-19 at 3 06 30 PM" src="https://user-images.githubusercontent.com/2417632/115215270-f8323f00-a120-11eb-9ec0-46231ee9bcca.png">

I don't think we need to show duration in the edit form. You can revert the change to the edit form for this specific issue and update the phase card to look something similar to what you have in edit form with exception that instead of text boxes, we would show dates in standard labels.

**Comment by mirzailhami** [comment]
@vikasrohit ah ok, sorry. I will get @deandex to revert.

**Comment by vikasrohit** [comment]
@mirzailhami I don't see the changes to actually show the start date, end date and duration in the suggested format by @acshields. I mean read only view of the phase card show the start & end dates and duration with their separate labels.

**Comment by mirzailhami** [comment]
> Show the start/end date fields similar to how they look during phase set-up

@vikasrohit Do you mean this part? It still confuse me how should the FE looks like and where it should be shown.

**Comment by vikasrohit** [comment]
@mirzailhami Let me try fixing it to save some time for now. @acshields what do you think if we update the phase card layout for the existing project phases as well? I mean showing the labels for start/end dates and duration in the phase card read only view?

**Comment by vikasrohit** [comment]
@acshields I have assumed to update the layout for the existing project phases as well because it does not alter the functionality but rather just eases the read view of the phases. Please let me know if we don't want it.

**Comment by vikasrohit** [comment]
@SathyaJayabal deployed to dev for testing.

**Comment by SathyaJayabal** [comment]
verified on dev
manager view
<img width="776" alt="Screenshot 2021-04-21 at 5 43 15 PM" src="https://user-images.githubusercontent.com/58783823/115551758-22befc00-a2c9-11eb-92e0-44169fe1796a.png">

customer view
<img width="783" alt="Screenshot 2021-04-21 at 5 43 21 PM" src="https://user-images.githubusercontent.com/58783823/115551782-2c486400-a2c9-11eb-8675-411fdee310ef.png">

Also updated for older projects, Please confirm if that ok, @vikasrohit 
<img width="771" alt="Screenshot 2021-04-21 at 5 45 24 PM" src="https://user-images.githubusercontent.com/58783823/115551964-60238980-a2c9-11eb-9664-2fc578981747.png">

**Comment by vikasrohit** [comment]
@SathyaJayabal yes that is okay https://github.com/appirio-tech/connect-app/issues/4350#issuecomment-824002131

**Comment by drasticdpk** [comment]
with beta=true created project.

![image](https://user-images.githubusercontent.com/25297859/115727411-4a829280-a3a3-11eb-9671-246e6a3698e8.png)


**Older Project** 

![image](https://user-images.githubusercontent.com/25297859/115727135-11e2b900-a3a3-11eb-8dca-8c62b13c7027.png)

**Comment by drasticdpk** [comment]
![image](https://user-images.githubusercontent.com/25297859/115728140-f6c47900-a3a3-11eb-9ada-8621116c5013.png)
