### ISSUE TITLE
File Upload not available in assets library

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#4370]
### Expected behavior
When viewing Assets Library on a project, the option to upload files should be present.

### Actual behavior
It is not showing on https://connect.topcoder.com/projects/26407

### Screenshot/screencast
![image](https://user-images.githubusercontent.com/3812270/116465969-ee54be00-a83b-11eb-9246-5b7ed11a0252.png)

--

**Comment by ajefts** [comment]
fyi @acshields @vikasrohit Can we take a look at this one quickly?  It's blocking the experience on a customer project.  Thanks.

**Comment by acshields** [comment]
@vikasrohit - I went into this project as well and also see no "files" option when I look at it. I am unsure what could be driving this behavior...

@ajefts - A potential workaround just dawned on me... If you post a message and include the file you want to upload as an attachment, what happens? In our normal flow, what should happen is that: the message is posted w/ file attached a folder is created in the Assets Library w/ the message thread title and the file is also listed there.

**Comment by ajefts** [comment]
@acshields that let me upload to the message, but didn't impact the asset library

**Comment by vikasrohit** [comment]
@acshields @ajefts it happens because there is no file upload feature enabled for the template used by the project. We implemented the file upload section as per original requirements when we created these templates. I have added it to the template for now, it has enabled the file section in asset library section but it  might show the file upload while creating a new project with that same template (I don't remember this part exactly, I can go in detail if needed)

**Comment by ajefts** [comment]
Thanks @vikasrohit
