### ISSUE TITLE
Unable to delete selected Milestone 

### ISSUE THREAD

**Issue by drasticdpk** [appirio-tech/connect-app#4427]
- [ ] This is not a functional issue, it is a UX issue, if you are confusing about why delete not deleting multiple items, then the UI should update to disable these icons on multiple items selection so user is forced to use the items at top of the table.

Here user can delete only one milestone at a time, Either we have to change message content of confirmation window or remove the checkbox ( column 1) ,  please confirm. 

Reference 
![image](https://user-images.githubusercontent.com/25297859/126936104-e668d636-7c81-47ad-89c9-2eafcf144004.png)

![image](https://user-images.githubusercontent.com/25297859/126936377-b70d29c1-ed3b-4587-9b56-312b41277048.png)

**Comment by elkhawajah** [comment]
This is old UX. @drasticdpk clarify with latest screenshots.

**Comment by drasticdpk** [comment]
@elkhawajah 
FYI 
![image](https://user-images.githubusercontent.com/25297859/129358057-51bd5a4e-7edb-44bb-838b-b7202ad99499.png)

**Comment by elkhawajah** [comment]
That's expected behavior, the delete icon at top of the table is for deleting multiple entries. the one in corresponding row only for that row.

This is not a functional issue, it is a UX issue, if you are confusing about why delete not deleting multiple items, then the UI should update to disable these icons on multiple items selection so user is forced to use the items at top of the table.

**Comment by RishiRajSahu** [comment]
@drasticdpk yep agree.

**Comment by drasticdpk** [comment]
Verified. 
![image](https://user-images.githubusercontent.com/25297859/131638193-7e077fcc-0acf-4737-96ce-81bedb0a183f.png)
