### ISSUE TITLE
General: Connect links leading to blank page 

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#490]
When you click a Connect link (e.g., https://connectv2.topcoder.com/projects/24) from an external tool such as Slack, you first see a blank page and need to refresh for the page to load correctly.

**Comment by parthshah** [comment]
@vikasrohit I am not sure why this happening. All I could trace it back to was maybe it's stalling in some iframe connection. Could you please check?

![image](https://cloud.githubusercontent.com/assets/1987710/19541661/d88f9788-961c-11e6-8c61-1f1da9ac3063.png)

**Comment by parthshah** [comment]
Bumping the priority on this since multiple folks are seeing this error.

**Comment by vikasrohit** [comment]
It seems the issue is again the same which was there with members app. My changes were overridden in this [commit](https://github.com/appirio-tech/accounts-app/commit/7dc6f01ca3d361092de9e8101a4f17c7db561d53). It seems this was done in reference to a security issue reported by Sky_. @mahestro Can you please elaborate more on that security issue and what all changes were made for that?

**Comment by fnisen** [comment]
@vikasrohit @mahestro is out for a few more days, but @ajefts was involved in the fix, along with Sudo. Tony can you please tell Vikas what was done? Thank you.

**Comment by vikasrohit** [comment]
@fnisen I guess, I have found the changes. It seems the commit I mentioned above is the only change set for that fix. Anyway, I think I have fixed the issue. It appeared because one of the security fix, removed safe format check which is required to ignore non interesting events. One such example is cache event which happens to be thrown after session inactivity for some time and because we are not checking for the safe format, current code removes the callback listener and when actually we receive jwt token from accounts app, we don't have the listener to act on that, causing blank screens.

**Comment by fnisen** [comment]
Thanks @vikasrohit! It's working for me in Dev. Well done.
