### ISSUE TITLE
Dashboard/Project info: Budget and Duration may be confusing for PB customers

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#50]
Is it useful to pull Status and Duration info from Direct or will it confuse new customers such as GE and EY? If so, maybe we should remove it for this release.

**Comment by fnisen** [comment]
@ajefts I'm thinking we should: 
1. Remove budget
2. Keep duration (if that's usually accurate in Direct)
3. Use the space created to add the Direct project link, visible for manager and copilots

What do you think?

**Comment by fnisen** [comment]
@ajefts who would enter budget in this scenario? Would it be the AD or Joey? Is this something they normally do? Also, is the budget set up per project or per account? Right now we could only show it at the project level.

**Comment by parthshah** [comment]
I agree with the solution @fnisen listed with the caveat that we should remove duration as well. I'd like to spend some more time analyzing these and other project health metrics. Ideally we would launch with such metrics managed through status updates / reports via external links.

**Comment by fnisen** [comment]
@parthshah what's worrying you about duration? That's tied to the original game plan, so as long as it's entered in Direct, the info would be accurate.

**Comment by parthshah** [comment]
The fact that it doesn't include JIRA tasks (this is my assumption), not sure if there are other tasks that are not included. Eventually we also need to make sure we include Personal challenges which direct does not have any knowledge of today.

**Comment by fnisen** [comment]
OK, got it. Let me talk to a few more folks on the operational side to understand exactly how this works and its utility.

**Comment by ajefts** [comment]
Sorry, lost track of this thread.  

As far as who fills in the budget...yes, it's usually Joey or an AD. Seems like people are actually starting to do this more now that we're monitoring SOW/Budget/Burndown/etc. more closely. However, I would still get more insight on that since it's inconsistent across the board.  For management views, I think we'll definitely want some notion of seeing budget vs. actual.

I'm fine removing it all for now and using status, but I think if we do keep something then just keep the planned budget and planned duration (both user entered #'s in Direct).  Actual duration doesn't need to be calculated against the game plan (which does not include "tasks")...it could just be the time since the project was launched metered against the planned duration (i.e. "23 out of 45 planned day").

**Comment by fnisen** [comment]
Being addressed as part of https://github.com/appirio-tech/connect-app/issues/51

Guys, OK final decision on this: 
1. We'll take out budget mainly because we don't have customer and PB user separation right now. Everyone sees budget and it won't reflect PB mark-up (or our discounts for them) for their end users. So, we may get into some embarrassing situations. We need either more robust reporting or an admin panel where this info can be broken down and edited. 
2. We'll show duration in the basic way Tony suggests--number of days elapsed from launch compared to the total duration in Direct. Total duration can be adjusted easily, if needed, to take into account extracurricular work. It's a helpful signal that "something is happening on your project," especially if you may not be getting frequent status updates.

**Comment by fnisen** [comment]
@mahestro no extra work required on this one. Being addressed as part of https://github.com/appirio-tech/connect-app/issues/51
