### ISSUE TITLE
Redirect Discourse messages to connectv2 

### ISSUE THREAD

**Issue by parthshah** [appirio-tech/connect-app#509]
When user's post a message through connect (status updates or messages/discussions) Discourse will send out emails to users notifying them of updates. Emails will contain a link to the post message. https://connectv2.topcoder-dev.com/messages/{topicId}. 

We need to add a route to connect v2 to handle this URL. 
- When the route is loaded, retrieve topic information from v4/messages/{topicId}
- retrieve projectId from the response & redirect user to that project dashboard
- If the call fails redirect the user to connectv2.topcoder.com

fyi @vikasrohit @fnisen

**Comment by vikasrohit** [comment]
@parthshah I guess, we should keep the URL as /discussions/{topicId} instead of /messages/{topicId}, to be consistent with the naming convention we are following for the messaging tab.

**Comment by vikasrohit** [comment]
Done. Changes are in dev. I have made couple of improvements:

1. used 'discussions' instead of 'messages' in URL to be consistent with other messaging URL
2. Opened discussions tab when the concerned topic/feed is not a project status
3. Further, selected the particular feed in the discussion tab. However, right now, it won't scroll if the selected feed is in below the visible part of the list of the topics in the left panel. If that is not accepted as UX, I can revert the logic for selecting particular topic on load.

**Comment by vikasrohit** [comment]
@fnisen @ajefts  Any feedback on the #3 in my previous comment?

**Comment by fnisen** [comment]
@vikasrohit sorry for the delay. I would want the user taken to the topic, and I'm not sure how reverting  #3 would fix that. You won't be taken to the topic at all? Could you maybe include a video of the options? Thank you.

**Comment by vikasrohit** [comment]
Yep, you won't be taken to the topic at all. Page would open with first topic selected. On the other hand, I can start working on scrolling the left panel to the correct topic, if we can put that in a known issue.

**Comment by fnisen** [comment]
@vikasrohit yeah, getting you to the correct place is important. I've created a new issue for that https://github.com/appirio-tech/connect-app/issues/517.

**Comment by vikasrohit** [comment]
Thanks @fnisen

**Comment by vikasrohit** [comment]
BTW, I have found another issue #518 which I would try to fix asap.
