### ISSUE TITLE
Alerts and Notifications: Style toaster messages

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#52]
The action confirmation messages that appear (e.g., after adding a link from the Dashboard) don't have the correct font and appear on the far right of the screen. Is there a way to tweak them to look better, before we implement new confirmations/notifications later?

**Comment by vic-appirio** [comment]
Specification is here: https://drive.google.com/folderview?id=0B1LbmKnex41fUmo0aGJkQkt2NGc&usp=sharing

**Comment by vic-appirio** [comment]
![19060bae-a43c-4891-8136-9bfc98ea7c93](https://cloud.githubusercontent.com/assets/8484061/18366128/456e25b8-75ca-11e6-87b9-0683bd2c5458.png)

**Comment by fnisen** [comment]
@vic-appirio yes, great idea!

@sirakovaDimitrina welcome to our project, by the way! Really glad to have your help. Have heard amazing things about you from Vic.

**Comment by mahestro** [comment]
Welcome @sirakovaDimitrina. Thanks for joining.

**Comment by parthshah** [comment]
@sirakovaDimitrina welcome 👍 

@fnisen - I chose snackbar (Google Inbox) style notifications over the ones we used in Topcoder App 'cos these allow dynamic messages - Saving... --> Saved etc. Have we considered dynamic alerts?

**Comment by fnisen** [comment]
@parthshah yes, good idea. These are dynamic... or at least there is a loading state, as shown at the top of Vic's design: "Loading progress bar."

**Comment by parthshah** [comment]
Comments from GDoc - https://docs.google.com/document/d/1gPMqEmTLgA6Tf5DT3KiHl9hqFszH2oj-r58o9OeWfJU/edit#
I prefer re-using an existing component (open source library) for this instead of building our own. +tjefts@topcoder.com +fnisenzoun@topcoder.com thoughts? +vic@topcoder.com have you found a react component library that fits the requirements?
Tony Jefts	
Tony Jefts
7:34 PM Yesterday
agreed. would much rather just grab something off the shelf...
Filipp Nisenzoun	
Filipp Nisenzoun
10:28 PM Yesterday
Yes, this is mentioned in the GitHub issue. Here is the library Vic found: http://tympanus.net/Development/NotificationStyles/bar-exploader.html

**Comment by parthshah** [comment]
@fnisen @vic-appirio That link you posted is to a JS library. We would need to convert that to a re-usable React Component. Do you know if one already exists?
@vic-appirio / @vikasrohit -  The current library supports style overriding. Can you check if we can style it according to our requirements?

**Comment by vic-appirio** [comment]
I'll do research on this one today

**Comment by vic-appirio** [comment]
We use '[react-s-alert](https://github.com/schiehll/react-alert)' which does indeed support:

- States
- Transitions
- Custom content template overrides (albeit "tricky" as the author said)

**Comment by vic-appirio** [comment]
This one should be right fit for Didi - there's a ton of documentation at the plugin GitHub repo

**Comment by fnisen** [comment]
@parthshah will be ready by the end of this week, according to @vic-appirio
