### ISSUE TITLE
Dashboard/Project info/Team management: Adding member expands component

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#55]
When a user clicks on the "+" to add a team member, the component greatly expands in size. All team management actions should not effect the size of the component, as shown in the design. 
![d81f44f7-2147-4cae-83f9-625bc48b9683](https://cloud.githubusercontent.com/assets/12552247/18332586/c335aeb6-751c-11e6-9978-7ecebd7f195e.png)

**Comment by vikasrohit** [comment]
Tracking with asana task https://app.asana.com/0/95614844085038/177715475605030

**Comment by vikasrohit** [comment]
Done. Waiting for green signal to get it merged into dev.

**Comment by fnisen** [comment]
Thanks @vikasrohit. It's no longer expanding, but now is being cut off at the bottom. 

<img width="603" alt="screen shot 2016-09-09 at 12 03 58 pm" src="https://cloud.githubusercontent.com/assets/12552247/18399411/ab06af88-7685-11e6-9f47-360e1d191b0a.png">

**Comment by vikasrohit** [comment]
@fnisen my changes are not yet merged. So, it must be existing issue. The modal is not expanding for you because you have scrolled down a bit. It is expanding only when browser is not scrolled down.
I think  for cutoff issue we need to make the dropdown intelligent enough to render itself above the dropdown header if space below is not enough to get it fit. I guess, we need to track that in separate issue. May be ask community to get it fixed.
