### ISSUE TITLE
Messaging: Owner response post missing from status update

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#572]
https://connect.topcoder.com/projects/193

Valerie posted a status update to the customer, which he got by email. He responded, but the response didn't show up on the Dashboard. Please see exchange below: 

---------- Forwarded message ----------
From: Imad Harb <topcoder@discoursemail.com>
Date: Mon, Dec 5, 2016 at 1:49 PM
Subject: [Topcoder Connect] [PM] Project
To: vbailey+connect@topcoder.com

imadharb	imadharb Imad Harb 
December 5
Hi Valerie,

Thanks for the message.

It will be great if you could start with the scoping.

I have included the documentation I have. Let me know if you need further information.

Regards,

Imad

Visit Message or reply to this email to respond.

In Reply To

vbaileyconnect	vbaileyconnect Valerie Bailey%20Connect 
December 5
Hiu Imad, ​ Thank you for submitting your Topcoder Connect project. I wanted to reach out to you to see if you wanted us to move forward with scoping your project. If so we will need more information about your project and any supporting documentation you may have. Please let us know and …
Visit Message or reply to this email to respond.

To unsubscribe from these emails, click here.

**Comment by vikasrohit** [comment]
@fnisen I tried to debug the issue. However, not able to find the cause. One of the probable reasons is that if you are viewing dashboard of a project with joining a project, you might not see the comments. Can you try joining the project and let me know the results? Or allow me to join the project so that I can see the results. I can leave the project after debugging.

**Comment by vikasrohit** [comment]
@fnisen As per our discussion over Slack, I am removing the constraint of user to be a team member of the project in order to view the comments of status updates. Further, I am assuming we need to do the same for Discussions tab as well, so removing the constraint there as well. So, now any user who has the access to the project's dashboard and discussions pages, can view posts and comments.
