### ISSUE TITLE
Topcoder challenge links not displaying correctly on Dashboard

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#614]
Please have a look at this project Dashboard: https://connect.topcoder.com/projects/341

<img width="723" alt="screen shot 2017-01-10 at 3 24 11 pm" src="https://cloud.githubusercontent.com/assets/12552247/21829082/f7245496-d748-11e6-89fb-da2c9aa32b38.png">

**Comment by vikasrohit** [comment]
@fnisen It seems the link from challenge details page is copied as is which contains angular expressions.
`
{{CD.challenge.challengeName}}
`
This would have work for the angular app, but we have React in connect app. So, this link won't work. We have to use absolute values i.e. for posting link to the challenge something like this would work:
`
<a href="https://www.topcoder.com/challenge-details/30056094/?type=design&amp;noncache=true" target="_blank">ABC - GUIDED CUSTOMER SUPPORT MOBILE DESIGN CONCEPTS CHALLENGE</a>
`

**Comment by fnisen** [comment]
@vikasrohit OK. What can we do without requiring people to post the link a certain way?

**Comment by vikasrohit** [comment]
I guess, we need to do nothing. Users can simply paste normal HTML. The link code I shared above, has nothing special. It is a simple HTML link.

**Comment by vikasrohit** [comment]
Got some useful information from @gondzo It seem like it is happening because discourse is trying to parse the document of the target link to retrieve the page title and other stuff, however, somehow either angular in the target page is not loading correctly or taking more time than what discourse is timing out. Hence, it renders the partial information. May be we need to look into discourse for some config parameter which allows more time for parsing the link or disable that completely.
cc: @parthshah @fnisen

**Comment by fnisen** [comment]
@parthshah back to you please.

**Comment by parthshah** [comment]
We use Prerender.io to render SPAs to SEOs etc. This works with slack as well since prerender is able to identify a slack request via it's user-agent - 'slackbot'. I haven't been able to find out what user agent Discourse uses.
For now you can append `&_escaped_fragment_=1` to the end of your URL. Note that this will render a cached version of the challenge page , which might be up to 7 days old. 
The ideal way to solve this would be to support Server side rendering for Challenge Details page, which requires considerable changes.

**Comment by vikasrohit** [comment]
Just to double sure, the user who is posting the link should add `&_escaped_fragment_=1` to the URL, right?

**Comment by fnisen** [comment]
@parthshah @vikasrohit I'm not getting a page preview by appending; the link just looks like a normal one: https://connect.topcoder.com/projects/1256/discussions
We could ask copilots to append, but not all of them will remember, nor will our managers. So, basically we're stuck until we make the infrastructure changes.
