### ISSUE TITLE
Project 908: Dashboard stuck in infinite loop

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#625]
The Dashboard for this project never loads: https://connect.topcoder.com/projects/908/. Been seeing this for a few days now.

**Comment by vikasrohit** [comment]
Fixed and deployed as hot fix on production. However, the problem was that userId field of few posts was null. I am not sure why it was null, but API is returning it as null so the code breaks when trying to pull in the author of the post. For now, I have fixed it by using 'Not Available' as the author name when userId of the comment is null. Please let me know if you want to use other copy for this type of use case or want it to handle in completely different manner.
cc: @parthshah @fnisen

**Comment by vikasrohit** [comment]
One more strange thing is that somehow there are comments of system user's  posts in this project. I am wondering how it is possible. There seems to be a loop hole in the code which is allowing users to comment on system user's post.

**Comment by fnisen** [comment]
Thanks @vikasrohit. Can you please make the copy: "Connect user" (this way the error is not so obvious)? 

@parthshah can you please have a look at this one? The unknown user is actually Joey: https://connect.topcoder.com/projects/908/

**Comment by vikasrohit** [comment]
Okay.

@parthshah Can we find out the log entry for request made for that particular comment (topic id 1741 and post ids 5980, 5982) ? I want to be sure that if it is front end or discourse who is missing that user Id.

**Comment by vikasrohit** [comment]
@fnisen I am applying the copy change as regular fix not as hotfix, to avoid product update. Please let me know if you want to push it immediately to the production, I would create hot fix in that case.

**Comment by fnisen** [comment]
@vikasrohit thanks, this is fine--no need for the hot fix.
