### ISSUE TITLE
Remove blue font and blue hover state from components

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#653]
<img width="309" alt="screen shot 2017-03-02 at 5 19 56 pm" src="https://cloud.githubusercontent.com/assets/12552247/23534400/8f7adef4-ff6c-11e6-98ac-06a87b014830.png">
<img width="576" alt="screen shot 2017-03-02 at 5 20 17 pm" src="https://cloud.githubusercontent.com/assets/12552247/23534402/93aed872-ff6c-11e6-9fa1-d4fd89e25d67.png">

**Comment by vic-topcoder** [comment]
Change hover state on selected element to be black.

**Comment by vic-topcoder** [comment]
Still appears on Ref code

![screen shot 4](https://cloud.githubusercontent.com/assets/8484061/23633891/717e5a26-027c-11e7-9c74-0ebb3ddd1e22.png)

**Comment by vic-topcoder** [comment]
The text size is jumping between normal and active states. We should be consistent with text size at all cases.

- separate input and text area to support 2 sizes:

- input - normal  - 15/20px; 
- input - large - 20/30px;
- textarea - normal - 15/25px;
- fix font-weight to be normal/400. Currently it is 300


+ add `text-rendering: geometricPrecision` in order to assure correct typography on the fields/text area

![screen shot 5](https://cloud.githubusercontent.com/assets/8484061/23634586/ca7c6764-027f-11e7-9d7e-56a0b6363da9.png)

**Comment by vic-topcoder** [comment]
The ref code input in challenge specification still represents blue hover state.

**Comment by vic-topcoder** [comment]
![screen shot 10](https://cloud.githubusercontent.com/assets/8484061/23683849/24b96c60-0350-11e7-8126-547ea401dadc.png)

Note: the `optional` label is not using the correct text color (tc-gray-50)
