### ISSUE TITLE
Feature Selector: Style fixes

### ISSUE THREAD

**Issue by vic-appirio** [appirio-tech/connect-app#67]
The Feature Selector is a modal view that is shown to the user from the Project Specification page when they click on "Add / Edit Features". It allows the users to select one or more predefined features, and also specify their own project features. After clicking on the close icon, the system displays all the selected features as a table inside the Project Specification.

![479e8b36-06d0-420e-948d-fb855cd6f4cf](https://cloud.githubusercontent.com/assets/8484061/18400085/2f60105a-7689-11e6-9814-bad119a12fe1.png)

![0476f095-cd4d-4145-b301-743df2fee6e6](https://cloud.githubusercontent.com/assets/8484061/18400091/351dec42-7689-11e6-8829-9efe2f9c8427.png)

**N.B. We should modify the current preview component to separate the device from the feature preview image.**

Specification is here: https://drive.google.com/drive/folders/0B1LbmKnex41fYUtpV1AwOFFFMUE?usp=sharing

**Comment by mahestro** [comment]
Looking good!

I saw this is implemented in the current version of the app. The styles are not matching though. Is it something of class linkings? Does the HTML exists for this?

If there's no a clean CSS/HTML I could launch a quick task to create it. @vikasrohit, is there a way to extract a clean HTML from the react structure that we can use to skin so we can keep the same markup it's laid out there and not to modify too much?

**Comment by vikasrohit** [comment]
@mahestro It is bit time consuming to extract the HTML and css of all components in the feature picker and put them in single file. Can you get it styled in its react components form? I am mostly done with feature picker changes and changes are already merged into dev branch. You can take it over for getting it styled as per specs.

**Comment by mahestro** [comment]
I understand, it must be tricky to put all that out into a separate html.

I'm going to do a little research to see what I can find about this. I wouldn't like to run a html/scss+react task all together for a good number of reasons.

From the existing members from the community that compete in react components, they're not very strong in generating clean HTML/CSS. Also, unfortunately we count on a few developers only. I would need to assign a private task for this to one of the tops but since there is a lot of markup and css involved I'd really like a clean code there and a thoroughly detailed review. 

We usually take this to HTML/SCSS first because there are a lots of prototypers available. Particularly, after one this type of tasks ends I go through the css and make sure they're using variables, not redefining colors and making sure it's pixel perfect. It's not a good option to use a react developer for generating html/css.

I'll think about it. I'm waking up ☀️ ☕

**Comment by vikasrohit** [comment]
Agree!! However, now we just need css tweaks to get it look like Vic's specs. I don't think they would need any react knowledge to style it. I have tried to use Vic's style in most of the places, however, I may have missed it at few places. So, I just want to be double sure if we are following the right specs for the feature picker.

**Comment by vic-appirio** [comment]
I'm going to take over and work on the style of the feature picker. There are some breaking things when I do restyle, the Webpack breaks, probably the dependencies are too strange or something. @vikasrohit are we done with all the functional changes for the feature picker in "dev"?

**Comment by vikasrohit** [comment]
Yes, @vic-appirio but @fnisen found a few issues with feature picker today, so I might be working on them.
