### ISSUE TITLE
First post in discussions is not displayed

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#673]
### Expected behavior
All posts should be displayed in the project discussions thread

### Actual behavior
The first post is sometimes not displayed at all and there is no 'load earlier messages' button.

### Steps to reproduce the problem
Not sure, but I think it's happening only when the number of messages to be displayed is near the limit for displaying 'load earlier messages' button.

### Screenshot/screencast
For example https://connect.topcoder.com/projects/873/discussions
![image](https://cloud.githubusercontent.com/assets/3051646/23581223/88eb6536-0110-11e7-957e-893b3fa0a49a.png)

--

#### Environment
- OS: windows,linux
- Browser (w/version): Chrome, firefox
- User role (client, copilot or manager): copilot
- Account used: gondzo

**Comment by fnisen** [comment]
Note: this is not a products issue, but one currently in production. Please work on this after all the products bugs.

**Comment by parthshah** [comment]
This one is getting more visibility lately, could we please prioritize this - @fnisen @gondzo @vikasrohit .
Thanks!

**Comment by vikasrohit** [comment]
Fixed. Applied as hot fix to the production. It was copy paste magic. Basically we are showing the dashboard feeds and discussion messages in slightly different way. In dashboard feeds we show the first post of a topic as post and others as comments while in discussions page we are showing all posts of a topic as comment. So this issue was happening only for the edge case when the total posts for a topic is 4, as soon as there more comments than 4, it disappears. That is why it was not seen consistently.

**Comment by fnisen** [comment]
Thanks a lot Vikas.
