### ISSUE TITLE
Discussion: should have a max length validation on discussion topic 

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#709]
Discussion: should have a max length validation on discussion topic otherwise in the list topic looks ugly

**Steps to Reproduce:**
1. Open the Application
2. Login with valid credentials: Manager: pat_monahan / topcoder123!
3. create new project
4. enter all specification
5. go to discussion topic
6. enter a long paragraph in discussion topic

**Expected Result:**
must have a max length validation

**Actual Result:**
no validation on max length

Environment:
Windows 7, 
Chrome

![image](https://cloud.githubusercontent.com/assets/16131461/23721738/d98d5d36-0468-11e7-8dcb-c8998b17348d.png)

**Comment by fnisen** [comment]
@vic-topcoder is there a specified length for this in the design?

**Comment by vic-topcoder** [comment]
Not sure, but we allow 3 lines of text. The field should break, but since it was entered as a single word, there's no breaking to a new line. Look at some other elements, but we might just add `text-overflow: ellipses` to negate very long single words. In real life there rarely are "suchlongwordsthatwearejusttestingfieldshowtheybreakwith"

**Comment by fnisen** [comment]
Working in Dev.
