### ISSUE TITLE
App Screens - new screens and save changes

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#834]
- [x] "Define another screen" should be "Define screen" initially, because there are no screens
- [x] The "Save" button in the App Screens section is turned off when that section is not passing validation. But, Save is still active in other sections. We should be consistent--either have all the buttons off or all of them on. (~~We should keep the "Submit for Review" button off until all sections pass validation~~).

**UPDATE:** @fnisen @gondzo Removed the strikethrough portion of the requirement from the scope of this story because we already have other changes in production and if we continue working on this after the release it might give false impression that already fixed issues were not fixed in this release. I have created two separate issues( #857 and #858) for that strikethrough portion. Sorry for too much redirections from one issue to another, however, the issue was bit complicated and required staged fixing.

**Comment by vikasrohit** [comment]
Hey @Colinh84 If you haven't started on this one, can you please remove the assignment? We may need to handle it internally.

**Comment by Colinh84** [comment]
@vikasrohit No problem. I just finished the fix for #751 and hadn't got to this one yet anyhow because #751 was very difficult to track down and fix.

**Comment by vikasrohit** [comment]
PR is created however, the link of 'Submit for Review' button with incomplete/invalid state of 'App Screens' section may not seem to work because currently changes in one component of the specification form does not reflect in other components of the same page. This is the same reason which is preventing the immediate update of Quick Quote section when user updates the answer for Number of Screens question. I guess, we can handle that after today's major release.

**Comment by vikasrohit** [comment]
Can we close this @fnisen ?

**Comment by fnisen** [comment]
@vikasrohit yes, all the non-crossed out stuff is working correctly in Dev. Closing.
