### ISSUE TITLE
CoderBot message changes

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#893]
TBD

**Comment by fnisen** [comment]
@vikasrohit what's needed here?

**Comment by vikasrohit** [comment]
What exactly we need to change in coderbot message?

**Comment by fnisen** [comment]
So right now, it looks like we usually post two Coderbot messages (below). One confirming project creation and then one confirming submission. Because the project is being created and submitted at once, let's combine these into one. Here is the new copy:

Headline: "Your project is being reviewed. Provide additional info if you have it."
Message: "Hello, Coder here! Thanks for submitting your project [Project name (as a link)]! I've used my super computational powers to route it to one of our trusty humans. They'll get back to you in 1-2 business days. Meanwhile, if have any additional project information or documents to upload, please head over to the Specification (link) section. Get stuck or need help? Email us at support@topcoder.com (link)."

![screen shot 2017-08-01 at 9 38 12 am](https://user-images.githubusercontent.com/12552247/28945400-2ab73e64-785b-11e7-9588-c6194775aaa3.png)

**Comment by vikasrohit** [comment]
Changes are in dev.

**Comment by fnisen** [comment]
Working well, thank you!
