### ISSUE TITLE
Provide new validation layout and styling

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#928]
### Actual behavior
<img width="558" alt="screen shot 2017-06-29 at 12 05 10 pm" src="https://user-images.githubusercontent.com/12552247/27705670-7fa28608-5cc3-11e7-921b-582c3891beb2.png">

---
The above is the current behavior in production, but it's pretty messy. Can you please provide updated styling, perhaps similar to what the member side  uses currently: 
<img width="617" alt="screen shot 2017-06-29 at 12 08 41 pm" src="https://user-images.githubusercontent.com/12552247/27705751-bb9f0442-5cc3-11e7-8641-5630b2d9c762.png">

**Comment by vic-topcoder** [comment]
We have the styles provided from Didi, we should treat the username/password as separate fields, displaying a message "there's no such combo" is bad UX.

There are 2 error states:
1. Non-existent account - we should error on account and explain that there's no account.
![login - invalid username](https://user-images.githubusercontent.com/8484061/27709708-f2a33220-5cd1-11e7-93ce-4c830fb44412.png)

2. Wrong password - ask to try again or reset password
![login - invalid password](https://user-images.githubusercontent.com/8484061/27709705-ee1d8232-5cd1-11e7-852f-d8a4472ba509.png)

**Comment by vikasrohit** [comment]
> We have the styles provided from Didi, we should treat the username/password as separate fields, displaying a message "there's no such combo" is bad UX.

Yes, we do have error styles. However, I kept things simple so that we don't break working things. I assumed we can refine these little things after release.

One more thing, mostly in my past experience we used to avoid telling user that there is no account with the particular email/username because if we do, we give user clear hint that user exists with that username/email. This decreases the time required to hack into the system using brute force because hacker can be certain that user exists and now only try with password. We never treated username/password as separate entity, they are credentials and a credential can be valid or invalid. We should avoid telling which portion was wrong.

**Comment by fnisen** [comment]
@vikasrohit yes, agree that this is not a release blocker

**Comment by vikasrohit** [comment]
Done.

**Comment by fnisen** [comment]
Closing this. Outstanding issues being tracked here https://github.com/appirio-tech/connect-app/issues/929
