### ISSUE TITLE
Create URL for each project spec page...

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#932]
...so we can deep link to it from a marketing page (with a logged out user)

**Comment by vikasrohit** [comment]
@fnisen this is already supported. Sorry, I missed to update it along with my status update 😬 

Wireframes - http://connect.topcoder-dev.com/new-project/product/wireframes
Visual Design - http://connect.topcoder-dev.com/new-project/product/visual_design_concepts (Right now I have used the visual design concepts template for this one, and it would behave same for new projects with Visual Design product and old projects with Visual Design Concepts product. We can create separate product for this one, if required.)
Visual Design Prod - http://connect.topcoder-dev.com/new-project/product/visual_design_prod (this one is disabled in product type selection UI, if we want to disable it through deep links as well, let me know)
Infographic - http://connect.topcoder-dev.com/new-project/product/infographic
Generic Design - http://connect.topcoder-dev.com/new-project/product/generic_design
Front end prototype - http://connect.topcoder-dev.com/new-project/product/visual_prototype
Website - http://connect.topcoder-dev.com/new-project/product/website_development
App - http://connect.topcoder-dev.com/new-project/product/application_development
Generic Dev - http://connect.topcoder-dev.com/new-project/product/generic_dev

Also, as you noticed that it is using non user friendly (may non seo friendly as well) product names in URL, please let me know if need to use more user friendly names here. Currently it is using id of the product as is to identify the product, otherwise we have to create another mapping to identify the product from that user friendly name. However, I guess _ are seo friendly and can properly index these URLs.

**Comment by vikasrohit** [comment]
One more thing, I have to handle the case where the deep link is having wrong project id (may be a typo by marketing user or some body trying to break our system). I think we should just present the product type selection screen in this case and update the URL to exclude the wrong product param altogether.

**Comment by fnisen** [comment]
@vikasrohit these links are not working for me currently. Not sure if the page is down or it's some other issue. Also, there are only 8 options currently: 

1. Wireframes
2. Visual design (merging two into one; can make this the concepts one and deprecate prod option)
3. Front-end prototype (renaming prototype)
4. Software development (renaming generic dev)
5. Website
6. Infographic (new)
7. App
8. Other design (renaming generic design)

Let me check with Greg regarding the names and link structure

**Comment by vikasrohit** [comment]
@fnisen Yes, that is the reason I guess.

We have only one extra option from the list and that is for visual design production. And this is not available in product select screen. This exists just because I have to keep backward compatibility with old projects of this type. I can disable this option on deep links as well.

**Comment by vikasrohit** [comment]
Deployed changes again. And removed disabled visual_design_concepts, instead of visual_design_prod, from deep links as well. For visual design concepts now it would take you to 404. And visual design is essentially the old visual design production template.

**Comment by fnisen** [comment]
@vikasrohit yup, it's working for me. Why did you decide to keep design_prod and deprecated design_concepts? Just curious regarding your thinking.

**Comment by vikasrohit** [comment]
Because it says `prod` and its description (`Create development-ready designs`) is more generic than concepts one (`Visualize and test your app requirements and ideas`) 😬

**Comment by fnisen** [comment]
Makes sense, thanks.

One more thing: can you please change the links to this format: http://connect.topcoder-dev.com/new-project/wireframes (drop the "/product")? No need to change the names for now. I checked with Greg, and he said we'll look at SEO later. So, we might need to do a mapping later, but it's not critical for now.

**Comment by vikasrohit** [comment]
Done.
