### ISSUE TITLE
"Register" button not working

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#937]
Start a project, complete spec, then end up on the registration form. Complete form (no validation errors), but "Register" button is inactive: 

<img width="1280" alt="screen shot 2017-07-05 at 11 37 27 am" src="https://user-images.githubusercontent.com/12552247/27879574-06f10dc0-6177-11e7-8fed-3445c0ac7d42.png">

**Comment by vikasrohit** [comment]
@fnisen it seems this is because of country field issue https://github.com/appirio-tech/connect-app/issues/920#issuecomment-313244086
Right now we are validating only country field on the front end. Register button is enabled as soon as a valid country is selected by user. For rest of the fields we show error when it comes back from the server. Do you want me to update the form such that it validates all required fields on front end itself?

**Comment by fnisen** [comment]
@vikasrohit yes, let's do that. Opening a new issue to track: https://github.com/appirio-tech/connect-app/issues/950
