### ISSUE TITLE
User shouldn't be able to focus another textarea while editing a post

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#943]
While editing a post users can click to compose a new post. This shouldn't be happening. Display an alert that there are unsaved changes if the user wants to compose a new post.

![screen shot 6](https://user-images.githubusercontent.com/8484061/27886593-a1a8e418-6191-11e7-9f06-053e48c74fb5.png)

**Comment by gondzo** [comment]
Does this cover only editing a post and posting a new one, and editing multiple comments and/or posts is ok, or the goal is to have exactly one active post editor at a time ?

**Comment by vic-topcoder** [comment]
It should be for all instances of a post composer. Right now it is kind of changing status unless you enter some value. We should fix that. Anytime we are in editing mode and there's value change, we should ask to save before being able to focus away (and leave the form in enabled state).
![screen shot 3](https://user-images.githubusercontent.com/8484061/27890983-723d6e6e-61ab-11e7-98e7-62d7427920b9.png)

**Comment by gondzo** [comment]
@fnisen @vic-topcoder I'm not sure how to implement this one reliably, there are too many cases to cover (new post, edit post, new comment, edit comment, and all that in dashboard and then again in discussions tab). There are too many edge cases and would probably introduce new bugs.
@vikasrohit any ideas ?

**Comment by vikasrohit** [comment]
I haven't seen any application yet which prevents user from editing multiple form fields in the same page. It is only when user leaves the page, we should show the unsaved content alert because in essence we are not removing the changes made in the first post editor when user is editing the second one. So, IMO, showing alert is not a good way to achieve this and in fact user might get irritated if he/she is trying to see another post's content while preparing a reply to another post or trying compose a new post.
However, if this requirement is critical, we can show modal overlay when user is editing a post, like Facebook does for a new post. However, facebook does not show any alert even when you close that modal. Further, it also allows users to reply in multiple posts without any constraint. It show that alert only when user leaves the page.

**Comment by fnisen** [comment]
Yeah, I'm with @vikasrohit on this one. Facebook is lenient about this, and I assume they've tested the News Feed to death. 

Theoretically it's a good idea to focus the user with a modal, but then we'd need to constrain them to posting there before going anywhere else, which seems overly strict. It doesn't seem like users would often end up in an error state of writing something and forgetting to post. Clicking a button to post is now very natural, with text messages, chat, and other applications. Let's let this one go unless we find that users are actually forgetting to post.
