### ISSUE TITLE
Provide design for indicating that a user post has been edited (updated) after initial posting

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#971]
As suggested by Greg and Joey on the call today

**Comment by vic-topcoder** [comment]
Can we reuse the new post indicator that we currently have? That's the goal of the side marker - to drive the user's attention towards what's latest. When a post is edited, the new timestamp would push it to the top because we're sorting according to latest post (event) date (including edits), I assume.

Do you want to have a special "edited" badge as well? Have to research what other services use in that case

**Comment by vic-topcoder** [comment]
So, the addition of ` Posted 2h ago • Edited` on the timestamp plus the new post indicator should do the trick.

Example from Facebook:
![screen shot 3](https://user-images.githubusercontent.com/8484061/28145911-c1622082-672a-11e7-8075-495287f3bf3f.png)

I wonder how this would trigger a notification though.

**Comment by vic-topcoder** [comment]
Connect version. Please note that the timestamp would represent the latest edit

![screen shot 4](https://user-images.githubusercontent.com/8484061/28145967-2d5d129c-672b-11e7-93b2-0cb13148bab8.png)

**Comment by fnisen** [comment]
@gondzo one update here please: "Edited" does not show up until the page is reloaded. Can you please make it appear immediately after the user has edited the post?

**Comment by fnisen** [comment]
Now working--thanks!
