### ISSUE TITLE
Project Creation: Visual issue when creating "Other work" project

### ISSUE THREAD

**Issue by mahestro** [appirio-tech/connect-app#98]
Using chrome/mac, when you switch the tab to "other work" it shows a blue line below the form and it exits if you click there in that area.

![createproject](https://cloud.githubusercontent.com/assets/729632/18564007/fed31db4-7b89-11e6-95a8-dc6e866d0c8b.png)

**Comment by fnisen** [comment]
@mahestro can this be done as a community fix?

**Comment by mahestro** [comment]
@fnisen Totally, F2F research and fix.

**Comment by mahestro** [comment]
Fixed. I noticed something though, not sure if it's intentional or not. When you switch between tabs, the state is not stored or reflected at least. If I set some fields in one tab, once I move to the another one I lose what I did.

This could be a topic for discussion or a new issue. As you wish, guys @fnisen @parthshah

**Comment by fnisen** [comment]
@mahestro the only info to be persisted between states is the name/description/code, correct? I think it's fine not to persist those because we ask for that info at the end. So, you're not likely to select the initial few options, then enter the description, and decide that you don't want a prototype after all. I think a user would click around first to understand the options. Let me know if you disagree. cc @vic-appirio 

Let me open a new Issue for the URL.
